import { NextRequest, NextResponse } from "next/server";
import { requireAdminApiRole } from "@/lib/admin-api-auth";
import { ADMIN_PAGE_ACCESS } from "@/lib/admin-permissions";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { classifySearchIntent } from "@/lib/ml/intentBuckets";
import { calculateConfidenceScore, calculateConversionRate, calculateCtr, calculateLocationIntentScore, calculatePairScore, INTENT_SCORE_VERSION, PAIR_SCORE_VERSION } from "@/lib/ml/intentScoring";
import { CALL_EVENTS, CLICK_EVENTS, Diagnostics, NEGATIVE_EVENTS, RESERVE_EVENTS, SAVE_EVENTS, VIEW_EVENTS, bump, intentsForSearch, isUuid, locationIdsFromAnalytics, marketFromSearch, mlPairs, mlResults, normalizeEventName, pairFromAnalytics, pick, recommendation, text } from "@/lib/ml/recalculationSignals";
export const runtime = "nodejs"; export const dynamic = "force-dynamic"; export const maxDuration = 300;
function bearer(req:NextRequest){ const h=req.headers.get("authorization")||""; return h.toLowerCase().startsWith("bearer ") ? h.slice(7).trim() : null; }
async function authorize(req:NextRequest){ if (process.env.NODE_ENV === "development" || (process.env.CRON_SECRET && bearer(req) === process.env.CRON_SECRET)) return null; const { error } = await requireAdminApiRole(ADMIN_PAGE_ACCESS.import); return error; }
function inc(row:any, event:string, recent7:boolean){ if (VIEW_EVENTS.has(event)){row.impressions_30d++; if(recent7)row.impressions_7d++; row.views_30d++; if(recent7)row.views_7d++;} if (CLICK_EVENTS.has(event)){row.clicks_30d++; if(recent7)row.clicks_7d++;} if (RESERVE_EVENTS.has(event)) row.reservation_clicks_30d++; if (CALL_EVENTS.has(event)) row.call_clicks_30d++; if (SAVE_EVENTS.has(event)) row.saves_30d++; if (NEGATIVE_EVENTS.has(event)) row.negative_signals_30d++; }
function baseLoc(location_id:string,intent_bucket:string,market:string|null,location_type:string|null){ return { location_id,intent_bucket,market,location_type, impressions_7d:0,impressions_30d:0,views_7d:0,views_30d:0,clicks_7d:0,clicks_30d:0,reservation_clicks_30d:0,call_clicks_30d:0,website_clicks_30d:0,saves_30d:0,completed_outings_30d:0,negative_signals_30d:0 }; }
function basePair(r:string,a:string,intent_bucket:string,market:string|null){ return { restaurant_location_id:r,activity_location_id:a,intent_bucket,market,pair_distance_miles:null,estimated_travel_minutes:null, impressions_7d:0,impressions_30d:0,clicks_7d:0,clicks_30d:0,saves_30d:0,completed_outings_30d:0,reservation_clicks_30d:0,call_clicks_30d:0,website_clicks_30d:0,negative_signals_30d:0 }; }
function finalizeLoc(row:any){ row.market_key = row.market || ""; row.location_type_key = row.location_type || ""; const conversions=row.completed_outings_30d+row.reservation_clicks_30d+row.call_clicks_30d+row.website_clicks_30d; const ctr=calculateCtr(row.clicks_30d,row.impressions_30d); const cr=calculateConversionRate(conversions,row.impressions_30d); const intent_score=calculateLocationIntentScore({...row,ctr_30d:ctr,conversion_rate_30d:cr}); return {...row, ctr_30d:ctr, conversion_rate_30d:cr, engagement_score: intent_score, conversion_score: cr*100, confidence_score: calculateConfidenceScore(row.impressions_30d,row.clicks_30d,conversions), intent_score, score_version: INTENT_SCORE_VERSION, updated_at:new Date().toISOString(), metadata:{source:"phase2_recalculate", pii:false}}; }
function finalizePair(row:any){ row.market_key = row.market || ""; const conversions=row.completed_outings_30d+row.reservation_clicks_30d+row.call_clicks_30d+row.website_clicks_30d; const ctr=calculateCtr(row.clicks_30d,row.impressions_30d); const cr=calculateConversionRate(conversions,row.impressions_30d); const pair_score=calculatePairScore({...row,ctr_30d:ctr,conversion_rate_30d:cr}); return {...row, ctr_30d:ctr, conversion_rate_30d:cr, distance_score: row.pair_distance_miles == null ? 0 : Math.max(0,20-Number(row.pair_distance_miles)*5), engagement_score: pair_score, conversion_score: cr*100, confidence_score: calculateConfidenceScore(row.impressions_30d,row.clicks_30d,conversions), pair_score, score_version: PAIR_SCORE_VERSION, updated_at:new Date().toISOString(), metadata:{source:"phase2_recalculate", pii:false}}; }
function loc(locAgg:Map<string,any>, id:string, intent:string, market:string|null, type:string|null){ const key=`${id}:${intent}:${market||""}:${type||""}`; const row=locAgg.get(key)||baseLoc(id,intent,market,type); locAgg.set(key,row); return row; }
function pair(pairAgg:Map<string,any>, r:string,a:string,intent:string,market:string|null){ const key=`${r}:${a}:${intent}:${market||""}`; const row=pairAgg.get(key)||basePair(r,a,intent,market); pairAgg.set(key,row); return row; }
export async function POST(req: NextRequest) { const authError = await authorize(req); if (authError) return authError; const errors:string[]=[]; const since30=new Date(Date.now()-30*864e5).toISOString(); const since7=new Date(Date.now()-7*864e5).toISOString(); const locAgg=new Map<string,any>(); const pairAgg=new Map<string,any>(); const diagnostics:Diagnostics={searchEventsRead:0,searchEventsWithMlResultIds:0,searchEventsWithMlPairIds:0,searchEventsWithOnlyFirstResultNames:0,analyticsEventsRead:0,analyticsEventsWithLocationId:0,analyticsEventsWithPairIds:0,outingsRead:0,outingsWithRestaurantActivityIds:0,candidateLocationIntentRows:0,candidatePairRows:0,upsertLocationIntentRows:0,upsertPairRows:0,skippedReasons:{}};
 const searchRes = await supabaseAdmin.from("search_events").select("*").gte("created_at", since30).limit(20000); if (searchRes.error) errors.push(`search_events: ${searchRes.error.message}`); diagnostics.searchEventsRead=(searchRes.data||[]).length; for (const ev of searchRes.data || []) { const meta=ev.metadata||{}; const results=mlResults(meta); const pairs=mlPairs(meta); if(results.length) diagnostics.searchEventsWithMlResultIds++; if(pairs.length) diagnostics.searchEventsWithMlPairIds++; if(!results.length&&!pairs.length&&Array.isArray(meta?.debugParity?.firstResultNames)&&meta.debugParity.firstResultNames.length) diagnostics.searchEventsWithOnlyFirstResultNames++; const intents=intentsForSearch(ev); const market=marketFromSearch(ev); const recent=String(ev.created_at||"")>=since7; for (const intent of intents) { for (const r of results) inc(loc(locAgg,r.location_id,intent,market||r.market||null,text(r.location_type,50)),"search_result_impression",recent); for (const p of pairs) { const pr=pair(pairAgg,p.restaurant_location_id,p.activity_location_id,intent,market||p.market||null); pr.pair_distance_miles=p.pair_distance_miles; inc(pr,"search_result_impression",recent); inc(loc(locAgg,p.restaurant_location_id,intent,market||p.market||null,"restaurant"),"search_result_impression",recent); inc(loc(locAgg,p.activity_location_id,intent,market||p.market||null,"activity"),"search_result_impression",recent); } } }
 const eventsRes = await supabaseAdmin.from("analytics_events").select("*").gte("created_at", since30).limit(50000); if (eventsRes.error) errors.push(`analytics_events: ${eventsRes.error.message}`); diagnostics.analyticsEventsRead=(eventsRes.data||[]).length; for (const ev of eventsRes.data || []) { const meta=ev.metadata||{}; const locs=locationIdsFromAnalytics(ev); const p=pairFromAnalytics(ev); if(locs.length) diagnostics.analyticsEventsWithLocationId++; if(p) diagnostics.analyticsEventsWithPairIds++; if(!locs.length&&!p){ bump(diagnostics,"analytics_missing_ids"); continue; } const q = text(ev.query || pick(meta,["query","rawQuery","search_query","searchQuery","prompt"])); const cls=classifySearchIntent(q || ""); const market=text(ev.city || ev.borough || ev.neighborhood || pick(meta,["market","requestedMarket","requested_market","city","borough","neighborhood"]),100); const ltype=text(ev.location_type || pick(meta,["location_type","locationType","resultType"]),50); const name=normalizeEventName(ev); for (const intent of cls.allIntents) { for (const id of locs) inc(loc(locAgg,id,intent,market,ltype),name,String(ev.created_at||"")>=since7); if(p){ inc(pair(pairAgg,p.restaurant_location_id,p.activity_location_id,intent,market),name,String(ev.created_at||"")>=since7); } } }
 const outingRes = await supabaseAdmin.from("outings").select("*").gte("created_at", since30).limit(50000); if (outingRes.error) errors.push(`outings: ${outingRes.error.message}`); diagnostics.outingsRead=(outingRes.data||[]).length; for (const o of outingRes.data || []) { const r=pick(o,["restaurant_location_id","restaurant_id","selected_restaurant_location_id"]); const a=pick(o,["activity_location_id","activity_id","selected_activity_location_id"]); if(isUuid(r)&&isUuid(a)) diagnostics.outingsWithRestaurantActivityIds++; else { bump(diagnostics,"outings_missing_pair_ids"); continue; } const q=text(pick(o,["raw_query","search_query","query","prompt"]) || pick(o.metadata,["query","rawQuery"])); const cls=classifySearchIntent(q || ""); const market=text(pick(o,["market","requested_market","city","borough","neighborhood"]),100); const status=String(o.status||"").toLowerCase(); const names=["search_result_impression", o.saved_at||status.includes("saved")?"plan_saved":null, o.completed_at||o.completed_no_feedback_at||o.completion_inferred_at||status.includes("completed")?"completed":null, o.last_link_clicked_at||status.includes("link")?"external_link_clicked":null].filter(Boolean) as string[]; for (const intent of cls.allIntents) for (const name of names) { inc(loc(locAgg,r,intent,market,"restaurant"),name,String(o.created_at||"")>=since7); inc(loc(locAgg,a,intent,market,"activity"),name,String(o.created_at||"")>=since7); inc(pair(pairAgg,r,a,intent,market),name,String(o.created_at||"")>=since7); } }
 const locRows=[...locAgg.values()].map(finalizeLoc); const pairRows=[...pairAgg.values()].map(finalizePair); diagnostics.candidateLocationIntentRows=locRows.length; diagnostics.candidatePairRows=pairRows.length; let updatedLoc=0, updatedPair=0; if (locRows.length) { const { error } = await supabaseAdmin.from("location_intent_ml_features").upsert(locRows,{onConflict:"location_id,intent_bucket,market_key,location_type_key"}); if (error) errors.push(`location upsert: ${error.message}`); else updatedLoc=locRows.length; } if (pairRows.length) { const { error } = await supabaseAdmin.from("location_pair_ml_features").upsert(pairRows,{onConflict:"restaurant_location_id,activity_location_id,intent_bucket,market_key"}); if (error) errors.push(`pair upsert: ${error.message}`); else updatedPair=pairRows.length; } diagnostics.upsertLocationIntentRows=updatedLoc; diagnostics.upsertPairRows=updatedPair; diagnostics.recommendation=recommendation(diagnostics, updatedLoc+updatedPair);
 await supabaseAdmin.from("ml_phase2_score_runs").insert({ status: errors.length?"completed_with_errors":"completed", processed_location_intents:locRows.length, updated_location_intents:updatedLoc, processed_pairs:pairRows.length, updated_pairs:updatedPair, error_count:errors.length, score_version:"phase2_rank_v1", metadata:{errors:errors.slice(0,20), diagnostics} });
 return NextResponse.json({ success: errors.length===0, processedLocationIntents:locRows.length, updatedLocationIntents:updatedLoc, processedPairs:pairRows.length, updatedPairs:updatedPair, errors, scoreVersion:"phase2_rank_v1", diagnostics, sampleTopLocationIntentScores: locRows.sort((a,b)=>b.intent_score-a.intent_score).slice(0,5), sampleTopPairScores: pairRows.sort((a,b)=>b.pair_score-a.pair_score).slice(0,5)}); }
export async function GET(req: NextRequest) { return POST(req); }
