import { NextRequest, NextResponse } from "next/server";
import { requireAdminApiRole } from "@/lib/admin-api-auth";
import { ADMIN_PAGE_ACCESS } from "@/lib/admin-permissions";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { classifySearchIntent } from "@/lib/ml/intentBuckets";
import { calculateConfidenceScore, calculateConversionRate, calculateCtr, calculateLocationIntentScore, calculatePairScore, INTENT_SCORE_VERSION, PAIR_SCORE_VERSION } from "@/lib/ml/intentScoring";
export const runtime = "nodejs"; export const dynamic = "force-dynamic"; export const maxDuration = 300;
const IMP = new Set(["search_result_impression","result_impression","result_viewed","location_view","location_viewed","plan_location_view"]);
const CLK = new Set(["result_click","location_click","card_click","plan_location_click","reserve_clicked","reservation_clicked","call_clicked","website_clicked","link_clicked","external_link_clicked"]);
const RSV = new Set(["reserve_clicked","reservation_clicked","reservation_click"]); const CALL = new Set(["call_clicked","call_click"]); const WEB = new Set(["website_clicked","website_click","link_clicked","external_link_clicked"]); const SAVE = new Set(["plan_saved","outing_saved","saved"]); const NEG = new Set(["not_interested","skipped","bad_result","hidden","reported_bad_match"]);
function bearer(req:NextRequest){ const h=req.headers.get("authorization")||""; return h.toLowerCase().startsWith("bearer ") ? h.slice(7).trim() : null; }
async function authorize(req:NextRequest){ if (process.env.NODE_ENV === "development" || (process.env.CRON_SECRET && bearer(req) === process.env.CRON_SECRET)) return null; const { error } = await requireAdminApiRole(ADMIN_PAGE_ACCESS.import); return error; }
const pick=(o:any,keys:string[])=>{ for (const k of keys) if (o?.[k] != null && o[k] !== "") return o[k]; return null; };
const text=(v:any)=> typeof v === "string" ? v.slice(0,500) : v == null ? null : String(v).slice(0,500);
const isUuid=(v:any)=>typeof v === "string" && /^[0-9a-f-]{36}$/i.test(v);
function inc(row:any, event:string, recent7:boolean){ if (IMP.has(event)){row.impressions_30d++; if(recent7)row.impressions_7d++; row.views_30d++; if(recent7)row.views_7d++;} if (CLK.has(event)){row.clicks_30d++; if(recent7)row.clicks_7d++;} if (RSV.has(event)) row.reservation_clicks_30d++; if (CALL.has(event)) row.call_clicks_30d++; if (WEB.has(event)) row.website_clicks_30d++; if (SAVE.has(event)) row.saves_30d++; if (NEG.has(event)) row.negative_signals_30d++; }
function baseLoc(location_id:string,intent_bucket:string,market:string|null,location_type:string|null){ return { location_id,intent_bucket,market,location_type, impressions_7d:0,impressions_30d:0,views_7d:0,views_30d:0,clicks_7d:0,clicks_30d:0,reservation_clicks_30d:0,call_clicks_30d:0,website_clicks_30d:0,saves_30d:0,completed_outings_30d:0,negative_signals_30d:0 }; }
function basePair(r:string,a:string,intent_bucket:string,market:string|null){ return { restaurant_location_id:r,activity_location_id:a,intent_bucket,market,pair_distance_miles:null,estimated_travel_minutes:null, impressions_7d:0,impressions_30d:0,clicks_7d:0,clicks_30d:0,saves_30d:0,completed_outings_30d:0,reservation_clicks_30d:0,call_clicks_30d:0,website_clicks_30d:0,negative_signals_30d:0 }; }
function finalizeLoc(row:any){ row.market_key = row.market || ""; row.location_type_key = row.location_type || ""; const conversions=row.completed_outings_30d+row.reservation_clicks_30d+row.call_clicks_30d+row.website_clicks_30d; const ctr=calculateCtr(row.clicks_30d,row.impressions_30d); const cr=calculateConversionRate(conversions,row.impressions_30d); const intent_score=calculateLocationIntentScore({...row,ctr_30d:ctr,conversion_rate_30d:cr}); return {...row, ctr_30d:ctr, conversion_rate_30d:cr, engagement_score: intent_score, conversion_score: cr*100, confidence_score: calculateConfidenceScore(row.impressions_30d,row.clicks_30d,conversions), intent_score, score_version: INTENT_SCORE_VERSION, updated_at:new Date().toISOString(), metadata:{source:"phase2_recalculate", pii:false}}; }
function finalizePair(row:any){ row.market_key = row.market || ""; const conversions=row.completed_outings_30d+row.reservation_clicks_30d+row.call_clicks_30d+row.website_clicks_30d; const ctr=calculateCtr(row.clicks_30d,row.impressions_30d); const cr=calculateConversionRate(conversions,row.impressions_30d); const pair_score=calculatePairScore({...row,ctr_30d:ctr,conversion_rate_30d:cr}); return {...row, ctr_30d:ctr, conversion_rate_30d:cr, distance_score: row.pair_distance_miles == null ? 0 : Math.max(0,20-Number(row.pair_distance_miles)*5), engagement_score: pair_score, conversion_score: cr*100, confidence_score: calculateConfidenceScore(row.impressions_30d,row.clicks_30d,conversions), pair_score, score_version: PAIR_SCORE_VERSION, updated_at:new Date().toISOString(), metadata:{source:"phase2_recalculate", pii:false}}; }
export async function POST(req: NextRequest) { const authError = await authorize(req); if (authError) return authError; const errors:string[]=[]; const since30=new Date(Date.now()-30*864e5).toISOString(); const since7=new Date(Date.now()-7*864e5).toISOString(); const locAgg=new Map<string,any>(); const pairAgg=new Map<string,any>(); const eventsRes = await supabaseAdmin.from("analytics_events").select("*").gte("created_at", since30).limit(50000); if (eventsRes.error) errors.push(`analytics_events: ${eventsRes.error.message}`); for (const ev of eventsRes.data || []) { const meta=ev.metadata||{}; const loc = pick(ev,["location_id","source_location_id"]) || pick(meta,["location_id","locationId","restaurant_location_id","restaurantLocationId","activity_location_id","activityLocationId","result_location_id","resultLocationId"]); if (!isUuid(loc)) continue; const q = text(ev.query || pick(meta,["query","rawQuery","search_query","searchQuery","prompt"])); const cls=classifySearchIntent(q || ""); const market=text(ev.city || ev.borough || ev.neighborhood || pick(meta,["market","requestedMarket","requested_market","city","borough","neighborhood"])); const ltype=text(ev.location_type || pick(meta,["location_type","locationType","type","resultType"])); for (const intent of cls.allIntents) { const key=`${loc}:${intent}:${market||""}:${ltype||""}`; const row=locAgg.get(key)||baseLoc(loc,intent,market,ltype); inc(row,String(ev.event_name||""),String(ev.created_at||"")>=since7); locAgg.set(key,row); } }
 const searchRes = await supabaseAdmin.from("search_events").select("*").gte("created_at", since30).limit(20000); if (searchRes.error) errors.push(`search_events: ${searchRes.error.message}`); for (const ev of searchRes.data || []) { const q=text(ev.raw_query || ev.normalized_query); if (!q) continue; /* search rows classify future metadata but do not fabricate location rows */ }
 const outingRes = await supabaseAdmin.from("outings").select("*").gte("created_at", since30).limit(50000); if (outingRes.error) errors.push(`outings: ${outingRes.error.message}`); for (const o of outingRes.data || []) { const r=pick(o,["restaurant_location_id","restaurantLocationId"]); const a=pick(o,["activity_location_id","activityLocationId"]); const q=text(pick(o,["raw_query","query","search_query","prompt"])); const cls=classifySearchIntent(q || ""); const market=text(pick(o,["market","requested_market","city","borough","neighborhood"])); const completed=Boolean(o.completed_at||o.completed_no_feedback_at||o.completion_inferred_at||String(o.status||"").includes("complete")); for (const intent of cls.allIntents) { if (isUuid(r)) { const key=`${r}:${intent}:${market||""}:restaurant`; const row=locAgg.get(key)||baseLoc(r,intent,market,"restaurant"); if (completed) row.completed_outings_30d++; locAgg.set(key,row); } if (isUuid(a)) { const key=`${a}:${intent}:${market||""}:activity`; const row=locAgg.get(key)||baseLoc(a,intent,market,"activity"); if (completed) row.completed_outings_30d++; locAgg.set(key,row); } if (isUuid(r)&&isUuid(a)) { const key=`${r}:${a}:${intent}:${market||""}`; const row=pairAgg.get(key)||basePair(r,a,intent,market); row.impressions_30d++; if (String(o.created_at||"")>=since7) row.impressions_7d++; if (completed) row.completed_outings_30d++; if (o.saved_at) row.saves_30d++; if (o.last_link_clicked_at) row.clicks_30d++; pairAgg.set(key,row); } } }
 const locRows=[...locAgg.values()].map(finalizeLoc); const pairRows=[...pairAgg.values()].map(finalizePair); let updatedLoc=0, updatedPair=0; if (locRows.length) { const { error } = await supabaseAdmin.from("location_intent_ml_features").upsert(locRows,{onConflict:"location_id,intent_bucket,market_key,location_type_key"}); if (error) errors.push(`location upsert: ${error.message}`); else updatedLoc=locRows.length; } if (pairRows.length) { const { error } = await supabaseAdmin.from("location_pair_ml_features").upsert(pairRows,{onConflict:"restaurant_location_id,activity_location_id,intent_bucket,market_key"}); if (error) errors.push(`pair upsert: ${error.message}`); else updatedPair=pairRows.length; }
 await supabaseAdmin.from("ml_phase2_score_runs").insert({ status: errors.length?"completed_with_errors":"completed", processed_location_intents:locRows.length, updated_location_intents:updatedLoc, processed_pairs:pairRows.length, updated_pairs:updatedPair, error_count:errors.length, score_version:"phase2_rank_v1", metadata:{errors:errors.slice(0,20)} });
 return NextResponse.json({ success: errors.length===0, processedLocationIntents:locRows.length, updatedLocationIntents:updatedLoc, processedPairs:pairRows.length, updatedPairs:updatedPair, errors, scoreVersion:"phase2_rank_v1", sampleTopLocationIntentScores: locRows.sort((a,b)=>b.intent_score-a.intent_score).slice(0,5), sampleTopPairScores: pairRows.sort((a,b)=>b.pair_score-a.pair_score).slice(0,5)}); }
export async function GET(req: NextRequest) { return POST(req); }
