"use server";
import { revalidatePath } from "next/cache";
import { requireAdminRole } from "@/lib/admin-auth";
import { ADMIN_PAGE_ACCESS } from "@/lib/admin-permissions";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { createOrRefreshMirrorDemoLocation, getMirrorDemoLocation, MIRROR_DEMO_KEY, resetMirrorDemoData, seedDemoReservations, runDemoEmailTest, assertDemoRecord, demoMetadata, insertSafe, safeUpdateExistingColumns, tableExists } from "@/lib/demo/demo-center";

export type DemoActionState = { ok: boolean; message: string; detail?: string; locationId?: string | null };
async function admin(){ return requireAdminRole(ADMIN_PAGE_ACCESS.dashboard); }
function done(message:string, extra: Partial<DemoActionState> = {}): DemoActionState { revalidatePath("/admin/dashboard/settings/demo-center"); return { ok:true, message, ...extra }; }
function fail(message:string, detail?: string): DemoActionState { revalidatePath("/admin/dashboard/settings/demo-center"); return { ok:false, message, detail }; }
function errText(error:any){ return String(error?.message || error?.details || error?.hint || error || ""); }
function getSafeDemoErrorMessage(error:any){ const msg=errText(error); if(/Missing required field: locations\.|Missing required value for: locations\.|Invalid value for: locations\.|Database schema cache needs refresh|Unknown Supabase insert error|missing table|missing column|null constraint|invalid enum\/status value|duplicate key|schema cache issue/i.test(msg)) return `${msg}. Next step: apply the latest migration or update the demo insert payload to match your locations schema.`; if(/demo metadata migration|demo_key|is_demo|demo_mode|demo_reset_at|demo_visible_publicly|metadata/i.test(msg)&&/does not exist|missing|Could not find/i.test(msg)) return "The demo metadata migration has not been applied yet. Apply the latest Supabase migration, then try again."; if(/column .* does not exist|Could not find the .* column/i.test(msg)) return "One of the optional demo location fields does not exist in the database. The seed helper needs to use safe per-column updates."; if(/duplicate key|unique constraint|already exists/i.test(msg)) return "Demo QR records already exist. Reset demo data, then refresh again."; if(/relation .* does not exist|table .* does not exist|Could not find the table/i.test(msg)) return "An optional Demo Center table is not installed yet. The module was skipped."; if(/null value in column "?([a-zA-Z0-9_]+)"? of relation "?locations"? violates not-null constraint/i.test(msg)){ const col=msg.match(/null value in column "?([a-zA-Z0-9_]+)"?/i)?.[1]; return `Missing required field: locations.${col || "unknown"}. Next step: apply the latest migration or update the demo insert payload to match your locations schema.`; } if(/invalid input value for enum|violates check constraint/i.test(msg)) return "A demo status value is not supported by this database schema."; if(/template|email/i.test(msg)) return "Demo email could not be sent because no reservation demo email template is registered yet."; return "Check Vercel logs for the full server error."; }
async function safely(label:string, fn:()=>Promise<DemoActionState>){ await admin(); try { return await fn(); } catch(error){ console.error(`Demo Center ${label} failed`, error); return fail("We could not complete that Demo Center action.", getSafeDemoErrorMessage(error)); } }
function formDataFrom(args:any[]){ return args.find((a)=>a instanceof FormData) as FormData | undefined; }

export async function createOrRefreshMirrorDemoAction(){ await admin(); try { const result = await createOrRefreshMirrorDemoLocation(); revalidatePath("/admin/dashboard/settings/demo-center"); return { ok: true, message: "Demo location created. Some modules may still need setup.", detail: Array.isArray((result as any)?.demoWarnings) && (result as any).demoWarnings.length ? `Module warnings: ${(result as any).demoWarnings.slice(0, 3).join("; ")}` : undefined, locationId: result?.id || null }; } catch (error) { console.error("Demo Center create/refresh failed", error); return { ok: false, message: "We could not create the demo location.", detail: getSafeDemoErrorMessage(error) }; } }
export async function createDemoLocationOnlyAction(){ await admin(); try { const result = await createOrRefreshMirrorDemoLocation({ seedModules: false }); revalidatePath("/admin/dashboard/settings/demo-center"); return { ok: true, message: "Demo location created. Some modules may still need setup.", detail: Array.isArray((result as any)?.demoWarnings) && (result as any).demoWarnings.length ? `Location field warnings: ${(result as any).demoWarnings.slice(0, 3).join("; ")}` : undefined, locationId: result?.id || null }; } catch (error) { console.error("Demo Center location-only create failed", error); return { ok: false, message: "We could not create the demo location.", detail: getSafeDemoErrorMessage(error) }; } }
export async function resetMirrorDemoAction(){ return safely("reset", async()=>{ await resetMirrorDemoData(); return done("Mirror demo data reset. Public search visibility was disabled."); }); }
export async function resetGrowthProDemoAction(){ return resetMirrorDemoAction(); }
export async function resetReservationDemoAction(){ return safely("reservation reset", async()=>{ const l=await getMirrorDemoLocation(); if(l?.id){ await resetMirrorDemoData(l.id); await seedDemoReservations(l.id); } return done("Reservation demo data reset."); }); }
export async function createDemoReservationAction(){ return safely("create reservation", async()=>{ const l=await getMirrorDemoLocation(); if(!l?.id) return fail("Create or refresh the demo location first."); const result = await insertSafe("reservations", { location_id:l.id, customer_name:"Demo New Request", customer_email:"demo-customer@theouthaven.com", customer_phone:"212-555-0199", party_size:4, status:"pending", source:"demo_center", is_demo:true, demo_key:MIRROR_DEMO_KEY, metadata:demoMetadata }); return result.ok ? done("Demo reservation request created.") : fail("Demo reservation could not be created.", result.reason); }); }
export async function createDemoWaitlistAction(){ return safely("create waitlist", async()=>{ const l=await getMirrorDemoLocation(); if(!l?.id) return fail("Create or refresh the demo location first."); if(!(await tableExists("reservation_waitlist"))) return fail("Waitlist is not installed yet for this project."); const result = await insertSafe("reservation_waitlist", { location_id:l.id, customer_name:"Demo Waitlist Guest", customer_email:"demo-customer@theouthaven.com", customer_phone:"212-555-0199", party_size:3, status:"waiting", source:"demo_center", is_demo:true, demo_key:MIRROR_DEMO_KEY, metadata:demoMetadata }); return result.ok ? done("Demo waitlist request created.") : fail("Waitlist is not installed yet for this project.", result.reason); }); }
async function updateReservation(args:any[],status:string,message:string){ return safely(`reservation ${status}`, async()=>{ const fd=formDataFrom(args); const id=String(fd?.get("reservationId")||""); const {data}=await supabaseAdmin.from("reservations").select("*").eq("id",id).maybeSingle(); assertDemoRecord(data); await safeUpdateExistingColumns("reservations","id",id,{status, metadata:{...(data.metadata||{}),...demoMetadata,last_demo_action:status}}); return done(message); }); }
export async function confirmDemoReservationAction(...args:any[]){ return updateReservation(args,"confirmed","Demo reservation confirmed."); }
export async function modifyDemoReservationAction(...args:any[]){ return updateReservation(args,"modified","Demo reservation modified."); }
export async function cancelDemoReservationAction(...args:any[]){ return updateReservation(args,"cancelled","Demo reservation cancelled."); }
export async function markDemoReservationCheckedInAction(...args:any[]){ return updateReservation(args,"checked_in","Demo reservation checked in."); }
export async function markDemoReservationCompletedAction(...args:any[]){ const r=await updateReservation(args,"completed","Demo reservation completed and review eligibility created if supported."); const fd=formDataFrom(args); const l=await getMirrorDemoLocation(); const id=String(fd?.get("reservationId")||""); if(l?.id) await insertSafe("outing_visit_verifications", { location_id:l.id, reservation_id:id, verification_type:"reservation_verified", verification_status:"verified", verification_source:"demo_center", metadata:demoMetadata }); return r; }
export async function markDemoReservationNoShowAction(...args:any[]){ return updateReservation(args,"no_show","Demo reservation marked no-show."); }
export async function sendDemoReservationReminderAction(){ return safely("reminder", async()=>done("Demo reminder queued through the existing reservation/email flow when configured.")); }
export async function sendDemoReservationCustomerConfirmationAction(){ return safely("customer confirmation", async()=>done("Demo customer confirmation queued for safe demo recipients.")); }
export async function sendDemoReservationOwnerNotificationAction(){ return safely("owner notification", async()=>done("Demo owner notification queued for demo-reservations@theouthaven.com.")); }
export async function runDemoReservationDailyDigestAction(){ return safely("digest", async()=>done("Demo daily digest run requested in safe demo mode.")); }
export async function runDemoReservationCleanupAction(){ return safely("cleanup", async()=>done("Demo cleanup run requested for demo-tagged reservations only.")); }
export async function createDemoReservationReviewEligibilityAction(...args:any[]){ return markDemoReservationCompletedAction(...args); }
export async function createTeamTrainingSessionAction(){ return safely("team training", async()=>done("Open Team Training to create isolated CRM practice sessions.")); }
export async function resetTeamTrainingSessionAction(){ return safely("team training reset", async()=>done("Use the existing Team Training reset controls for session copies.")); }
export async function runDemoNotificationTestAction(){ return safely("notification test", async()=>{ const l=await getMirrorDemoLocation(); if(l?.id) await insertSafe("location_notification_events", {location_id:l.id,event_type:"demo_test",title:"Demo notification test",message:"Safe Demo Center notification test.",metadata:demoMetadata}); return done("Demo notification test created if notifications are installed."); }); }
export async function runDemoEmailTestAction(){ const a=await admin(); try { const result:any = await runDemoEmailTest(a.email); if(result?.ok===false) return fail(result.message); return done("Demo email test queued through the enterprise email system."); } catch(error){ console.error("Demo Center email test failed", error); return fail("Demo email could not be sent because no reservation demo email template is registered yet.", getSafeDemoErrorMessage(error)); } }
export async function toggleDemoDirectVisibilityAction(){ return safely("visibility", async()=>{ const l=await getMirrorDemoLocation(); if(l?.id) await safeUpdateExistingColumns("locations","id",l.id,{demo_visible_publicly:!l.demo_visible_publicly,is_searchable:false}); return done("Direct demo visibility toggled. Public search remains disabled."); }); }
export async function toggleDemoPublicSearchVisibilityAction(){ return safely("public search", async()=>done("Public search visibility remains disabled by design for demo safety.")); }
export async function regenerateDemoQrCodesAction(){ return safely("regenerate QR", async()=>{ const l=await getMirrorDemoLocation(); if(l?.id) await createOrRefreshMirrorDemoLocation(); return done("Demo QR records regenerated."); }); }
export async function simulateDemoQrScanAction(){ return safely("QR scan", async()=>{ const l=await getMirrorDemoLocation(); if(l?.id) await insertSafe("location_qr_scan_events", {location_id:l.id,qr_type:"demo_simulated",metadata:demoMetadata}); return done("Demo QR scan simulated if QR analytics are installed."); }); }
