import "server-only";
import { supabaseAdmin } from "@/lib/supabase-admin";
import type { PipelineKey } from "../pipelines";
import { forecastTotals, opportunityHealth } from "./forecasting";
import type { OpportunityRecord } from "./types";
export async function listOpportunities(input: { pipeline: PipelineKey; stage?: string; forecast?: string; risk?: string; search?: string; view?: string; page?: number }) {
  const page = Math.max(1, input.page ?? 1), size = input.view === "board" ? 250 : 25;
  let query = supabaseAdmin.from("crm_opportunities").select("*,crm_accounts(id,name),locations:primary_location_id(id,name),crm_tasks(count),crm_opportunity_contacts(count)", { count: "exact" }).eq("pipeline_key", input.pipeline).is("archived_at", null).order("last_stage_changed_at", { ascending: false }).range((page - 1) * size, page * size - 1);
  if (input.stage) query = query.eq("stage", input.stage); if (input.forecast) query = query.eq("forecast_category", input.forecast); if (input.risk) query = query.eq("risk_level", input.risk); if (input.search) query = query.ilike("name", `%${input.search.replace(/[%_]/g, "\\$&")}%`);
  const [{ data, error, count }, stages] = await Promise.all([query, getPipelineStages(input.pipeline)]); if (error) throw error;
  const rows = (data ?? []) as unknown as OpportunityRecord[]; return { rows: rows.map((o) => ({ ...o, health: opportunityHealth(o) })), count: count ?? 0, page, size, stages, totals: forecastTotals(rows) };
}
export async function getPipelineStages(pipeline: PipelineKey) { const { data, error } = await supabaseAdmin.from("crm_pipeline_stages").select("*,crm_pipelines!inner(pipeline_key)").eq("crm_pipelines.pipeline_key", pipeline).order("display_order"); if (error) throw error; return data ?? []; }
export async function getOpportunityDetail(id: string) { const [opportunity, products, contacts, stages, history, fieldHistory, tasks, activities] = await Promise.all([supabaseAdmin.from("crm_opportunities").select("*,crm_accounts(*),locations:primary_location_id(id,name,address,city,state),crm_contacts:primary_contact_id(*)").eq("id", id).is("archived_at", null).single(),supabaseAdmin.from("crm_opportunity_products").select("*").eq("opportunity_id", id).limit(100),supabaseAdmin.from("crm_opportunity_contacts").select("*,crm_contacts(*)").eq("opportunity_id", id).limit(100),supabaseAdmin.from("crm_opportunity_stage_history").select("*").eq("opportunity_id", id).order("entered_at"),supabaseAdmin.from("crm_opportunity_stage_history").select("*").eq("opportunity_id", id).order("entered_at", { ascending: false }).limit(100),supabaseAdmin.from("crm_opportunity_history").select("*").eq("opportunity_id", id).order("changed_at", { ascending: false }).limit(100),supabaseAdmin.from("crm_tasks").select("*").eq("opportunity_id", id).is("archived_at", null).order("due_at").limit(100),supabaseAdmin.from("crm_activities").select("*").eq("opportunity_id", id).order("occurred_at", { ascending: false }).limit(100)]); if (opportunity.error) throw opportunity.error; return { opportunity: opportunity.data, products: products.data ?? [], contacts: contacts.data ?? [], stages: stages.data ?? [], history: history.data ?? [], fieldHistory: fieldHistory.data ?? [], tasks: tasks.data ?? [], activities: activities.data ?? [] }; }
export async function getForecast(input: { start: string; end: string; pipeline?: string }) { let q = supabaseAdmin.from("crm_opportunities").select("*").gte("expected_close_date", input.start).lte("expected_close_date", input.end).is("archived_at", null); if (input.pipeline) q = q.eq("pipeline_key", input.pipeline); const { data, error } = await q; if (error) throw error; const rows = data as OpportunityRecord[]; const { data: snapshots } = await supabaseAdmin.from("crm_forecast_snapshots").select("*").gte("snapshot_date", input.start).lte("snapshot_date", input.end).order("snapshot_date"); return { rows, totals: forecastTotals(rows), snapshots: snapshots ?? [] }; }
