import Link from "next/link";
import { addExperienceSlotAction, createExperienceAction, setExperienceStatusAction } from "@/app/experiences/manage-actions";

type ExperienceRow = { id:string; title:string; description:string|null; category:string|null; status:string; searchable:boolean; duration_minutes:number; min_party_size:number; max_party_size:number; price_per_person:number|string; city:string|null; state:string|null; created_at:string };
type SlotRow = { id:string; experience_id:string; starts_at:string; ends_at:string; capacity:number; status:string };
type BookingRow = { id:string; experience_id:string; customer_name:string; customer_email:string; party_size:number; checked_in_count:number; status:string; checkin_code:string; created_at:string };

export default function CreatorExperienceManager({ ownerType, ownerId, experiences, slots, bookings }: { ownerType:"organization"|"location"; ownerId:string; experiences:ExperienceRow[]; slots:SlotRow[]; bookings:BookingRow[] }) {
  const hiddenName = ownerType === "organization" ? "organization_id" : "location_id";
  return <div className="space-y-6">
    <section className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#ff5570]">Create</p><h2 className="mt-1 text-2xl font-black">New Experience</h2><p className="mt-1 text-sm text-white/45">Create the offering first, then add bookable times below.</p></div><Link href="/experiences/check-in" className="rounded-xl border border-white/10 bg-white/[.05] px-4 py-3 text-sm font-black">Open Check-in Scanner</Link></div>
      <form action={createExperienceAction} className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input type="hidden" name={hiddenName} value={ownerId}/><input name="title" required placeholder="Experience title" className="rounded-xl border border-white/10 bg-black/30 p-3"/><input name="category" placeholder="Category" className="rounded-xl border border-white/10 bg-black/30 p-3"/><input name="venue_name" placeholder="Venue" className="rounded-xl border border-white/10 bg-black/30 p-3"/><input name="city" placeholder="City" className="rounded-xl border border-white/10 bg-black/30 p-3"/><input name="address" placeholder="Address" className="rounded-xl border border-white/10 bg-black/30 p-3"/><input name="state" defaultValue="NY" placeholder="State" className="rounded-xl border border-white/10 bg-black/30 p-3"/><input name="zip_code" placeholder="ZIP" className="rounded-xl border border-white/10 bg-black/30 p-3"/><input name="image_url" type="url" placeholder="Image URL" className="rounded-xl border border-white/10 bg-black/30 p-3"/><input name="duration_minutes" type="number" min="15" defaultValue="60" placeholder="Duration minutes" className="rounded-xl border border-white/10 bg-black/30 p-3"/><input name="min_party_size" type="number" min="1" defaultValue="1" placeholder="Min party" className="rounded-xl border border-white/10 bg-black/30 p-3"/><input name="max_party_size" type="number" min="1" defaultValue="10" placeholder="Max party" className="rounded-xl border border-white/10 bg-black/30 p-3"/><input name="price_per_person" type="number" min="0" step="0.01" defaultValue="0" placeholder="Price per person" className="rounded-xl border border-white/10 bg-black/30 p-3"/><textarea name="description" placeholder="What should guests expect?" className="min-h-28 rounded-xl border border-white/10 bg-black/30 p-3 md:col-span-2 xl:col-span-3"/><button className="rounded-xl bg-[#e1062a] px-4 py-3 font-black">Create Draft Experience</button></form>
    </section>

    <section className="space-y-4">{experiences.length ? experiences.map((experience) => { const experienceSlots=slots.filter(s=>s.experience_id===experience.id); const experienceBookings=bookings.filter(b=>b.experience_id===experience.id); const checkedIn=experienceBookings.reduce((sum,b)=>sum+b.checked_in_count,0); return <article key={experience.id} className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#ff5570]">{experience.category||"Experience"}</p><h3 className="mt-1 text-xl font-black">{experience.title}</h3><p className="mt-1 text-xs text-white/40">{experience.status} · {experience.duration_minutes} min · ${Number(experience.price_per_person).toFixed(2)}/person</p></div><div className="flex flex-wrap gap-2"><Link href={`/experiences/${experience.id}`} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-black">Public Page</Link><form action={setExperienceStatusAction}><input type="hidden" name="experience_id" value={experience.id}/><input type="hidden" name="status" value={experience.status==="published"?"paused":"published"}/><button className="rounded-xl bg-[#e1062a] px-3 py-2 text-xs font-black">{experience.status==="published"?"Pause":"Publish"}</button></form></div></div>
      <div className="mt-4 grid gap-3 md:grid-cols-4"><Metric label="Time slots" value={experienceSlots.length}/><Metric label="Bookings" value={experienceBookings.length}/><Metric label="Booked guests" value={experienceBookings.reduce((s,b)=>s+b.party_size,0)}/><Metric label="Checked in" value={checkedIn}/></div>
      <form action={addExperienceSlotAction} className="mt-4 grid gap-3 md:grid-cols-[1fr_150px_150px_auto]"><input type="hidden" name="experience_id" value={experience.id}/><input name="starts_at" type="datetime-local" required className="rounded-xl border border-white/10 bg-black/30 p-3"/><input name="duration_minutes" type="number" min="15" defaultValue={experience.duration_minutes} className="rounded-xl border border-white/10 bg-black/30 p-3"/><input name="capacity" type="number" min="1" defaultValue={experience.max_party_size} className="rounded-xl border border-white/10 bg-black/30 p-3"/><button className="rounded-xl border border-white/10 bg-white/[.06] px-4 py-3 font-black">Add Time</button></form>
      {experienceSlots.length ? <div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{experienceSlots.slice(0,12).map(slot=><div key={slot.id} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"><b>{new Date(slot.starts_at).toLocaleString()}</b><p className="mt-1 text-xs text-white/40">Capacity {slot.capacity} · {slot.status}</p></div>)}</div>:null}
      {experienceBookings.length ? <div className="mt-5"><h4 className="text-sm font-black">Recent bookings</h4><div className="mt-2 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{experienceBookings.slice(0,9).map(b=><div key={b.id} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"><b>{b.customer_name}</b><p className="text-xs text-white/40">{b.customer_email}</p><p className="mt-1 text-xs font-black">{b.checked_in_count}/{b.party_size} checked in · code {b.checkin_code}</p></div>)}</div></div>:null}
    </article>}) : <div className="rounded-3xl border border-white/10 bg-white/[.03] p-8 text-center text-white/40">No experiences yet.</div>}</section>
  </div>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-xs text-white/40">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
