"use client";

import Link from "next/link";
import type { ReactNode } from "react";
import { useMemo, useState } from "react";
import { addExperienceSlotAction, createExperienceAction, setExperienceStatusAction } from "@/app/experiences/manage-actions";

type Experience={id:string;title:string;slug:string|null;description:string|null;category:string|null;status:string;searchable:boolean;duration_minutes:number;min_party_size:number;max_party_size:number;price_per_person:number|string;created_at:string};
type Slot={id:string;experience_id:string;starts_at:string;ends_at:string;capacity:number;status:string};
type Booking={id:string;experience_id:string;party_size:number;checked_in_count:number;status:string;created_at:string};
type Metrics={experiences:number;published:number;bookings:number;guests:number;checkedIn:number;estimatedRevenue:number;upcomingSlots:number};
const STEPS=["Basics","Guest details","Pricing","Public URL","Review"];
function slugify(v:string){return v.toLowerCase().normalize("NFKD").replace(/[’']/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,90);}

export default function LocationExperienceManager({locationId,location,experiences,slots,bookings,metrics}:{locationId:string;location:{name:string;address:string|null;city:string|null;state:string|null;zip_code:string|null};experiences:Experience[];slots:Slot[];bookings:Booking[];metrics:Metrics}){
 const[step,setStep]=useState(0);const[title,setTitle]=useState("");const[slug,setSlug]=useState("");const generated=useMemo(()=>slug||slugify(title),[slug,title]);
 return <div className="space-y-6">
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Experiences" value={metrics.experiences}/><Metric label="Published" value={metrics.published}/><Metric label="Bookings" value={metrics.bookings}/><Metric label="Guests booked" value={metrics.guests}/><Metric label="Checked in" value={metrics.checkedIn}/><Metric label="Upcoming times" value={metrics.upcomingSlots}/><Metric label="Estimated booking value" value={money(metrics.estimatedRevenue)}/></section>
  <section className="rounded-3xl border border-white/10 bg-white/[.035] p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#ff5570]">Create Experience</p><h2 className="mt-1 text-2xl font-black">Guided experience setup</h2><p className="mt-1 text-sm text-white/45">Your venue details are already connected to this location.</p></div><span className="rounded-full border border-white/10 px-3 py-2 text-xs font-black">Step {step+1} of {STEPS.length}</span></div>
   <div className="mt-5 flex gap-2 overflow-x-auto">{STEPS.map((label,index)=><button type="button" key={label} onClick={()=>setStep(index)} className={`shrink-0 rounded-full border px-4 py-2 text-xs font-black ${index===step?"border-[#ff2142]/70 bg-[#e1062a]/20":"border-white/10 bg-black/20 text-white/45"}`}>{index+1}. {label}</button>)}</div>
   <form action={createExperienceAction} className="mt-6 space-y-5"><input type="hidden" name="location_id" value={locationId}/><input type="hidden" name="venue_name" value={location.name}/><input type="hidden" name="address" value={location.address||""}/><input type="hidden" name="city" value={location.city||""}/><input type="hidden" name="state" value={location.state||"NY"}/><input type="hidden" name="zip_code" value={location.zip_code||""}/>
    <div className={step===0?"grid gap-3 md:grid-cols-2":"hidden"}><Field label="Experience name"><input name="title" required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Couples Paint & Sip" className="input"/></Field><Field label="Category"><input name="category" placeholder="Dining, workshop, nightlife..." className="input"/></Field><Field label="Cover image URL"><input name="image_url" type="url" className="input" placeholder="https://..."/></Field><Field label="Description"><textarea name="description" className="input min-h-28" placeholder="What should guests expect?"/></Field></div>
    <div className={step===1?"grid gap-3 md:grid-cols-3":"hidden"}><Field label="Duration (minutes)"><input name="duration_minutes" type="number" min="15" defaultValue="60" className="input"/></Field><Field label="Minimum party"><input name="min_party_size" type="number" min="1" defaultValue="1" className="input"/></Field><Field label="Maximum party"><input name="max_party_size" type="number" min="1" defaultValue="10" className="input"/></Field><div className="md:col-span-3 rounded-2xl border border-white/10 bg-black/20 p-4 text-sm text-white/55">Availability is added immediately after the draft is created, so you can publish only when bookable times are ready.</div></div>
    <div className={step===2?"space-y-3":"hidden"}><Field label="Price per person"><input name="price_per_person" type="number" min="0" step="0.01" defaultValue="0" className="input"/></Field><p className="text-xs text-white/40">Free experiences can use $0. Paid experience booking value is shown in your dashboard from booked guests × current experience price.</p></div>
    <div className={step===3?"space-y-3":"hidden"}><p className="text-sm text-white/55">The public URL is generated from the experience name. Customize it if you want.</p><div className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-xs font-black uppercase tracking-[.14em] text-white/40">Public URL</p><div className="mt-2 flex flex-wrap items-center gap-1 text-sm"><span className="text-white/45">theouthaven.com/experiences/</span><input name="slug" value={generated} onChange={e=>setSlug(slugify(e.target.value))} className="min-w-[220px] flex-1 rounded-lg border border-white/10 bg-black/30 px-3 py-2 font-black"/></div></div></div>
    <div className={step===4?"space-y-4":"hidden"}><div className="rounded-2xl border border-white/10 bg-black/20 p-5"><p className="text-sm font-black">Create your draft</p><p className="mt-1 text-sm text-white/45">After creation, add available dates and times below. Published experiences automatically appear on your TheOutHaven location page and hosted website.</p></div><button className="w-full rounded-xl bg-[#e1062a] px-4 py-3 font-black">Create Draft Experience</button></div>
    <div className="flex justify-between gap-3"><button type="button" disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))} className="rounded-xl border border-white/10 px-4 py-3 text-sm font-black disabled:opacity-30">Back</button>{step<STEPS.length-1?<button type="button" onClick={()=>setStep(s=>Math.min(STEPS.length-1,s+1))} className="rounded-xl bg-white px-4 py-3 text-sm font-black text-black">Continue</button>:null}</div>
   </form></section>
  <section className="space-y-4"><h2 className="text-xl font-black">Your Experiences</h2>{experiences.length?experiences.map(exp=>{const expSlots=slots.filter(s=>s.experience_id===exp.id);const expBookings=bookings.filter(b=>b.experience_id===exp.id);return <article key={exp.id} className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#ff5570]">{exp.category||"Experience"}</p><h3 className="mt-1 text-xl font-black">{exp.title}</h3><p className="mt-1 text-xs text-white/40">{exp.status} · {exp.duration_minutes} min · ${Number(exp.price_per_person).toFixed(2)}/person</p></div><div className="flex gap-2"><Link href={`/experiences/${exp.slug||exp.id}`} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-black">Public Page</Link><form action={setExperienceStatusAction}><input type="hidden" name="experience_id" value={exp.id}/><input type="hidden" name="status" value={exp.status==="published"?"paused":"published"}/><button className="rounded-xl bg-[#e1062a] px-3 py-2 text-xs font-black">{exp.status==="published"?"Pause":"Publish"}</button></form></div></div><div className="mt-4 grid gap-3 md:grid-cols-3"><Metric label="Times" value={expSlots.length}/><Metric label="Bookings" value={expBookings.length}/><Metric label="Guests" value={expBookings.reduce((s,b)=>s+b.party_size,0)}/></div><form action={addExperienceSlotAction} className="mt-4 grid gap-3 md:grid-cols-[1fr_150px_150px_auto]"><input type="hidden" name="experience_id" value={exp.id}/><input name="starts_at" type="datetime-local" required className="input"/><input name="duration_minutes" type="number" min="15" defaultValue={exp.duration_minutes} className="input"/><input name="capacity" type="number" min="1" defaultValue={exp.max_party_size} className="input"/><button className="rounded-xl border border-white/10 bg-white/[.06] px-4 py-3 font-black">Add Time</button></form></article>}):<div className="rounded-2xl border border-white/10 p-6 text-center text-white/40">No experiences yet.</div>}</section>
  <style jsx global>{`.input{width:100%;border-radius:.75rem;border:1px solid rgba(255,255,255,.1);background:rgba(0,0,0,.3);padding:.75rem;color:white}.input::placeholder{color:rgba(255,255,255,.3)}`}</style>
 </div>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-xs text-white/40">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="text-xs font-bold text-white/55">{label}<div className="mt-1">{children}</div></label>}
function money(value:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value)}
