"use client";

import Link from "next/link";
import type { ReactNode } from "react";
import { useMemo, useState } from "react";
import { addExperienceSlotAction, createExperienceAction, setExperienceStatusAction } from "@/app/experiences/manage-actions";
import VisualDateTimePicker from "@/components/forms/VisualDateTimePicker";

type Experience={id:string;title:string;slug:string|null;description:string|null;category:string|null;status:string;searchable:boolean;duration_minutes:number;min_party_size:number;max_party_size:number;price_per_person:number|string;created_at:string};
type Slot={id:string;experience_id:string;starts_at:string;ends_at:string;capacity:number;status:string};
type Booking={id:string;experience_id:string;party_size:number;checked_in_count:number;status:string;created_at:string};
type Metrics={experiences:number;published:number;bookings:number;guests:number;checkedIn:number;estimatedRevenue:number;upcomingSlots:number};

const inputClass="w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm font-semibold text-white outline-none transition placeholder:text-white/25 focus:border-[#ff2142]/60 focus:ring-4 focus:ring-[#e1062a]/10";
function slugify(value:string){return value.toLowerCase().normalize("NFKD").replace(/[’']/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,90)}
function Step({number,title,description,children}:{number:number;title:string;description:string;children:ReactNode}){return <section className="rounded-3xl border border-white/10 bg-gradient-to-br from-[#111722] to-[#090c12] p-5 sm:p-6"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#e1062a]/15 text-sm font-black text-[#ff6b86]">{number}</span><div><h2 className="text-xl font-black">{title}</h2><p className="mt-1 text-sm font-semibold text-white/45">{description}</p></div></div><div className="mt-5">{children}</div></section>}
function Field({label,children,optional=false}:{label:string;children:ReactNode;optional?:boolean}){return <label className="grid gap-1.5"><span className="text-xs font-black text-white/60">{label} {optional?<span className="font-semibold text-white/30">Optional</span>:<span className="text-[#ff6b86]">* Required</span>}</span>{children}</label>}

export default function LocationExperienceManager({locationId,location,experiences,slots,bookings:_bookings,metrics:_metrics}:{locationId:string;location:{name:string;address:string|null;city:string|null;state:string|null;zip_code:string|null};experiences:Experience[];slots:Slot[];bookings:Booking[];metrics:Metrics}){
  const[title,setTitle]=useState("");
  const[slug,setSlug]=useState("");
  const generated=useMemo(()=>slug||slugify(title),[slug,title]);
  const readinessChecks=[Boolean(title.trim()),Boolean(generated),true,true];
  const readiness=Math.round((readinessChecks.filter(Boolean).length/readinessChecks.length)*100);

  return <div className="space-y-5">
    <section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_290px]">
      <div className="rounded-3xl border border-white/10 bg-gradient-to-br from-[#111722] to-[#090c12] p-5 sm:p-6"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#e1062a]/15 text-sm font-black text-[#ff6b86]">1</span><div><h2 className="text-xl font-black">Choose the experience you are setting up</h2><p className="mt-1 text-sm font-semibold text-white/45">Create a new experience below or open one you already offer to see its bookings and guest activity.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{experiences.slice(0,6).map(exp=><Link key={exp.id} href={`/locations/dashboard/events-experiences/experiences/${exp.id}`} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4 transition hover:border-white/20 hover:bg-white/[0.05]"><p className="truncate text-sm font-black">{exp.title}</p><p className="mt-1 text-xs font-semibold text-white/35">{exp.status} · {exp.duration_minutes} min</p><p className="mt-3 text-xs font-black text-[#ff6b86]">View overview →</p></Link>)}{!experiences.length?<div className="rounded-2xl border border-dashed border-white/10 p-5 text-sm font-semibold text-white/40">No experiences yet. Start with the setup below.</div>:null}</div></div>
      <aside className="rounded-3xl border border-white/10 bg-white/[0.04] p-5"><p className="text-xs font-black uppercase tracking-[0.18em] text-white/35">Experience readiness</p><div className="mt-3 flex items-end gap-2"><p className="text-4xl font-black">{readiness}%</p><p className="pb-1 text-xs font-bold text-white/30">new experience</p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#ff2142]" style={{width:`${readiness}%`}}/></div><p className="mt-4 text-sm font-semibold leading-6 text-white/45">The experience stays a draft until you publish it. Add at least one available time during setup so it can be bookable immediately.</p></aside>
    </section>

    <form action={createExperienceAction} className="space-y-5">
      <input type="hidden" name="location_id" value={locationId}/><input type="hidden" name="venue_name" value={location.name}/><input type="hidden" name="address" value={location.address||""}/><input type="hidden" name="city" value={location.city||""}/><input type="hidden" name="state" value={location.state||"NY"}/><input type="hidden" name="zip_code" value={location.zip_code||""}/>
      <Step number={2} title="Experience basics" description="Give guests a clear name, category, description, and cover image."><div className="grid gap-4 md:grid-cols-2"><Field label="Experience name"><input name="title" required value={title} onChange={event=>setTitle(event.target.value)} placeholder="Couples Paint & Sip" className={inputClass}/></Field><Field label="Category"><input name="category" required placeholder="Dining, workshop, nightlife..." className={inputClass}/></Field><Field label="Cover image URL" optional><input name="image_url" type="url" placeholder="https://..." className={inputClass}/></Field><Field label="Description"><textarea name="description" required rows={4} placeholder="What should guests expect?" className={inputClass}/></Field></div></Step>
      <Step number={3} title="Guest setup" description="Set the duration and party-size rules for each booking."><div className="grid gap-4 md:grid-cols-3"><Field label="Duration (minutes)"><input name="duration_minutes" type="number" min="15" defaultValue="60" required className={inputClass}/></Field><Field label="Minimum party"><input name="min_party_size" type="number" min="1" defaultValue="1" required className={inputClass}/></Field><Field label="Maximum party"><input name="max_party_size" type="number" min="1" defaultValue="10" required className={inputClass}/></Field></div></Step>
      <Step number={4} title="Pricing" description="Set the per-person price. Use $0 for a free experience."><div className="max-w-md"><Field label="Price per person"><input name="price_per_person" type="number" min="0" step="0.01" defaultValue="0" required className={inputClass}/></Field></div></Step>
      <Step number={5} title="Initial availability" description="Choose the first bookable date from a real calendar and the start time from a 12-hour time picker."><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_220px]"><VisualDateTimePicker label="First available" dateName="initial_date" timeName="initial_time" required/><Field label="Capacity for this time"><input name="initial_capacity" type="number" min="1" defaultValue="10" required className={inputClass}/></Field></div><p className="mt-3 text-xs font-semibold text-white/35">Eastern Time is applied automatically.</p></Step>
      <Step number={6} title="Public URL" description="A readable URL is generated from the experience name. Customize it if you want."><div className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-xs font-black uppercase tracking-[0.14em] text-white/35">Public experience page</p><div className="mt-2 flex flex-wrap items-center gap-1 text-sm"><span className="text-white/40">theouthaven.com/experiences/</span><input name="slug" value={generated} onChange={event=>setSlug(slugify(event.target.value))} className="min-w-[220px] flex-1 rounded-xl border border-white/10 bg-black/30 px-3 py-2 font-black text-white outline-none focus:border-[#ff2142]/60"/></div></div></Step>
      <Step number={7} title="Review and create" description="Create the draft with its first available time. You can add more times before publishing."><div className="flex flex-col gap-3 border-t border-white/10 pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-semibold text-white/45">Published experiences automatically appear on the public location page and hosted website content.</p><button className="rounded-2xl bg-gradient-to-r from-[#e1062a] to-[#ff2142] px-5 py-3 text-sm font-black text-white shadow-lg shadow-[#ff1654]/20">Create draft experience</button></div></Step>
    </form>

    <section className="rounded-3xl border border-white/10 bg-gradient-to-br from-[#111722] to-[#090c12] p-5 sm:p-6"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#e1062a]/15 text-sm font-black text-[#ff6b86]">8</span><div><h2 className="text-xl font-black">Manage availability and publish</h2><p className="mt-1 text-sm font-semibold text-white/45">Performance numbers live on each experience Overview. Use this section to add times, open the overview, preview, or publish.</p></div></div><div className="mt-5 space-y-4">{experiences.length?experiences.map(exp=>{const expSlots=slots.filter(slot=>slot.experience_id===exp.id);return <article key={exp.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.14em] text-[#ff6b86]">{exp.category||"Experience"}</p><h3 className="mt-1 text-lg font-black">{exp.title}</h3><p className="mt-1 text-xs font-semibold text-white/35">{exp.status} · {exp.duration_minutes} min · ${Number(exp.price_per_person).toFixed(2)}/person · {expSlots.length} scheduled time{expSlots.length===1?"":"s"}</p></div><div className="flex flex-wrap gap-2"><Link href={`/locations/dashboard/events-experiences/experiences/${exp.id}`} className="rounded-xl border border-[#ff2142]/30 bg-[#e1062a]/10 px-3 py-2 text-xs font-black">Overview</Link><Link href={`/experiences/${exp.slug||exp.id}`} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-black">Public page</Link><form action={setExperienceStatusAction}><input type="hidden" name="experience_id" value={exp.id}/><input type="hidden" name="status" value={exp.status==="published"?"paused":"published"}/><button className="rounded-xl bg-[#e1062a] px-3 py-2 text-xs font-black">{exp.status==="published"?"Pause":"Publish"}</button></form></div></div><form action={addExperienceSlotAction} className="mt-4 grid gap-3 xl:grid-cols-[minmax(0,1fr)_150px_150px_auto]"><input type="hidden" name="experience_id" value={exp.id}/><VisualDateTimePicker label="New available time" dateName="slot_date" timeName="slot_time" required/><input name="duration_minutes" aria-label="Duration in minutes" type="number" min="15" defaultValue={exp.duration_minutes} className={inputClass}/><input name="capacity" aria-label="Capacity" type="number" min="1" defaultValue={exp.max_party_size} className={inputClass}/><button className="rounded-2xl border border-white/10 bg-white/[0.06] px-4 py-3 text-sm font-black">Add time</button></form></article>}):<p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm font-semibold text-white/40">No experiences yet.</p>}</div></section>
  </div>
}
