import Link from "next/link";import CrmContextBanner from "@/components/admin/crm/CrmContextBanner";import { parseCrmContextSearchParams } from "@/lib/crm/context";
import { requireAdminRole } from "@theouthaven/auth/admin-session";
import { CRM_READ_ROLES } from "@/lib/crm/permissions";
import { CRM_PIPELINES } from "@/lib/crm/pipelines";
import { listOpportunities, listOpportunitySelectors } from "@/lib/crm/opportunities/queries";
import { stageAgeDays } from "@/lib/crm/opportunities";
import { createOpportunityAction } from "./actions";
import { AdminActionButton, AdminPageHeader, AdminPageShell, AdminStatusBadge } from "@/lib/admin-design-system";
export const dynamic = "force-dynamic";
const money = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
export default async function OpportunitiesPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) { await requireAdminRole(CRM_READ_ROLES); const p = await searchParams, pipeline = p.pipeline || "all", view = p.view === "table" ? "table" : "board"; const [result, selectors] = await Promise.all([listOpportunities({ pipeline, view, stage: p.stage, forecast: p.forecast, risk: p.risk, search: p.q, page: Number(p.page) || 1, account_id:p.account_id, contact_id:p.contact_id, location_id:p.location_id, opportunity_id:p.opportunity_id }), listOpportunitySelectors({account_id:p.account_id})]); return <AdminPageShell>
<AdminPageHeader eyebrow="Locations CRM · Sales" title="Sales Opportunities" subtitle="Manage owner conversations, claim conversion, paid plans, expansion, and renewal opportunities without losing the location relationship." badge={<AdminStatusBadge tone={result.rows.some((o:any)=>o.health.status==="stalled")?"amber":"green"}>{result.rows.filter((o:any)=>o.health.status==="stalled").length} need follow-up</AdminStatusBadge>} actions={<><AdminActionButton href="/admin/dashboard/crm/customer-lifecycle" variant="primary">Customer Lifecycle</AdminActionButton><AdminActionButton href="/admin/dashboard/crm/forecast">Revenue Forecast</AdminActionButton><AdminActionButton href={`?pipeline=${pipeline}&view=${view === "board" ? "table" : "board"}`}>{view === "board" ? "Table view" : "Board view"}</AdminActionButton></>} />
<CrmContextBanner context={parseCrmContextSearchParams(p)} />
<nav className="flex gap-2 overflow-x-auto pb-1">{result.pipelineCounts.map((pc:any)=><Link key={pc.key} href={`?pipeline=${pc.key}&view=${view}`} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${pc.key===pipeline?"bg-rose-600 font-bold":"bg-white/5 text-white/60"}`}>{pc.label} · {pc.count}</Link>)}</nav>
<section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[["Open opportunities",result.totals.pipeline],["Likely value",result.totals.weighted],["Expected",result.totals.commit],["Possible",result.totals.bestCase],["Won",result.totals.closed],["Needs follow-up",result.rows.filter((o:any)=>o.health.status==="stalled").length]].map(([label,value])=><article key={String(label)} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><p className="text-xs uppercase text-white/45">{label}</p><b className="text-xl">{label==="Needs follow-up"?value:money(Number(value))}</b></article>)}</section>
<form className="grid gap-2 rounded-2xl border border-white/10 bg-white/[.03] p-3 md:grid-cols-5"><input type="hidden" name="pipeline" value={pipeline}/> {p.location_id?<input type="hidden" name="location_id" value={p.location_id}/>:null}{p.account_id?<input type="hidden" name="account_id" value={p.account_id}/>:null}<input type="hidden" name="view" value={view}/><input name="q" defaultValue={p.q} placeholder="Search by opportunity or location" className="rounded-lg bg-black/40 p-2"/><select name="stage" defaultValue={p.stage??""} className="rounded-lg bg-black p-2"><option value="">All stages</option>{result.stages.map((s:any)=><option key={s.stage_key}>{s.stage_key}</option>)}</select><select name="forecast" defaultValue={p.forecast??""} className="rounded-lg bg-black p-2"><option value="">All outlooks</option><option value="pipeline">Open</option><option value="best_case">Possible</option><option value="commit">Expected</option><option value="closed">Won</option><option value="omitted">Not active</option></select><select name="risk" defaultValue={p.risk??""} className="rounded-lg bg-black p-2"><option value="">All attention levels</option><option value="low">On track</option><option value="medium">Watch</option><option value="high">Needs attention</option><option value="critical">Urgent</option></select><button className="rounded-lg bg-white px-3 font-bold text-black">Apply filters</button></form>
<details className="rounded-2xl border border-white/10 p-4"><summary className="cursor-pointer font-bold">Add sales opportunity</summary><form action={createOpportunityAction} className="mt-3 grid gap-2 md:grid-cols-7"><input required name="name" placeholder="Opportunity name" className="rounded-lg bg-black/40 p-2"/><select required name="account_id" className="rounded-lg bg-black p-2"><option value="">Select account</option>{selectors.accounts.map((a:any)=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select name="primary_contact_id" className="rounded-lg bg-black p-2"><option value="">Primary contact</option>{selectors.contacts.map((c:any)=><option key={c.id} value={c.id}>{c.full_name||c.email}</option>)}</select><select name="primary_location_id" className="rounded-lg bg-black p-2"><option value="">Related location</option>{selectors.locations.map((l:any)=><option key={l.id} value={l.id}>{l.name}</option>)}</select><select name="pipeline_key" defaultValue={pipeline} className="rounded-lg bg-black p-2">{Object.keys(CRM_PIPELINES).map(k=><option key={k}>{k}</option>)}</select><input name="amount" type="number" min="0" step=".01" placeholder="Amount" className="rounded-lg bg-black/40 p-2"/><button className="rounded-lg bg-rose-600 font-bold">Create</button></form></details>
{view === "board" ? <section className="grid gap-3 md:grid-cols-2 xl:flex xl:overflow-x-auto">{result.stages.map((stage:any)=><div key={stage.id} className="min-w-72 flex-1 rounded-2xl bg-black/25 p-3"><header className="mb-3 flex justify-between"><b>{stage.name}</b><span className="text-white/40">{result.rows.filter((o:any)=>o.stage===stage.stage_key).length}</span></header><div className="space-y-2">{result.rows.filter((o:any)=>o.stage===stage.stage_key).map((o:any)=><Link key={o.id} href={`/admin/dashboard/crm/opportunities/${o.id}`} className="block rounded-xl border border-white/10 bg-white/[.05] p-3 hover:border-rose-500"><b>{o.name}</b><small className="block text-white/50">{o.crm_accounts?.name??"Account"} · {money(o.amount??0)}</small><div className="mt-2 flex flex-wrap gap-1 text-[11px]"><span className="rounded bg-white/10 px-2 py-1">{o.forecast_category}</span><span className="rounded bg-white/10 px-2 py-1">{o.probability??0}%</span><span className="rounded bg-white/10 px-2 py-1">{stageAgeDays(o.last_stage_changed_at)}d</span><span className="rounded bg-rose-950 px-2 py-1">{o.health.status}</span></div><p className="mt-2 truncate text-xs text-white/55">Next: {o.next_step??"Not set"}</p></Link>)}</div></div>)}</section> : <section className="overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-white/10 text-xs uppercase"><tr>{["Opportunity","Stage","Customer","Value","Likely value","Outlook","Chance","Expected close","Days here","Attention","Next action","Follow-ups"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{result.rows.map((o:any)=><tr key={o.id} className="border-t border-white/10"><td className="p-3"><Link className="font-bold text-rose-300" href={`/admin/dashboard/crm/opportunities/${o.id}`}>{o.name}</Link></td><td>{o.stage}</td><td>{o.crm_accounts?.name}</td><td>{money(o.amount??0)}</td><td>{money(o.weighted_amount??0)}</td><td>{o.forecast_category}</td><td>{o.probability??0}%</td><td>{o.expected_close_date??"—"}</td><td>{stageAgeDays(o.last_stage_changed_at)}</td><td>{o.risk_level??o.health.status}</td><td>{o.next_step??"—"}</td><td>{o.crm_tasks?.[0]?.count??0}</td></tr>)}</tbody></table></section>}
<p className="text-sm text-white/40">{result.count} opportunities · showing up to {result.size} at a time</p></AdminPageShell> }
