"use client";
import { useState } from "react";
import Link from "next/link";
import { buildCreateUrlWithPrompt, normalizeTesterPrompt } from "@/lib/beta/prompts";
export default function BetaDashboardClient({ assignments }: { assignments: any[] }) {
  const [custom, setCustom] = useState<Record<string,string>>({});
  async function complete(id:string){await fetch(`/api/beta/tasks/${id}/complete`,{method:"PATCH"}); window.location.reload();}
  function startUrl(a:any, prompt?:string, used=false){const sp=new URLSearchParams(); if(prompt)sp.set("prompt",prompt); sp.set("usedCustomPrompt",String(used)); const qs=sp.toString(); return `/beta/start-task/${a.id}${qs?`?${qs}`:""}`;}
  return <div className="grid gap-4">{assignments.map(a=>{const task=a.beta_tasks||{}; const prompt=a.assigned_prompt||task.predefined_prompt; const own=custom[a.id]||""; return <article key={a.id} className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-black">{task.title||"Beta task"}</h3><p className="mt-1 text-sm text-white/55">{task.feature_area||"general"} · about {task.estimated_minutes||5} minutes · {a.status}</p></div><span className="rounded-full border border-white/10 bg-black/20 px-3 py-1 text-xs font-bold">{a.status}</span></div><p className="mt-4 text-sm leading-6 text-white/70">{task.instructions||"Complete this quick test and tell us what happened."}</p>{prompt&&<div className="mt-4 rounded-2xl border border-rose-300/20 bg-rose-500/10 p-4"><p className="text-xs font-black uppercase tracking-[.2em] text-rose-100">Predefined prompt</p><p className="mt-2 text-white/85">{prompt}</p><Link href={startUrl(a,prompt,false)} className="mt-3 inline-flex rounded-full bg-rose-600 px-4 py-2 text-xs font-black text-white">Use this prompt</Link></div>}{task.allow_custom_prompt&&<div className="mt-4"><label className="text-sm font-bold text-white/80">Use your own prompt</label><p className="mt-1 text-xs text-white/50">Type what you would naturally search for on TheOutHaven.</p><input value={own} onChange={e=>setCustom(c=>({...c,[a.id]:e.target.value}))} placeholder="birthday dinner and rooftop lounge in Queens" className="mt-2 w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-white outline-none placeholder:text-white/35"/><Link onClick={(e)=>{if(!normalizeTesterPrompt(own)){e.preventDefault();alert("Please enter your custom prompt.");}}} href={startUrl(a,own,true)} className="mt-3 inline-flex rounded-full bg-white px-4 py-2 text-xs font-black text-black">Test My Prompt</Link></div>}<div className="mt-5 flex flex-wrap gap-2"><Link href={startUrl(a)} className="rounded-full border border-white/10 bg-black/30 px-4 py-2 text-xs font-black text-white">{task.button_label||"Start Test"}</Link><Link href={`/beta/feedback?assignmentId=${a.id}`} className="rounded-full border border-white/10 bg-black/30 px-4 py-2 text-xs font-black text-white">Submit Feedback</Link><button onClick={()=>complete(a.id)} className="rounded-full bg-emerald-600 px-4 py-2 text-xs font-black text-white">Mark Complete</button></div></article>})}</div>;
}
