import type { SupabaseClient } from "@supabase/supabase-js";
import { canonicalTaxonomy, type CanonicalTaxonomyEntry, type EvidenceField, type TaxonomyDomain } from "./index";
const CACHE_TTL_MS=5*60*1000; let active:readonly CanonicalTaxonomyEntry[]=canonicalTaxonomy; let loadedAt=0; let loadPromise:Promise<void>|null=null;
let entryIndex=new Map<string,CanonicalTaxonomyEntry>(); let matchCache=new Map<string,CanonicalTaxonomyEntry[]>(); let normalizedCache=new Map<string,string>();
function textArray(v:unknown):string[]{return Array.isArray(v)?v.map(String).filter(Boolean):[]}
function normalize(v:string){const cached=normalizedCache.get(v);if(cached!=null)return cached;const n=v.toLowerCase().replace(/[_–—-]+/g," ").replace(/[^a-z0-9+\s]/g," ").replace(/\s+/g," ").trim();normalizedCache.set(v,n);return n}
function rebuildIndexes(){entryIndex=new Map(active.map(e=>[e.id,e]));matchCache.clear();normalizedCache.clear()}
function rowToEntry(row:any):CanonicalTaxonomyEntry{const id=String(row.canonical_term),aliases=textArray(row.aliases),retrievalTerms=textArray(row.retrieval_terms);return{id,domain:String(row.domain) as TaxonomyDomain,aliases,retrievalTerms:retrievalTerms.length?retrievalTerms:[id.replaceAll("_"," "),...aliases],relatedCategories:textArray(row.related_terms),eligibleRoles:textArray(row.eligible_roles),evidenceRules:textArray(row.evidence_rules) as EvidenceField[],exclusions:textArray(row.negative_terms),incompatibleCategories:textArray(row.incompatible_domains),audienceRestrictions:textArray(row.audience_restrictions),mealPeriods:row.term_type==="meal_period"?[id]:[],features:row.term_type==="feature"||row.term_type==="vibe"?[id]:[]}}
rebuildIndexes();
export async function hydrateRuntimeTaxonomy(supabase:SupabaseClient,force=false):Promise<void>{if(!force&&Date.now()-loadedAt<CACHE_TTL_MS)return;if(loadPromise)return loadPromise;loadPromise=(async()=>{const{data,error}=await supabase.from("search_taxonomy_active").select("canonical_term,domain,term_type,aliases,eligible_roles,retrieval_terms,evidence_rules,related_terms,negative_terms,incompatible_domains,audience_restrictions,version").order("canonical_term");if(!error&&data?.length){active=data.map(rowToEntry);loadedAt=Date.now();rebuildIndexes()}})().finally(()=>{loadPromise=null});return loadPromise}
export function runtimeTaxonomy():readonly CanonicalTaxonomyEntry[]{return active}
export function runtimeTaxonomyEntry(id:string,domains?:readonly TaxonomyDomain[]):CanonicalTaxonomyEntry|undefined{const key=id.trim().toLowerCase().replace(/[\s-]+/g,"_"),entry=entryIndex.get(key);return entry&&(!domains||domains.includes(entry.domain))?entry:undefined}
export function runtimeRetrievalTerms(id:string):readonly string[]{return runtimeTaxonomyEntry(id)?.retrievalTerms??[id.replaceAll("_"," ")]}
export function runtimeAliases(id:string):readonly string[]{return runtimeTaxonomyEntry(id)?.aliases??[id.replaceAll("_"," ")]}
export function runtimeEligibleRoles(id:string):readonly string[]{return runtimeTaxonomyEntry(id)?.eligibleRoles??[]}
export function matchRuntimeTaxonomy(input:string,domains?:readonly TaxonomyDomain[]):CanonicalTaxonomyEntry[]{const domainKey=domains?.slice().sort().join(",")??"*",cacheKey=`${domainKey}:${input}`,cached=matchCache.get(cacheKey);if(cached)return cached;const normalized=normalize(input),matched=active.filter(item=>{if(domains&&!domains.includes(item.domain))return false;return[item.id.replaceAll("_"," "),...item.aliases].some(alias=>{const term=normalize(alias);return term.length>1&&new RegExp(`(?:^|\\s)${term.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}(?:$|\\s)`).test(normalized)})});matchCache.set(cacheKey,matched);return matched}
export function runtimeTaxonomyStatus(){return{source:active===canonicalTaxonomy?"static_fallback":"database",termCount:active.length,loadedAt:loadedAt||null,entryCacheSize:entryIndex.size,matchCacheSize:matchCache.size,normalizationCacheSize:normalizedCache.size}}
