import type { SupabaseClient } from "@supabase/supabase-js";
import { normalizeGeoTerm } from "../../enterprise/geo-taxonomy";
import type { EnterpriseLocation } from "../../enterprise/types";
import type { SearchTrace } from "../observability/searchTrace";
import type { RetrievalRequest } from "./retrievalTypes";

export type GeoLevel = "exact_neighborhood" | "city" | "borough_or_county" | "market" | "state";
type LegacyGeoScope = { level: GeoLevel; neighborhood: string | null; city: string | null; borough: string | null; county: string | null; market: string | null; state: string | null; latitude: number | null; longitude: number | null; radiusMiles: number | null };
const LEVEL_ORDER: GeoLevel[] = ["exact_neighborhood", "city", "borough_or_county", "market", "state"];

function normalize(value: unknown) { return typeof value === "string" ? value.trim().toLowerCase() : ""; }
function finiteNumber(value: unknown): number | null { const parsed = typeof value === "number" ? value : typeof value === "string" && value.trim() ? Number(value) : NaN; return Number.isFinite(parsed) ? parsed : null; }
function haversineMiles(lat1: number, lon1: number, lat2: number, lon2: number) { const r = 3958.7613; const rad = (d: number) => d * Math.PI / 180; const dLat = rad(lat2 - lat1); const dLon = rad(lon2 - lon1); const a = Math.sin(dLat / 2) ** 2 + Math.cos(rad(lat1)) * Math.cos(rad(lat2)) * Math.sin(dLon / 2) ** 2; return r * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); }
function resolveRegion(request: RetrievalRequest, marketOverride?: string | null): string | null { const geo = request.geo; const record = normalizeGeoTerm(marketOverride ?? geo.neighborhood ?? geo.borough ?? geo.city ?? geo.county ?? geo.market ?? geo.state); return record?.region ?? (record?.type === "region" ? record.name : null); }
function normalizeCoordinates(location: EnterpriseLocation, request: RetrievalRequest): EnterpriseLocation { const row = location as EnterpriseLocation & Record<string, unknown>; const latitude = finiteNumber(row.latitude ?? row.lat); const longitude = finiteNumber(row.longitude ?? row.lng ?? row.lon); const originLatitude = finiteNumber(request.geo.latitude); const originLongitude = finiteNumber(request.geo.longitude); const rpcDistance = finiteNumber(row.distance_miles ?? row.distanceMiles); const computedDistance = rpcDistance ?? (latitude != null && longitude != null && originLatitude != null && originLongitude != null ? haversineMiles(originLatitude, originLongitude, latitude, longitude) : null); return { ...location, latitude, longitude, distance_miles: computedDistance, distanceMiles: computedDistance } as EnterpriseLocation; }
function matchesScope(location: EnterpriseLocation, scope: LegacyGeoScope) { const city = normalize(location.city); const neighborhood = normalize(location.neighborhood); const borough = normalize(location.borough); const county = normalize(location.county); const state = normalize(location.state); const market = normalize((location as EnterpriseLocation & Record<string, unknown>).market); if (scope.state && state && state !== normalize(scope.state)) return false; if (scope.neighborhood && city !== normalize(scope.neighborhood) && neighborhood !== normalize(scope.neighborhood)) return false; if (scope.city && city !== normalize(scope.city) && neighborhood !== normalize(scope.city)) return false; if (scope.borough && borough !== normalize(scope.borough)) return false; if (scope.county && county !== normalize(scope.county)) return false; if (scope.market && market && market !== normalize(scope.market)) return false; return true; }
function explicitLocalGeo(request: RetrievalRequest) { return Boolean(request.geo.neighborhood || request.geo.city || request.geo.borough || request.geo.county); }
function maxOriginMiles(request: RetrievalRequest, level: GeoLevel) { const base = finiteNumber(request.geo.radiusMiles) ?? 6; if (level === "exact_neighborhood" || level === "city") return Math.max(base, 6); if (level === "borough_or_county") return Math.min(Math.max(base * 2, 12), 25); if (level === "market") return Math.min(Math.max(base * 3, 18), 35); return explicitLocalGeo(request) ? 0 : Math.min(Math.max(base * 4, 25), 60); }

export function buildLegacyGeoLevels(request: RetrievalRequest, allowBroaderGeo: boolean): GeoLevel[] { const levels: GeoLevel[] = ["exact_neighborhood"]; if (!allowBroaderGeo) return levels; if (request.geo.city) levels.push("city"); if (request.geo.borough || request.geo.county) levels.push("borough_or_county"); if (request.geo.market || request.geo.region) levels.push("market"); if (!explicitLocalGeo(request) && request.geo.state) levels.push("state"); return LEVEL_ORDER.filter((level) => levels.includes(level)); }
function scopeFor(request: RetrievalRequest, level: GeoLevel): LegacyGeoScope { const geo = request.geo; if (level === "exact_neighborhood") return { level, neighborhood: geo.neighborhood ?? null, city: geo.city ?? null, borough: geo.borough ?? null, county: geo.county ?? null, market: geo.market ?? null, state: geo.state ?? null, latitude: geo.latitude ?? null, longitude: geo.longitude ?? null, radiusMiles: geo.radiusMiles ?? null }; if (level === "city") return { level, neighborhood: null, city: geo.city ?? null, borough: null, county: geo.county ?? null, market: geo.market ?? null, state: geo.state ?? null, latitude: geo.latitude ?? null, longitude: geo.longitude ?? null, radiusMiles: maxOriginMiles(request, level) }; if (level === "borough_or_county") return { level, neighborhood: null, city: null, borough: geo.borough ?? null, county: geo.county ?? null, market: geo.market ?? null, state: geo.state ?? null, latitude: geo.latitude ?? null, longitude: geo.longitude ?? null, radiusMiles: maxOriginMiles(request, level) }; if (level === "market") return { level, neighborhood: null, city: null, borough: null, county: null, market: geo.market ?? geo.region ?? null, state: geo.state ?? null, latitude: geo.latitude ?? null, longitude: geo.longitude ?? null, radiusMiles: maxOriginMiles(request, level) }; return { level, neighborhood: null, city: null, borough: null, county: null, market: null, state: geo.state ?? null, latitude: geo.latitude ?? null, longitude: geo.longitude ?? null, radiusMiles: maxOriginMiles(request, level) }; }
function isLiveMusicRequest(request: RetrievalRequest) { const role = normalize(request.desiredRole); const terms = request.retrievalTerms.map(normalize); return role === "live_music_activity" || terms.some((term) => /^(live music|music venue|jazz|concert|live band)$/.test(term)); }

export async function retrieveUnifiedLocations(supabase: SupabaseClient, request: RetrievalRequest, limit = 60, trace?: SearchTrace, options: { allowBroaderGeo?: boolean; forcedGeoLevel?: GeoLevel } = {}): Promise<EnterpriseLocation[]> {
  const searchTerms = [...new Set(request.retrievalTerms)].slice(0, 20); const liveMusic = isLiveMusicRequest(request); const rpcName = liveMusic ? "enterprise_search_live_music_locations" : "enterprise_search_locations";
  const levels = options.forcedGeoLevel ? [options.forcedGeoLevel] : buildLegacyGeoLevels(request, Boolean(options.allowBroaderGeo));
  for (const level of levels) {
    const scope = scopeFor(request, level); if (level === "state" && maxOriginMiles(request, level) === 0) continue;
    const params = liveMusic ? { p_search_terms: searchTerms, p_neighborhood: scope.neighborhood, p_borough: scope.borough, p_city: scope.city, p_county: scope.county, p_state: scope.state, p_latitude: scope.latitude, p_longitude: scope.longitude, p_radius_miles: scope.radiusMiles, p_limit: limit } : { p_search_terms: searchTerms, p_domain: request.desiredRole === "restaurant" ? "restaurant" : "activity", p_neighborhood: scope.neighborhood, p_borough: scope.borough, p_city: scope.city, p_county: scope.county, p_region: resolveRegion(request, scope.market), p_state: scope.state, p_latitude: scope.latitude, p_longitude: scope.longitude, p_radius_miles: scope.radiusMiles, p_limit: limit, p_allow_places_of_worship: false, p_allow_low_level: false };
    const { data, error } = await supabase.rpc(rpcName, params); if (error) throw new Error(`SEARCH_V2_RETRIEVAL_FAILED:${rpcName}:${error.message}`);
    const raw = (Array.isArray(data) ? data : []).map((location) => normalizeCoordinates(location as EnterpriseLocation, request));
    const cap = maxOriginMiles(request, level); const retained = raw.filter((location) => matchesScope(location, scope) && (cap <= 0 || finiteNumber((location as any).distance_miles) == null || finiteNumber((location as any).distance_miles)! <= cap)).map((location) => ({ ...location, retrieval_geo_level: level } as EnterpriseLocation));
    if (trace) { if (!raw.length) trace.rejections.retrievalRpcEmpty += 1; trace.rejections.strictGeo += raw.length - retained.length; trace.decisions.push({ stage: "retrieval_geo_fallback", decision: retained.length ? "geo_level_succeeded" : "geo_level_empty", reason: `${rpcName}: level=${level}, origin_cap_miles=${cap}, raw=${raw.length}, retained=${retained.length}` }); }
    if (retained.length) return retained.slice(0, limit);
  }
  return [];
}
