import Link from "next/link";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { AdminDataTableShell, AdminKpiCard, AdminKpiGrid, AdminPageHeader, AdminPageShell, AdminSectionCard, AdminStatusBadge, formatAdminDate } from "@/components/admin/AdminDesignSystem";
import { RecalculatePhase2Button } from "./RecalculatePhase2Button";
export const dynamic = "force-dynamic";
async function safe<T>(fn:()=>Promise<T>, fallback:T){ try { return await fn(); } catch { return fallback; } }
function n(v:any){ return Number(v||0).toFixed(1); }
export default async function MlPhase2Page(){
 const [lastRun, locCount, pairCount, topLoc, topPair, avgLoc, avgPair] = await Promise.all([
  safe(async()=> (await supabaseAdmin.from("ml_phase2_score_runs").select("*").order("created_at",{ascending:false}).limit(1).maybeSingle()).data, null),
  safe(async()=> (await supabaseAdmin.from("location_intent_ml_features").select("id",{count:"exact",head:true})).count || 0, 0),
  safe(async()=> (await supabaseAdmin.from("location_pair_ml_features").select("id",{count:"exact",head:true})).count || 0, 0),
  safe(async()=> (await supabaseAdmin.from("location_intent_ml_features").select("*, locations(name,restaurant_name,activity_name)").order("intent_score",{ascending:false}).limit(25)).data || [], [] as any[]),
  safe(async()=> (await supabaseAdmin.from("location_pair_ml_features").select("*, restaurant:locations!location_pair_ml_features_restaurant_location_id_fkey(name,restaurant_name), activity:locations!location_pair_ml_features_activity_location_id_fkey(name,activity_name)").order("pair_score",{ascending:false}).limit(25)).data || [], [] as any[]),
  safe(async()=> (await supabaseAdmin.from("location_intent_ml_features").select("intent_score").limit(1000)).data || [], [] as any[]),
  safe(async()=> (await supabaseAdmin.from("location_pair_ml_features").select("pair_score").limit(1000)).data || [], [] as any[]),
 ]);
 const avgIntent = avgLoc.length ? avgLoc.reduce((s:any,r:any)=>s+Number(r.intent_score||0),0)/avgLoc.length : 0;
 const avgPairScore = avgPair.length ? avgPair.reduce((s:any,r:any)=>s+Number(r.pair_score||0),0)/avgPair.length : 0;
 return <AdminPageShell><AdminPageHeader eyebrow="Machine Learning" title="ML Phase 2: intents & pairs" subtitle="Safe deterministic ML-readiness for intent bucket detection, location intent scoring, and restaurant/activity pair scoring." actions={<><Link className="rounded-xl border border-white/10 px-4 py-2 text-sm font-black text-white/75" href="/admin/dashboard">Admin home</Link><RecalculatePhase2Button/></>} badge={<AdminStatusBadge tone={lastRun?.status?.includes("error")?"amber":"green"}>{lastRun?.status||"not run"}</AdminStatusBadge>} />
 <AdminKpiGrid><AdminKpiCard label="Location intent rows" value={locCount}/><AdminKpiCard label="Pair score rows" value={pairCount}/><AdminKpiCard label="Avg intent score" value={n(avgIntent)}/><AdminKpiCard label="Avg pair score" value={n(avgPairScore)}/><AdminKpiCard label="Last run" value={formatAdminDate(lastRun?.created_at)}/><AdminKpiCard label="Errors" value={lastRun?.error_count||0}/></AdminKpiGrid>
 <AdminSectionCard className="p-5"><h2 className="text-xl font-black">What Phase 2 does</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><p className="rounded-2xl bg-white/[0.04] p-4 text-sm text-white/65"><b className="text-white">2A Intent buckets:</b> classifies queries into primary/secondary structured intent buckets.</p><p className="rounded-2xl bg-white/[0.04] p-4 text-sm text-white/65"><b className="text-white">2B Location scores:</b> aggregates behavior by location + intent + market + location type.</p><p className="rounded-2xl bg-white/[0.04] p-4 text-sm text-white/65"><b className="text-white">2C Pair scores:</b> learns complete outing pair quality without overriding hard rules.</p></div></AdminSectionCard>
 <AdminDataTableShell><h2 className="p-2 text-lg font-black">Top location intent scores</h2><table className="min-w-full text-left text-xs"><thead className="text-white/45"><tr>{["Location","Intent","Market","Type","Impr","Clicks","Saves","Completed","Conf","Score"].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{topLoc.map((r:any)=><tr className="border-t border-white/10" key={r.id}><td className="p-2 font-bold">{r.locations?.name||r.locations?.restaurant_name||r.locations?.activity_name||r.location_id}</td><td className="p-2">{r.intent_bucket}</td><td className="p-2">{r.market||"—"}</td><td className="p-2">{r.location_type||"—"}</td><td className="p-2">{r.impressions_30d}</td><td className="p-2">{r.clicks_30d}</td><td className="p-2">{r.saves_30d}</td><td className="p-2">{r.completed_outings_30d}</td><td className="p-2">{n(r.confidence_score)}</td><td className="p-2 font-black">{n(r.intent_score)}</td></tr>)}</tbody></table></AdminDataTableShell>
 <AdminDataTableShell><h2 className="p-2 text-lg font-black">Top pair scores</h2><table className="min-w-full text-left text-xs"><thead className="text-white/45"><tr>{["Restaurant","Activity","Intent","Market","Miles","Impr","Clicks","Saves","Completed","Conf","Score"].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{topPair.map((r:any)=><tr className="border-t border-white/10" key={r.id}><td className="p-2 font-bold">{r.restaurant?.name||r.restaurant?.restaurant_name||r.restaurant_location_id}</td><td className="p-2 font-bold">{r.activity?.name||r.activity?.activity_name||r.activity_location_id}</td><td className="p-2">{r.intent_bucket}</td><td className="p-2">{r.market||"—"}</td><td className="p-2">{r.pair_distance_miles??"—"}</td><td className="p-2">{r.impressions_30d}</td><td className="p-2">{r.clicks_30d}</td><td className="p-2">{r.saves_30d}</td><td className="p-2">{r.completed_outings_30d}</td><td className="p-2">{n(r.confidence_score)}</td><td className="p-2 font-black">{n(r.pair_score)}</td></tr>)}</tbody></table></AdminDataTableShell></AdminPageShell>;
}
