export const EVENT_PROVIDERS = ["ticketmaster", "nyc_events", "nyc_parks", "native"] as const;
export type EventProvider = (typeof EVENT_PROVIDERS)[number];

export const EVENT_STATUSES = ["draft", "scheduled", "postponed", "cancelled", "completed"] as const;
export type EventStatus = (typeof EVENT_STATUSES)[number];

export type CanonicalEventInput = {
  organizationId?: string | null;
  locationId?: string | null;
  sourceKind?: "provider" | "native";
  provider: EventProvider;
  providerEventId: string;
  providerUpdatedAt?: string | null;
  sourceUrl?: string | null;
  title: string;
  description?: string | null;
  category?: string | null;
  subcategory?: string | null;
  venueName?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  zipCode?: string | null;
  market?: string | null;
  borough?: string | null;
  county?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  startsAt: string;
  endsAt?: string | null;
  timezone?: string | null;
  allDay?: boolean;
  priceMin?: number | null;
  priceMax?: number | null;
  currency?: string | null;
  isFree?: boolean;
  externalUrl?: string | null;
  imageUrl?: string | null;
  status?: EventStatus;
  searchable?: boolean;
  metadata?: Record<string, unknown>;
  providerPayload?: Record<string, unknown>;
};

export type NormalizedEvent = CanonicalEventInput & {
  sourceKind: "provider" | "native";
  title: string;
  providerEventId: string;
  startsAt: string;
  timezone: string;
  allDay: boolean;
  status: EventStatus;
  searchable: boolean;
  dedupeFingerprint: string;
  searchDocument: string;
};

export type CanonicalEventRow = {
  id: string;
  organization_id: string | null;
  location_id: string | null;
  source_kind: "provider" | "native";
  title: string;
  description: string | null;
  category: string | null;
  subcategory: string | null;
  venue_name: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  zip_code: string | null;
  market: string | null;
  borough: string | null;
  county: string | null;
  latitude: number | null;
  longitude: number | null;
  starts_at: string;
  ends_at: string | null;
  timezone: string;
  all_day: boolean;
  price_min: number | null;
  price_max: number | null;
  currency: string | null;
  is_free: boolean;
  external_url: string | null;
  image_url: string | null;
  status: EventStatus;
  searchable: boolean;
  dedupe_fingerprint: string;
  search_document: string;
  metadata: Record<string, unknown> | null;
};
