export const INTENT_SCORE_VERSION = "intent_rank_v1";
export const PAIR_SCORE_VERSION = "pair_rank_v1";
const clamp = (n:number,min=0,max=100)=>Math.max(min,Math.min(max,Number.isFinite(n)?n:0));
const logScore = (n:number, max:number)=>clamp(Math.log1p(Math.max(0,n))/Math.log1p(max),0,1);
export const calculateCtr = (clicks:number, impressions:number)=> impressions > 0 ? clamp(clicks / impressions, 0, 1) : 0;
export const calculateConversionRate = (conversions:number, impressions:number)=> impressions > 0 ? clamp(conversions / impressions, 0, 1) : 0;
export function calculateConfidenceScore(impressions:number, clicks:number, conversions:number) { return clamp((logScore(impressions, 100)*55 + logScore(clicks, 30)*25 + logScore(conversions, 10)*20)); }
function dampener(impressions:number) { return impressions < 5 ? 0.25 : impressions < 15 ? 0.5 : impressions < 30 ? 0.75 : 1; }
export function calculateLocationIntentScore(input: any) { const impressions = Number(input.impressions_30d ?? input.impressions30d ?? 0); const clicks = Number(input.clicks_30d ?? input.clicks30d ?? 0); const conversions = Number(input.completed_outings_30d ?? 0) + Number(input.reservation_clicks_30d ?? 0) + Number(input.call_clicks_30d ?? 0) + Number(input.website_clicks_30d ?? 0); const views = Number(input.views_30d ?? 0); const saves = Number(input.saves_30d ?? 0); const ctr = input.ctr_30d ?? calculateCtr(clicks, impressions); const cr = input.conversion_rate_30d ?? calculateConversionRate(conversions, impressions); const engagement = (logScore(clicks,50)*8 + logScore(views,100)*4 + logScore(saves,20)*4 + logScore(Number(input.completed_outings_30d ?? 0),10)*4); const penalty = clamp(Number(input.negative_signals_30d ?? 0) * 5, 0, 25); return Number(clamp(((clamp(ctr,0,0.5)/0.5)*25 + (clamp(cr,0,0.35)/0.35)*30 + engagement + 5 - penalty) * dampener(impressions)).toFixed(2)); }
export function calculatePairScore(input: any) { const impressions = Number(input.impressions_30d ?? 0); const clicks = Number(input.clicks_30d ?? 0); const completed = Number(input.completed_outings_30d ?? 0); const conversions = completed + Number(input.reservation_clicks_30d ?? 0) + Number(input.call_clicks_30d ?? 0) + Number(input.website_clicks_30d ?? 0); const cr = input.conversion_rate_30d ?? calculateConversionRate(conversions, impressions); const distance = input.pair_distance_miles == null ? 3 : Number(input.pair_distance_miles); const distanceScore = distance <= .5 ? 20 : distance <= 1.5 ? 14 : distance <= 3 ? 7 : 0; const engagement = logScore(clicks, 40)*10 + logScore(Number(input.saves_30d ?? 0),20)*7 + logScore(completed,10)*8; const completion = logScore(completed,8)*20; const penalty = clamp(Number(input.negative_signals_30d ?? 0)*5,0,25); return Number(clamp(((clamp(cr,0,0.4)/0.4)*35 + engagement + completion + distanceScore - penalty) * dampener(impressions)).toFixed(2)); }
