name: Build production mobile apps

on:
  push:
    branches:
      - main
    paths:
      - mobile/**

jobs:
  build_android:
    name: Build Android production app
    type: build
    params:
      platform: android
      profile: production

  build_ios:
    name: Build iOS production app
    type: build
    params:
      platform: ios
      profile: production
