import Link from "next/link";
import { requireAdminRole } from "@/lib/admin-auth";
import { ADMIN_PAGE_ACCESS } from "@/lib/admin-permissions";
import { getSearchHealthDashboardData, parseSearchHealthFilters, sanitizeSearchHealthDebug } from "@/lib/admin/search-health-dashboard";
import { supabaseAdmin } from "@/lib/supabase-admin";
import RecentCreateSearchesPanel from "./RecentCreateSearchesPanel";
import SearchHealthFiltersBar from "./SearchHealthFilters";
import SearchHealthIssueQueue from "./SearchHealthIssueQueue";
import SearchHealthClient from "./SearchHealthClient";
import SearchQualityReviewPanel from "./SearchQualityReviewPanel";
export const metadata={title:"Search Health – Admin",description:"Search operations health, performance, and review workflow."}; export const dynamic="force-dynamic";
type Params=Promise<Record<string,string|string[]|undefined>>;
export default async function SearchHealthPage({searchParams}:{searchParams:Params}) { await requireAdminRole(ADMIN_PAGE_ACCESS.searchHealth); const filters=parseSearchHealthFilters(await searchParams); const dashboard=await getSearchHealthDashboardData(filters);
 const selected=filters.issue?await supabaseAdmin.from("search_health_events").select("id,created_at,source,environment,raw_query,normalized_search_type,primary_domain,event_type,event_label,severity,review_status,restaurant_count,activity_count,pair_count,timing_ms,speed_status,no_results_reason,no_pairs_reason,distance_mode,default_market_id,debug,review_notes,reviewed_at").eq("id",filters.issue).maybeSingle():{data:null,error:null};
 const close=new URLSearchParams(Object.fromEntries(Object.entries(await searchParams).filter(([k,v])=>k!=="issue"&&typeof v==="string") as [string,string][]));
 return <main className="min-h-screen bg-[#090706] px-4 py-6 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-[1700px] space-y-5"><header data-testid="search-health-dashboard" className="rounded-3xl border border-white/10 bg-[radial-gradient(circle_at_top_left,rgba(225,29,72,.16),transparent_30%),#120b0a] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.3em] text-rose-200">Admin operations</p><h1 className="mt-2 text-4xl font-black">Search Health</h1><p className="mt-2 max-w-2xl text-sm text-white/60">Monitor search outcomes, investigate degraded experiences, and manage the review queue.</p><p className="mt-2 text-xs text-white/40">Last refreshed {new Date().toLocaleString()}</p></div><nav className="flex flex-wrap gap-2"><a href="#all-searches" className="rounded-full border border-white/15 px-4 py-2">All Searches</a><a href="#issue-queue" className="rounded-full border border-white/15 px-4 py-2">Issue Queue</a><Link href="/admin/dashboard/ml" className="rounded-full border border-rose-400/30 px-4 py-2">ML Dashboard</Link><Link href={`/admin/dashboard/search-health?${close}`} className="rounded-full bg-rose-700 px-4 py-2 font-bold">Refresh</Link></nav></div></header>
 <SearchHealthFiltersBar filters={filters}/><RecentCreateSearchesPanel rows={dashboard.searches} issues={dashboard.issues} count={dashboard.searchCount} kpis={dashboard.kpis} filters={filters} errors={dashboard.errors}/><SearchHealthIssueQueue rows={dashboard.issues} count={dashboard.issueCount} error={dashboard.errors.issues} filters={filters}/>
 {filters.issue?<section data-testid="issue-detail" id="search-health-issue" className="rounded-3xl border border-amber-300/25 bg-amber-500/10 p-5">{selected.data?<><div className="flex justify-between gap-3"><div><p className="text-xs font-black uppercase text-amber-200">Selected issue detail</p><h2 className="mt-1 text-2xl font-black">{selected.data.event_label||selected.data.event_type||"Search issue"}</h2></div><Link href={`/admin/dashboard/search-health?${close}#issue-queue`} className="rounded-full border border-white/15 px-4 py-2">Close</Link></div><dl className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(selected.data).filter(([key])=>key!=="debug").map(([key,value])=><div className="rounded-xl bg-black/20 p-3" key={key}><dt className="text-[10px] font-black uppercase text-white/40">{key.replaceAll("_"," ")}</dt><dd className="mt-1 break-words text-sm">{value===null?"—":String(value)}</dd></div>)}</dl><details className="mt-4 rounded-xl bg-black/30 p-4"><summary className="cursor-pointer font-bold">Sanitized debug data</summary><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap text-xs text-white/70">{JSON.stringify(sanitizeSearchHealthDebug(selected.data.debug),null,2)}</pre></details></>:<p role="alert">This issue is unavailable or was deleted. <Link className="underline" href={`/admin/dashboard/search-health?${close}`}>Return to the queue</Link>.</p>}</section>:null}
 <section id="quality-review" className="space-y-5"><SearchQualityReviewPanel/></section><details className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><summary className="cursor-pointer text-xl font-black">Advanced issue workflow</summary><div className="mt-5"><SearchHealthClient/></div></details></div></main> }
