import Link from "next/link";
import { classifySearchEvent, correlateIssue, type HealthIssue, type SearchEvent, type SearchHealthFilters, type SearchHealthKpis } from "@/lib/admin/search-health-dashboard";

const badge = "inline-flex rounded-full border px-2 py-1 text-[11px] font-black";
function href(filters: SearchHealthFilters, updates: Record<string, string | number | null>) {
  const p = new URLSearchParams({ range: filters.preset, from: filters.from, to: filters.to, q: filters.q, status: filters.status, severity: filters.severity, review: filters.reviewStatus, source: filters.source, speed: filters.speed, hasIssue: filters.hasIssue, noResults: filters.noResults, noPairs: filters.noPairs, page: String(filters.page), issuePage: String(filters.issuePage), pageSize: String(filters.pageSize), sort: filters.sort, direction: filters.direction });
  Object.entries(updates).forEach(([key, value]) => value === null ? p.delete(key) : p.set(key, String(value)));
  return `/admin/dashboard/search-health?${p}`;
}
export default function RecentCreateSearchesPanel({ rows, issues, count, kpis, filters, errors }: { rows: SearchEvent[]; issues: HealthIssue[]; count: number; kpis: SearchHealthKpis | null; filters: SearchHealthFilters; errors: { searches?: string; kpis?: string } }) {
  const cards = [["Total Searches", kpis?.total], ["Healthy Searches", kpis?.healthy], ["Searches With Issues", kpis?.issues], ["Failed Searches", kpis?.failed], ["Slow Searches", kpis?.slow], ["No Results", kpis?.noResults], ["No Pairs", kpis?.noPairs]] as const;
  const pages = Math.max(1, Math.ceil(count / filters.pageSize));
  return <section data-testid="recent-searches" id="all-searches" className="space-y-5">
    <div data-testid="search-health-kpis" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{cards.map(([label,value]) => <article key={label} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><p className="text-[11px] font-black uppercase tracking-wider text-white/50">{label}</p><p className="mt-2 text-3xl font-black">{value ?? "—"}</p></article>)}</div>
    {errors.kpis && <p role="status" className="rounded-2xl border border-amber-300/25 bg-amber-500/10 p-3 text-sm text-amber-100">KPI totals are temporarily unavailable. Recent searches can still be reviewed.</p>}
    <div className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.2em] text-rose-200">Operations</p><h2 className="mt-1 text-2xl font-black">Recent Searches</h2><p className="mt-1 text-sm text-white/55">{count.toLocaleString()} matching searches</p></div></div>
    {errors.searches ? <p role="alert" className="mt-4 rounded-2xl border border-red-300/25 bg-red-500/10 p-4 text-red-100">Recent searches could not be loaded: {errors.searches}</p> : rows.length === 0 ? <p className="mt-4 rounded-2xl border border-white/10 p-5 text-white/65">No searches match the active filters.</p> : <div className="mt-4 overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-[1550px] w-full text-left text-sm"><thead className="bg-black/30 text-xs uppercase text-white/45"><tr>{["Time","Query","Normalized Query","Search Type","Primary Domain","Location","Restaurants","Activities","Pairs","Results","Timing","Speed Status","Overall Status","Linked Issue","Action"].map(x=><th scope="col" className="px-3 py-3" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y divide-white/10">{rows.map(row=>{const issue=correlateIssue(row,issues); const c=classifySearchEvent(row,Boolean(issue)); const badges=[c.healthy&&"Healthy",c.issue&&"Issue",c.failed&&"Failed",c.slow&&"Slow",c.noResults&&"No Results",c.noPairs&&"No Pairs"].filter(Boolean); return <tr key={row.id} className="align-top"><td className="whitespace-nowrap px-3 py-3 text-white/55">{new Date(row.created_at).toLocaleString()}</td><td className="max-w-64 px-3 py-3 font-bold">{row.raw_query||"—"}</td><td className="max-w-64 px-3 py-3 text-white/60">{row.normalized_query||"—"}</td><td className="px-3 py-3">{row.search_type||"—"}</td><td className="px-3 py-3">{row.primary_domain||"—"}</td><td className="px-3 py-3">{[row.neighborhood,row.borough].filter(Boolean).join(", ")||"—"}</td><td className="px-3 py-3">{row.restaurant_count??"—"}</td><td className="px-3 py-3">{row.activity_count??"—"}</td><td className="px-3 py-3">{row.pair_count??"—"}</td><td className="px-3 py-3">{row.result_count??"—"}</td><td className="px-3 py-3">{row.timing_ms==null?"—":`${row.timing_ms} ms`}</td><td className="px-3 py-3">{row.speed_status||"—"}</td><td className="px-3 py-3"><div className="flex max-w-48 flex-wrap gap-1">{badges.map(x=><span key={String(x)} className={`${badge} ${x==="Healthy"?"border-emerald-400/30 text-emerald-100":"border-amber-400/30 text-amber-100"}`}>{x}</span>)}</div></td><td className="px-3 py-3">{issue?<Link className="text-amber-200 underline" href={href(filters,{issue:issue.id})+"#search-health-issue"}>{issue.event_label||issue.event_type||"Open issue"}</Link>:"—"}</td><td className="px-3 py-3"><Link className="text-rose-200 underline" href={`/create?q=${encodeURIComponent(row.raw_query||"")}`}>Replay</Link></td></tr>})}</tbody></table></div>}
    <nav aria-label="Recent searches pagination" className="mt-4 flex items-center justify-between"><Link aria-disabled={filters.page<=1} className="rounded-full border border-white/15 px-4 py-2 aria-disabled:pointer-events-none aria-disabled:opacity-40" href={href(filters,{page:Math.max(1,filters.page-1)})}>Previous</Link><span className="text-sm text-white/55">Page {Math.min(filters.page,pages)} of {pages}</span><Link aria-disabled={filters.page>=pages} className="rounded-full border border-white/15 px-4 py-2 aria-disabled:pointer-events-none aria-disabled:opacity-40" href={href(filters,{page:Math.min(pages,filters.page+1)})}>Next</Link></nav></div>
  </section>;
}
