import type { SearchHealthFilters } from "@/lib/admin/search-health-dashboard";
export default function SearchHealthFiltersBar({ filters }: { filters: SearchHealthFilters }) { return <form data-testid="search-health-filters" action="/admin/dashboard/search-health" className="rounded-3xl border border-white/10 bg-white/[.04] p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
  <label className="text-xs font-bold text-white/65">Date range<select name="range" defaultValue={filters.preset} className="mt-1 w-full rounded-xl border border-white/15 bg-black p-2 text-white"><option value="24h">Last 24 Hours</option><option value="7d">Last 7 Days</option><option value="30d">Last 30 Days</option><option value="custom">Custom</option></select></label>
  <label className="text-xs font-bold text-white/65">Custom start<input type="datetime-local" name="from" className="mt-1 w-full rounded-xl border border-white/15 bg-black p-2 text-white" /></label><label className="text-xs font-bold text-white/65">Custom end<input type="datetime-local" name="to" className="mt-1 w-full rounded-xl border border-white/15 bg-black p-2 text-white" /></label>
  <label className="text-xs font-bold text-white/65">Search text<input name="q" defaultValue={filters.q} placeholder="Query contains…" className="mt-1 w-full rounded-xl border border-white/15 bg-black p-2 text-white" /></label>
  <label className="text-xs font-bold text-white/65">Overall status<select name="status" defaultValue={filters.status} className="mt-1 w-full rounded-xl border border-white/15 bg-black p-2"><option value="all">All</option><option value="healthy">Healthy</option><option value="issue">Issue</option><option value="failed">Failed</option></select></label>
  <label className="text-xs font-bold text-white/65">Severity<select name="severity" defaultValue={filters.severity} className="mt-1 w-full rounded-xl border border-white/15 bg-black p-2"><option value="all">All</option>{["critical","error","warning","info"].map(x=><option key={x}>{x}</option>)}</select></label>
  <label className="text-xs font-bold text-white/65">Review status<select name="review" defaultValue={filters.reviewStatus} className="mt-1 w-full rounded-xl border border-white/15 bg-black p-2"><option value="open">Open</option><option value="all">All</option>{["new","reviewing","fixed","ignored","archived"].map(x=><option key={x}>{x}</option>)}</select></label>
  {[["Source","source",["public_create_search","all"]],["Speed status","speed",["all","slow","critical","failed","timeout","degraded"]],["Has issue","hasIssue",["all","yes","no"]],["No results","noResults",["all","yes","no"]],["No pairs","noPairs",["all","yes","no"]]] .map(([label,name,options])=><label key={String(name)} className="text-xs font-bold text-white/65">{label}<select name={String(name)} defaultValue={String(filters[name as keyof SearchHealthFilters])} className="mt-1 w-full rounded-xl border border-white/15 bg-black p-2">{(options as string[]).map(x=><option key={x}>{x}</option>)}</select></label>)}
  <label className="text-xs font-bold text-white/65">Rows per page<select name="pageSize" defaultValue={filters.pageSize} className="mt-1 w-full rounded-xl border border-white/15 bg-black p-2">{[25,50,100].map(x=><option key={x}>{x}</option>)}</select></label>
  </div><div className="mt-4 flex gap-2"><button className="rounded-full bg-rose-700 px-5 py-2 text-sm font-black">Apply filters</button><a className="rounded-full border border-white/15 px-5 py-2 text-sm font-black" href="/admin/dashboard/search-health">Clear all</a></div></form> }
