"use client";
import { useState } from "react";
import TurnstileWidget from "@/components/security/TurnstileWidget";
const interests = ["Search quality", "Search speed", "Real user prompts", "Reservations", "Claims", "Mobile", "Location pages"];
export default function BetaApplyForm() {
  const [token, setToken] = useState(""); const [status, setStatus] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function submit(formData: FormData) { setLoading(true); setStatus(null); const payload = Object.fromEntries(formData.entries()) as any; payload.testing_interests = formData.getAll("testing_interests"); payload.turnstileToken = token; try { const res = await fetch("/api/beta/apply", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Submission failed"); window.location.href = "/beta/apply/success"; } catch (e) { setStatus(e instanceof Error ? e.message : "Submission failed"); } finally { setLoading(false); } }
  const input = "rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-white outline-none placeholder:text-white/35";
  return <form action={submit} className="grid gap-4 rounded-3xl border border-white/10 bg-white/[.04] p-6">
    <div className="grid gap-4 md:grid-cols-2"><input name="name" required placeholder="Name" className={input}/><input name="email" type="email" required placeholder="Email" className={input}/><input name="phone" placeholder="Phone (optional)" className={input}/><input name="city" required placeholder="City" className={input}/><input name="borough" placeholder="Borough" className={input}/><select name="tester_type" defaultValue="user" className={input}><option value="user">Regular user</option><option value="location_owner">Business/location owner</option><option value="ambassador">Ambassador/sales</option><option value="experience_team">Experience/support</option><option value="admin">Admin tester</option><option value="superadmin">Superadmin tester</option></select><select name="device_type" className={input}><option>Mobile</option><option>Desktop</option><option>Both</option></select><input name="availability" placeholder="Availability" className={input}/></div>
    <div><p className="mb-2 text-sm font-bold text-white/80">Testing interests</p><div className="flex flex-wrap gap-2">{interests.map(i=><label key={i} className="rounded-full border border-white/10 bg-black/20 px-3 py-2 text-sm"><input type="checkbox" name="testing_interests" value={i} className="mr-2" />{i}</label>)}</div></div>
    <textarea name="notes" placeholder="Anything we should know?" className={`${input} min-h-28`} /><label className="text-sm text-white/70"><input required type="checkbox" name="agreement" className="mr-2"/>I agree to complete 5 quick beta tests per week if approved.</label>
    <p className="text-sm text-white/55">Verification helps protect TheOutHaven from spam.</p><TurnstileWidget action="beta_apply" onToken={setToken}/>{status && <p className="text-sm font-bold text-rose-200">{status}</p>}<button disabled={loading} className="rounded-full bg-rose-600 px-6 py-3 text-sm font-black text-white disabled:opacity-60">{loading ? "Submitting..." : "Submit application"}</button>
  </form>;
}
