import Link from "next/link";

export const growthProNav = [
  ["Overview", "/business/dashboard"], ["Profile", "/business/dashboard/profile"], ["Branding", "/business/dashboard/branding"], ["Menu / Packages", "/business/dashboard/menu"], ["QR Codes", "/business/dashboard/qr-codes"], ["Reservations", "/business/dashboard/reservations"], ["Leads", "/business/dashboard/leads"], ["Offers", "/business/dashboard/offers"], ["VIP List", "/business/dashboard/vip"], ["Messaging", "/business/dashboard/messaging"], ["Notifications", "/business/dashboard/notifications"], ["Reviews / Feedback", "/business/dashboard/reviews"], ["Marketing Studio", "/business/dashboard/marketing-studio"], ["Analytics", "/business/dashboard/analytics"], ["Billing", "/business/dashboard/billing"], ["Settings", "/business/dashboard/settings"],
] as const;

export function GrowthProShell({ title, eyebrow = "TheOutHaven Growth Pro", children }: { title: string; eyebrow?: string; children: React.ReactNode }) {
  return <main className="min-h-screen bg-[#090607] px-4 py-8 text-white"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[0.3em] text-rose-200">{eyebrow}</p><h1 className="mt-3 text-4xl font-black">{title}</h1><p className="mt-2 max-w-3xl text-white/60">Get discovered. Capture customers. Promote smarter. Respond faster. Track results.</p><nav className="mt-6 flex gap-2 overflow-x-auto pb-2">{growthProNav.map(([label, href]) => <Link key={href} href={href} className="shrink-0 rounded-full border border-white/10 bg-white/[0.04] px-4 py-2 text-xs font-black text-white/75 hover:border-rose-300/40 hover:text-white">{label}</Link>)}</nav><section className="mt-6">{children}</section></div></main>;
}

export function ModuleCards({ items }: { items: string[] }) { return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item} className="rounded-3xl border border-white/10 bg-white/[0.04] p-5"><h2 className="text-lg font-black">{item}</h2><p className="mt-2 text-sm leading-6 text-white/60">Growth Pro workspace for {item.toLowerCase()} with safe publishing controls, plain-language locked states, and admin-ready setup status.</p></article>)}</div>; }
