import Link from "next/link";
import { requireAdminRole } from "@/lib/admin-auth";
export const dynamic = "force-dynamic";
const tools = [
  ["Import", "Google, CSV workflow, NYC, OSM imports, and recent import logs", "Imports", "/admin/dashboard/settings/location-tools/import"],
  ["Enrichment", "Google enrichment review and high-value category correction", "Review", "/admin/dashboard/settings/location-tools/enrichment"],
  ["Duplicates", "Bounded duplicate scans and staged match decisions", "Review", "/admin/dashboard/settings/location-tools/duplicates"],
  ["Data Quality", "Missing addresses, coordinates, photos, categories, and search metadata", "Repair", "/admin/dashboard/settings/location-tools/data-quality"],
  ["Hidden Locations", "Review hidden and low-level records, then bulk unhide or make eligible locations searchable", "Repair", "/admin/dashboard/settings/location-tools/hidden-locations"],
  ["Photos", "Diagnostics, Google photo caching, and single-location repair", "Repair", "/admin/dashboard/settings/location-tools/photos"],
  ["Publishing", "Publish readiness and searchable status repair", "Publish", "/admin/dashboard/settings/location-tools/publishing"],
  ["Markets", "Market assignment counts and safe bounded repairs", "Repair", "/admin/dashboard/settings/location-tools/markets"],
  ["Anchor Locations", "Manage the named landmarks, venues, businesses, aliases, and radius policies used by anchored nearby search", "Search", "/admin/dashboard/search-anchors"],
  ["Claim URLs", "Claim code, canonical URL, and QR repair tools", "Claims", "/admin/dashboard/settings/location-tools/claim-urls"],
  ["Logs", "Import and maintenance activity filters", "Logs", "/admin/dashboard/settings/location-tools/logs"],
] as const;
export default async function LocationToolsPage() { await requireAdminRole(["superadmin", "admin"]); return <main className="min-h-screen bg-[#080407] px-4 pb-12 pt-6 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-6"><section className="rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_top_left,rgba(236,11,91,.2),transparent_34%),#0d0d0f] p-6"><p className="text-xs font-black uppercase tracking-[0.32em] text-rose-200">Admin Settings</p><h1 className="mt-3 text-4xl font-black">Location Tools</h1><p className="mt-3 max-w-3xl text-sm font-bold leading-6 text-white/60">Operations hub for technical location database maintenance: imports, enrichment, dedupe, quality checks, hidden-location repair, photos, publishing, markets, anchor locations, claim URLs, and logs.</p></section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{tools.map(([title, body, label, href]) => <Link key={href} href={href} className="rounded-3xl border border-white/10 bg-[#111] p-5 transition hover:bg-white/[0.07]"><span className="rounded-full border border-rose-300/20 bg-rose-500/10 px-3 py-1 text-xs font-black uppercase tracking-widest text-rose-100">{label}</span><h2 className="mt-4 text-xl font-black text-white">{title}</h2><p className="mt-2 text-sm font-bold leading-6 text-white/55">{body}</p></Link>)}</section><section className="rounded-3xl border border-white/10 bg-[#111] p-5 text-sm font-bold text-white/65"><p className="text-xs font-black uppercase tracking-widest text-white/35">Related</p><p className="mt-2">Browse and edit individual records in the <Link className="text-rose-200 underline" href="/admin/dashboard/locations">all-location database</Link>.</p></section></div></main>; }
