from pathlib import Path

promotion = Path('.github/workflows/oregon-dr-promotion.yml')
p = promotion.read_text()

old_validate = """          typo='VIRIN''IA_REF'\n          ! grep -F \"$typo\" .github/workflows/oregon-dr-promotion.yml >/dev/null\n"""
new_validate = """          typo='VIRIN''IA_REF'\n          ! grep -F \"$typo\" .github/workflows/oregon-dr-promotion.yml >/dev/null\n          grep -F 'DR write-fence probe' .github/workflows/oregon-dr-promotion.yml >/dev/null\n          grep -F \"'25006'\" .github/workflows/oregon-dr-promotion.yml >/dev/null\n          stats_token='public_tuple''_changes'\n          ! grep -F \"$stats_token\" .github/workflows/oregon-dr-promotion.yml >/dev/null\n"""
assert p.count(old_validate) == 1, 'promotion validation anchor mismatch'
p = p.replace(old_validate, new_validate, 1)

old_quiet = """          mod_sql=\"select coalesce(sum(n_tup_ins+n_tup_upd+n_tup_del),0)::bigint public_tuple_changes from pg_stat_user_tables where schemaname='public' and relname not in ('toh_region_migration_apply_errors','toh_storage_migration_manifest');\"\n          query_ref \"$mod_sql\" \"$RUNNER_TEMP/quiesce-before.json\"\n          sleep 5\n          query_ref \"$mod_sql\" \"$RUNNER_TEMP/quiesce-after.json\"\n          test \"$(jq -r '.[0].public_tuple_changes' \"$RUNNER_TEMP/quiesce-before.json\")\" = \"$(jq -r '.[0].public_tuple_changes' \"$RUNNER_TEMP/quiesce-after.json\")\" || { echo 'Virginia writes observed after database fence.' >&2; exit 1; }\n"""
new_quiet = """          service=\"$(cat \"$RUNNER_TEMP/virginia-service\")\"\n          echo \"::add-mask::$service\"\n          write_probe_ok=false\n          for attempt in $(seq 1 20); do\n            : > \"$RUNNER_TEMP/fence-write-probe.json\"\n            status=\"$(curl --silent --show-error --output \"$RUNNER_TEMP/fence-write-probe.json\" --write-out '%{http_code}' --request PATCH \\\n              --header \"apikey: $service\" --header \"Authorization: Bearer $service\" \\\n              --header 'Content-Type: application/json' --header 'Prefer: return=minimal' \\\n              --data '{\"name\":\"__dr_write_fence_probe__\"}' \\\n              \"${VIRGINIA_URL}/rest/v1/locations?id=eq.00000000-0000-0000-0000-000000000000\" || true)\"\n            code=\"$(jq -r '.code // empty' \"$RUNNER_TEMP/fence-write-probe.json\" 2>/dev/null || true)\"\n            if [ \"$code\" = '25006' ]; then write_probe_ok=true; break; fi\n            if [[ \"$status\" == 2* ]]; then\n              echo 'Virginia DR write-fence probe unexpectedly permitted a service-role UPDATE.' >&2\n              exit 1\n            fi\n            sleep 1\n          done\n          test \"$write_probe_ok\" = true || { echo 'Virginia DR write-fence probe did not prove SQLSTATE 25006.' >&2; exit 1; }\n"""
assert p.count(old_quiet) == 1, 'promotion quiet-window anchor mismatch'
p = p.replace(old_quiet, new_quiet, 1)
promotion.write_text(p)

failback = Path('scripts/dr/oregon-failback.sh')
s = failback.read_text()

old_function = """quiet_and_zero_lag() {\n  local zero=false\n  query_ref \"$OREGON_REF\" \"select coalesce(sum(n_tup_ins+n_tup_upd+n_tup_del),0)::bigint changes from pg_stat_user_tables where schemaname='public' and relname not in ('toh_region_migration_apply_errors','toh_storage_migration_manifest');\" \"$TMP/quiet-before.json\"\n  sleep 5\n  query_ref \"$OREGON_REF\" \"select coalesce(sum(n_tup_ins+n_tup_upd+n_tup_del),0)::bigint changes from pg_stat_user_tables where schemaname='public' and relname not in ('toh_region_migration_apply_errors','toh_storage_migration_manifest');\" \"$TMP/quiet-after.json\"\n  test \"$(jq -r '.[0].changes' \"$TMP/quiet-before.json\")\" = \"$(jq -r '.[0].changes' \"$TMP/quiet-after.json\")\" || {\n    echo 'Oregon public writes were observed during the final quiet window.' >&2\n    exit 1\n  }\n  for _ in $(seq 1 60); do\n    query_ref \"$OREGON_REF\" \"select coalesce((select pg_wal_lsn_diff(pg_current_wal_lsn(),confirmed_flush_lsn)::bigint from pg_replication_slots where slot_name='${FAILBACK_SLOT}'),-1) lag;\" \"$TMP/reverse-lag.json\"\n    if [ \"$(jq -r '.[0].lag' \"$TMP/reverse-lag.json\")\" = '0' ]; then zero=true; break; fi\n    sleep 2\n  done\n  test \"$zero\" = true || { echo 'Oregon to Virginia WAL lag did not reach zero.' >&2; exit 1; }\n}\n"""
new_function = """quiet_and_zero_lag() {\n  local zero=false service status code write_probe_ok=false\n  service=\"$(cat \"$TMP/oregon-service\")\"\n  echo \"::add-mask::$service\"\n  for _ in $(seq 1 20); do\n    : > \"$TMP/fence-write-probe.json\"\n    status=\"$(curl --silent --show-error --output \"$TMP/fence-write-probe.json\" --write-out '%{http_code}' --request PATCH \\\n      --header \"apikey: $service\" --header \"Authorization: Bearer $service\" \\\n      --header 'Content-Type: application/json' --header 'Prefer: return=minimal' \\\n      --data '{\"name\":\"__dr_write_fence_probe__\"}' \\\n      \"${OREGON_URL}/rest/v1/locations?id=eq.00000000-0000-0000-0000-000000000000\" || true)\"\n    code=\"$(jq -r '.code // empty' \"$TMP/fence-write-probe.json\" 2>/dev/null || true)\"\n    if [ \"$code\" = '25006' ]; then write_probe_ok=true; break; fi\n    if [[ \"$status\" == 2* ]]; then\n      echo 'Oregon DR write-fence probe unexpectedly permitted a service-role UPDATE.' >&2\n      exit 1\n    fi\n    sleep 1\n  done\n  test \"$write_probe_ok\" = true || { echo 'Oregon DR write-fence probe did not prove SQLSTATE 25006.' >&2; exit 1; }\n  for _ in $(seq 1 60); do\n    query_ref \"$OREGON_REF\" \"select coalesce((select pg_wal_lsn_diff(pg_current_wal_lsn(),confirmed_flush_lsn)::bigint from pg_replication_slots where slot_name='${FAILBACK_SLOT}'),-1) lag;\" \"$TMP/reverse-lag.json\"\n    if [ \"$(jq -r '.[0].lag' \"$TMP/reverse-lag.json\")\" = '0' ]; then zero=true; break; fi\n    sleep 2\n  done\n  test \"$zero\" = true || { echo 'Oregon to Virginia WAL lag did not reach zero.' >&2; exit 1; }\n}\n"""
assert s.count(old_function) == 1, 'failback quiet-window anchor mismatch'
s = s.replace(old_function, new_function, 1)
failback.write_text(s)
