from pathlib import Path

MIGRATION = Path('supabase/migrations/20260831233000_enable_dr_data_api_write_fence.sql')
MIGRATION.write_text("""-- Keep Supabase Data API reads available during a regional DR write fence while\n-- rejecting mutating PostgREST requests before their main query executes.\ncreate or replace function public.theouthaven_dr_pre_request()\nreturns void\nlanguage plpgsql\nset search_path = ''\nas $function$\ndeclare\n  request_method text := upper(coalesce(current_setting('request.method', true), ''));\n  write_fence text := lower(coalesce(current_setting('theouthaven.dr_write_fence', true), 'off'));\nbegin\n  if write_fence = 'on' and request_method in ('POST', 'PATCH', 'PUT', 'DELETE') then\n    raise sqlstate '25006' using message = 'TheOutHaven DR write fence is active';\n  end if;\nend;\n$function$;\n\ncomment on function public.theouthaven_dr_pre_request() is\n  'Rejects mutating Supabase Data API requests while the regional DR write fence is active.';\n\nalter role authenticator set pgrst.db_pre_request = 'public.theouthaven_dr_pre_request';\nalter database postgres set \"theouthaven.dr_write_fence\" = 'off';\nnotify pgrst, 'reload config';\n""")

promotion = Path('.github/workflows/oregon-dr-promotion.yml')
p = promotion.read_text()

old_validate = """          grep -F 'DR write-fence probe' .github/workflows/oregon-dr-promotion.yml >/dev/null\n          grep -F \"'25006'\" .github/workflows/oregon-dr-promotion.yml >/dev/null\n          stats_token='public_tuple''_changes'\n          ! grep -F \"$stats_token\" .github/workflows/oregon-dr-promotion.yml >/dev/null\n"""
new_validate = """          grep -F 'DR write-fence probe' .github/workflows/oregon-dr-promotion.yml >/dev/null\n          grep -F \"'25006'\" .github/workflows/oregon-dr-promotion.yml >/dev/null\n          test -f supabase/migrations/20260831233000_enable_dr_data_api_write_fence.sql\n          grep -F 'theouthaven_dr_pre_request' supabase/migrations/20260831233000_enable_dr_data_api_write_fence.sql >/dev/null\n          grep -F 'pgrst.db_pre_request' supabase/migrations/20260831233000_enable_dr_data_api_write_fence.sql >/dev/null\n          grep -F 'theouthaven.dr_write_fence' .github/workflows/oregon-dr-promotion.yml >/dev/null\n          stats_token='public_tuple''_changes'\n          ! grep -F \"$stats_token\" .github/workflows/oregon-dr-promotion.yml >/dev/null\n"""
assert p.count(old_validate) == 1, 'promotion validation anchor mismatch'
p = p.replace(old_validate, new_validate, 1)

old_start = """          source_sql=\"select (select count(*) from cron.job) cron_jobs,(select count(*) from pg_publication where pubname='${FORWARD_PUBLICATION}') publication_count,(select count(*) from pg_replication_slots where slot_name='${FORWARD_SLOT}') slot_count,(select count(*) from pg_replication_slots where slot_name='${FORWARD_SLOT}' and active) active_slots;\"\n          target_sql=\"select (select count(*) from cron.job where active) active_cron_jobs,(select count(*) from pg_subscription where subname='${FORWARD_SUBSCRIPTION}' and subenabled) enabled_subscriptions,(select count(*) from pg_stat_subscription where subname='${FORWARD_SUBSCRIPTION}' and pid is not null) workers,(select count(*) from pg_subscription_rel sr join pg_subscription s on s.oid=sr.srsubid where s.subname='${FORWARD_SUBSCRIPTION}' and sr.srsubstate='r') ready_tables;\"\n          query_ref \"$VIRGINIA_REF\" \"$source_sql\" \"$RUNNER_TEMP/source-start.json\"\n          query_ref \"$OREGON_REF\" \"$target_sql\" \"$RUNNER_TEMP/target-start.json\"\n          jq -e '.[0].cron_jobs==0 and .[0].publication_count==1 and .[0].slot_count==1 and .[0].active_slots==1' \"$RUNNER_TEMP/source-start.json\" >/dev/null\n          jq -e '.[0].active_cron_jobs==0 and .[0].enabled_subscriptions==1 and .[0].workers==1 and .[0].ready_tables==462' \"$RUNNER_TEMP/target-start.json\" >/dev/null\n"""
new_start = """          source_sql=\"select (select count(*) from cron.job) cron_jobs,(select count(*) from pg_publication where pubname='${FORWARD_PUBLICATION}') publication_count,(select count(*) from pg_replication_slots where slot_name='${FORWARD_SLOT}') slot_count,(select count(*) from pg_replication_slots where slot_name='${FORWARD_SLOT}' and active) active_slots,(select (to_regprocedure('public.theouthaven_dr_pre_request()') is not null)::int) dr_pre_request_functions,(select count(*) from pg_roles where rolname='authenticator' and coalesce(array_to_string(rolconfig,','),'') like '%pgrst.db_pre_request=public.theouthaven_dr_pre_request%') dr_pre_request_configured,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%theouthaven.dr_write_fence=on%') api_fences;\"\n          target_sql=\"select (select count(*) from cron.job where active) active_cron_jobs,(select count(*) from pg_subscription where subname='${FORWARD_SUBSCRIPTION}' and subenabled) enabled_subscriptions,(select count(*) from pg_stat_subscription where subname='${FORWARD_SUBSCRIPTION}' and pid is not null) workers,(select count(*) from pg_subscription_rel sr join pg_subscription s on s.oid=sr.srsubid where s.subname='${FORWARD_SUBSCRIPTION}' and sr.srsubstate='r') ready_tables,(select (to_regprocedure('public.theouthaven_dr_pre_request()') is not null)::int) dr_pre_request_functions,(select count(*) from pg_roles where rolname='authenticator' and coalesce(array_to_string(rolconfig,','),'') like '%pgrst.db_pre_request=public.theouthaven_dr_pre_request%') dr_pre_request_configured,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%theouthaven.dr_write_fence=on%') api_fences;\"\n          query_ref \"$VIRGINIA_REF\" \"$source_sql\" \"$RUNNER_TEMP/source-start.json\"\n          query_ref \"$OREGON_REF\" \"$target_sql\" \"$RUNNER_TEMP/target-start.json\"\n          jq -e '.[0].cron_jobs==0 and .[0].publication_count==1 and .[0].slot_count==1 and .[0].active_slots==1 and .[0].dr_pre_request_functions==1 and .[0].dr_pre_request_configured==1 and .[0].api_fences==0' \"$RUNNER_TEMP/source-start.json\" >/dev/null\n          jq -e '.[0].active_cron_jobs==0 and .[0].enabled_subscriptions==1 and .[0].workers==1 and .[0].ready_tables==462 and .[0].dr_pre_request_functions==1 and .[0].dr_pre_request_configured==1 and .[0].api_fences==0' \"$RUNNER_TEMP/target-start.json\" >/dev/null\n"""
assert p.count(old_start) == 1, 'promotion start-state anchor mismatch'
p = p.replace(old_start, new_start, 1)

old_fence = """          query_ref \"alter role postgres set default_transaction_read_only=off; alter database postgres set default_transaction_read_only=on;\" \"$RUNNER_TEMP/fence-set.json\"\n          query_ref \"select pg_terminate_backend(pid) terminated from pg_stat_activity where pid<>pg_backend_pid() and usename in ('authenticator','supabase_auth_admin','supabase_storage_admin');\" \"$RUNNER_TEMP/fence-terminate.json\"\n          query_ref \"select (select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%default_transaction_read_only=on%') database_fences,(select count(*) from pg_roles where rolname='postgres' and coalesce(array_to_string(rolconfig,','),'') like '%default_transaction_read_only=off%') admin_overrides,(select count(*) from pg_roles where rolname in ('authenticator','supabase_auth_admin','supabase_storage_admin') and coalesce(array_to_string(rolconfig,','),'') like '%default_transaction_read_only=off%') service_write_overrides;\" \"$RUNNER_TEMP/fence-verify.json\"\n          jq -e '.[0].database_fences==1 and .[0].admin_overrides==1 and .[0].service_write_overrides==0' \"$RUNNER_TEMP/fence-verify.json\" >/dev/null || { echo 'Virginia database write fence did not apply.' >&2; exit 1; }\n          printf '%s' true > \"$RUNNER_TEMP/virginia-fenced\"\n"""
new_fence = """          query_ref \"alter role postgres set default_transaction_read_only=off; alter database postgres set default_transaction_read_only=on; alter database postgres set \\\"theouthaven.dr_write_fence\\\"=on;\" \"$RUNNER_TEMP/fence-set.json\"\n          query_ref \"select pg_terminate_backend(pid) terminated from pg_stat_activity where pid<>pg_backend_pid() and usename in ('authenticator','supabase_auth_admin','supabase_storage_admin');\" \"$RUNNER_TEMP/fence-terminate.json\"\n          query_ref \"select (select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%default_transaction_read_only=on%') database_fences,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%theouthaven.dr_write_fence=on%') api_fences,(select count(*) from pg_roles where rolname='postgres' and coalesce(array_to_string(rolconfig,','),'') like '%default_transaction_read_only=off%') admin_overrides,(select count(*) from pg_roles where rolname in ('authenticator','supabase_auth_admin','supabase_storage_admin') and coalesce(array_to_string(rolconfig,','),'') like '%default_transaction_read_only=off%') service_write_overrides,(select count(*) from pg_roles where rolname='authenticator' and coalesce(array_to_string(rolconfig,','),'') like '%pgrst.db_pre_request=public.theouthaven_dr_pre_request%') dr_pre_request_configured;\" \"$RUNNER_TEMP/fence-verify.json\"\n          jq -e '.[0].database_fences==1 and .[0].api_fences==1 and .[0].admin_overrides==1 and .[0].service_write_overrides==0 and .[0].dr_pre_request_configured==1' \"$RUNNER_TEMP/fence-verify.json\" >/dev/null || { echo 'Virginia layered write fence did not apply.' >&2; exit 1; }\n          printf '%s' true > \"$RUNNER_TEMP/virginia-fenced\"\n"""
assert p.count(old_fence) == 1, 'promotion fence anchor mismatch'
p = p.replace(old_fence, new_fence, 1)

old_final = """          query_ref \"$VIRGINIA_REF\" \"select (select count(*) from cron.job) cron_jobs,(select count(*) from pg_replication_slots where slot_name='${FORWARD_SLOT}') forward_slots;\" \"$RUNNER_TEMP/virginia-final.json\"\n          query_ref \"$OREGON_REF\" \"select (select count(*) from cron.job where active) active_cron_jobs,(select count(*) from pg_subscription where subname='${FORWARD_SUBSCRIPTION}') forward_subscriptions;\" \"$RUNNER_TEMP/oregon-final.json\"\n          jq -e '.[0].cron_jobs==0 and .[0].forward_slots==0' \"$RUNNER_TEMP/virginia-final.json\" >/dev/null\n          jq -e '.[0].active_cron_jobs==0 and .[0].forward_subscriptions==0' \"$RUNNER_TEMP/oregon-final.json\" >/dev/null\n"""
new_final = """          query_ref \"$VIRGINIA_REF\" \"select (select count(*) from cron.job) cron_jobs,(select count(*) from pg_replication_slots where slot_name='${FORWARD_SLOT}') forward_slots,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%default_transaction_read_only=on%') database_fences,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%theouthaven.dr_write_fence=on%') api_fences;\" \"$RUNNER_TEMP/virginia-final.json\"\n          query_ref \"$OREGON_REF\" \"select (select count(*) from cron.job where active) active_cron_jobs,(select count(*) from pg_subscription where subname='${FORWARD_SUBSCRIPTION}') forward_subscriptions,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%default_transaction_read_only=on%') database_fences,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%theouthaven.dr_write_fence=on%') api_fences;\" \"$RUNNER_TEMP/oregon-final.json\"\n          jq -e '.[0].cron_jobs==0 and .[0].forward_slots==0 and .[0].database_fences==1 and .[0].api_fences==1' \"$RUNNER_TEMP/virginia-final.json\" >/dev/null\n          jq -e '.[0].active_cron_jobs==0 and .[0].forward_subscriptions==0 and .[0].database_fences==0 and .[0].api_fences==0' \"$RUNNER_TEMP/oregon-final.json\" >/dev/null\n"""
assert p.count(old_final) == 1, 'promotion final-state anchor mismatch'
p = p.replace(old_final, new_final, 1)

old_recovery = """              jq -n --arg query \"alter database postgres reset default_transaction_read_only; alter role postgres reset default_transaction_read_only; select pg_terminate_backend(pid) from pg_stat_activity where pid<>pg_backend_pid() and usename in ('authenticator','supabase_auth_admin','supabase_storage_admin');\" '{query:$query}' > \"$RUNNER_TEMP/unfence.json\"\n"""
new_recovery = """              jq -n --arg query \"alter database postgres set \\\"theouthaven.dr_write_fence\\\"=off; alter database postgres reset default_transaction_read_only; alter role postgres reset default_transaction_read_only; select pg_terminate_backend(pid) from pg_stat_activity where pid<>pg_backend_pid() and usename in ('authenticator','supabase_auth_admin','supabase_storage_admin');\" '{query:$query}' > \"$RUNNER_TEMP/unfence.json\"\n"""
assert p.count(old_recovery) == 1, 'promotion recovery anchor mismatch'
p = p.replace(old_recovery, new_recovery, 1)
promotion.write_text(p)

failback = Path('scripts/dr/oregon-failback.sh')
s = failback.read_text()

old_fence_functions = """fence_roles() {\n  local ref=\"$1\" out=\"$2\"\n  query_ref \"$ref\" \\\n    \"alter role postgres set default_transaction_read_only=off; alter database postgres set default_transaction_read_only=on; select pg_terminate_backend(pid) from pg_stat_activity where pid<>pg_backend_pid() and usename in ('authenticator','supabase_auth_admin','supabase_storage_admin');\" \\\n    \"$out\"\n  query_ref \"$ref\" \\\n    \"select (select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%default_transaction_read_only=on%') database_fences,(select count(*) from pg_roles where rolname='postgres' and coalesce(array_to_string(rolconfig,','),'') like '%default_transaction_read_only=off%') admin_overrides,(select count(*) from pg_roles where rolname in ('authenticator','supabase_auth_admin','supabase_storage_admin') and coalesce(array_to_string(rolconfig,','),'') like '%default_transaction_read_only=off%') service_write_overrides;\" \\\n    \"$TMP/fence-verify.json\"\n  jq -e '.[0].database_fences==1 and .[0].admin_overrides==1 and .[0].service_write_overrides==0' \"$TMP/fence-verify.json\" >/dev/null\n}\n\nunfence_roles() {\n  local ref=\"$1\" out=\"$2\"\n  query_ref \"$ref\" \\\n    \"alter database postgres reset default_transaction_read_only; alter role postgres reset default_transaction_read_only; select pg_terminate_backend(pid) from pg_stat_activity where pid<>pg_backend_pid() and usename in ('authenticator','supabase_auth_admin','supabase_storage_admin');\" \\\n    \"$out\"\n}\n"""
new_fence_functions = """fence_roles() {\n  local ref=\"$1\" out=\"$2\"\n  query_ref \"$ref\" \\\n    \"alter role postgres set default_transaction_read_only=off; alter database postgres set default_transaction_read_only=on; alter database postgres set \\\"theouthaven.dr_write_fence\\\"=on; select pg_terminate_backend(pid) from pg_stat_activity where pid<>pg_backend_pid() and usename in ('authenticator','supabase_auth_admin','supabase_storage_admin');\" \\\n    \"$out\"\n  query_ref \"$ref\" \\\n    \"select (select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%default_transaction_read_only=on%') database_fences,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%theouthaven.dr_write_fence=on%') api_fences,(select count(*) from pg_roles where rolname='postgres' and coalesce(array_to_string(rolconfig,','),'') like '%default_transaction_read_only=off%') admin_overrides,(select count(*) from pg_roles where rolname in ('authenticator','supabase_auth_admin','supabase_storage_admin') and coalesce(array_to_string(rolconfig,','),'') like '%default_transaction_read_only=off%') service_write_overrides,(select count(*) from pg_roles where rolname='authenticator' and coalesce(array_to_string(rolconfig,','),'') like '%pgrst.db_pre_request=public.theouthaven_dr_pre_request%') dr_pre_request_configured;\" \\\n    \"$TMP/fence-verify.json\"\n  jq -e '.[0].database_fences==1 and .[0].api_fences==1 and .[0].admin_overrides==1 and .[0].service_write_overrides==0 and .[0].dr_pre_request_configured==1' \"$TMP/fence-verify.json\" >/dev/null\n}\n\nunfence_roles() {\n  local ref=\"$1\" out=\"$2\"\n  query_ref \"$ref\" \\\n    \"alter database postgres set \\\"theouthaven.dr_write_fence\\\"=off; alter database postgres reset default_transaction_read_only; alter role postgres reset default_transaction_read_only; select pg_terminate_backend(pid) from pg_stat_activity where pid<>pg_backend_pid() and usename in ('authenticator','supabase_auth_admin','supabase_storage_admin');\" \\\n    \"$out\"\n}\n"""
assert s.count(old_fence_functions) == 1, 'failback fence function anchor mismatch'
s = s.replace(old_fence_functions, new_fence_functions, 1)

old_start_queries = """  query_ref \"$VIRGINIA_REF\" \\\n    \"select (select count(*) from cron.job) cron_jobs,(select count(*) from pg_replication_slots where slot_name='${FORWARD_SLOT}' and active) active_forward_slots;\" \\\n    \"$TMP/virginia-start.json\"\n  query_ref \"$OREGON_REF\" \\\n    \"select (select count(*) from cron.job where active) active_cron_jobs,(select count(*) from pg_subscription where subname='${FORWARD_SUBSCRIPTION}') forward_subscriptions,(select count(*) from pg_subscription where subname='${FORWARD_SUBSCRIPTION}' and subenabled) enabled_forward_subscriptions,(select count(*) from pg_stat_subscription where subname='${FORWARD_SUBSCRIPTION}' and pid is not null) forward_workers;\" \\\n    \"$TMP/oregon-start.json\"\n  jq -e '.[0].cron_jobs==0 and .[0].active_forward_slots==0' \"$TMP/virginia-start.json\" >/dev/null\n  jq -e '.[0].active_cron_jobs==0 and .[0].forward_subscriptions==0 and .[0].enabled_forward_subscriptions==0 and .[0].forward_workers==0' \"$TMP/oregon-start.json\" >/dev/null || {\n"""
new_start_queries = """  query_ref \"$VIRGINIA_REF\" \\\n    \"select (select count(*) from cron.job) cron_jobs,(select count(*) from pg_replication_slots where slot_name='${FORWARD_SLOT}' and active) active_forward_slots,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%default_transaction_read_only=on%') database_fences,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%theouthaven.dr_write_fence=on%') api_fences,(select count(*) from pg_roles where rolname='authenticator' and coalesce(array_to_string(rolconfig,','),'') like '%pgrst.db_pre_request=public.theouthaven_dr_pre_request%') dr_pre_request_configured;\" \\\n    \"$TMP/virginia-start.json\"\n  query_ref \"$OREGON_REF\" \\\n    \"select (select count(*) from cron.job where active) active_cron_jobs,(select count(*) from pg_subscription where subname='${FORWARD_SUBSCRIPTION}') forward_subscriptions,(select count(*) from pg_subscription where subname='${FORWARD_SUBSCRIPTION}' and subenabled) enabled_forward_subscriptions,(select count(*) from pg_stat_subscription where subname='${FORWARD_SUBSCRIPTION}' and pid is not null) forward_workers,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%default_transaction_read_only=on%') database_fences,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%theouthaven.dr_write_fence=on%') api_fences,(select count(*) from pg_roles where rolname='authenticator' and coalesce(array_to_string(rolconfig,','),'') like '%pgrst.db_pre_request=public.theouthaven_dr_pre_request%') dr_pre_request_configured;\" \\\n    \"$TMP/oregon-start.json\"\n  jq -e '.[0].cron_jobs==0 and .[0].active_forward_slots==0 and .[0].database_fences==1 and .[0].api_fences==1 and .[0].dr_pre_request_configured==1' \"$TMP/virginia-start.json\" >/dev/null\n  jq -e '.[0].active_cron_jobs==0 and .[0].forward_subscriptions==0 and .[0].enabled_forward_subscriptions==0 and .[0].forward_workers==0 and .[0].database_fences==0 and .[0].api_fences==0 and .[0].dr_pre_request_configured==1' \"$TMP/oregon-start.json\" >/dev/null || {\n"""
assert s.count(old_start_queries) == 1, 'failback primary-state anchor mismatch'
s = s.replace(old_start_queries, new_start_queries, 1)

old_final_queries = """  query_ref \"$VIRGINIA_REF\" \"select count(*) cron_jobs from cron.job;\" \"$TMP/virginia-cron-final.json\"\n  query_ref \"$OREGON_REF\" \"select count(*) active_cron_jobs from cron.job where active;\" \"$TMP/oregon-cron-final.json\"\n  test \"$(jq -r '.[0].cron_jobs' \"$TMP/virginia-cron-final.json\")\" = '0'\n  test \"$(jq -r '.[0].active_cron_jobs' \"$TMP/oregon-cron-final.json\")\" = '0'\n"""
new_final_queries = """  query_ref \"$VIRGINIA_REF\" \"select (select count(*) from cron.job) cron_jobs,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%default_transaction_read_only=on%') database_fences,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%theouthaven.dr_write_fence=on%') api_fences,(select count(*) from pg_roles where rolname='authenticator' and coalesce(array_to_string(rolconfig,','),'') like '%pgrst.db_pre_request=public.theouthaven_dr_pre_request%') dr_pre_request_configured;\" \"$TMP/virginia-cron-final.json\"\n  query_ref \"$OREGON_REF\" \"select (select count(*) from cron.job where active) active_cron_jobs,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%default_transaction_read_only=on%') database_fences,(select count(*) from pg_db_role_setting s join pg_database d on d.oid=s.setdatabase where d.datname='postgres' and s.setrole=0 and coalesce(array_to_string(s.setconfig,','),'') like '%theouthaven.dr_write_fence=on%') api_fences,(select count(*) from pg_roles where rolname='authenticator' and coalesce(array_to_string(rolconfig,','),'') like '%pgrst.db_pre_request=public.theouthaven_dr_pre_request%') dr_pre_request_configured;\" \"$TMP/oregon-cron-final.json\"\n  jq -e '.[0].cron_jobs==0 and .[0].database_fences==0 and .[0].api_fences==0 and .[0].dr_pre_request_configured==1' \"$TMP/virginia-cron-final.json\" >/dev/null\n  jq -e '.[0].active_cron_jobs==0 and .[0].database_fences==0 and .[0].api_fences==0 and .[0].dr_pre_request_configured==1' \"$TMP/oregon-cron-final.json\" >/dev/null\n"""
assert s.count(old_final_queries) == 1, 'failback final-state anchor mismatch'
s = s.replace(old_final_queries, new_final_queries, 1)
failback.write_text(s)
