import { PROFILE_VERSION, taxonomy, type SearchDomain } from "../v2/taxonomy";
import { evidence, isStrongEvidence } from "./profileEvidence";
import { profileHash } from "./profileHash";
import type { LocationRecord, LocationSearchProfile, ManualOverrides, ProfileEvidence } from "./profileTypes";
const list=(v:unknown):string[]=>Array.isArray(v)?v.filter(x=>typeof x==='string').map(x=>x.trim().toLowerCase()):typeof v==='string'?v.split(/[,|]/).map(x=>x.trim().toLowerCase()).filter(Boolean):[];
const scalar=(v:unknown):string=>typeof v==='string'?v.trim().toLowerCase():'';
export function buildLocationSearchProfile(location:LocationRecord, overrides:ManualOverrides={}):LocationSearchProfile {
 const found:ProfileEvidence[]=[]; const fields=['location_type','primary_category','activity_type','cuisine','cuisine_type','tags','vibe_tags','best_for_tags','date_style_tags','search_keywords','google_types','semantic_tags','intent_tags','description'] as const;
 for(const [id,item] of Object.entries(taxonomy)) for(const rule of item.evidenceRules) for(const field of rule.fields) { const values=list(location[field]); for(const value of values) if((rule.values??[id,...item.aliases]).some(term=>value===term.toLowerCase()||value.includes(term.toLowerCase()))) found.push(evidence(id,rule.source,rule.strength,field,value,`${field} supports ${id}`)); }
 const strongIds=new Set(found.filter(isStrongEvidence).map(x=>x.taxonomyId));
 const byDomain=(domain:SearchDomain)=>[...strongIds].filter(id=>taxonomy[id]?.domain===domain);
 let domains=(['restaurant','activity','nightlife'] as SearchDomain[]).filter(d=>byDomain(d).length>0); if(domains.length>1) domains.push('hybrid');
 const overriddenDomains=list(overrides.supportedDomains).filter(x=>['restaurant','activity','nightlife','hybrid'].includes(x)) as SearchDomain[]; if(overriddenDomains.length) domains=overriddenDomains;
 const primary=(typeof overrides.primaryDomain==='string'&&domains.includes(overrides.primaryDomain as SearchDomain)?overrides.primaryDomain:domains.includes('hybrid')?'hybrid':domains[0]??'activity') as SearchDomain;
 const idsFor=(domain:SearchDomain)=>[...strongIds].filter(id=>taxonomy[id]?.domain===domain);
 const getOverride=(key:keyof ManualOverrides,fallback:string[])=>overrides[key]===undefined?fallback:list(overrides[key]);
 let meals=getOverride('mealPeriods',[...strongIds].flatMap(id=>taxonomy[id]?.mealPeriods??[])); const dinnerEvidence=found.some(x=>isStrongEvidence(x)&&(x.taxonomyId==='dinner'||x.taxonomyId==='full_service_dining'||x.source==='website_or_menu'||x.source==='manual_override')); const coffeeFirst=['cafe','bakery','dessert'].some(x=>strongIds.has(x)); if(coffeeFirst&&!dinnerEvidence) meals=meals.filter(x=>x!=='dinner');
 const profile:LocationSearchProfile={locationId:location.id,primaryDomain:primary,supportedDomains:[...new Set(domains)],restaurantCategories:getOverride('restaurantCategories',idsFor('restaurant')),cuisines:getOverride('cuisines',['sushi','steakhouse','seafood','italian','mexican','halal','vegan'].filter(x=>strongIds.has(x))),foods:getOverride('foods',['chicken','steak','sushi','brunch'].filter(x=>strongIds.has(x))),activityCategories:getOverride('activityCategories',idsFor('activity')),nightlifeCategories:getOverride('nightlifeCategories',idsFor('nightlife')),mealPeriods:[...new Set(meals)],features:getOverride('features',[...strongIds].flatMap(id=>taxonomy[id]?.features??[])),audiences:getOverride('audiences',['family','teen','minors_present','adult_only','twenty_one_plus'].filter(x=>strongIds.has(x))),occasions:getOverride('occasions',['date_night','girls_night','group'].filter(x=>strongIds.has(x))),vibes:getOverride('vibes',list(location.vibe_tags)),canonicalTerms:[],exclusions:getOverride('exclusions',[...strongIds].flatMap(id=>taxonomy[id]?.exclusions??[])),searchText:'',latitude:typeof location.latitude==='number'?location.latitude:null,longitude:typeof location.longitude==='number'?location.longitude:null,market:scalar(location.market)||null,city:scalar(location.city)||null,neighborhood:scalar(location.neighborhood)||null,borough:scalar(location.borough)||null,county:scalar(location.county)||null,state:scalar(location.state)||null,classificationSources:{fields:found.map(x=>x.sourceField)},evidence:found,manualOverrides:{...overrides},confidence:Math.min(1,found.filter(isStrongEvidence).length/4),needsReview:false,reviewReasons:[],profileVersion:PROFILE_VERSION,profileHash:'',generatedAt:new Date().toISOString()};
 profile.canonicalTerms=[...new Set([profile.primaryDomain,...profile.restaurantCategories,...profile.cuisines,...profile.foods,...profile.activityCategories,...profile.nightlifeCategories,...profile.mealPeriods,...profile.features,...profile.audiences,...profile.occasions,...profile.vibes])].sort(); profile.searchText=[scalar(location.restaurant_name),scalar(location.activity_name),scalar(location.name),...profile.canonicalTerms].filter(Boolean).join(' '); if(!profile.supportedDomains.length) profile.reviewReasons.push('MISSING_SUPPORTED_DOMAIN'); if(profile.confidence<.5) profile.reviewReasons.push('LOW_CONFIDENCE'); if(location.is_searchable===true&&(profile.latitude===null||profile.longitude===null)) profile.reviewReasons.push('MISSING_COORDINATES'); profile.needsReview=profile.reviewReasons.length>0; profile.profileHash=profileHash(profile); return profile;
}
