import { NextRequest, NextResponse } from "next/server";
import { requireAdminApiRole } from "@/lib/admin-api-auth";
import { ADMIN_PAGE_ACCESS } from "@/lib/admin-permissions";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { calculateLocationMlScore, ML_SCORE_VERSION } from "@/lib/ml/locationRanking";
import { CALL_EVENTS, CLICK_EVENTS, Diagnostics, NEGATIVE_EVENTS, RESERVE_EVENTS, SAVE_EVENTS, VIEW_EVENTS, bump, isUuid, locationIdsFromAnalytics, mlPairs, mlResults, normalizeEventName, pairFromAnalytics, pick, recommendation } from "@/lib/ml/recalculationSignals";

export const runtime = "nodejs"; export const dynamic = "force-dynamic"; export const maxDuration = 300;
type Agg = { impressions_7d: number; impressions_30d: number; views_7d: number; views_30d: number; clicks_7d: number; clicks_30d: number; reservation_clicks_30d: number; call_clicks_30d: number; website_clicks_30d: number; saves_30d: number; completed_outings_30d: number; negative_signals_30d: number; last_engaged_at?: string | null };
function getBearerToken(request: NextRequest) { const auth = request.headers.get("authorization") || ""; return auth.toLowerCase().startsWith("bearer ") ? auth.slice(7).trim() : null; }
function isCronAuthorized(request: NextRequest) { return Boolean(process.env.CRON_SECRET && getBearerToken(request) === process.env.CRON_SECRET); }
async function authorize(request: NextRequest) { if (process.env.NODE_ENV === "development" || isCronAuthorized(request)) return null; const { error } = await requireAdminApiRole(ADMIN_PAGE_ACCESS.searchHealth); return error; }
function emptyAgg(): Agg { return { impressions_7d: 0, impressions_30d: 0, views_7d: 0, views_30d: 0, clicks_7d: 0, clicks_30d: 0, reservation_clicks_30d: 0, call_clicks_30d: 0, website_clicks_30d: 0, saves_30d: 0, completed_outings_30d: 0, negative_signals_30d: 0 }; }
function aggFor(map: Map<string, Agg>, id: unknown) { const key = typeof id === "string" ? id : ""; if (!isUuid(key)) return null; if (!map.has(key)) map.set(key, emptyAgg()); return map.get(key)!; }
function is7d(createdAt: string | null | undefined, since7d: Date) { const date = new Date(createdAt || 0); return !Number.isNaN(date.getTime()) && date >= since7d; }
function touch(agg: Agg, at?: string | null) { if (at && (!agg.last_engaged_at || new Date(at) > new Date(agg.last_engaged_at))) agg.last_engaged_at = at; }
async function safeSelect(table: string, columns: string, sinceIso: string) { try { const { data, error } = await supabaseAdmin.from(table).select(columns).gte("created_at", sinceIso).limit(50000); if (error) { console.warn(`ML ranking skipped ${table}:`, error.message); return []; } return data || []; } catch (error) { console.warn(`ML ranking skipped ${table}:`, error); return []; } }
function applyEvent(agg: Agg, name: string, createdAt: string | null, since7d: Date) { const in7d=is7d(createdAt,since7d); if (VIEW_EVENTS.has(name)) { agg.impressions_30d++; agg.views_30d++; if (in7d) { agg.impressions_7d++; agg.views_7d++; } } if (CLICK_EVENTS.has(name)) { agg.clicks_30d++; if (in7d) agg.clicks_7d++; touch(agg, createdAt); } if (RESERVE_EVENTS.has(name)) agg.reservation_clicks_30d++; if (CALL_EVENTS.has(name)) agg.call_clicks_30d++; if (SAVE_EVENTS.has(name)) { agg.saves_30d++; touch(agg, createdAt); } if (NEGATIVE_EVENTS.has(name)) agg.negative_signals_30d++; }

export async function POST(request: NextRequest) {
  const authError = await authorize(request); if (authError) return authError;
  const now = new Date(); const since30d = new Date(now.getTime() - 30 * 864e5); const since7d = new Date(now.getTime() - 7 * 864e5);
  const features = new Map<string, Agg>(); let errors = 0;
  const diagnostics: Diagnostics = { analyticsEventsRead:0, analyticsEventsWithLocationId:0, analyticsEventsWithPairIds:0, searchEventsRead:0, searchEventsWithMlResultIds:0, searchEventsWithMlPairIds:0, searchEventsWithOnlyFirstResultNames:0, outingsRead:0, outingsWithRestaurantActivityIds:0, candidateLocationRows:0, upsertLocationRows:0, skippedReasons:{} };
  const searchEvents = await safeSelect("search_events", "id,created_at,metadata", since30d.toISOString()); diagnostics.searchEventsRead = searchEvents.length;
  for (const row of searchEvents as any[]) { const meta=row.metadata||{}; const results=mlResults(meta); const pairs=mlPairs(meta); if (results.length) diagnostics.searchEventsWithMlResultIds++; if (pairs.length) diagnostics.searchEventsWithMlPairIds++; if (!results.length && !pairs.length && Array.isArray(meta?.debugParity?.firstResultNames) && meta.debugParity.firstResultNames.length) diagnostics.searchEventsWithOnlyFirstResultNames++; for (const r of results) { const a=aggFor(features,r.location_id); if(a){ a.impressions_30d++; a.views_30d++; if(is7d(row.created_at,since7d)){a.impressions_7d++; a.views_7d++;} } } for (const p of pairs) for (const id of [p.restaurant_location_id,p.activity_location_id]) { const a=aggFor(features,id); if(a){ a.impressions_30d++; a.views_30d++; if(is7d(row.created_at,since7d)){a.impressions_7d++; a.views_7d++;} } } }
  const events = await safeSelect("analytics_events", "*", since30d.toISOString()); diagnostics.analyticsEventsRead = events.length;
  for (const row of events as any[]) { const locs=locationIdsFromAnalytics(row); const pair=pairFromAnalytics(row); if(locs.length) diagnostics.analyticsEventsWithLocationId++; if(pair) diagnostics.analyticsEventsWithPairIds++; if(!locs.length && !pair){ bump(diagnostics,"analytics_missing_ids"); continue; } for (const id of [...locs, pair?.restaurant_location_id, pair?.activity_location_id].filter(Boolean)) { const a=aggFor(features,id); if (a) applyEvent(a, normalizeEventName(row), row.created_at, since7d); } }
  const outings = await safeSelect("outings", "*", since30d.toISOString()); diagnostics.outingsRead = outings.length;
  for (const row of outings as any[]) { const ids=[pick(row,["location_id"]),pick(row,["restaurant_location_id","restaurant_id","selected_restaurant_location_id"]),pick(row,["activity_location_id","activity_id","selected_activity_location_id"])].filter(isUuid); if(ids.length>=2) diagnostics.outingsWithRestaurantActivityIds++; if(!ids.length){ bump(diagnostics,"outings_missing_location_ids"); continue; } const status=String(row.status||"").toLowerCase(); for (const id of ids) { const a=aggFor(features,id); if(!a) continue; a.impressions_30d++; if(is7d(row.created_at,since7d)) a.impressions_7d++; if(row.saved_at||status.includes("saved")){a.saves_30d++; touch(a,row.saved_at||row.created_at);} if(row.completed_at||row.completed_no_feedback_at||row.completion_inferred_at||status.includes("completed")){a.completed_outings_30d++; touch(a,row.completed_at||row.created_at);} if(row.last_link_clicked_at||status.includes("link")){a.clicks_30d++; a.website_clicks_30d++; touch(a,row.last_link_clicked_at||row.created_at);} if(status.includes("reservation")) a.reservation_clicks_30d++; if(status.includes("call")) a.call_clicks_30d++; } }
  diagnostics.candidateLocationRows = features.size;
  const rows = Array.from(features.entries()).map(([location_id, a]) => { const conversions = a.reservation_clicks_30d + a.call_clicks_30d + a.website_clicks_30d + a.saves_30d + a.completed_outings_30d; const ctr_30d = a.clicks_30d / Math.max(a.impressions_30d, 1); const conversion_rate_30d = conversions / Math.max(a.views_30d + a.clicks_30d, 1); const freshness_score = a.last_engaged_at ? Math.max(0, 10 - (now.getTime() - new Date(a.last_engaged_at).getTime()) / 86400000) : 0; const engagement_score = Math.min(25, Math.log1p(a.clicks_30d * 2 + a.views_30d * 0.25 + a.saves_30d * 5 + a.completed_outings_30d * 8) * 7); const conversion_score = Math.min(30, conversion_rate_30d * 30); const quality_component = 0; const ml_score = calculateLocationMlScore({ ...a, ctr_30d, conversion_rate_30d, engagement_score, conversion_score, freshness_score, quality_component }); return { location_id, updated_at: now.toISOString(), ...a, ctr_30d, conversion_rate_30d, engagement_score, conversion_score, freshness_score, quality_component, ml_score, score_version: ML_SCORE_VERSION, metadata: { signal_window_days: 30, last_engaged_at: a.last_engaged_at ?? null } }; });
  let updated = 0; if (rows.length) { const { error } = await supabaseAdmin.from("location_ml_features").upsert(rows, { onConflict: "location_id" }); if (error) { errors += rows.length; console.error("ML feature upsert failed", error.message); } else updated = rows.length; }
  diagnostics.upsertLocationRows = updated; diagnostics.recommendation = recommendation(diagnostics, updated);
  await supabaseAdmin.from("location_ml_score_runs").insert({ status: errors ? "completed_with_errors" : "completed", processed_count: rows.length, updated_count: updated, error_count: errors, score_version: ML_SCORE_VERSION, metadata: { diagnostics } });
  return NextResponse.json({ success: errors === 0, processed: rows.length, updated, errors, score_version: ML_SCORE_VERSION, sample_top_scores: rows.sort((a,b)=>b.ml_score-a.ml_score).slice(0,10).map(({ location_id, ml_score }) => ({ location_id, ml_score })), diagnostics });
}
export async function GET(request: NextRequest) { return POST(request); }
