import Link from "next/link";
import CrmWorkspaceShell from "@/components/admin/crm/CrmWorkspaceShell";
import { requireAdminRole } from "@/lib/admin-auth";
import { CRM_READ_ROLES } from "@/lib/crm/permissions";
import { getBusinessClaimSequenceMetrics } from "@/lib/gtm/sequenceMetrics";

export const dynamic = "force-dynamic";

export default async function BusinessClaimSequencesPage() {
  await requireAdminRole(CRM_READ_ROLES);
  const data = await getBusinessClaimSequenceMetrics();
  const cards = [
    ["Contactable", data.totals.contactable], ["Enrolled", data.totals.enrolled], ["Emails sent", data.totals.emailsSent],
    ["Delivered", data.totals.delivered], ["Opened", data.totals.opened], ["Clicked", data.totals.clicked],
    ["Replies", data.totals.replies], ["Claims", data.totals.claimed], ["Activated", data.totals.activated], ["Paid", data.totals.paid],
  ];
  return <CrmWorkspaceShell><main className="space-y-5 text-white">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-rose-300">GTM Automation</p><h1 className="mt-1 text-3xl font-black">Business Claim Sequences</h1><p className="mt-1 max-w-3xl text-white/55">Cold claim outreach → claim completion → owner activation → Essentials conversion, with suppression and event-driven exits.</p></div><Link href="/admin/dashboard/crm/gtm" className="rounded-xl border border-white/10 px-4 py-2 text-sm font-black">Revenue Intelligence</Link></header>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-5">{cards.map(([label,value])=><div key={String(label)} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><b className="text-2xl">{value}</b><small className="mt-1 block text-white/50">{label}</small></div>)}</section>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Email → Claim",data.rates.emailToClaim],["Claim → Paid",data.rates.claimToPaid],["Email → Paid",data.rates.emailToPaid],["Click rate",data.rates.clickRate],["Reply rate",data.rates.replyRate]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-white/10 bg-[#0e0e11] p-4"><b className="text-xl">{value}%</b><small className="mt-1 block text-zinc-500">{label}</small></div>)}</section>
    <section className="overflow-hidden rounded-3xl border border-white/10 bg-[#0e0e11]"><div className="border-b border-white/10 p-5"><h2 className="text-xl font-black">Lifecycle sequences</h2><p className="mt-1 text-sm text-zinc-500">Live execution and delivery posture by sequence.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-xs uppercase tracking-wide text-zinc-500"><tr>{["Sequence","Status","Enrollments","Active","Sent","Delivered","Opened","Clicked"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-white/[.07]">{data.sequences.map((row:any)=><tr key={row.key}><td className="px-4 py-3"><b>{row.name}</b><div className="text-xs text-zinc-600">{row.key}</div></td><td className="px-4 py-3 capitalize">{row.status}</td><td className="px-4 py-3">{row.enrollments}</td><td className="px-4 py-3">{row.active}</td><td className="px-4 py-3">{row.sent}</td><td className="px-4 py-3">{row.delivered}</td><td className="px-4 py-3">{row.opened}</td><td className="px-4 py-3">{row.clicked}</td></tr>)}</tbody></table></div></section>
    <section className="grid gap-4 lg:grid-cols-3"><div className="rounded-3xl border border-white/10 bg-[#0e0e11] p-5"><h2 className="font-black">Claim funnel</h2><div className="mt-3 space-y-2 text-sm text-zinc-400"><p>Contacted businesses: <b className="text-white">{data.funnel.contactedLocations}</b></p><p>Claim started: <b className="text-white">{data.funnel.claimStarted}</b></p><p>Claim submitted: <b className="text-white">{data.funnel.claimSubmitted}</b></p><p>Claimed: <b className="text-white">{data.funnel.claimed}</b></p><p>Activated: <b className="text-white">{data.funnel.activated}</b></p><p>Paid: <b className="text-white">{data.funnel.paid}</b></p></div></div><div className="rounded-3xl border border-white/10 bg-[#0e0e11] p-5"><h2 className="font-black">Safety gates</h2><p className="mt-2 text-sm leading-6 text-zinc-500">Approved templates only. Public-business contacts require confidence ≥80. Do-not-contact, unsubscribe, bounce, complaint and provider suppression stop promotional automation. Existing CRM limits remain 1 email/day and 3/week per contact.</p></div><div className="rounded-3xl border border-white/10 bg-[#0e0e11] p-5"><h2 className="font-black">Behavior-driven routing</h2><p className="mt-2 text-sm leading-6 text-zinc-500">Replies pause automation for human handling. Claim starts exit cold outreach. Claim approval moves to activation. Activated free businesses can enter Essentials conversion. Paid status exits acquisition.</p></div></section>
  </main></CrmWorkspaceShell>;
}
