import { revalidatePath } from "next/cache";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { sendTemplatedEmail } from "@/lib/email/send";

export const MIRROR_DEMO_KEY = "real_location_mirror_demo";
export const MIRROR_DEMO_MODE = "real_location_mirror";
export const DEMO_LOCATION_NAME = "TheOutHaven Demo Lounge";
export const SAFE_DEMO_EMAILS = new Set(["demo-owner@theouthaven.com","demo-events@theouthaven.com","demo-reservations@theouthaven.com","demo-customer@theouthaven.com","demo-vip@theouthaven.com"]);
export type DemoStatus = "Ready" | "Needs setup" | "Not installed" | "Needs data";
export type DemoLink = { label: string; href: string; description?: string };
export const demoMetadata = { demo: true, demo_key: MIRROR_DEMO_KEY, demo_mode: MIRROR_DEMO_MODE };

async function tableExists(table: string) { try { const { error } = await supabaseAdmin.from(table).select("id", { head: true, count: "exact" }).limit(1); return !error; } catch { return false; } }
async function countRows(table: string, locationId?: string) { try { let q = supabaseAdmin.from(table).select("id", { head: true, count: "exact" }); if (locationId) q = q.eq("location_id", locationId); const { count, error } = await q; return error ? null : count || 0; } catch { return null; } }
async function insertSafe(table: string, rows: Record<string, any> | Record<string, any>[]) { try { if (!(await tableExists(table))) return { skipped: true }; const { data, error } = await supabaseAdmin.from(table).insert(rows as any).select("*"); if (error) return { error: error.message }; return { data }; } catch { return { error: "Skipped because this module is not installed yet." }; } }
async function deleteDemoRows(table: string, locationId: string) { try { if (!(await tableExists(table))) return; await supabaseAdmin.from(table).delete().eq("location_id", locationId).contains("metadata", { demo: true, demo_key: MIRROR_DEMO_KEY }); } catch {} }

export function isSafeDemoEmail(email?: string | null, adminEmail?: string | null, confirmedAdminEmail = false) { const normalized = String(email || "").trim().toLowerCase(); if (!normalized) return false; if (SAFE_DEMO_EMAILS.has(normalized)) return true; return Boolean(confirmedAdminEmail && adminEmail && normalized === adminEmail.toLowerCase()); }
export function assertDemoRecord(record: any) { if (!record) throw new Error("Demo record was not found."); const meta = record.metadata || {}; if (record.is_demo === true && record.demo_key === MIRROR_DEMO_KEY) return true; if (meta.demo === true && meta.demo_key === MIRROR_DEMO_KEY) return true; throw new Error("This action can only change records tagged for the mirror demo."); }

export async function getMirrorDemoLocation() { try { const { data } = await supabaseAdmin.from("locations").select("*").eq("demo_key", MIRROR_DEMO_KEY).maybeSingle(); return data || null; } catch { return null; } }

export async function createOrRefreshMirrorDemoLocation() {
  const existing = await getMirrorDemoLocation();
  const payload: any = { name: DEMO_LOCATION_NAME, restaurant_name: DEMO_LOCATION_NAME, activity_name: DEMO_LOCATION_NAME, location_type: "hybrid", primary_category: "Restaurant + Lounge + Activity", address: "123 Demo Ave", city: "New York", state: "NY", zip_code: "10001", phone: "212-555-0199", website: "https://theouthaven.com", market: "NYC", status: "active", active: true, is_searchable: false, is_hidden: true, is_demo: true, demo_key: MIRROR_DEMO_KEY, demo_mode: MIRROR_DEMO_MODE, demo_visible_publicly: false, growth_pro_override: true, reservation_enabled: true, reservation_mode: "internal_booking", reservation_source: "theouthaven", external_reservation_url: "https://theouthaven.com/demo-reservation", reservation_phone: "212-555-0199", reservation_owner_email: "demo-reservations@theouthaven.com", description: "TheOutHaven Demo Lounge is a sample Growth Pro location used to test menus, reservations, QR codes, offers, VIP signups, event leads, notifications, reviews, feedback, messaging, analytics, and staff training flows.", metadata: demoMetadata, updated_at: new Date().toISOString() };
  let location = existing;
  if (existing?.id) { const { data } = await supabaseAdmin.from("locations").update(payload).eq("id", existing.id).select("*").single(); location = data || existing; }
  else { const { data, error } = await supabaseAdmin.from("locations").insert({ ...payload, created_at: new Date().toISOString() }).select("*").single(); if (error) throw new Error("Could not create the mirror demo location. Run the demo metadata migration, then try again."); location = data; }
  await seedMirrorDemoData(location.id);
  revalidatePath("/admin/dashboard/settings/demo-center");
  return location;
}

const pages = ["Food Menu","Drinks & Hookah","Birthday Packages","Private Events","Activity Pricing"];
const items = ["Demo Truffle Fries","Demo Steak Tacos","Demo Salmon Dinner","Demo Signature Mocktail","Demo Date Night Cocktail","Demo Classic Hookah Package","Demo Birthday Table Package","Demo Private Room Package","Demo Group Activity Package"];
export async function seedMirrorDemoData(locationId: string) {
  await resetMirrorDemoData(locationId, false);
  await insertSafe("location_branding_settings", { location_id: locationId, logo_url: "/theouthaven-icon.png", hero_image_url: "/og-image.png", brand_accent_color: "#e1062a", theme_key: "deep_red", metadata: demoMetadata });
  await insertSafe("location_offerings", { location_id: locationId, offers_food:true, offers_drinks:true, offers_hookah:true, offers_activities:true, offers_reservations:true, offers_private_events:true, offers_group_packages:true, offers_catering:true, offers_live_events:true, offers_tickets:true, offers_bottle_service:true, primary_offering_type:"hybrid", metadata: demoMetadata });
  const pageResult:any = await insertSafe("location_commerce_pages", pages.map((title, i) => ({ location_id: locationId, page_type: title.toLowerCase().replaceAll(" ","_"), title, description: `${title} demo page for owner walkthroughs.`, sort_order: i, metadata: demoMetadata })));
  const firstPage = pageResult.data?.[0]?.id;
  if (firstPage) await insertSafe("location_commerce_items", items.map((name, i) => ({ location_id: locationId, commerce_page_id: firstPage, name, description: "Demo item seeded for realistic Growth Pro testing.", price: i < 3 ? "$18" : "$49+", sort_order: i, is_featured: i < 4, metadata: demoMetadata })));
  await insertSafe("location_qr_codes", ["main","menu","review","check_in","reservation","event","offer","vip","claim"].map(t => ({ location_id: locationId, code: `${MIRROR_DEMO_KEY}_${t}`, qr_type: t, destination_path: getMirrorDemoLinks(locationId).find(l=>l.label.toLowerCase().includes(t.replace("_"," ")))?.href || `/locations/hybrid/${locationId}?demo=1`, label: `Demo ${t.replace("_"," ")} QR`, metadata: demoMetadata })));
  await insertSafe("location_offers", ["Birthday Dessert Perk","Weekend Date Night Package","Group Celebration Offer"].map(title=>({ location_id: locationId, title, description:"Safe demo offer for claim flow testing.", offer_type:"demo", is_active:true, metadata: demoMetadata })));
  await insertSafe("location_vip_signups", ["Demo VIP Customer","Demo SMS Subscriber","Demo Birthday Guest"].map(name=>({ location_id: locationId, name, email:"demo-vip@theouthaven.com", source:"demo_center", email_consent:true, sms_consent:false, metadata: demoMetadata })));
  await insertSafe("location_notification_recipients", [{name:"Demo Owner",email:"demo-owner@theouthaven.com",role:"owner",is_primary:true,receives_all:true},{name:"Demo Events",email:"demo-events@theouthaven.com",role:"events",receives_all:true},{name:"Demo Reservations",email:"demo-reservations@theouthaven.com",role:"reservations",receives_all:true}].map(r=>({location_id:locationId,...r,metadata:demoMetadata})));
  await insertSafe("location_notification_events", ["New private event lead","New offer claim","New VIP signup","Low-rating private feedback","SMS credits low","QR scans increased this week","Reservation request received"].map(title=>({ location_id: locationId, event_type: title.toLowerCase().replaceAll(" ","_"), title, message:"Demo notification generated by Demo Center.", metadata: demoMetadata })));
  await insertSafe("location_leads", ["birthday party for 12 guests","corporate outing for 20 guests","private hookah lounge request","girls night group package request"].map((notes,i)=>({ location_id: locationId, customer_name:`Demo Lead ${i+1}`, customer_email:"demo-events@theouthaven.com", guest_count:[12,20,8,10][i], notes, status:"new", source:"demo_center", metadata: demoMetadata })));
  await insertSafe("location_private_feedback", [5,3,2].map(rating=>({ location_id: locationId, customer_name:"Demo Customer", customer_email:"demo-customer@theouthaven.com", rating, feedback_text:`${rating}-star demo feedback`, source:"demo_center", metadata: demoMetadata })));
  await insertSafe("location_marketing_suggestions", ["Birthday package push","Weekend date night offer","VIP signup QR promo","Private event flyer idea","Brunch/happy hour campaign idea","Review feedback follow-up idea","Menu highlight idea"].map(title=>({ location_id: locationId, title, description:"Demo marketing suggestion.", recommended_channel:"email", status:"new", metadata: demoMetadata })));
  await insertSafe("location_marketing_generations", ["Instagram caption","SMS campaign draft","email campaign draft","flyer copy","VIP signup promo","event package promo"].map(goal=>({ location_id: locationId, generation_type:"demo", channel: goal.includes("SMS") ? "sms" : "email", goal, generated_content:{ text: goal }, metadata: demoMetadata })));
  await insertSafe("location_sms_credit_ledger", { location_id: locationId, credit_type:"included", credits_added:100, credits_used:22, credits_remaining:78, source:"demo_center", metadata: demoMetadata });
  await seedDemoReservations(locationId);
  await insertSafe("location_analytics_events", ["profile_view","search_appearance","qr_scan","menu_view","offer_claim","vip_signup","event_lead_submitted","reservation_requested","reservation_confirmed","reservation_checked_in","reservation_completed","reservation_cancelled","reservation_no_show","private_feedback_submitted","marketing_generation_created","email_campaign_sent","sms_credits_used"].map(event_type=>({ location_id: locationId, event_type, metadata: demoMetadata })));
}
export async function seedDemoReservations(locationId:string) { const rows = ["pending","confirmed","checked_in","completed","cancelled","no_show"].map((status,i)=>({ location_id: locationId, customer_name:`Demo Reservation ${i+1}`, customer_email:"demo-customer@theouthaven.com", customer_phone:"212-555-0199", party_size: i+2, reservation_date: new Date(Date.now()+86400000*(i+1)).toISOString().slice(0,10), reservation_time: `${18+i}:00`, status, is_demo:true, demo_key:MIRROR_DEMO_KEY, demo_mode:MIRROR_DEMO_MODE, metadata: demoMetadata })); await insertSafe("reservations", rows); await insertSafe("location_reservations", rows); }
export async function resetMirrorDemoData(locationId?: string, stampLocation = true) { const loc = locationId ? { id: locationId } : await getMirrorDemoLocation(); if (!loc?.id) return { reset:false }; for (const table of ["location_branding_settings","location_offerings","location_commerce_items","location_commerce_sections","location_commerce_pages","location_qr_scan_events","location_qr_codes","location_offer_claims","location_offers","location_vip_signups","location_notification_deliveries","location_notification_events","location_notification_recipients","location_notification_preferences","location_leads","location_private_feedback","outing_visit_verifications","location_marketing_suggestions","location_marketing_generations","location_marketing_generation_usage","location_sms_credit_ledger","location_messaging_campaigns","location_messaging_custom_requests","reservations","location_reservations","location_analytics_events"]) await deleteDemoRows(table, loc.id); if (stampLocation) await supabaseAdmin.from("locations").update({ demo_reset_at: new Date().toISOString(), is_searchable:false, demo_visible_publicly:false }).eq("id", loc.id).eq("demo_key", MIRROR_DEMO_KEY); return { reset:true }; }
export function getMirrorDemoLinks(locationId: string): DemoLink[] { const pub=`/locations/hybrid/${locationId}`; return ["Public Profile","Public Menu","Public Offers","Public VIP","Public Events","Public Feedback","Public Check-in","Public Review","Public Reservation"].map(label=>({label,href: label==="Public Profile"?`${pub}?demo=1`: label.includes("Reservation")?`/reserve/location/${locationId}?demo=1`:`${pub}/${label.split(" ")[1].toLowerCase().replace("check-in","check-in")}?demo=1`})).concat([{label:"Admin CRM",href:`/admin/dashboard/crm/${locationId}`},{label:"Business Dashboard",href:`/business/dashboard?locationId=${locationId}`},{label:"Sales Demo",href:`/admin/dashboard/settings/demo-center?mode=sales&locationId=${locationId}`},{label:"Team Training",href:"/admin/dashboard/team/demo"}]); }
export async function getTeamTrainingDemoOverview(){ const [masters,sessions]=await Promise.all([countRows("crm_demo_locations"),countRows("crm_demo_sessions")]); return { status: masters===null?"Not installed":"Ready", masterCount: masters||0, sessionCount: sessions||0, href:"/admin/dashboard/team/demo" }; }
export async function getDemoCenterOverview(){ const location=await getMirrorDemoLocation(); const id=location?.id; const tables=["location_qr_codes","location_offers","location_vip_signups","location_leads","reservations","location_notification_events","location_marketing_suggestions","location_analytics_events"]; const counts:any={}; for(const t of tables) counts[t]=id?await countRows(t,id):null; const links=id?getMirrorDemoLinks(id):[]; const teamTraining=await getTeamTrainingDemoOverview(); const statusOf=(table:string):DemoStatus=>counts[table]===null?"Not installed":counts[table]>0?"Ready":"Needs data"; return { location, links, counts, teamTraining, lastReset: location?.demo_reset_at || null, publicSearchExposed: Boolean(location?.is_searchable), warnings: [!location && "Create the canonical mirror demo location to unlock links and seeded data.", location?.is_searchable && "Demo location is currently searchable; disable before public launch."].filter(Boolean) as string[], health:{ growthPro:statusOf("location_offers"), reservations:statusOf("reservations"), publicRoutes:id?"Ready":"Needs setup", businessDashboard:id?"Ready":"Needs setup", adminCrm:id?"Ready":"Needs setup", emailNotifications:statusOf("location_notification_events"), qr:statusOf("location_qr_codes"), analytics:statusOf("location_analytics_events"), salesDemo:id?"Ready":"Needs setup" } }; }
export async function getSalesDemoView(locationId:string){ return { sections: ["Discovery profile","Growth Pro value","Branding","Menu/packages","QR kit","VIP capture","Offers","Event leads","Reservations","Notifications","Feedback/reviews","Marketing Studio","Analytics/ROI"].map(title=>({ title, talkingPoints:[`Show how ${title.toLowerCase()} uses the same live product surfaces as a real Growth Pro location.`, "Keep demo emails and customer data safely tagged."], href: getMirrorDemoLinks(locationId).find(l=>l.label.includes("Public") || l.label.includes("Business"))?.href || "/admin/dashboard/settings/demo-center" })) }; }
export async function runDemoEmailTest(adminEmail?:string|null){ const to="demo-owner@theouthaven.com"; if(!isSafeDemoEmail(to,adminEmail)) throw new Error("Demo email recipient is not safe."); return sendTemplatedEmail({ to, templateKey:"reservation_daily_summary", input:{ locationName: DEMO_LOCATION_NAME } as any, sourceType:"demo_center", sourceId:MIRROR_DEMO_KEY }); }
