import Link from "next/link";
import { requireAdminRole } from "@/lib/admin-auth";
import { ADMIN_PAGE_ACCESS } from "@/lib/admin-permissions";
import { supabaseAdmin } from "@/lib/supabase-admin";

export const dynamic = "force-dynamic";

export default async function CommunityPage({ searchParams }: { searchParams: Promise<{ conversation?: string }> }) {
  await requireAdminRole(ADMIN_PAGE_ACCESS.marketing);
  const params = await searchParams;
  const { data: conversations } = await supabaseAdmin.from("social_community_conversations").select("id,provider,status,person_type,intent,occasion,area,timing,sentiment,opportunity_strength,risk_level,last_message_at,metadata,social_community_contacts(username,display_name)").order("last_message_at", { ascending: false }).limit(100);
  const selectedId = params.conversation || conversations?.[0]?.id || null;
  const { data: messages } = selectedId ? await supabaseAdmin.from("social_community_messages").select("id,direction,sender_type,body,status,created_at").eq("conversation_id", selectedId).order("created_at") : { data: [] as any[] };
  const selected = conversations?.find((row) => row.id === selectedId) as any;
  const contact = selected ? (Array.isArray(selected.social_community_contacts) ? selected.social_community_contacts[0] : selected.social_community_contacts) : null;
  const suggestion = String(selected?.metadata?.suggested_reply || "");

  return <main className="min-h-screen bg-[#090706] px-4 py-6 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-[1500px] space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-rose-300">Social Manager</p><h1 className="mt-2 text-4xl font-semibold">Community</h1><p className="mt-2 text-white/55">Messages, customer opportunities, business leads, creator interest, and conversations that need a person.</p></div><Link href="/admin/dashboard/marketing/social-manager" className="rounded-full border border-white/15 px-5 py-3 text-sm font-semibold">Back to Social Manager</Link></div>
    <div className="grid min-h-[650px] gap-4 lg:grid-cols-[380px_1fr]">
      <section className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.05]"><div className="border-b border-white/10 px-4 py-3 font-semibold">Messages</div><div className="max-h-[760px] overflow-y-auto divide-y divide-white/10">{(conversations || []).map((row: any) => { const c = Array.isArray(row.social_community_contacts) ? row.social_community_contacts[0] : row.social_community_contacts; return <Link key={row.id} href={`/admin/dashboard/marketing/community?conversation=${row.id}`} className={`block px-4 py-4 ${row.id === selectedId ? "bg-rose-500/10" : "hover:bg-white/[0.04]"}`}><div className="flex justify-between gap-3"><div><p className="font-medium">{c?.display_name || c?.username || "Social user"}</p><p className="mt-1 text-sm text-white/45">{row.intent || row.person_type}{row.area ? ` · ${row.area}` : ""}</p></div><span className={`h-fit rounded-full px-2.5 py-1 text-[11px] font-semibold ${row.risk_level === "red" ? "bg-red-500/15 text-red-200" : row.status === "ai_handled" ? "bg-sky-500/15 text-sky-200" : "bg-white/10 text-white/60"}`}>{row.risk_level === "red" ? "Needs a person" : row.status === "ai_handled" ? "AI handled" : "Needs reply"}</span></div></Link>})}{!conversations?.length ? <div className="p-8 text-center text-sm text-white/45">No conversations yet.</div> : null}</div></section>
      <section className="rounded-2xl border border-white/10 bg-white/[0.05]">{selected ? <><div className="border-b border-white/10 p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">{contact?.display_name || contact?.username || "Conversation"}</h2><p className="mt-1 text-sm text-white/45 capitalize">{selected.provider} · {selected.person_type}{selected.area ? ` · ${selected.area}` : ""}{selected.timing ? ` · ${selected.timing}` : ""}</p></div><div className="flex gap-2"><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs font-semibold">{selected.opportunity_strength === "very_strong" ? "Very strong opportunity" : selected.opportunity_strength === "good" ? "Good opportunity" : "Low interest"}</span>{selected.risk_level !== "green" ? <span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${selected.risk_level === "red" ? "bg-red-500/15 text-red-200" : "bg-amber-500/15 text-amber-200"}`}>{selected.risk_level === "red" ? "Human only" : "Review before sending"}</span> : null}</div></div></div>
        <div className="space-y-3 p-5">{(messages || []).map((message: any) => <div key={message.id} className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm leading-6 ${message.direction === "outbound" ? "ml-auto bg-rose-600 text-white" : "bg-white/10 text-white/85"}`}><p>{message.body}</p><p className="mt-1 text-[11px] opacity-60">{new Date(message.created_at).toLocaleString("en-US", { timeZone: "America/New_York" })}</p></div>)}</div>
        <div className="border-t border-white/10 p-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-white/40">Suggested reply</p><div className="mt-2 rounded-2xl border border-white/10 bg-black/20 p-4 text-sm leading-6 text-white/80">{suggestion || "No suggestion yet."}</div><div className="mt-3 flex flex-wrap gap-2"><form action="/api/admin/marketing/community/reply" method="post"><input type="hidden" name="conversation_id" value={selected.id}/><input type="hidden" name="reply" value={suggestion}/><button disabled={!suggestion || selected.risk_level === "red"} className="rounded-full bg-rose-600 px-4 py-2.5 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-40">Send Suggested Reply</button></form><form action="/api/admin/marketing/community/take-over" method="post"><input type="hidden" name="conversation_id" value={selected.id}/><button className="rounded-full border border-white/15 px-4 py-2.5 text-sm font-semibold">Take Over</button></form><form action="/api/admin/marketing/community/close" method="post"><input type="hidden" name="conversation_id" value={selected.id}/><button className="rounded-full border border-white/15 px-4 py-2.5 text-sm font-semibold">Close</button></form></div></div></> : <div className="grid h-full place-items-center p-10 text-white/45">Choose a conversation.</div>}</section>
    </div>
  </div></main>;
}
