import { supabaseAdmin } from '@/lib/supabase-admin';
import { aggregateReviewSignals } from './reviewIntelligence';
import { calculateBusinessQuality } from './businessQuality';
import { calculatePhotoQuality } from './photoQuality';
import { calculateBookingLikelihood } from './bookingLikelihood';
import { calculateOwnerLeadScore, assignLeadPriority, formatRecommendedPitch } from './ownerLeadScoring';
export type RecalcOptions={dryRun?:boolean;limit?:number;daysBack?:number;locationId?:string;userId?:string;};
async function runLog(type:string){ const {data}=await supabaseAdmin.from('advanced_ml_score_runs').insert({run_type:type,status:'running'}).select('id').maybeSingle(); return data?.id; }
async function finish(id:string|undefined, patch:any){ if(id) await supabaseAdmin.from('advanced_ml_score_runs').update({completed_at:new Date().toISOString(),...patch}).eq('id',id); }
async function locs(o:RecalcOptions){ let q=supabaseAdmin.from('locations').select('*').limit(o.limit||200); if(o.locationId) q=q.eq('id',o.locationId); const {data}=await q; return data||[]; }
export async function recalculateReviewIntelligence(o:RecalcOptions={}){ const id=await runLog('review_intelligence'); let updated=0; try{ for(const l of await locs(o)){ const {data:reviews}=await supabaseAdmin.from('location_reviews').select('*').eq('location_id',l.id).eq('status','approved').limit(500); const row={location_id:l.id,...aggregateReviewSignals(reviews||[]),review_summary:null,last_review_at:(reviews||[])[0]?.created_at||null,updated_at:new Date().toISOString()}; if(!o.dryRun){ await supabaseAdmin.from('location_review_ml_features').upsert(row,{onConflict:'location_id'}); } updated++; } await finish(id,{status:'completed',records_updated:updated}); return {ok:true,recordsUpdated:updated}; }catch(e:any){ await finish(id,{status:'failed',errors:[e.message]}); return {ok:false,error:e.message}; } }
export async function recalculateBusinessQuality(o:RecalcOptions={}){ const id=await runLog('business_quality'); let updated=0; try{ for(const l of await locs(o)){ const row={location_id:l.id,...calculateBusinessQuality(l),updated_at:new Date().toISOString()}; if(!o.dryRun) await supabaseAdmin.from('business_quality_ml_features').upsert(row,{onConflict:'location_id'}); updated++; } await finish(id,{status:'completed',records_updated:updated}); return {ok:true,recordsUpdated:updated}; }catch(e:any){ await finish(id,{status:'failed',errors:[e.message]}); return {ok:false,error:e.message}; } }
export async function recalculatePhotoQuality(o:RecalcOptions={}){ const id=await runLog('photo_quality'); let updated=0; try{ for(const l of await locs(o)){ const row={location_id:l.id,...calculatePhotoQuality(l),updated_at:new Date().toISOString()}; if(!o.dryRun) await supabaseAdmin.from('photo_quality_ml_features').upsert(row,{onConflict:'location_id'}); updated++; } await finish(id,{status:'completed',records_updated:updated}); return {ok:true,recordsUpdated:updated}; }catch(e:any){ await finish(id,{status:'failed',errors:[e.message]}); return {ok:false,error:e.message}; } }
export async function recalculateBookingLikelihood(o:RecalcOptions={}){ const id=await runLog('booking_likelihood'); let updated=0; try{ for(const l of await locs(o)){ const {data:r}=await supabaseAdmin.from('reservations').select('status,created_at').eq('location_id',l.id).limit(500); const req=r?.length||0, conf=r?.filter((x:any)=>['confirmed','checked_in','completed'].includes(x.status)).length||0, comp=r?.filter((x:any)=>x.status==='completed').length||0, can=r?.filter((x:any)=>x.status==='cancelled').length||0, no=r?.filter((x:any)=>x.status==='no_show').length||0; const calc=calculateBookingLikelihood({reservation_enabled:l.reservation_enabled,owner_active:!!l.owner_user_id,booking_request_count:req,confirmed_booking_count:conf,completed_booking_count:comp,cancelled_booking_count:can,no_show_count:no}); const row={location_id:l.id,reservation_enabled:!!l.reservation_enabled,owner_active:!!l.owner_user_id,booking_request_count:req,confirmed_booking_count:conf,completed_booking_count:comp,cancelled_booking_count:can,no_show_count:no,...calc,updated_at:new Date().toISOString()}; if(!o.dryRun) await supabaseAdmin.from('booking_likelihood_ml_features').upsert(row,{onConflict:'location_id'}); updated++; } await finish(id,{status:'completed',records_updated:updated}); return {ok:true,recordsUpdated:updated}; }catch(e:any){ await finish(id,{status:'failed',errors:[e.message]}); return {ok:false,error:e.message}; } }
export async function recalculateOwnerLeads(o:RecalcOptions={}){ const id=await runLog('owner_lead_scoring'); let updated=0; try{ for(const l of await locs(o)){ const score=calculateOwnerLeadScore({...l,claim_status:l.owner_user_id?'claimed':'unclaimed'}); const row={location_id:l.id,claim_status:l.owner_user_id?'claimed':'unclaimed',owner_user_id:l.owner_user_id||null,business_trust_score:l.business_trust_score||0,owner_lead_score:score,lead_priority:assignLeadPriority(score),recommended_pitch:formatRecommendedPitch({business_trust_score:l.business_trust_score}),updated_at:new Date().toISOString()}; if(!o.dryRun) await supabaseAdmin.from('owner_lead_ml_features').upsert(row,{onConflict:'location_id'}); updated++; } await finish(id,{status:'completed',records_updated:updated}); return {ok:true,recordsUpdated:updated}; }catch(e:any){ await finish(id,{status:'failed',errors:[e.message]}); return {ok:false,error:e.message}; } }
export async function recalculatePlaceholder(type:string,o:RecalcOptions={}){ const id=await runLog(type); await finish(id,{status:'completed',records_updated:0,metadata:{message:'No source rows available; route is ready and degrades gracefully.', options:o}}); return {ok:true,recordsUpdated:0,message:'No source rows available; route completed gracefully.'}; }
