import { clampScore, confidenceWeight, patternStrength, safeDivide } from './scoring';
const terms = { quiet:/\b(quiet|calm|cozy|intimate|relaxed|peaceful)\b/i, loud:/\b(loud|noisy|club|dj|packed|crowded)\b/i, romantic:/\b(romantic|date|anniversary|intimate)\b/i, group:/\b(group|friends|party|girls night|birthday)\b/i, family:/\b(family|kids|children)\b/i, photo:/\b(photo|instagram|beautiful|pretty|aesthetic)\b/i, service:/\b(service|server|staff|rude|slow)\b/i, wait:/\b(wait|line|delayed|slow)\b/i, value:/\b(overpriced|expensive|pricey|not worth|value)\b/i };
export function extractReviewSignals(review:any){ const text=String(review.review_text||review.text||''); const rating=Number(review.rating||0); const has=(k:keyof typeof terms)=>terms[k].test(text); return { rating, verified:Boolean(review.verified_visit), aiBoost:Number(review.ai_score_boost||0), sentiment: review.ai_sentiment || (rating>=4?'positive':rating<=2?'negative':'neutral'), quiet:has('quiet')||review.noise_level==='quiet', loud:has('loud')||review.noise_level==='loud', romantic:has('romantic')||!!review.date_night, group:has('group')||!!review.group_friendly, family:has('family')||!!review.family_friendly, photo:has('photo'), serviceIssue:has('service')&&rating<=3, waitIssue:has('wait'), valueIssue:has('value')&&rating<=3, bestFor:[...(review.best_for||[]),...(review.occasion_fit||[])].filter(Boolean), avoidIf:(review.avoid_if||[]).filter(Boolean) }; }
export function aggregateReviewSignals(reviews:any[]){ const rows=reviews.map(extractReviewSignals); const count=rows.length; const verified=rows.filter(r=>r.verified).length; const sum=(p:string)=>rows.filter((r:any)=>r[p]).length; const avg=(p:string)=>safeDivide(rows.reduce((a:any,r:any)=>a+Number(r[p]||0),0),count); const loud=sum('loud'), quiet=sum('quiet'); const neg=rows.filter(r=>r.sentiment==='negative'||r.rating<=2).length; return { approved_review_count:count, verified_review_count:verified, avg_rating:avg('rating'), avg_ai_score_boost:avg('aiBoost'), positive_review_count:rows.filter(r=>r.sentiment==='positive'||r.rating>=4).length, neutral_review_count:rows.filter(r=>r.sentiment==='neutral'||r.rating===3).length, negative_review_count:neg, quiet_score:clampScore((sum('quiet')+Math.max(0,quiet-loud))*18), loud_score:clampScore(loud*18), romantic_score:clampScore(sum('romantic')*20), group_score:clampScore(sum('group')*20), family_score:clampScore(sum('family')*20), photo_worthy_score:clampScore(sum('photo')*20), lively_score:clampScore(loud*14+sum('group')*8), relaxed_score:clampScore(quiet*18), date_night_score:clampScore(sum('romantic')*18+quiet*8-Math.max(0,loud-quiet)*5), service_score:clampScore(100-sum('serviceIssue')*18), food_score:clampScore(avg('rating')*20), ambiance_score:clampScore((sum('quiet')+sum('romantic')+sum('photo'))*12), value_score:clampScore(100-sum('valueIssue')*18), overall_review_quality_score:clampScore(avg('rating')*16+avg('aiBoost')*2+count), review_confidence_score:confidenceWeight(count,20), wait_penalty:clampScore(patternStrength(sum('waitIssue'),verified)*35), service_penalty:clampScore(patternStrength(sum('serviceIssue'),verified)*35), overpriced_penalty:clampScore(patternStrength(sum('valueIssue'),verified)*30), noise_penalty:clampScore(patternStrength(Math.max(0,loud-quiet),verified)*30), crowded_penalty:clampScore(patternStrength(loud,verified)*15), quiet_mention_count:quiet, loud_mention_count:loud, romantic_mention_count:sum('romantic'), group_mention_count:sum('group'), family_mention_count:sum('family'), photo_worthy_mention_count:sum('photo'), service_issue_count:sum('serviceIssue'), wait_issue_count:sum('waitIssue'), value_issue_count:sum('valueIssue'), best_for_terms:[...new Set(rows.flatMap(r=>r.bestFor))].slice(0,8), avoid_if_terms:[...new Set(rows.flatMap(r=>r.avoidIf))].slice(0,8) }; }
export function calculateReviewConfidence(i:any){ return confidenceWeight(i?.approved_review_count||0,20); }
export function calculateReviewQualityScore(i:any){ return clampScore((Number(i?.avg_rating||0)*16)+(Number(i?.positive_review_count||0)*2)-Number(i?.negative_review_count||0)); }
export function calculateIntentReviewFit(intent:any,f:any){ const q=String(intent?.rawQuery||intent||'').toLowerCase(); let s=0; if(/quiet|cozy|date|romantic/.test(q)) s+=(f?.quiet_score||0)*.08+(f?.romantic_score||0)*.08- (f?.noise_penalty||0)*.08; if(/birthday|girls|group|nightlife|lively/.test(q)) s+=(f?.lively_score||0)*.08+(f?.group_score||0)*.08; if(/family|kids/.test(q)) s+=(f?.family_score||0)*.1; return clampScore(s, -10, 12); }
export function calculatePairReviewFit(r:any,a:any,intent:any){ return clampScore(calculateIntentReviewFit(intent,r)+calculateIntentReviewFit(intent,a),-12,18); }
export function getReviewPenaltyForIntent(intent:any,f:any){ return Math.abs(Math.min(0, calculateIntentReviewFit(intent,f))); }
export function formatReviewIntelligenceSummary(f:any){ return f?.approved_review_count ? `Based on ${f.approved_review_count} approved reviews: ${f.best_for_terms?.slice?.(0,3)?.join(', ')||'general fit'}.` : 'Not enough approved review data yet.'; }
