import { handleOptions } from "../_shared/cors.ts";
import { ok, serverError } from "../_shared/response.ts";
import { createSupabaseAdminClient } from "../_shared/supabaseAdmin.ts";
import { logCronJobRun } from "../_shared/cronLogger.ts";
import { sendEmail } from "../_shared/email.ts";

type Row = Record<string, any>;
type RankItem = { label: string; current: number; trendPct: number | null; meta?: string };
const JOB_NAME = "admin-daily-marketing-pulse";
const B = { bg:"#090706", card:"#141010", elevated:"#1c1614", border:"rgba(255,255,255,.12)", text:"#fff7f2", muted:"#b8aaa3", subtle:"#8f817a", red:"#e1062a", green:"#70df8b", amber:"#f5c76b", blue:"#8fb8ff" };
const WEIGHTS: Record<string, number> = { profile_view:1, search_click:3, share_click:4, reservation_started:5, reservation_completed:8, website_click:3 };
const DAY = 86400000;

const esc = (v: unknown) => String(v ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const since = (days:number) => new Date(Date.now() - days * DAY).toISOString();
const pct = (c:number,p:number) => p === 0 ? (c === 0 ? 0 : null) : Math.round(((c-p)/p)*1000)/10;
const pctLabel = (v:number|null) => v == null ? "new / no baseline" : v === 0 ? "flat" : `${v > 0 ? "+" : ""}${v}%`;
const rate = (n:number,d:number) => d ? Math.round((n/d)*1000)/10 : 0;
const duration = (ms:number) => { const s=Math.round(ms/1000); return s<60 ? `${s}s` : `${Math.floor(s/60)}m ${s%60}s`; };
function siteUrl(){ return (Deno.env.get("NEXT_PUBLIC_SITE_URL")||Deno.env.get("SITE_URL")||"https://theouthaven.com").replace(/\/$/,""); }
function recipients(){ return (Deno.env.get("MARKETING_PULSE_TO")||Deno.env.get("ADMIN_EMAIL")||Deno.env.get("SUPERADMIN_EMAIL")||"").split(",").map(v=>v.trim()).filter(Boolean); }
function cronSecretMatches(req:Request){ const expected=Deno.env.get("CRON_SECRET"); return Boolean(expected)&&req.headers.get("x-cron-secret")===expected; }
function isSendTime(date=new Date()){ const parts=new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(date); const get=(t:string)=>Number(parts.find(p=>p.type===t)?.value||0); return get("hour")===7&&get("minute")>=25&&get("minute")<=40; }

async function rows(s:any, table:string, select:string, timeCol:string, days:number, extra?:(q:any)=>any, limit=10000){ let q=s.from(table).select(select).gte(timeCol,since(days)).order(timeCol,{ascending:false}).limit(limit); if(extra) q=extra(q); const {data,error}=await q; if(error) throw error; return data??[]; }
function countWindow(data:Row[], col:string, fromMs:number,toMs:number=Date.now()){ return data.filter(r=>{const t=Date.parse(String(r[col])); return t>=fromMs&&t<toMs;}).length; }
function trendCounts(data:Row[], col:string){ const now=Date.now(); const d1=countWindow(data,col,now-DAY); const p1=countWindow(data,col,now-2*DAY,now-DAY); const d7=countWindow(data,col,now-7*DAY); const p7=countWindow(data,col,now-14*DAY,now-7*DAY); const d30=countWindow(data,col,now-30*DAY); const p30=countWindow(data,col,now-60*DAY,now-30*DAY); return { d1, dod:pct(d1,p1), d7, wow:pct(d7,p7), d30, mom:pct(d30,p30) }; }
function metric(label:string,value:string|number,helper:string,tone=B.text){ return `<td width="33.33%" valign="top" style="padding:6px"><div style="background:${B.elevated};border:1px solid ${B.border};border-radius:14px;padding:15px;min-height:88px"><div style="font-size:10px;text-transform:uppercase;letter-spacing:.07em;color:${B.subtle};font-weight:850">${esc(label)}</div><div style="font-size:24px;line-height:30px;color:${tone};font-weight:900;margin-top:5px">${esc(value)}</div><div style="font-size:11px;line-height:17px;color:${B.muted};margin-top:3px">${esc(helper)}</div></div></td>`; }
function section(title:string,body:string){ return `<div style="margin-top:22px"><div style="font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:${B.red};font-weight:900;margin-bottom:10px">${esc(title)}</div><div style="background:${B.card};border:1px solid ${B.border};border-radius:18px;padding:18px">${body}</div></div>`; }
function list(items:RankItem[],empty:string){ if(!items.length)return `<div style="color:${B.muted};font-size:13px">${esc(empty)}</div>`; return `<table width="100%">${items.map((x,i)=>`<tr><td style="padding:10px 0;border-bottom:1px solid ${B.border}"><b style="color:${B.text}">${i+1}. ${esc(x.label)}</b>${x.meta?`<div style="color:${B.subtle};font-size:11px;margin-top:3px">${esc(x.meta)}</div>`:""}</td><td align="right" style="border-bottom:1px solid ${B.border}"><b style="color:${B.text}">${Math.round(x.current)}</b><div style="font-size:11px;color:${x.trendPct!=null&&x.trendPct<0?B.amber:B.green}">${esc(pctLabel(x.trendPct))}</div></td></tr>`).join("")}</table>`; }

function engagementRank(events:Row[], locations:Map<string,Row>, key:(loc:Row)=>string|null){ const now=Date.now(), current=now-DAY, prior=now-8*DAY; const m=new Map<string,{cur:number,prev:number}>(); for(const e of events){const loc=locations.get(String(e.location_id||"")); if(!loc)continue; const k=key(loc); if(!k)continue; const t=Date.parse(String(e.created_at)); const s=WEIGHTS[String(e.event_type)]??1; const v=m.get(k)??{cur:0,prev:0}; if(t>=current)v.cur+=s; else if(t>=prior)v.prev+=s; m.set(k,v);} return [...m.entries()].map(([label,v])=>({label,current:v.cur,trendPct:pct(v.cur,v.prev/7)})).filter(x=>x.current>0).sort((a,b)=>b.current-a.current); }
function funnelRow(label:string,count:number,previous:number|null,first:number){ const drop=previous==null?null:rate(Math.max(0,previous-count),previous); const completion=rate(count,first); return `<tr><td style="padding:11px 0;border-bottom:1px solid ${B.border};color:${B.text};font-weight:800">${esc(label)}</td><td align="right" style="border-bottom:1px solid ${B.border};color:${B.text};font-weight:850">${count}</td><td align="right" style="border-bottom:1px solid ${B.border};color:${drop!=null&&drop>=30?B.amber:B.muted}">${drop==null?"—":`${drop}%`}</td><td align="right" style="border-bottom:1px solid ${B.border};color:${B.green}">${completion}%</td></tr>`; }

async function build(s:any){
  const [locEvents, searches, attribution, telemetry, analytics] = await Promise.all([
    rows(s,"location_analytics_events","location_id,event_type,event_name,created_at","created_at",8,undefined,10000),
    rows(s,"search_events","created_at,raw_query,normalized_query,session_id,neighborhood","created_at",60,q=>q.eq("source","public_create_search").eq("route","/api/generate"),10000),
    rows(s,"marketing_attribution_events","source,medium,campaign,event_type,occurred_at","occurred_at",8,undefined,5000),
    rows(s,"platform_telemetry_events","event_type,event_name,session_id,page_path,metadata,occurred_at","occurred_at",60,undefined,15000),
    rows(s,"analytics_events","event_name,canonical_event_name,event_type,session_id,page_path,created_at,occurred_at","created_at",2,undefined,15000),
  ]);
  const ids=[...new Set(locEvents.map((e:Row)=>String(e.location_id||"")).filter(Boolean))];
  const {data:locData,error:locErr}=ids.length?await s.from("locations").select("id,name,city,borough,neighborhood,cuisine,activity_type").in("id",ids.slice(0,1000)):{data:[],error:null}; if(locErr)throw locErr;
  const locations=new Map((locData??[]).map((r:Row)=>[String(r.id),r]));
  const searchTrend=trendCounts(searches,"created_at");
  const page24=telemetry.filter((r:Row)=>r.event_type==="page_view"&&Date.parse(String(r.occurred_at))>=Date.now()-DAY);
  const homeViews=page24.filter((r:Row)=>r.page_path==="/").length;
  const createViews=page24.filter((r:Row)=>r.page_path==="/create").length;
  const sessions24=new Map<string,number>(); for(const r of telemetry){ if(Date.parse(String(r.occurred_at))<Date.now()-DAY||!r.session_id)continue; const ms=Number(r?.metadata?.duration_ms); if(Number.isFinite(ms)) sessions24.set(r.session_id,Math.max(sessions24.get(r.session_id)??0,ms)); }
  const avgSession=sessions24.size?[...sessions24.values()].reduce((a,b)=>a+b,0)/sessions24.size:0;

  const stageSets=[new Set<string>(),new Set<string>(),new Set<string>(),new Set<string>(),new Set<string>(),new Set<string>()];
  for(const r of page24){ if(!r.session_id)continue; if(r.page_path==="/")stageSets[0].add(r.session_id); if(r.page_path==="/create")stageSets[1].add(r.session_id); }
  for(const r of analytics){ if(Date.parse(String(r.created_at||r.occurred_at))<Date.now()-DAY||!r.session_id)continue; const name=String(r.canonical_event_name||r.event_name||r.event_type||"").toLowerCase(); if(name==="search_started")stageSets[2].add(r.session_id); if(["search_completed","search_results_impression","result_rendered"].includes(name))stageSets[3].add(r.session_id); if(["result_clicked","result_opened","location_clicked","pair_clicked"].includes(name))stageSets[4].add(r.session_id); if(["outing_created","outing_completed","book_my_outing_clicked"].includes(name))stageSets[5].add(r.session_id); }
  const stageNames=["Home viewed","Create viewed","Search started","Results shown","Result engaged","Search flow completed"];
  const funnel=stageNames.map((label,i)=>({label,count:stageSets[i].size}));
  const start=Math.max(funnel[0].count,1); const fullCompletion=rate(funnel[5].count,start);

  const topLocations=engagementRank(locEvents,locations,l=>String(l.name||"")||null).slice(0,8);
  const trendingLocations=[...topLocations].filter(x=>x.trendPct==null||(x.trendPct??0)>0).sort((a,b)=>(b.trendPct??9999)-(a.trendPct??9999)).slice(0,6);
  const neighborhoods=engagementRank(locEvents,locations,l=>l.neighborhood?String(l.neighborhood):null).slice(0,8);
  const trendingNeighborhoods=[...neighborhoods].filter(x=>x.trendPct==null||(x.trendPct??0)>0).sort((a,b)=>(b.trendPct??9999)-(a.trendPct??9999)).slice(0,6);
  const cuisines=engagementRank(locEvents,locations,l=>l.cuisine?String(l.cuisine):null).filter(x=>x.trendPct==null||(x.trendPct??0)>0).slice(0,6);
  const activities=engagementRank(locEvents,locations,l=>l.activity_type?String(l.activity_type):null).filter(x=>x.trendPct==null||(x.trendPct??0)>0).slice(0,6);
  const sourceMap=new Map<string,number>(); for(const r of attribution){if(Date.parse(String(r.occurred_at))<Date.now()-DAY)continue;const k=[r.source,r.medium].filter(Boolean).join(" / ")||"unattributed";sourceMap.set(k,(sourceMap.get(k)??0)+1);} const sources=[...sourceMap.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,current])=>({label,current,trendPct:null}));
  const queries=new Map<string,number>(); for(const r of searches){if(Date.parse(String(r.created_at))<Date.now()-DAY)continue;const q=String(r.normalized_query||r.raw_query||"").trim();if(q)queries.set(q,(queries.get(q)??0)+1);} const topQueries=[...queries.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,current])=>({label,current,trendPct:null}));

  const funnelTable=`<table width="100%"><tr><th align="left" style="color:${B.subtle};font-size:10px">STEP</th><th align="right" style="color:${B.subtle};font-size:10px">SESSIONS</th><th align="right" style="color:${B.subtle};font-size:10px">DROP-OFF</th><th align="right" style="color:${B.subtle};font-size:10px">FROM START</th></tr>${funnel.map((x,i)=>funnelRow(x.label,x.count,i?funnel[i-1].count:null,start)).join("")}</table>`;
  const searchTrendTable=`<table width="100%"><tr>${metric("Last 24h",searchTrend.d1,`DoD ${pctLabel(searchTrend.dod)}`,B.blue)}${metric("Last 7d",searchTrend.d7,`WoW ${pctLabel(searchTrend.wow)}`,B.green)}${metric("Last 30d",searchTrend.d30,`MoM ${pctLabel(searchTrend.mom)}`,B.amber)}</tr></table>`;
  const opportunity=[trendingNeighborhoods[0]?`Feature ${trendingNeighborhoods[0].label}; neighborhood interest is ${pctLabel(trendingNeighborhoods[0].trendPct)} vs its 7-day daily baseline.`:null,trendingLocations[0]?`Consider spotlighting ${trendingLocations[0].label}; it is the fastest-rising location signal today.`:null,funnel.length?`Largest funnel loss: ${funnel.slice(1).map((x,i)=>({label:x.label,drop:rate(Math.max(0,funnel[i].count-x.count),funnel[i].count)})).sort((a,b)=>b.drop-a.drop)[0]?.label}.`:null].filter(Boolean) as string[];

  const html=`<!doctype html><html><body style="margin:0;background:${B.bg};font-family:Arial,Helvetica,sans-serif;color:${B.text}"><table width="100%" style="background:${B.bg};padding:28px 12px"><tr><td align="center"><table width="100%" style="max-width:720px;background:${B.card};border:1px solid ${B.border};border-radius:26px;overflow:hidden"><tr><td style="padding:30px;background:linear-gradient(135deg,#141010,#1c1614 60%,#2a0d13);border-bottom:1px solid ${B.border}"><div style="font-size:22px;font-weight:900">TheOutHaven</div><div style="margin-top:7px;color:${B.muted};font-size:11px;letter-spacing:.2em;text-transform:uppercase;font-weight:900">Daily Marketing Pulse</div><h1 style="font-size:30px;line-height:36px;margin:18px 0 6px">Audience, traffic and what is trending</h1><div style="color:${B.muted};font-size:14px;line-height:21px">Production behavior from the last 24 hours, with momentum and funnel signals for the marketing team.</div></td></tr><tr><td style="padding:24px"><table width="100%"><tr>${metric("Home Views",homeViews,"Homepage page views",B.blue)}${metric("Create Views",createViews,"/create page views",B.green)}${metric("Avg Session",duration(avgSession),`${sessions24.size} measured sessions`,B.amber)}</tr><tr>${metric("Searches",searchTrend.d1,`DoD ${pctLabel(searchTrend.dod)}`)}${metric("Full Flow",`${fullCompletion}%`,`${funnel[5].count} completed sessions`,B.green)}${metric("Tracked Sessions",sessions24.size,"Last 24 hours")}</tr></table>${section("Search Traffic Trends",searchTrendTable)}${section("Search Funnel & Drop-off",funnelTable)}${section("Top Locations",list(topLocations,"No location engagement yet."))}${section("Trending Locations",list(trendingLocations,"No rising locations have enough signal yet."))}${section("Trending Neighborhoods",list(trendingNeighborhoods,"No neighborhood trend has enough signal yet."))}${section("Top Neighborhoods",list(neighborhoods,"No neighborhood engagement yet."))}${section("Trending Cuisines",list(cuisines,"No cuisine trend yet."))}${section("Trending Activities",list(activities,"No activity trend yet."))}${section("Top Search Themes",list(topQueries,"No public search themes in the last 24 hours."))}${section("Acquisition Sources",list(sources,"No attributed marketing activity in the last 24 hours."))}${section("Marketing Opportunities",opportunity.length?`<ul style="margin:0;padding-left:20px;color:${B.text};line-height:24px">${opportunity.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:`<div style="color:${B.muted}">More production activity is needed before recommendations can be generated.</div>`)}<div style="text-align:center;margin-top:26px"><a href="${siteUrl()}/admin/dashboard/marketing" style="display:inline-block;background:${B.red};color:white;text-decoration:none;font-weight:900;padding:13px 22px;border-radius:999px">Open Marketing Dashboard</a></div></td></tr></table></td></tr></table></body></html>`;
  return {html,summary:{home_views_24h:homeViews,create_views_24h:createViews,avg_session_ms_24h:Math.round(avgSession),searches_24h:searchTrend.d1,dod_pct:searchTrend.dod,wow_pct:searchTrend.wow,mom_pct:searchTrend.mom,full_flow_completion_pct:fullCompletion,funnel:Object.fromEntries(funnel.map(x=>[x.label,x.count])),top_location:topLocations[0]?.label??null,trending_location:trendingLocations[0]?.label??null,trending_neighborhood:trendingNeighborhoods[0]?.label??null}};
}

Deno.serve(async(req:Request)=>{ const preflight=handleOptions(req); if(preflight)return preflight; const started=Date.now(); let s:any=null; try{ if(req.method!=="POST")return ok({success:false,error:"method_not_allowed"},{status:405}); if(!cronSecretMatches(req))return ok({success:false,error:"unauthorized"},{status:401}); const body=await req.json().catch(()=>({})); const source=String(body?.source||"cron"); const force=body?.force===true; if(!force&&!isSendTime()){ return ok({success:true,sent:false,skipped:true,reason:"outside_7_30_et_window"}); } s=createSupabaseAdminClient(); const to=recipients(); if(!to.length)throw new Error("No marketing pulse recipients configured"); const built=await build(s); const email=await sendEmail({to,subject:"TheOutHaven Daily Marketing Pulse",html:built.html,text:"TheOutHaven Daily Marketing Pulse — open the HTML email for full traffic, funnel and trend details.",senderKey:"admin"}); await logCronJobRun(s,{job_name:JOB_NAME,function_name:JOB_NAME,source,status:email?.sent===true?"success":"warning",started_at:new Date(started).toISOString(),finished_at:new Date().toISOString(),duration_ms:Date.now()-started,success_count:email?.sent===true?1:0,failed_count:email?.sent===true?0:1,details:{email,summary:built.summary},schedule_hint:"Daily at 7:30 AM America/New_York"}); return ok({success:true,sent:email?.sent===true,recipient_count:to.length,email,summary:built.summary}); }catch(error){ const message=error instanceof Error?error.message:String(error); if(s)await logCronJobRun(s,{job_name:JOB_NAME,function_name:JOB_NAME,source:"edge_function",status:"failed",started_at:new Date(started).toISOString(),finished_at:new Date().toISOString(),duration_ms:Date.now()-started,error_message:message}).catch(()=>{}); console.error("DAILY_MARKETING_PULSE_FAILED",message); return serverError("Daily marketing pulse failed"); } });
