"use client";

import Link from "next/link";
import type { ReactNode } from "react";
import { useMemo, useState } from "react";
import { createLocationEventAction, updateLocationEventStatusAction } from "@/app/locations/dashboard/events/actions";

type EventRow = { id:string; title:string; slug:string|null; category:string|null; starts_at:string; ends_at:string|null; status:string; searchable:boolean; is_free:boolean; price_min:number|string|null; capacity:number|null; image_url:string|null };
type Metrics = { events:number; upcoming:number; published:number; tickets:number; checkedIn:number; grossSalesCents:number; netSalesCents:number };

const STEPS = ["Basics", "Date & place", "Tickets & fees", "Public URL", "Review"];
function slugify(value:string){return value.toLowerCase().normalize("NFKD").replace(/[’']/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,90);}

export default function LocationEventManager({ locationId, location, events, metrics }:{ locationId:string; location:{name:string;address:string|null;city:string|null;state:string|null;zip_code:string|null}; events:EventRow[]; metrics:Metrics }){
  const [step,setStep]=useState(0);
  const [title,setTitle]=useState("");
  const [slug,setSlug]=useState("");
  const generated=useMemo(()=>slug || slugify(title),[slug,title]);
  return <div className="space-y-6">
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Events" value={metrics.events}/><Metric label="Upcoming" value={metrics.upcoming}/><Metric label="Published" value={metrics.published}/><Metric label="Tickets issued" value={metrics.tickets}/><Metric label="Checked in" value={metrics.checkedIn}/><Metric label="Gross ticket sales" value={money(metrics.grossSalesCents)}/><Metric label="Location net" value={money(metrics.netSalesCents)}/></section>
    <section className="rounded-3xl border border-white/10 bg-white/[.035] p-5 sm:p-6">
      <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#ff5570]">Create Event</p><h2 className="mt-1 text-2xl font-black">Guided event setup</h2><p className="mt-1 text-sm text-white/45">Complete one short step at a time. Your location details are prefilled.</p></div><span className="rounded-full border border-white/10 px-3 py-2 text-xs font-black">Step {step+1} of {STEPS.length}</span></div>
      <div className="mt-5 flex gap-2 overflow-x-auto">{STEPS.map((label,index)=><button type="button" key={label} onClick={()=>setStep(index)} className={`shrink-0 rounded-full border px-4 py-2 text-xs font-black ${index===step?"border-[#ff2142]/70 bg-[#e1062a]/20":"border-white/10 bg-black/20 text-white/45"}`}>{index+1}. {label}</button>)}</div>
      <form action={createLocationEventAction} className="mt-6 space-y-5"><input type="hidden" name="location_id" value={locationId}/>
        <div className={step===0?"grid gap-3 md:grid-cols-2":"hidden"}><Field label="Event name"><input name="title" required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Rooftop R&B Summer Night" className="input"/></Field><Field label="Category"><input name="category" placeholder="Nightlife, dining, workshop..." className="input"/></Field><Field label="Cover image URL"><input name="image_url" type="url" placeholder="https://..." className="input"/></Field><Field label="Description"><textarea name="description" placeholder="Tell guests what to expect" className="input min-h-28"/></Field></div>
        <div className={step===1?"grid gap-3 md:grid-cols-2":"hidden"}><Field label="Starts"><input name="starts_at" type="datetime-local" required className="input"/></Field><Field label="Ends"><input name="ends_at" type="datetime-local" className="input"/></Field><input name="venue_name" defaultValue={location.name} className="input"/><input name="address" defaultValue={location.address||""} className="input"/><input name="city" defaultValue={location.city||""} className="input"/><input name="state" defaultValue={location.state||"NY"} className="input"/><input name="zip_code" defaultValue={location.zip_code||""} className="input"/><input name="timezone" defaultValue="America/New_York" className="input"/></div>
        <div className={step===2?"grid gap-3 md:grid-cols-2":"hidden"}><label className="rounded-2xl border border-white/10 bg-black/20 p-4 text-sm font-bold"><input name="ticketing_enabled" type="checkbox" defaultChecked className="mr-2"/>Enable tickets / registration</label><label className="rounded-2xl border border-white/10 bg-black/20 p-4 text-sm font-bold"><input name="is_free" type="checkbox" defaultChecked className="mr-2"/>Free event</label><Field label="Ticket price"><input name="price_min" type="number" min="0" step="0.01" placeholder="0.00" className="input"/></Field><Field label="Capacity"><input name="capacity" type="number" min="1" placeholder="Optional" className="input"/></Field><Field label="Who pays fees?"><select name="fee_payer" defaultValue="customer" className="input"><option value="customer">Customer pays fees</option><option value="organizer">Location pays fees</option><option value="split">Split 50 / 50</option></select></Field></div>
        <div className={step===3?"space-y-3":"hidden"}><p className="text-sm text-white/55">The public URL is generated from the event name. Customize it if you want.</p><div className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-xs font-black uppercase tracking-[.14em] text-white/40">Public URL</p><div className="mt-2 flex flex-wrap items-center gap-1 text-sm"><span className="text-white/45">theouthaven.com/events/</span><input name="slug" value={generated} onChange={e=>setSlug(slugify(e.target.value))} className="min-w-[220px] flex-1 rounded-lg border border-white/10 bg-black/30 px-3 py-2 font-black"/></div></div></div>
        <div className={step===4?"space-y-4":"hidden"}><div className="rounded-2xl border border-white/10 bg-black/20 p-5"><p className="text-sm font-black">Ready to create your draft?</p><p className="mt-1 text-sm text-white/45">Published events automatically appear on your TheOutHaven location page and hosted website.</p></div><button className="w-full rounded-xl bg-[#e1062a] px-4 py-3 font-black">Create Draft Event</button></div>
        <div className="flex justify-between gap-3"><button type="button" disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))} className="rounded-xl border border-white/10 px-4 py-3 text-sm font-black disabled:opacity-30">Back</button>{step<STEPS.length-1?<button type="button" onClick={()=>setStep(s=>Math.min(STEPS.length-1,s+1))} className="rounded-xl bg-white px-4 py-3 text-sm font-black text-black">Continue</button>:null}</div>
      </form>
    </section>
    <section className="space-y-3"><h2 className="text-xl font-black">Your Events</h2>{events.length?events.map(event=><article key={event.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#ff5570]">{event.category||"Event"}</p><h3 className="mt-1 font-black">{event.title}</h3><p className="mt-1 text-xs text-white/45">{new Date(event.starts_at).toLocaleString()} · {event.status}</p></div><div className="flex gap-2"><Link href={`/events/${event.slug||event.id}`} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-black">Public Page</Link><form action={updateLocationEventStatusAction}><input type="hidden" name="location_id" value={locationId}/><input type="hidden" name="event_id" value={event.id}/><input type="hidden" name="status" value={event.status==="scheduled"?"draft":"scheduled"}/><button className="rounded-xl bg-[#e1062a] px-3 py-2 text-xs font-black">{event.status==="scheduled"?"Unpublish":"Publish"}</button></form></div></div></article>):<div className="rounded-2xl border border-white/10 p-6 text-center text-white/40">No events yet.</div>}</section>
    <style jsx global>{`.input{width:100%;border-radius:.75rem;border:1px solid rgba(255,255,255,.1);background:rgba(0,0,0,.3);padding:.75rem;color:white}.input::placeholder{color:rgba(255,255,255,.3)}`}</style>
  </div>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-xs text-white/40">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="text-xs font-bold text-white/55">{label}<div className="mt-1">{children}</div></label>}
function money(cents:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100)}
