import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase-server";
import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { verifyTurnstileToken, shouldBypassTurnstileForUser } from "@/lib/security/turnstile";
const SAFE = "We could not verify that submission. Please refresh and try again.";
function remoteIp(req: NextRequest) { return req.headers.get("cf-connecting-ip") || req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || null; }
async function currentTester() { const supabase = await createClient(); const { data:{user} } = await supabase.auth.getUser(); let tester:any=null; if (user?.id || user?.email) { const or=[`user_id.eq.${user.id}`]; if(user.email) or.push(`email.eq.${user.email}`); const {data}=await supabaseAdmin.from("beta_testers").select("*").or(or.join(",")).maybeSingle(); tester=data; } return {user,tester}; }
export async function POST(request: NextRequest) { try { const body=await request.json().catch(()=>({})); const message=String(body.message??"").trim(); if(!message) return NextResponse.json({success:false,error:"Message is required."},{status:400}); const {user,tester}=await currentTester(); const bypass=shouldBypassTurnstileForUser({isAuthenticated:Boolean(user),isBetaTester:Boolean(tester)}); let turnstile:any={success:true,bypassed:true}; if(!bypass){ turnstile=await verifyTurnstileToken({token:body.turnstileToken??body["cf-turnstile-response"],remoteIp:remoteIp(request),expectedAction:"beta_feedback",source:"beta_feedback",metadata:{assignmentId:body.assignmentId??null}}); if(!turnstile.success) return NextResponse.json({success:false,error:SAFE},{status:400}); }
  const {data,error}=await supabaseAdmin.from("beta_feedback").insert({tester_id:tester?.id??null,user_id:user?.id??null,feedback_type:body.feedback_type||"general",feature_area:body.feature_area||"general",page_url:body.page_url||null,search_query:body.search_query||null,search_log_id:body.search_log_id||null,submitted_prompt:body.submitted_prompt||null,expected_result:body.expected_result||null,actual_result:body.actual_result||null,result_accuracy_rating:body.result_accuracy_rating?Number(body.result_accuracy_rating):null,speed_rating:body.speed_rating||null,rating:body.rating?Number(body.rating):null,message,screenshot_url:body.screenshot_url||null,browser:body.browser||null,device:body.device||null,turnstile_verified:!turnstile.bypassed,turnstile_action:turnstile.action??null,turnstile_hostname:turnstile.hostname??null}).select("*").single(); if(error) throw error; return NextResponse.json({success:true,feedback:data}); } catch(error){ console.error("BETA_FEEDBACK_ERROR", error); return NextResponse.json({success:false,error:"Feedback could not be submitted."},{status:500}); } }
