import Link from "next/link";
import { requireAdminRole } from "@/lib/admin-auth";
import { ADMIN_PAGE_ACCESS } from "@/lib/admin-permissions";
import { supabaseAdmin } from "@/lib/supabase-admin";

export const dynamic = "force-dynamic";

export default async function MarketingTodayPage() {
  const admin = await requireAdminRole(ADMIN_PAGE_ACCESS.marketing);
  const now = new Date();
  const dayStart = new Date(now); dayStart.setHours(0,0,0,0);
  const dayEnd = new Date(dayStart.getTime()+24*60*60*1000);
  const [taskResult,scheduledResult,approvalResult,failureResult,communityResult,opportunityResult] = await Promise.all([
    supabaseAdmin.from("crm_tasks").select("id,title,status,priority,due_at,subtype,metadata").eq("category","marketing").is("archived_at",null).in("status",["open","in_progress","blocked"]).or(`assigned_to_user_id.eq.${admin.user_id},assigned_to_user_id.is.null`).order("priority").order("due_at",{ascending:true,nullsFirst:false}).limit(100),
    supabaseAdmin.from("marketing_content_items").select("id,title,status,publish_at,selected_platforms,auto_publish").gte("publish_at",dayStart.toISOString()).lt("publish_at",dayEnd.toISOString()).neq("status","archived").order("publish_at"),
    supabaseAdmin.from("marketing_approvals").select("id,content_item_id,version,created_at").eq("status","pending").eq("assigned_to",admin.user_id).order("created_at",{ascending:true}).limit(30),
    supabaseAdmin.from("social_publish_jobs").select("id,provider,error_message,updated_at,social_posts(content_item_id,title,caption)").eq("status","failed").order("updated_at",{ascending:false}).limit(20),
    supabaseAdmin.from("social_community_conversations").select("id,person_type,status,risk_level,opportunity_score").in("status",["needs_reply","escalated"]).limit(200),
    supabaseAdmin.from("social_growth_opportunities").select("id",{count:"exact",head:true}).eq("status","new").gte("score",70),
  ]);
  const tasks=taskResult.data||[]; const scheduled=scheduledResult.data||[]; const approvals=approvalResult.data||[]; const failures=failureResult.data||[]; const community=communityResult.data||[];
  const messages=community.length; const customerIdeas=community.filter((r:any)=>r.person_type==="consumer"&&r.opportunity_score>=50).length; const businessLeads=community.filter((r:any)=>r.person_type==="business").length; const creators=community.filter((r:any)=>r.person_type==="creator").length;
  return <main className="min-h-screen bg-[#090706] px-4 py-6 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-[1400px] space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-rose-300">Marketing</p><h1 className="mt-2 text-4xl font-semibold">Your Day</h1><p className="mt-2 text-white/55">Everything that needs your attention today, in priority order.</p></div><Link href="/admin/dashboard/marketing/social-manager" className="rounded-full bg-rose-600 px-5 py-3 text-sm font-semibold">Open Social Manager</Link></div>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{[["Posts to review",approvals.length],["Messages need attention",messages],["Customer opportunities",customerIdeas],["Businesses interested",businessLeads],["Creators interested",creators],["Strong opportunities",opportunityResult.count||0],["Posts going out",scheduled.length],["Posting issues",failures.length]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-white/10 bg-white/[0.06] p-4"><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-white/45">{label}</p></div>)}</section>
    <section className="rounded-2xl border border-white/10 bg-white/[0.05]"><div className="flex justify-between border-b border-white/10 px-5 py-4"><div><h2 className="font-semibold">What to do next</h2><p className="mt-1 text-sm text-white/45">Social leads, creator work, and marketing follow-ups are added here automatically.</p></div><Link href="/admin/dashboard/crm/my-work" className="text-sm font-semibold text-rose-300">View all work</Link></div><div className="divide-y divide-white/10">{tasks.length?tasks.slice(0,12).map((task:any)=>{const metadata=(task.metadata||{}) as Record<string,unknown>;const href=typeof metadata.deep_link==="string"?metadata.deep_link:"/admin/dashboard/crm/my-work";return <Link key={task.id} href={href} className="flex flex-wrap items-center justify-between gap-3 px-5 py-4 hover:bg-white/[0.04]"><div><p className="font-medium">{task.title}</p><p className="mt-1 text-xs capitalize text-white/40">{String(task.subtype||"marketing task").replaceAll("_"," ")}</p></div><div className="text-right"><p className={`text-xs font-semibold capitalize ${task.priority==="urgent"||task.priority==="high"?"text-rose-300":"text-white/55"}`}>{task.priority}</p><p className="mt-1 text-xs text-white/35">{task.due_at?new Date(task.due_at).toLocaleString("en-US",{timeZone:"America/New_York"}):"Ready when you are"}</p></div></Link>;}):<div className="p-8 text-center text-sm text-white/45">Nothing waiting for you.</div>}</div></section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.05]"><div className="border-b border-white/10 px-5 py-4 font-semibold">Going out today</div><div className="divide-y divide-white/10">{scheduled.length?scheduled.map((item:any)=><Link href={`/admin/dashboard/marketing/content/${item.id}`} key={item.id} className="flex justify-between gap-3 px-5 py-4 hover:bg-white/[0.04]"><div><p className="font-medium">{item.title}</p><p className="mt-1 text-xs text-white/40">{(item.selected_platforms||[]).join(", ")}</p></div><span className="text-sm font-semibold">{item.publish_at?new Date(item.publish_at).toLocaleTimeString("en-US",{timeZone:"America/New_York",hour:"numeric",minute:"2-digit"}):""}</span></Link>):<div className="p-8 text-center text-sm text-white/45">Nothing scheduled today.</div>}</div></div>
      <div className="rounded-2xl border border-white/10 bg-white/[0.05]"><div className="border-b border-white/10 px-5 py-4 font-semibold">Needs fixing</div><div className="divide-y divide-white/10">{failures.length?failures.map((failure:any)=>{const post=Array.isArray(failure.social_posts)?failure.social_posts[0]:failure.social_posts;return <Link key={failure.id} href={post?.content_item_id?`/admin/dashboard/marketing/content/${post.content_item_id}`:"/admin/dashboard/marketing/social-accounts"} className="block px-5 py-4 hover:bg-white/[0.04]"><p className="font-medium capitalize">{failure.provider}: {post?.title||post?.caption||"Social post"}</p><p className="mt-1 text-sm text-amber-200">This post didn’t go out. Open it to fix or try again.</p></Link>}):<div className="p-8 text-center text-sm text-white/45">No posting problems.</div>}</div></div></section>
  </div></main>;
}
