import type { Metadata } from "next";
import { cache } from "react";
import { createClient } from "@supabase/supabase-js";
import { getLocationName } from "@/lib/locationName";
import { getLocationImage } from "@/lib/locationImage";
import { getPrimaryCategory } from "@/lib/locationFields";
import { isPublicSearchVisible } from "@/lib/locationVisibility";
import PublicLocationOfferings from "@/components/public-location/PublicLocationOfferings";
import ExpandableGroupBooking from "@/components/reserve/ExpandableGroupBooking";
import { breadcrumbJsonLd, buildMetadata, canonicalUrl, jsonLdScript, localSeoDescription, openGraphImage } from "@/lib/seo";
import { getInternalDemoViewer } from "@/lib/demo/internal-demo-access";
import { MIRROR_DEMO_KEY } from "@/lib/demo/demo-center";

function serverSupabase(){return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{auth:{persistSession:false}})}
type LocationRecord=Record<string,any>;
type Props={children:React.ReactNode;params:Promise<{type:string;locationId:string}>};

const loadLocation=cache(async(type:string,locationId:string)=>{const sourceTables=type==="activities"||type==="activity"?["activities","activity"]:["restaurants","restaurant"];const sourceOr=sourceTables.map(sourceTable=>`and(source_table.eq.${sourceTable},source_id.eq.${locationId})`).join(",");const supabase=serverSupabase();let{data}=await supabase.from("locations").select("*").or(`id.eq.${locationId},${sourceOr}`).maybeSingle();if(!data){const slugResult=await supabase.from("locations").select("*").eq("slug",locationId).maybeSingle();data=slugResult.data}if(!data)return null;if(isPublicSearchVisible(data))return data as LocationRecord;const internalViewer=await getInternalDemoViewer().catch(()=>null);const isSafeInternalDemo=Boolean(internalViewer&&data.demo_key===MIRROR_DEMO_KEY&&data.is_demo===true&&data.is_hidden===true&&data.is_searchable!==true&&data.demo_visible_publicly!==true&&data.publish_ready!==true);return isSafeInternalDemo?(data as LocationRecord):null});
function asHttpsUrl(value:unknown){const raw=String(value||"").trim();if(!raw)return"";return /^https?:\/\//i.test(raw)?raw:`https://${raw}`}
const loadHostedWebsite=cache(async(locationId:string)=>{const supabase=serverSupabase();const{data}=await supabase.from("business_websites").select("domain,platform_domain,status,deployment_status,last_publish_status,published_version").eq("location_id",locationId).eq("status","live").eq("deployment_status","deployed").eq("last_publish_status","published").not("published_version","is",null).order("published_version",{ascending:false}).limit(1).maybeSingle();if(!data)return"";return asHttpsUrl(data.domain||data.platform_domain)});
const loadOfferings=cache(async(locationId:string)=>{const supabase=serverSupabase();const now=new Date().toISOString();const[{data:events},{data:experiences}]=await Promise.all([
  supabase.from("events").select("id,slug,title,category,starts_at,image_url,is_free,price_min").eq("location_id",locationId).eq("searchable",true).in("status",["scheduled","postponed"]).gte("starts_at",now).order("starts_at",{ascending:true}).limit(6),
  supabase.from("experiences").select("id,slug,title,category,image_url,duration_minutes,price_per_person").eq("location_id",locationId).eq("searchable",true).eq("status","published").order("created_at",{ascending:false}).limit(6),
]);return{events:events||[],experiences:experiences||[]}});
function locationPath(type:string,locationId:string){return `/locations/${type}/${locationId}`}
function locationDescription(location:LocationRecord){const name=getLocationName(location,"TheOutHaven location");const category=getPrimaryCategory(location);const area=[location.neighborhood,location.borough||location.city].filter(Boolean).join(", ");const detail=location.description||location.primary_tag||location.cuisine||location.activity_type;return localSeoDescription({area:area||location.city,category:`${name}${category?`, a ${category}`:""}${detail?` known for ${detail}`:""}`})}
function locationJsonLd(location:LocationRecord,type:string,locationId:string,hostedWebsite?:string){const name=getLocationName(location,"TheOutHaven location");const isRestaurant=String(location.location_type||type).toLowerCase().includes("restaurant");const image=getLocationImage(location);const addressParts=[location.address,location.city,location.state,location.zip_code].filter(Boolean);const jsonLd:Record<string,unknown>={"@context":"https://schema.org","@type":isRestaurant?"Restaurant":"LocalBusiness",name,url:canonicalUrl(locationPath(type,locationId)),description:locationDescription(location)};if(image)jsonLd.image=openGraphImage(image);if(location.phone)jsonLd.telephone=location.phone;const sameAs=Array.from(new Set([location.website,hostedWebsite].map(asHttpsUrl).filter(Boolean)));if(sameAs.length)jsonLd.sameAs=sameAs;if(addressParts.length>0)jsonLd.address={"@type":"PostalAddress",streetAddress:location.address||undefined,addressLocality:location.city||undefined,addressRegion:location.state||undefined,postalCode:location.zip_code||undefined,addressCountry:"US"};if(location.latitude&&location.longitude)jsonLd.geo={"@type":"GeoCoordinates",latitude:Number(location.latitude),longitude:Number(location.longitude)};if(isRestaurant&&(location.cuisine||location.cuisine_type))jsonLd.servesCuisine=location.cuisine||location.cuisine_type;return jsonLd}

export async function generateMetadata({params}:Props):Promise<Metadata>{const{type,locationId}=await params;const location=await loadLocation(type,locationId);const path=locationPath(type,locationId);if(!location)return buildMetadata({title:"Location Not Found",description:"This TheOutHaven location is not currently searchable.",path,noIndex:true});const isDemo=location.demo_key===MIRROR_DEMO_KEY&&location.is_demo===true;const name=getLocationName(location,"TheOutHaven Location");const area=[location.neighborhood,location.borough||location.city].filter(Boolean).join(", ");return buildMetadata({title:`${name}${area?` in ${area}`:""}`,description:locationDescription(location),path,image:getLocationImage(location),noIndex:isDemo})}

export default async function LocationDetailLayout({children,params}:Props){const{type,locationId}=await params;const location=await loadLocation(type,locationId);if(!location)return children;const realLocationId=String(location.id||locationId);const[hostedWebsite,offerings]=await Promise.all([loadHostedWebsite(realLocationId),loadOfferings(realLocationId)]);const name=getLocationName(location,"TheOutHaven Location");const category=getPrimaryCategory(location);const basePath=locationPath(type,locationId);const structuredData=[breadcrumbJsonLd([{name:"Home",path:"/"},{name:"Explore",path:"/explore"},{name:category||"Locations",path:"/explore"},{name,path:basePath}]),locationJsonLd(location,type,locationId,hostedWebsite)];const groupEnabled=Boolean(location.large_group_booking_enabled);const groupMin=Number(location.large_group_min_party_size||8);const groupMax=Number(location.large_group_max_party_size||40);return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLdScript(structuredData)}}/>{children}{groupEnabled?<div className="toh-container pb-10"><ExpandableGroupBooking locationId={realLocationId} locationName={name} minPartySize={groupMin} maxPartySize={groupMax}/></div>:null}<PublicLocationOfferings basePath={basePath} events={offerings.events} experiences={offerings.experiences}/>{hostedWebsite?<a href={hostedWebsite} target="_blank" rel="noopener noreferrer" className="fixed right-4 top-24 z-40 inline-flex min-h-11 items-center justify-center rounded-full border border-white/15 bg-[#090607]/95 px-4 text-sm font-black text-white shadow-xl backdrop-blur-xl transition hover:border-red-400/50 hover:bg-red-600" aria-label={`Visit ${name} website`}>Visit Website ↗</a>:null}</>}
