import { CAREER_STAGE_LABELS, CAREER_TONE_BY_STAGE, INTERNSHIP_TYPE_LABELS, JOB_STATUS_TONES } from "./constants";
import type { CareerApplication, CareerJob } from "./types";
export function formatCareerDate(value?: string | null) { if (!value) return "—"; const d = new Date(value); return Number.isNaN(d.getTime()) ? "—" : d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }); }
export function formatCareerStage(stage?: string | null) { return CAREER_STAGE_LABELS[String(stage || "")] || "Under Review"; }
export function getCareerStageTone(stage?: string | null) { return CAREER_TONE_BY_STAGE[String(stage || "")] || "muted"; }
export function getJobStatusTone(status?: string | null) { return JOB_STATUS_TONES[String(status || "")] || "muted"; }
export function getInternshipTypeLabel(type?: string | null) { return type ? INTERNSHIP_TYPE_LABELS[type] || type.replace(/_/g, " ") : "Not an internship"; }
export function getCompensationLabel(job: Pick<CareerJob, "compensation_text" | "compensation_min" | "compensation_max" | "compensation_type" | "internship_type" | "is_paid">) { if (job.compensation_text) return job.compensation_text; if (job.compensation_min || job.compensation_max) return [job.compensation_min, job.compensation_max].filter(Boolean).map((v)=>`$${v}`).join("–") + (job.compensation_type ? ` ${job.compensation_type}` : ""); if (job.internship_type === "unpaid_educational" || job.internship_type === "college_credit") return "Educational / College Credit"; return job.is_paid === false ? "Educational experience" : "Compensation shared during hiring"; }
export function isMarketingJob(job: Pick<CareerJob, "department" | "subdepartment" | "role_track" | "title">) { return /marketing|social|content|creator|campus|ambassador|influencer/i.test(`${job.department} ${job.subdepartment} ${job.role_track} ${job.title}`); }
export function isInternshipJob(job: Pick<CareerJob, "is_internship" | "employment_type" | "internship_type" | "title">) { return Boolean(job.is_internship || job.internship_type || /intern/i.test(`${job.employment_type} ${job.title}`)); }
export function requiresInternshipComplianceChecklist(job: Pick<CareerJob, "is_internship" | "internship_type" | "is_paid" | "supports_college_credit" | "requires_school_credit">) { return Boolean(job.is_internship && (job.is_paid === false || job.internship_type === "unpaid_educational" || job.internship_type === "college_credit" || job.supports_college_credit || job.requires_school_credit)); }
export function calculateApplicantDisplayName(app: Pick<CareerApplication, "first_name" | "last_name" | "email">) { return `${app.first_name || ""} ${app.last_name || ""}`.trim() || app.email; }
export function calculateApplicationScore(scores: Array<number | null | undefined>) { const nums = scores.filter((n): n is number => typeof n === "number"); return nums.length ? Math.round(nums.reduce((a,b)=>a+b,0)/nums.length) : null; }
export function getNextRecommendedAction(stage?: string | null) { const map: Record<string,string> = { submitted: "Review application", portfolio_review: "Review portfolio links", under_review: "Shortlist or send update", shortlisted: "Request interview", interview_requested: "Schedule interview", interview_scheduled: "Complete interview", interview_completed: "Complete scorecard", content_test: "Review content test", offer_pending: "Prepare offer", offer_sent: "Await candidate response", hired: "Start team conversion", not_selected: "No action needed", talent_pool: "Follow up later" }; return map[String(stage || "")] || "Review application"; }
