export type WebsiteHeroStyle =
  | "editorial_split"
  | "photo_mosaic"
  | "cinematic_strip"
  | "typography_first"
  | "asymmetric_gallery"
  | "framed_photo";

export type WebsiteDesignDirection = {
  id: string;
  name: string;
  summary: string;
  signals: string[];
  variants: WebsiteHeroStyle[];
  defaultVariant: WebsiteHeroStyle;
  theme: {
    mood: string;
    contrast: "light" | "dark" | "mixed";
    typography: "editorial" | "modern" | "classic" | "playful";
    density: "airy" | "balanced" | "compact";
    imageTreatment: "editorial" | "grid" | "minimal";
    reservationPriority: "primary";
  };
};

const d = (direction: WebsiteDesignDirection) => direction;

export const WEBSITE_DESIGN_DIRECTIONS: WebsiteDesignDirection[] = [
  d({ id:"editorial_luxury", name:"Editorial Dining", summary:"High-end hospitality with oversized editorial typography, generous whitespace, cinematic food photography, and an intentionally paced guest journey.", signals:["editorial","light","cream","ivory","elegant","refined","magazine","chef","premium","fine dining","tasting menu"], variants:["editorial_split","framed_photo","cinematic_strip","typography_first"], defaultVariant:"editorial_split", theme:{mood:"editorial",contrast:"light",typography:"editorial",density:"airy",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"refined_after_dark", name:"After Dark", summary:"Cinematic nightlife design for lounges, rooftops, cocktail bars, steakhouses, and restaurants where mood and atmosphere sell the experience.", signals:["dark","lounge","romantic","moody","intimate","cocktail","nightlife","luxury","candlelight","upscale","steakhouse","rooftop"], variants:["asymmetric_gallery","cinematic_strip","typography_first","editorial_split"], defaultVariant:"asymmetric_gallery", theme:{mood:"refined",contrast:"dark",typography:"editorial",density:"airy",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"modern_minimal", name:"Contemporary Hospitality", summary:"Crisp, modern hospitality with strong conversion hierarchy, restrained surfaces, and prominent reservation or booking actions.", signals:["modern","clean","reservation","book","minimal","sleek","simple","conversion","contemporary","chef driven"], variants:["typography_first","editorial_split","framed_photo"], defaultVariant:"editorial_split", theme:{mood:"modern",contrast:"light",typography:"modern",density:"balanced",imageTreatment:"minimal",reservationPriority:"primary"}}),
  d({ id:"bold_social", name:"High Energy Social", summary:"Large-scale imagery, bold typography, and energetic rhythm for brunch, nightlife, sports bars, group dining, and social-first venues.", signals:["bold","energetic","social","fun","nightlife","party","vibrant","brunch","groups","lively","sports bar","club"], variants:["photo_mosaic","asymmetric_gallery","cinematic_strip"], defaultVariant:"photo_mosaic", theme:{mood:"energetic",contrast:"dark",typography:"modern",density:"balanced",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"classic_bistro", name:"Classic European", summary:"Timeless restaurant design with restrained typography, elegant menu presentation, narrow editorial proportions, and traditional hospitality cues.", signals:["bistro","french","italian","wine bar","brasserie","classic","traditional","european","vintage","trattoria"], variants:["editorial_split","framed_photo","typography_first"], defaultVariant:"editorial_split", theme:{mood:"classic",contrast:"mixed",typography:"classic",density:"balanced",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"coastal_airy", name:"Coastal Escape", summary:"Open, bright, image-led design for seafood, waterfront, rooftop, resort-style, and daylight-driven hospitality concepts.", signals:["coastal","seafood","waterfront","beach","airy","bright","fresh","relaxed","ocean","rooftop","resort"], variants:["framed_photo","editorial_split","cinematic_strip"], defaultVariant:"framed_photo", theme:{mood:"breezy",contrast:"light",typography:"modern",density:"airy",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"warm_neighborhood", name:"Neighborhood Favorite", summary:"Warm, approachable and polished for restaurants, pubs, cafés, and local destinations where personality and familiarity matter most.", signals:["warm","local","neighborhood","friendly","cozy","casual","authentic","welcoming","cafe","pub","family"], variants:["editorial_split","framed_photo","photo_mosaic"], defaultVariant:"editorial_split", theme:{mood:"welcoming",contrast:"light",typography:"classic",density:"balanced",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"luxury_minimal", name:"Quiet Luxury", summary:"Gallery-like restraint, dramatic whitespace, selective imagery, and oversized typography for premium restaurants, spas, and private experiences.", signals:["luxury minimal","minimal luxury","quiet luxury","high end","exclusive","restrained","sophisticated","private","fine dining","spa"], variants:["typography_first","framed_photo","cinematic_strip"], defaultVariant:"typography_first", theme:{mood:"luxury",contrast:"mixed",typography:"editorial",density:"airy",imageTreatment:"minimal",reservationPriority:"primary"}}),
  d({ id:"experiential_escape", name:"Immersive Experience", summary:"Image-forward, action-oriented layouts for escape rooms, bowling, mini golf, attractions, and bookable destinations where the experience is the product.", signals:["experience","activity","immersive","escape room","bowling","mini golf","adventure","attraction","book now","arcade","axe throwing"], variants:["asymmetric_gallery","photo_mosaic","cinematic_strip"], defaultVariant:"asymmetric_gallery", theme:{mood:"immersive",contrast:"mixed",typography:"modern",density:"balanced",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"creative_workshop", name:"Creative Studio", summary:"Expressive, premium and playful for workshops, maker spaces, classes, date activities, family entertainment, and hands-on venues.", signals:["creative","playful","pottery","painting","candle","cooking class","diy","workshop","studio","colorful","family fun"], variants:["photo_mosaic","framed_photo","editorial_split"], defaultVariant:"photo_mosaic", theme:{mood:"creative",contrast:"light",typography:"playful",density:"balanced",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"chef_counter", name:"Chef Counter", summary:"Intimate, food-first storytelling for omakase counters, tasting rooms, chef tables, and small-format concepts where craft is the centerpiece.", signals:["omakase","chef counter","chef table","tasting room","intimate","sushi counter","prix fixe","craft"], variants:["typography_first","editorial_split","framed_photo","cinematic_strip"], defaultVariant:"typography_first", theme:{mood:"crafted",contrast:"mixed",typography:"editorial",density:"airy",imageTreatment:"minimal",reservationPriority:"primary"}}),
  d({ id:"brunch_social", name:"Brunch Social", summary:"Bright, stylish and highly photographic for brunch restaurants, cafés and all-day concepts built around groups and shareable moments.", signals:["brunch","all day cafe","girls brunch","social brunch","mimosas","day party","instagrammable","cafe"], variants:["photo_mosaic","framed_photo","editorial_split","asymmetric_gallery"], defaultVariant:"photo_mosaic", theme:{mood:"sunny",contrast:"light",typography:"modern",density:"balanced",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"fast_casual_polished", name:"Polished Fast Casual", summary:"Fast, clear and appetizing for counter service, quick bites, cafés and takeout-forward businesses without making them feel generic.", signals:["fast casual","quick bite","counter service","takeout","grab and go","sandwich","burger","wings","bakery"], variants:["framed_photo","photo_mosaic","typography_first"], defaultVariant:"framed_photo", theme:{mood:"direct",contrast:"light",typography:"modern",density:"compact",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"social_games", name:"Competitive Social", summary:"High-energy premium design for bowling, darts, billiards, axe throwing, mini golf and social gaming venues.", signals:["competitive social","darts","billiards","bowling","axe throwing","mini golf","games","groups","corporate events"], variants:["cinematic_strip","asymmetric_gallery","photo_mosaic","typography_first"], defaultVariant:"cinematic_strip", theme:{mood:"competitive",contrast:"dark",typography:"modern",density:"balanced",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"family_entertainment", name:"Family Entertainment", summary:"Energetic but polished for arcades, family attractions, indoor play, museums and all-ages entertainment destinations.", signals:["family entertainment","kids","all ages","arcade","indoor play","family fun","birthday parties","museum"], variants:["photo_mosaic","framed_photo","cinematic_strip"], defaultVariant:"photo_mosaic", theme:{mood:"friendly",contrast:"light",typography:"playful",density:"balanced",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"wellness_retreat", name:"Wellness Retreat", summary:"Calm, tactile and spacious for spas, wellness studios, bathhouses and restorative experiences.", signals:["wellness","spa","massage","sauna","bathhouse","retreat","relaxing","self care","meditation"], variants:["framed_photo","typography_first","editorial_split","cinematic_strip"], defaultVariant:"framed_photo", theme:{mood:"calm",contrast:"light",typography:"editorial",density:"airy",imageTreatment:"minimal",reservationPriority:"primary"}}),
  d({ id:"arts_culture", name:"Arts & Culture", summary:"Curatorial, editorial presentation for museums, galleries, theaters, cultural institutions and performance venues.", signals:["museum","gallery","theater","theatre","arts","culture","exhibition","performance","jazz","live music"], variants:["typography_first","asymmetric_gallery","editorial_split","cinematic_strip"], defaultVariant:"typography_first", theme:{mood:"curated",contrast:"mixed",typography:"editorial",density:"airy",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"cinematic_entertainment", name:"Cinematic Entertainment", summary:"Dramatic, immersive presentation for theaters, comedy venues, live shows, nightlife attractions and ticketed entertainment.", signals:["cinema","movie theater","comedy","show","live entertainment","performance","tickets","night out"], variants:["cinematic_strip","typography_first","asymmetric_gallery"], defaultVariant:"cinematic_strip", theme:{mood:"cinematic",contrast:"dark",typography:"modern",density:"balanced",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"modern_steakhouse", name:"Modern Steakhouse", summary:"Dark architectural luxury with confident typography, fire-and-grill imagery and reservation-forward pacing.", signals:["steakhouse","prime steak","dry aged","grill","chophouse","modern steakhouse"], variants:["cinematic_strip","editorial_split","typography_first"], defaultVariant:"cinematic_strip", theme:{mood:"architectural",contrast:"dark",typography:"editorial",density:"airy",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"sushi_modern", name:"Modern Japanese", summary:"Precise, minimal composition for sushi, ramen, izakaya and Japanese concepts with an emphasis on craft and detail.", signals:["sushi","japanese","ramen","izakaya","sashimi","yakitori"], variants:["typography_first","framed_photo","editorial_split"], defaultVariant:"framed_photo", theme:{mood:"precise",contrast:"mixed",typography:"modern",density:"airy",imageTreatment:"minimal",reservationPriority:"primary"}}),
  d({ id:"tropical_caribbean", name:"Tropical Caribbean", summary:"Warm, saturated hospitality for Caribbean, Jamaican, Haitian, Cuban and island-inspired restaurants and lounges.", signals:["caribbean","jamaican","haitian","cuban","tropical","island","rum bar"], variants:["photo_mosaic","asymmetric_gallery","framed_photo"], defaultVariant:"photo_mosaic", theme:{mood:"tropical",contrast:"mixed",typography:"playful",density:"balanced",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"latin_night", name:"Latin Night", summary:"Expressive after-dark presentation for Latin restaurants, dance-forward dining, lounges and celebratory group occasions.", signals:["latin","salsa","bachata","reggaeton","dominican","puerto rican","peruvian","nightlife"], variants:["asymmetric_gallery","cinematic_strip","photo_mosaic"], defaultVariant:"asymmetric_gallery", theme:{mood:"rhythmic",contrast:"dark",typography:"modern",density:"balanced",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"rooftop_city", name:"City Rooftop", summary:"Skyline-first luxury for rooftops and elevated bars with panoramic imagery and high-conversion reservation calls to action.", signals:["rooftop","skyline","terrace","city view","penthouse","roof bar"], variants:["cinematic_strip","framed_photo","typography_first"], defaultVariant:"cinematic_strip", theme:{mood:"elevated",contrast:"dark",typography:"modern",density:"airy",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"garden_terrace", name:"Garden Terrace", summary:"Botanical, daylight-rich presentation for patios, gardens, conservatories and romantic outdoor dining.", signals:["garden","patio","terrace","botanical","outdoor dining","greenhouse"], variants:["framed_photo","editorial_split","photo_mosaic"], defaultVariant:"framed_photo", theme:{mood:"botanical",contrast:"light",typography:"editorial",density:"airy",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"wine_cellar", name:"Wine Cellar", summary:"Textural old-world refinement for wine bars, tasting rooms and cellar-driven restaurants.", signals:["wine bar","wine cellar","sommelier","tasting room","vineyard","wine list"], variants:["editorial_split","typography_first","framed_photo"], defaultVariant:"editorial_split", theme:{mood:"cellar",contrast:"mixed",typography:"classic",density:"airy",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"craft_brewery", name:"Craft Brewery", summary:"Industrial but polished presentation for breweries, taprooms and beer halls with strong event and group-booking visibility.", signals:["brewery","taproom","beer hall","craft beer","brewpub","taps"], variants:["photo_mosaic","editorial_split","cinematic_strip"], defaultVariant:"photo_mosaic", theme:{mood:"crafted",contrast:"mixed",typography:"modern",density:"balanced",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"sports_watch", name:"Game Day", summary:"Fast-scanning, energetic design for sports bars and watch venues where screens, food, groups and reservations compete for attention.", signals:["sports bar","game day","watch party","football","basketball","baseball","screens"], variants:["photo_mosaic","cinematic_strip","typography_first"], defaultVariant:"photo_mosaic", theme:{mood:"game-day",contrast:"dark",typography:"modern",density:"compact",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"jazz_room", name:"Jazz Room", summary:"Low-light editorial storytelling for jazz clubs, supper clubs and intimate live-music rooms.", signals:["jazz","supper club","live music","piano","blues","intimate music"], variants:["cinematic_strip","typography_first","editorial_split"], defaultVariant:"typography_first", theme:{mood:"soulful",contrast:"dark",typography:"classic",density:"airy",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"comedy_club", name:"Comedy Club", summary:"Punchy, ticket-forward entertainment design balancing upcoming shows, venue personality and food or drink conversion.", signals:["comedy club","stand up","comedian","show tickets","open mic"], variants:["typography_first","cinematic_strip","photo_mosaic"], defaultVariant:"typography_first", theme:{mood:"punchy",contrast:"dark",typography:"modern",density:"balanced",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"karaoke_social", name:"Karaoke Social", summary:"Playful nightlife design for karaoke rooms and singing lounges with group booking and private-room emphasis.", signals:["karaoke","private karaoke","singing room","karaoke bar","private room"], variants:["asymmetric_gallery","photo_mosaic","cinematic_strip"], defaultVariant:"asymmetric_gallery", theme:{mood:"playful-night",contrast:"dark",typography:"playful",density:"balanced",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"arcade_neon", name:"Neon Arcade", summary:"Electric, immersive design for arcades and gaming venues with bold visual rhythm and immediate booking actions.", signals:["arcade","neon","gaming","video games","retro games","game room"], variants:["photo_mosaic","asymmetric_gallery","cinematic_strip"], defaultVariant:"photo_mosaic", theme:{mood:"neon",contrast:"dark",typography:"modern",density:"compact",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"bowling_luxe", name:"Bowling Luxe", summary:"Premium social-entertainment styling for modern bowling lounges, lanes, food, drinks and corporate groups.", signals:["bowling","bowling lounge","lanes","bowling alley","corporate bowling"], variants:["cinematic_strip","asymmetric_gallery","framed_photo"], defaultVariant:"cinematic_strip", theme:{mood:"luxe-play",contrast:"dark",typography:"modern",density:"balanced",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"escape_cinematic", name:"Escape Adventure", summary:"Story-driven cinematic design for escape rooms and immersive adventures with clear difficulty, room and booking hierarchy.", signals:["escape room","escape game","immersive adventure","puzzle room","mission"], variants:["cinematic_strip","asymmetric_gallery","typography_first"], defaultVariant:"cinematic_strip", theme:{mood:"mysterious",contrast:"dark",typography:"modern",density:"balanced",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"mini_golf_playful", name:"Playful Mini Golf", summary:"Colorful premium entertainment layout for indoor and outdoor mini golf, dates, groups and parties.", signals:["mini golf","putt putt","crazy golf","indoor golf","putting"], variants:["photo_mosaic","framed_photo","asymmetric_gallery"], defaultVariant:"photo_mosaic", theme:{mood:"playful",contrast:"mixed",typography:"playful",density:"balanced",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"museum_modern", name:"Modern Museum", summary:"Clean curatorial presentation for museums and exhibitions with strong current-program and visit-planning hierarchy.", signals:["museum","exhibition","collection","installation","cultural center"], variants:["typography_first","editorial_split","asymmetric_gallery"], defaultVariant:"typography_first", theme:{mood:"curatorial",contrast:"light",typography:"editorial",density:"airy",imageTreatment:"minimal",reservationPriority:"primary"}}),
  d({ id:"theater_grand", name:"Grand Theater", summary:"Elegant performance-led design for theaters and stage venues with strong show, ticket and venue-story hierarchy.", signals:["theater","theatre","broadway","stage","performance venue","playhouse"], variants:["cinematic_strip","editorial_split","typography_first"], defaultVariant:"cinematic_strip", theme:{mood:"grand",contrast:"dark",typography:"classic",density:"airy",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"spa_serene", name:"Serene Spa", summary:"Soft, spacious wellness design focused on treatments, atmosphere, trust and effortless appointment booking.", signals:["spa","massage","facial","wellness","sauna","body treatment"], variants:["framed_photo","typography_first","editorial_split"], defaultVariant:"framed_photo", theme:{mood:"serene",contrast:"light",typography:"editorial",density:"airy",imageTreatment:"minimal",reservationPriority:"primary"}}),
  d({ id:"dessert_bakery", name:"Dessert Atelier", summary:"Editorial-playful styling for bakeries, dessert bars, pastry shops and sweet-focused cafés.", signals:["bakery","dessert","pastry","cake","ice cream","sweet shop"], variants:["framed_photo","photo_mosaic","editorial_split"], defaultVariant:"framed_photo", theme:{mood:"sweet",contrast:"light",typography:"playful",density:"balanced",imageTreatment:"grid",reservationPriority:"primary"}}),
  d({ id:"coffee_roastery", name:"Coffee Roastery", summary:"Warm modern craft presentation for specialty coffee, roasteries and design-conscious cafés.", signals:["coffee","roastery","espresso","specialty cafe","coffee shop","cafe"], variants:["editorial_split","framed_photo","typography_first"], defaultVariant:"editorial_split", theme:{mood:"roasted",contrast:"light",typography:"modern",density:"balanced",imageTreatment:"editorial",reservationPriority:"primary"}}),
  d({ id:"private_events", name:"Private Events", summary:"Conversion-focused hospitality presentation for venues whose primary business is parties, corporate events, buyouts and celebrations.", signals:["private events","private dining","party venue","corporate events","buyout","celebration","wedding"], variants:["cinematic_strip","framed_photo","editorial_split"], defaultVariant:"framed_photo", theme:{mood:"celebratory",contrast:"mixed",typography:"editorial",density:"balanced",imageTreatment:"editorial",reservationPriority:"primary"}}),
];

const LEGACY_DIRECTION_ALIASES: Record<string, string> = {
  cocktail_society: "refined_after_dark",
  experiential_escape: "experiential_escape",
  natural_retreat: "coastal_airy",
  playful_local: "creative_workshop",
  industrial_edge: "bold_social",
  heritage_story: "classic_bistro",
  contemporary_culture: "editorial_luxury",
  high_energy_experience: "experiential_escape",
  competitive_social: "experiential_escape",
  immersive_adventure: "experiential_escape",
  family_fun: "creative_workshop",
  wellness_escape: "luxury_minimal",
};

export function normalizeWebsiteDesignDirectionId(id: string) {
  return LEGACY_DIRECTION_ALIASES[id] || id;
}

export function getWebsiteDesignDirection(id: string) {
  const normalized = normalizeWebsiteDesignDirectionId(id);
  return WEBSITE_DESIGN_DIRECTIONS.find((direction) => direction.id === normalized) || null;
}
