"use client";

import { useEffect, useState } from "react";

type LocationType = "restaurants" | "activities";
type Form = { dress_code:string; parking_info:string; best_for:string; special_features:string; logo_url:string; reservation_provider:string; reservation_url:string; uses_internal_reservations:boolean; allow_external_reservations:boolean };
const empty:Form={dress_code:"",parking_info:"",best_for:"",special_features:"",logo_url:"",reservation_provider:"",reservation_url:"",uses_internal_reservations:false,allow_external_reservations:true};
const input="w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm font-semibold text-white outline-none focus:border-[#ff2142]/60";

export default function WebsiteReadyLocationPanel({locationId,locationType}:{locationId:string;locationType:LocationType}){
  const [form,setForm]=useState<Form>(empty);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
  useEffect(()=>{let cancelled=false;(async()=>{try{const response=await fetch(`/api/locations/edit-context?type=${locationType}&id=${encodeURIComponent(locationId)}`,{cache:"no-store"});const data=await response.json();if(!response.ok||!data.location)throw new Error(data.error||"Unable to load website-ready details.");const row=data.location;if(!cancelled)setForm({dress_code:row.dress_code||"",parking_info:row.parking_info||"",best_for:row.best_for||"",special_features:row.special_features||"",logo_url:row.logo_url||row.brand_logo_url||row.location_logo_url||"",reservation_provider:row.reservation_provider||"",reservation_url:row.external_reservation_url||row.reservation_url||row.reservation_link||row.booking_url||"",uses_internal_reservations:Boolean(row.uses_internal_reservations||row.internal_reservations_enabled),allow_external_reservations:row.allow_external_reservations!==false})}catch(error){if(!cancelled)setMessage(error instanceof Error?error.message:"Unable to load details.")}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[locationId,locationType]);
  const set=<K extends keyof Form>(key:K,value:Form[K])=>setForm(current=>({...current,[key]:value}));
  async function save(){setSaving(true);setMessage("");try{const response=await fetch("/api/locations/edit-context",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:locationType,id:locationId,payload:{dress_code:form.dress_code,parking_info:form.parking_info,best_for:form.best_for,special_features:form.special_features,logo_url:form.logo_url,reservation_provider:form.reservation_provider,reservation_url:form.reservation_url,reservation_link:form.reservation_url,external_reservation_url:form.reservation_url,uses_internal_reservations:form.uses_internal_reservations,internal_reservations_enabled:form.uses_internal_reservations,allow_external_reservations:form.allow_external_reservations,reservation_source:form.uses_internal_reservations?(form.reservation_url?"both":"internal"):(form.reservation_url?"external":"none")}})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to save website details.");setMessage("Saved. Your website will use these details automatically.")}catch(error){setMessage(error instanceof Error?error.message:"Unable to save details.")}finally{setSaving(false)}}
  if(loading)return <div className="mx-auto max-w-6xl px-4 pb-5 sm:px-6 lg:px-8"><div className="h-40 animate-pulse rounded-3xl border border-white/10 bg-white/[0.04]"/></div>;
  return <div className="mx-auto max-w-6xl px-4 pb-5 sm:px-6 lg:px-8"><section className="rounded-3xl border border-white/10 bg-[#0c1017] p-5 text-white sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#ff6b86]">Website-ready business details</p><h2 className="mt-2 text-xl font-black">Edit once. Your website updates from here.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/50">These are business facts, so they stay in Edit Location—not in a separate website editor. Hosted websites use them automatically.</p></div><button type="button" onClick={save} disabled={saving} className="rounded-2xl bg-[#ff2142] px-5 py-3 text-sm font-black disabled:opacity-40">{saving?"Saving…":"Save website-ready details"}</button></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Logo URL" value={form.logo_url} onChange={value=>set("logo_url",value)} placeholder="https://…"/><Field label="Dress code" value={form.dress_code} onChange={value=>set("dress_code",value)} placeholder="Casual, smart casual, upscale…"/><Field label="Parking" value={form.parking_info} onChange={value=>set("parking_info",value)} placeholder="Valet, street parking, nearby garage…"/><Field label="Best for" value={form.best_for} onChange={value=>set("best_for",value)} placeholder="Date night, groups, families…"/><Field label="Special features" value={form.special_features} onChange={value=>set("special_features",value)} placeholder="Rooftop, live music, private rooms…"/><Field label="Reservation provider" value={form.reservation_provider} onChange={value=>set("reservation_provider",value)} placeholder="TheOutHaven, Resy, OpenTable, Toast…"/><div className="md:col-span-2"><Field label="External reservation link" value={form.reservation_url} onChange={value=>set("reservation_url",value)} placeholder="https://…"/></div><label className="flex items-center gap-3 rounded-2xl border border-white/10 bg-black/20 p-4 text-sm font-bold"><input type="checkbox" checked={form.uses_internal_reservations} onChange={event=>set("uses_internal_reservations",event.target.checked)}/>Use TheOutHaven Reserve</label><label className="flex items-center gap-3 rounded-2xl border border-white/10 bg-black/20 p-4 text-sm font-bold"><input type="checkbox" checked={form.allow_external_reservations} onChange={event=>set("allow_external_reservations",event.target.checked)}/>Allow existing reservation provider</label></div>{message?<p className="mt-4 text-sm font-bold text-white/65">{message}</p>:null}</section></div>;
}
function Field({label,value,onChange,placeholder}:{label:string;value:string;onChange:(value:string)=>void;placeholder:string}){return <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-[0.14em] text-white/40">{label}</span><input className={input} value={value} onChange={event=>onChange(event.target.value)} placeholder={placeholder}/></label>}
