import Link from "next/link";
import { requireAdminRole } from "@/lib/admin-auth";
import { CRM_READ_ROLES } from "@/lib/crm/permissions";
import { CRM_PIPELINES, type PipelineKey } from "@/lib/crm/pipelines";
import { listOpportunities, listOpportunitySelectors } from "@/lib/crm/opportunities/queries";
import { stageAgeDays } from "@/lib/crm/opportunities";
import { createOpportunityAction } from "./actions";
export const dynamic = "force-dynamic";
const money = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
export default async function OpportunitiesPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) { await requireAdminRole(CRM_READ_ROLES); const p = await searchParams, pipeline = (p.pipeline && p.pipeline in CRM_PIPELINES ? p.pipeline : "reserve_pro") as PipelineKey, view = p.view === "table" ? "table" : "board"; const [result, selectors] = await Promise.all([listOpportunities({ pipeline, view, stage: p.stage, forecast: p.forecast, risk: p.risk, search: p.q, page: Number(p.page) || 1 }), listOpportunitySelectors()]); return <main className="mx-auto max-w-[1600px] space-y-5 p-5 text-white">
<header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-rose-400">Commercial CRM</p><h1 className="text-3xl font-black">Opportunities</h1><p className="text-white/55">Pipeline execution, revenue, risk, and next actions.</p></div><nav className="flex gap-2"><Link className="rounded-lg bg-rose-600 px-4 py-2 font-bold" href="/admin/dashboard/crm/forecast">Forecast</Link><Link className="rounded-lg border border-white/15 px-4 py-2" href={`?pipeline=${pipeline}&view=${view === "board" ? "table" : "board"}`}>{view === "board" ? "Table" : "Board"}</Link></nav></header>
<nav className="flex gap-2 overflow-x-auto pb-1">{Object.keys(CRM_PIPELINES).map(k=><Link key={k} href={`?pipeline=${k}&view=${view}`} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${k===pipeline?"bg-rose-600 font-bold":"bg-white/5 text-white/60"}`}>{k.replaceAll("_"," ")}</Link>)}</nav>
<section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[["Open pipeline",result.totals.pipeline],["Weighted",result.totals.weighted],["Commit",result.totals.commit],["Best case",result.totals.bestCase],["Closed won",result.totals.closed],["Stalled",result.rows.filter((o:any)=>o.health.status==="stalled").length]].map(([label,value])=><article key={String(label)} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><p className="text-xs uppercase text-white/45">{label}</p><b className="text-xl">{label==="Stalled"?value:money(Number(value))}</b></article>)}</section>
<form className="grid gap-2 rounded-2xl border border-white/10 bg-white/[.03] p-3 md:grid-cols-5"><input type="hidden" name="pipeline" value={pipeline}/><input type="hidden" name="view" value={view}/><input name="q" defaultValue={p.q} placeholder="Search opportunities" className="rounded-lg bg-black/40 p-2"/><select name="stage" defaultValue={p.stage??""} className="rounded-lg bg-black p-2"><option value="">All stages</option>{result.stages.map((s:any)=><option key={s.stage_key}>{s.stage_key}</option>)}</select><select name="forecast" defaultValue={p.forecast??""} className="rounded-lg bg-black p-2"><option value="">All forecasts</option>{["pipeline","best_case","commit","closed","omitted"].map(x=><option key={x}>{x}</option>)}</select><select name="risk" defaultValue={p.risk??""} className="rounded-lg bg-black p-2"><option value="">All risk levels</option>{["low","medium","high","critical"].map(x=><option key={x}>{x}</option>)}</select><button className="rounded-lg bg-white px-3 font-bold text-black">Apply filters</button></form>
<details className="rounded-2xl border border-white/10 p-4"><summary className="cursor-pointer font-bold">Create opportunity</summary><form action={createOpportunityAction} className="mt-3 grid gap-2 md:grid-cols-7"><input required name="name" placeholder="Opportunity name" className="rounded-lg bg-black/40 p-2"/><select required name="account_id" className="rounded-lg bg-black p-2"><option value="">Select account</option>{selectors.accounts.map((a:any)=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select name="primary_contact_id" className="rounded-lg bg-black p-2"><option value="">Primary contact</option>{selectors.contacts.map((c:any)=><option key={c.id} value={c.id}>{c.full_name||c.email}</option>)}</select><select name="primary_location_id" className="rounded-lg bg-black p-2"><option value="">Related location</option>{selectors.locations.map((l:any)=><option key={l.id} value={l.id}>{l.name}</option>)}</select><select name="pipeline_key" defaultValue={pipeline} className="rounded-lg bg-black p-2">{Object.keys(CRM_PIPELINES).map(k=><option key={k}>{k}</option>)}</select><input name="amount" type="number" min="0" step=".01" placeholder="Amount" className="rounded-lg bg-black/40 p-2"/><button className="rounded-lg bg-rose-600 font-bold">Create</button></form></details>
{view === "board" ? <section className="grid gap-3 md:grid-cols-2 xl:flex xl:overflow-x-auto">{result.stages.map((stage:any)=><div key={stage.id} className="min-w-72 flex-1 rounded-2xl bg-black/25 p-3"><header className="mb-3 flex justify-between"><b>{stage.name}</b><span className="text-white/40">{result.rows.filter((o:any)=>o.stage===stage.stage_key).length}</span></header><div className="space-y-2">{result.rows.filter((o:any)=>o.stage===stage.stage_key).map((o:any)=><Link key={o.id} href={`/admin/dashboard/crm/opportunities/${o.id}`} className="block rounded-xl border border-white/10 bg-white/[.05] p-3 hover:border-rose-500"><b>{o.name}</b><small className="block text-white/50">{o.crm_accounts?.name??"Account"} · {money(o.amount??0)}</small><div className="mt-2 flex flex-wrap gap-1 text-[11px]"><span className="rounded bg-white/10 px-2 py-1">{o.forecast_category}</span><span className="rounded bg-white/10 px-2 py-1">{o.probability??0}%</span><span className="rounded bg-white/10 px-2 py-1">{stageAgeDays(o.last_stage_changed_at)}d</span><span className="rounded bg-rose-950 px-2 py-1">{o.health.status}</span></div><p className="mt-2 truncate text-xs text-white/55">Next: {o.next_step??"Not set"}</p></Link>)}</div></div>)}</section> : <section className="overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-white/10 text-xs uppercase"><tr>{["Opportunity","Stage","Account","Amount","Weighted","Forecast","Probability","Close","Days","Risk","Next step","Tasks"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{result.rows.map((o:any)=><tr key={o.id} className="border-t border-white/10"><td className="p-3"><Link className="font-bold text-rose-300" href={`/admin/dashboard/crm/opportunities/${o.id}`}>{o.name}</Link></td><td>{o.stage}</td><td>{o.crm_accounts?.name}</td><td>{money(o.amount??0)}</td><td>{money(o.weighted_amount??0)}</td><td>{o.forecast_category}</td><td>{o.probability??0}%</td><td>{o.expected_close_date??"—"}</td><td>{stageAgeDays(o.last_stage_changed_at)}</td><td>{o.risk_level??o.health.status}</td><td>{o.next_step??"—"}</td><td>{o.crm_tasks?.[0]?.count??0}</td></tr>)}</tbody></table></section>}
<p className="text-sm text-white/40">{result.count} opportunities · bounded to {result.size} results</p></main> }
