import "server-only";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { isUuid } from "./context";
import { paging, type SearchParams } from "./core-modules";
export type CanonicalClaimStatus = "new"|"in_review"|"information_needed"|"approved"|"rejected"|"expired"|"duplicate"|"escalated"|"cancelled";
export type NormalizedClaim = { id:string; source:string; sourceId:string; locationId:string|null; accountId:string|null; claimantUserId:string|null; claimantName:string|null; claimantEmail:string|null; claimantPhone:string|null; submittedBusinessName:string|null; status:CanonicalClaimStatus; reviewerId:string|null; assignedTeamId:string|null; riskLevel:string|null; verificationState:string|null; submittedAt:string; updatedAt:string; reviewedAt:string|null; metadata:Record<string,unknown> };
export class ClaimsQueryError extends Error { code:string; safeMessage:string; source?:string; retryable:boolean; constructor(code:string,safeMessage:string,opts:{source?:string;retryable?:boolean;cause?:unknown}={}){super(safeMessage);this.code=code;this.safeMessage=safeMessage;this.source=opts.source;this.retryable=opts.retryable??false;if(opts.cause) (this as any).cause=opts.cause;} }
const statusMap: Record<string,CanonicalClaimStatus>={ pending:"new", submitted:"new", open:"new", under_review:"in_review", reviewing:"in_review", in_review:"in_review", needs_info:"information_needed", more_info_required:"information_needed", information_needed:"information_needed", verified:"approved", accepted:"approved", approved:"approved", denied:"rejected", declined:"rejected", rejected:"rejected", closed:"cancelled", duplicate_detected:"duplicate", duplicate:"duplicate", escalation_required:"escalated", escalated:"escalated", expired:"expired", cancelled:"cancelled" };
export function normalizeClaimStatus(raw?: string|null): CanonicalClaimStatus { return statusMap[String(raw||"pending").toLowerCase()] || "new"; }
export function getClaimSourceStatusFilter(status: string) { const s = normalizeClaimStatus(status); return Object.entries(statusMap).filter(([,v])=>v===s).map(([k])=>k); }
export function getClaimAllowedTransitions(s: CanonicalClaimStatus){ return ({new:["in_review","approved","rejected","duplicate","cancelled"],in_review:["information_needed","approved","rejected","escalated","duplicate"],information_needed:["in_review","cancelled"],escalated:["in_review","approved","rejected"],approved:[],rejected:[],expired:[],duplicate:[],cancelled:[]} as Record<CanonicalClaimStatus,CanonicalClaimStatus[]>)[s];}
export function validateClaimTransition(a:CanonicalClaimStatus,b:CanonicalClaimStatus){ if(!getClaimAllowedTransitions(a).includes(b)) throw new ClaimsQueryError("CLAIMS_INVALID_FILTER","That claim status transition is not allowed."); return true; }
function normalize(r:any, accounts = new Map<string,string>()): NormalizedClaim { return { id:r.id, source:"location_claim_requests", sourceId:r.id, locationId:r.location_id??null, accountId:r.location_id?accounts.get(r.location_id)??null:null, claimantUserId:r.user_id??null, claimantName:r.owner_name??null, claimantEmail:r.owner_email??null, claimantPhone:r.owner_phone??null, submittedBusinessName:r.location_name??null, status:normalizeClaimStatus(r.status), reviewerId:r.reviewed_by??null, assignedTeamId:null, riskLevel:r.match_status === "conflict" ? "high" : null, verificationState:r.verification_status??r.match_status??null, submittedAt:r.submitted_at??r.created_at, updatedAt:r.updated_at??r.submitted_at??r.created_at, reviewedAt:r.reviewed_at??null, metadata:{requestType:r.request_type, planInterest:r.plan_interest, sourceStatus:r.status} }; }
export async function listNormalizedClaims(p: SearchParams) { const pg=paging(p); let q=supabaseAdmin.from("location_claim_requests").select("*",{count:"exact"}); if(p.location_id&&isUuid(p.location_id)) q=q.eq("location_id",p.location_id); if(p.status) q=q.in("status",getClaimSourceStatusFilter(p.status)); if(p.source&&p.source!=="location_claim_requests") throw new ClaimsQueryError("CLAIMS_INVALID_FILTER","Unsupported claim source filter."); if(p.q) q=q.or(`location_name.ilike.%${p.q.replace(/[%_]/g,"\\$&")}%,owner_email.ilike.%${p.q.replace(/[%_]/g,"\\$&")}%,owner_phone.ilike.%${p.q.replace(/[%_]/g,"\\$&")}%`); const {data,error,count}=await q.order("submitted_at",{ascending:false}).range(pg.from,pg.to); if(error) throw new ClaimsQueryError("CLAIMS_QUERY_FAILED","Claims could not be loaded right now.",{source:"location_claim_requests",retryable:true,cause:error}); const locIds=[...new Set((data??[]).map((r:any)=>r.location_id).filter(Boolean))]; const accounts=new Map<string,string>(); if(locIds.length){ const {data:rels}=await supabaseAdmin.from("crm_account_locations").select("location_id,account_id").in("location_id",locIds).eq("status","active"); for(const r of rels??[]) accounts.set(r.location_id,r.account_id); } let rows=(data??[]).map((r:any)=>normalize(r,accounts)); if(p.account_id&&isUuid(p.account_id)) rows=rows.filter(r=>r.accountId===p.account_id); return {rows,count:p.account_id?rows.length:count??0,page:pg.page,pageSize:25,warnings:[],sourceHealth:[{source:"location_claim_requests",available:true,canonical:true}]}; }
export async function getNormalizedClaim(id:string){ const {data,error}=await supabaseAdmin.from("location_claim_requests").select("*").eq("id",id).single(); if(error) throw new ClaimsQueryError("CLAIMS_QUERY_FAILED","Claim could not be loaded right now.",{source:"location_claim_requests",retryable:true,cause:error}); return normalize(data); }
