import "server-only";
import { supabaseAdmin } from "@/lib/supabase-admin";

export type SearchParams = Record<string, string | undefined>;
const esc = (v: string) => v.replace(/[%_]/g, "\\$&");
export const pageSize = 25;
export function paging(p: SearchParams) { const page = Math.max(1, Number(p.page) || 1); return { page, from: (page - 1) * pageSize, to: page * pageSize - 1 }; }

export async function listClaims(p: SearchParams) { const pg = paging(p); let q = supabaseAdmin.from("locations").select("id,name,address,city,state,phone,website,claim_status,claim_outreach_status,claim_code,claim_url,updated_at,created_at,is_searchable,is_hidden,source_quality,duplicate_status", { count: "exact" }); if (p.status) q = q.eq("claim_status", p.status); if (p.market) q = q.eq("state", p.market); if (p.q) q = q.or(`name.ilike.%${esc(p.q)}%,address.ilike.%${esc(p.q)}%,phone.ilike.%${esc(p.q)}%`); const { data, error, count } = await q.order(p.sort || "updated_at", { ascending: p.dir === "asc" }).range(pg.from, pg.to); if (error) throw error; return { rows: data ?? [], count: count ?? 0, ...pg }; }
export async function getClaim(id: string) { const [{ data: claim, error }, { data: codes }, { data: tasks }, { data: acts }] = await Promise.all([supabaseAdmin.from("locations").select("*").eq("id", id).single(), supabaseAdmin.from("location_claim_codes").select("*").eq("location_id", id).order("created_at", { ascending: false }).limit(50), supabaseAdmin.from("crm_tasks").select("*").eq("location_id", id).is("archived_at", null).limit(50), supabaseAdmin.from("crm_activities").select("*").eq("location_id", id).order("occurred_at", { ascending: false }).limit(100)]); if (error) throw error; return { claim, codes: codes ?? [], tasks: tasks ?? [], activities: acts ?? [] }; }
export async function listClaimCodes(p: SearchParams) { const pg = paging(p); let q = supabaseAdmin.from("location_claim_codes").select("*,locations(id,name,city,state),crm_accounts(id,name)", { count: "exact" }); if (p.status) q = q.eq("status", p.status); if (p.q) q = q.or(`claim_code.ilike.%${esc(p.q)}%,claim_url.ilike.%${esc(p.q)}%`); const { data, error, count } = await q.order("created_at", { ascending: false }).range(pg.from, pg.to); if (error) throw error; return { rows: data ?? [], count: count ?? 0, ...pg }; }
export async function listOutreach(p: SearchParams) { const pg = paging(p); let q = supabaseAdmin.from("crm_tasks").select("*,crm_accounts(id,name),locations(id,name,city,state),crm_contacts(id,full_name,email),crm_opportunities(id,name)", { count: "exact" }).in("task_type", ["social_outreach","phone_outreach","email_outreach","site_visit","follow_up","claim_code_delivery","owner_meeting"]).is("archived_at", null); if (p.status) q = q.eq("status", p.status); if (p.channel) q = q.eq("task_type", p.channel); if (p.q) q = q.ilike("title", `%${esc(p.q)}%`); const { data, error, count } = await q.order("updated_at", { ascending: false }).range(pg.from, pg.to); if (error) throw error; return { rows: data ?? [], count: count ?? 0, ...pg }; }
export async function listSupport(p: SearchParams) { const pg = paging(p); let q = supabaseAdmin.from("support_tickets").select("*", { count: "exact" }); if (p.status) q = q.eq("status", p.status); if (p.priority) q = q.eq("priority", p.priority); if (p.category) q = q.eq("category", p.category); if (p.q) q = q.or(`subject.ilike.%${esc(p.q)}%,email.ilike.%${esc(p.q)}%,requester_email.ilike.%${esc(p.q)}%`); const { data, error, count } = await q.order("updated_at", { ascending: false }).range(pg.from, pg.to); if (error) throw error; return { rows: data ?? [], count: count ?? 0, ...pg }; }
export async function getSupportCase(id: string) { const [{ data: ticket, error }, { data: messages }, { data: acts }] = await Promise.all([supabaseAdmin.from("support_tickets").select("*").eq("id", id).single(), supabaseAdmin.from("support_ticket_messages").select("*").eq("ticket_id", id).order("created_at"), supabaseAdmin.from("crm_activities").select("*").eq("record_id", id).order("occurred_at", { ascending: false }).limit(100)]); if (error) throw error; return { ticket, messages: messages ?? [], activities: acts ?? [] }; }
export async function operationsSnapshot() { const [claims, hidden, support, tasks, codes] = await Promise.all([supabaseAdmin.from("locations").select("id,name,claim_status,updated_at", { count: "exact", head: false }).in("claim_status", ["pending","in_review","information_needed"] as any).limit(20), supabaseAdmin.from("locations").select("id,name,is_searchable,is_hidden,updated_at", { count: "exact" }).or("is_searchable.eq.false,is_hidden.eq.true").limit(20), supabaseAdmin.from("support_tickets").select("id,subject,status,priority,updated_at", { count: "exact" }).in("status", ["new","open","pending"] as any).limit(20), supabaseAdmin.from("crm_tasks").select("id,title,status,priority,due_at,updated_at", { count: "exact" }).in("status", ["open","blocked","in_progress"] as any).limit(20), supabaseAdmin.from("location_claim_codes").select("id,claim_code,status,expires_at,updated_at", { count: "exact" }).limit(20)]); return { claims, hidden, support, tasks, codes }; }
export async function reportSnapshot(p: SearchParams) { const start = p.start || new Date(Date.now() - 30*864e5).toISOString().slice(0,10), end = p.end || new Date().toISOString().slice(0,10); const [opps, claims, support, outreach] = await Promise.all([supabaseAdmin.from("crm_opportunities").select("amount,weighted_amount,stage,forecast_category,created_at").gte("created_at", start).lte("created_at", end), supabaseAdmin.from("locations").select("claim_status,created_at").gte("created_at", start).lte("created_at", end), supabaseAdmin.from("support_tickets").select("status,priority,category,created_at,closed_at").gte("created_at", start).lte("created_at", end), supabaseAdmin.from("crm_tasks").select("task_type,status,created_at").in("task_type", ["social_outreach","phone_outreach","email_outreach","site_visit","follow_up","claim_code_delivery"]).gte("created_at", start).lte("created_at", end)]); return { start, end, opps: opps.data ?? [], claims: claims.data ?? [], support: support.data ?? [], outreach: outreach.data ?? [] }; }
