import type { SearchMode, SearchPlan } from "../planner/searchPlanTypes";
import type { EnterpriseLocation } from "../../enterprise/types";
import type { resultCounts } from "./resultCounts";

export type PublicLocationCard = EnterpriseLocation & { searchRole?: string; searchScore?: number; whyMatched?: string; why_it_matched?: string; matchReasons?: string[] };
export type PublicPairCard = { restaurant: PublicLocationCard; activity: PublicLocationCard; distanceMiles: number | null; walkingMinutes: number | null; score: number; whyMatched?: string; why_it_matched?: string; matchReasons?: string[] };
export type PublicAnchorContext = { requested: boolean; resolved: boolean; rawName: string | null; relationship: "near" | "nearby" | null; location: PublicLocationCard | null };
export type PublicBuilderContext = { enabled: boolean; restaurants: PublicLocationCard[]; activities: PublicLocationCard[]; selectedRestaurantId: string | null; selectedActivityId: string | null };
export type PublicSearchResponseV2 = {
  version: "public-search-v2";
  success: boolean;
  requestFulfilled: boolean;
  partialResults: boolean;
  requestId: string;
  requestedMode: SearchMode;
  resolvedMode: SearchMode;
  primaryDomain: "restaurant" | "activity" | "mixed" | "anchor";
  primary_domain: "restaurant" | "activity" | "mixed" | "anchor";
  displayMode: "restaurant_cards" | "activity_cards" | "same_venue_cards" | "pairs" | "partial_mixed" | "empty";
  searchPlan: SearchPlan;
  restaurants: PublicLocationCard[];
  activities: PublicLocationCard[];
  sameVenueResults: PublicLocationCard[];
  pairs: PublicPairCard[];
  builder: PublicBuilderContext;
  anchor: PublicAnchorContext;
  counts: ReturnType<typeof resultCounts>;
  fallback: { used: boolean; reason: string | null };
  retrieval: {
    configuredMode: "off" | "shadow" | "canary" | "primary";
    servedSource: "legacy" | "canonical_profile" | "mixed";
    profileVersion: number | null;
    canaryBucket: number | null;
    canaryPercent: number | null;
    profileCandidateCount: number;
    legacyCandidateCount: number;
    legacyFallbackUsed: boolean;
    fallbackDomains: string[];
  };
  message: string;
  timing: Record<string, number>;
  ml: { enabled: boolean; modelVersion: string | null; rankingVariant: string; configuredVariant: string | null; appliedVariant: string; applied: boolean; shadowOnly: boolean; rolloutBucket: number | null; reason: string };
  debug?: Record<string, unknown>;
};
