"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { USER_ROLE_OPTIONS } from "@/lib/users/roles";
const ageOptions = ["Under 21", "21–24", "25–34", "35–44", "45–54", "55–64", "65+", "Prefer not to say"];
const planOptions = [{ value: "free", label: "Free" }, { value: "unlimited", label: "TheOutHaven Plus / Unlimited" }, { value: "comped", label: "Comped" }, { value: "admin", label: "Admin" }];
function Field({ label, helper, children }: { label: string; helper?: string; children: any }) { return <label className="grid gap-1 text-sm font-bold text-white/80"><span>{label}</span>{children}{helper ? <span className="text-xs font-medium text-white/45">{helper}</span> : null}</label>; }
export function ProfileForm({ userId, profile }: { userId: string; profile: any }) {
  const [m, setM] = useState("");
  const [confirmSuper, setConfirmSuper] = useState(false);
  const [f, setF] = useState({ full_name: profile.full_name || "", preferred_name: profile.preferred_name || "", phone: profile.phone || profile.mobile_number || "", zip_code: profile.zip_code || profile.derived_market_area || "", age_range: profile.age_range || "", birthday: profile.birthday_month && profile.birthday_day ? `${String(profile.birthday_month).padStart(2, "0")}-${String(profile.birthday_day).padStart(2, "0")}` : "", sms_opt_in: !!profile.sms_opt_in, birthday_opt_in: !!profile.birthday_opt_in, role: profile.role || "user", plan: profile.plan || "free" });
  async function save(e: any) { e.preventDefault(); setM(""); if (f.role === "superadmin" && !confirmSuper) { setM("Confirm the superadmin role change before saving."); return; } const r = await fetch(`/api/admin/users/${userId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(f) }); const p = await r.json().catch(() => ({})); setM(r.ok ? "Profile saved." : p.error || "Could not save profile."); }
  return <form id="profile" onSubmit={save} className="grid gap-4 md:grid-cols-2">
    <Field label="Full name"><input className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-white" value={f.full_name} onChange={e => setF({ ...f, full_name: e.target.value })} /></Field>
    <Field label="Preferred name"><input className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-white" value={f.preferred_name} onChange={e => setF({ ...f, preferred_name: e.target.value })} /></Field>
    <Field label="Phone"><input className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-white" value={f.phone} onChange={e => setF({ ...f, phone: e.target.value })} /></Field>
    <Field label="ZIP / main area"><input className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-white" value={f.zip_code} onChange={e => setF({ ...f, zip_code: e.target.value })} /></Field>
    <Field label="Age range"><select aria-label="Age range" className="rounded-2xl border border-white/10 bg-[#120809] px-4 py-3 text-white" value={f.age_range} onChange={e => setF({ ...f, age_range: e.target.value })}><option value="">Select age range</option>{ageOptions.map(o => <option key={o}>{o}</option>)}</select></Field>
    <Field label="Birthday" helper="Month and day only. No birth year needed."><input placeholder="MM-DD" className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-white" value={f.birthday} onChange={e => setF({ ...f, birthday: e.target.value })} /></Field>
    <Field label="User role" helper="Superadmin-only. Role changes are audit logged."><select aria-label="User role" className="rounded-2xl border border-white/10 bg-[#120809] px-4 py-3 text-white" value={f.role} onChange={e => setF({ ...f, role: e.target.value })}><option value="">Select user role</option>{USER_ROLE_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select></Field>
    <Field label="Plan" helper="Updates the active customer subscription."><select aria-label="Plan" className="rounded-2xl border border-white/10 bg-[#120809] px-4 py-3 text-white" value={f.plan} onChange={e => setF({ ...f, plan: e.target.value })}><option value="">Select plan</option>{planOptions.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select></Field>
    {f.role === "superadmin" ? <label className="md:col-span-2 flex gap-2 text-sm text-amber-100"><input type="checkbox" checked={confirmSuper} onChange={e => setConfirmSuper(e.target.checked)} /> I confirm this account should have superadmin access.</label> : null}
    <label className="text-sm text-white/70"><input type="checkbox" checked={f.sms_opt_in} onChange={e => setF({ ...f, sms_opt_in: e.target.checked })} /> SMS opt-in</label>
    <label className="text-sm text-white/70"><input type="checkbox" checked={f.birthday_opt_in} onChange={e => setF({ ...f, birthday_opt_in: e.target.checked })} /> Birthday opt-in</label>
    <button className="rounded-full bg-rose-600 px-5 py-3 text-sm font-black">Save profile, role, and plan</button>{m && <p className="text-sm text-emerald-100">{m}</p>}
  </form>;
}
export function PasswordReset({ userId }: { userId: string }) { const [m, setM] = useState(""); return <button onClick={async () => { const r = await fetch(`/api/admin/users/${userId}/password-reset`, { method: "POST" }); setM(r.ok ? "Password reset email sent." : "Could not send reset email."); }} className="rounded-xl border border-white/10 bg-white/[.06] px-4 py-2 text-sm font-black text-white">Send password reset {m && <span className="ml-2 text-rose-100">{m}</span>}</button>; }
export function DeleteUser({ userId, email }: { userId: string; email?: string | null }) { const router = useRouter(); const [confirmation, setConfirmation] = useState(""); const [reason, setReason] = useState(""); const [m, setM] = useState(""); async function del() { const r = await fetch(`/api/admin/users/${userId}`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmation, reason }) }); const p = await r.json().catch(() => ({})); if (r.ok) router.push("/admin/dashboard/users?status=disabled"); else setM(p.error || "Could not disable user."); } return <div className="rounded-3xl border border-red-300/25 bg-red-950/20 p-4"><h3 className="text-lg font-black text-red-100">Delete / Disable User</h3><p className="mt-2 text-sm text-white/60">Soft disables the account, preserves support/audit records, and logs who performed the action.</p><input aria-label="Delete confirmation" className="mt-3 w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-white" placeholder={`Type DELETE or ${email || "the user email"}`} value={confirmation} onChange={e => setConfirmation(e.target.value)} /><textarea aria-label="Delete reason" className="mt-3 w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-white" placeholder="Reason" value={reason} onChange={e => setReason(e.target.value)} /><button type="button" onClick={del} className="mt-3 rounded-full bg-red-600 px-5 py-3 text-sm font-black text-white">Delete / Disable User</button>{m ? <p className="mt-2 text-sm text-red-100">{m}</p> : null}</div>; }
