"use client";

import { useEffect, useMemo, useState } from "react";

type Promo = {
  id: string; code: string; name: string | null; audience: "users"|"locations"|"both"; promo_type: string;
  target_scope: string; plan_granted: string | null; is_active: boolean; redemption_count: number; max_redemptions: number | null;
  starts_at: string; expires_at: string | null; created_at: string;
};

type PromoFormState = { code:string; prefix:string; name:string; description:string; internal_notes:string; audience:"users"|"locations"|"both"; target_scope:"any"|"specific_user"|"specific_location"|"signup_user"|"signup_location_owner"; assigned_user_id:string; assigned_location_id:string; assigned_location_name:string; signup_context:""|"user_signup"|"location_owner_signup"|"both_signups"; promo_type:"premium_access"|"search_boost"|"location_pro_trial"|"discount"; plan_granted:string; duration_days:string; search_limit_override:string; discount_mode:"none"|"percent"|"amount"; discount_percent:string; discount_amount:string; max_redemptions:string; max_redemptions_per_user:string; starts_at:string; expires_at:string; is_active:boolean; };

const initialForm: PromoFormState = { code:"", prefix:"OUT", name:"", description:"", internal_notes:"", audience:"users", target_scope:"any", assigned_user_id:"", assigned_location_id:"", assigned_location_name:"", signup_context:"", promo_type:"premium_access", plan_granted:"", duration_days:"30", search_limit_override:"", discount_mode:"none", discount_percent:"", discount_amount:"", max_redemptions:"", max_redemptions_per_user:"1", starts_at:"", expires_at:"", is_active:true };

export default function AdminPromoCodesPage() {
  const [items,setItems]=useState<Promo[]>([]); const [form,setForm]=useState<PromoFormState>(initialForm); const [msg,setMsg]=useState("");
  const [filters,setFilters]=useState({q:"",audience:"",promo_type:"",status:""});

  const load=async()=>{ const p=new URLSearchParams(); Object.entries(filters).forEach(([k,v])=>v&&p.set(k,v)); const res=await fetch(`/api/admin/promo-codes?${p.toString()}`); const d=await res.json(); setItems(d.promo_codes||[]); };
  useEffect(()=>{load();},[]);
  useEffect(()=>{ if(form.target_scope==="signup_user") setForm(s=>({...s,signup_context:"user_signup"})); if(form.target_scope==="signup_location_owner") setForm(s=>({...s,signup_context:"location_owner_signup"}));},[form.target_scope]);

  const summary=useMemo(()=>{ const now=Date.now(); return { total:items.length, active:items.filter(i=>i.is_active).length, redemptions:items.reduce((a,b)=>a+(b.redemption_count||0),0), expired:items.filter(i=>i.expires_at&&new Date(i.expires_at).getTime()<now).length };},[items]);
  const statusFor=(p:Promo)=>{ const now=Date.now(); if(!p.is_active) return "Inactive"; if(p.max_redemptions!==null&&p.redemption_count>=p.max_redemptions) return "Exhausted"; if(new Date(p.starts_at).getTime()>now) return "Scheduled"; if(p.expires_at&&new Date(p.expires_at).getTime()<now) return "Expired"; return "Active"; };

  const create=async()=>{ const payload={...form, auto_generated:!form.code, discount_percent: form.discount_mode==="percent"?form.discount_percent:"", discount_amount: form.discount_mode==="amount"?form.discount_amount:"", search_limit_override: form.search_limit_override==="unlimited"?"":form.search_limit_override};
    const res=await fetch('/api/admin/promo-codes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const d=await res.json(); if(!res.ok){setMsg(d.error||"Failed");return;} setMsg("Promo code created."); setForm(s=>({...initialForm,prefix:s.prefix,audience:s.audience,promo_type:s.promo_type})); await load(); };

  return <main className="min-h-screen bg-[#090706] px-4 pb-12 pt-24 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-6">
    <div><h1 className="text-3xl font-black">Promo Codes</h1><p className="text-white/70">Create invite codes, signup offers, premium trials, and location owner promotions.</p></div>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(summary).map(([k,v])=><div key={k} className="rounded-3xl border border-white/10 bg-[#120d0b] p-4"><p className="text-white/60 capitalize">{k}</p><p className="text-2xl font-bold">{v}</p></div>)}</section>
    <section className="rounded-3xl border border-white/10 bg-[#120d0b] p-6 space-y-4">
      <h2 className="text-xl font-bold">Create Promo Code</h2>{msg&&<p className="text-emerald-300">{msg}</p>}
      <div className="grid gap-3 md:grid-cols-3">
        <input className="field" placeholder="Code" value={form.code} onChange={e=>setForm(s=>({...s,code:e.target.value}))}/>
        <select className="field" value={form.prefix} onChange={e=>setForm(s=>({...s,prefix:e.target.value}))}>{["OUT","BETA","VIP","USER","OWNER","PRO","COMP"].map(v=><option key={v}>{v}</option>)}</select>
        <button onClick={async()=>{const r=await fetch('/api/admin/promo-codes/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prefix:form.prefix})}); const d=await r.json(); setForm(s=>({...s,code:d.code||""}));}} className="rounded-2xl bg-gradient-to-r from-rose-700 to-amber-500 px-4">Generate unique code</button>
        <input className="field" placeholder="Name" value={form.name} onChange={e=>setForm(s=>({...s,name:e.target.value}))}/><input className="field" placeholder="Description" value={form.description} onChange={e=>setForm(s=>({...s,description:e.target.value}))}/><input className="field" placeholder="Internal notes" value={form.internal_notes} onChange={e=>setForm(s=>({...s,internal_notes:e.target.value}))}/>
      </div>
      <div className="grid gap-3 md:grid-cols-3">
        <select className="field" value={form.audience} onChange={e=>setForm(s=>({...s,audience:e.target.value as PromoFormState["audience"]}))}><option value="users">Users</option><option value="locations">Location owners</option><option value="both">Users + location owners</option></select>
        <select className="field" value={form.target_scope} onChange={e=>setForm(s=>({...s,target_scope:e.target.value as PromoFormState["target_scope"]}))}><option value="any">Anyone in selected audience</option><option value="specific_user">One specific user</option><option value="specific_location">One specific location</option><option value="signup_user">User signup only</option><option value="signup_location_owner">Location owner signup only</option></select>
        <select className="field" value={form.promo_type} onChange={e=>setForm(s=>({...s,promo_type:e.target.value as PromoFormState["promo_type"]}))}><option value="premium_access">User premium access</option><option value="search_boost">Search limit boost</option><option value="location_pro_trial">Location Pro trial</option><option value="discount">Discount</option></select>
        {form.target_scope==="specific_user"&&<input className="field" placeholder="assigned_user_id" value={form.assigned_user_id} onChange={e=>setForm(s=>({...s,assigned_user_id:e.target.value}))}/>}        
        {form.target_scope==="specific_location"&&<><input className="field" placeholder="assigned_location_id (public.locations.id)" value={form.assigned_location_id} onChange={e=>setForm(s=>({...s,assigned_location_id:e.target.value}))}/><input className="field" placeholder="assigned_location_name" value={form.assigned_location_name} onChange={e=>setForm(s=>({...s,assigned_location_name:e.target.value}))}/></>}
      </div>
      <div className="grid gap-3 md:grid-cols-4"><input className="field" placeholder="plan_granted" value={form.plan_granted} onChange={e=>setForm(s=>({...s,plan_granted:e.target.value}))}/><input className="field" placeholder="duration_days" value={form.duration_days} onChange={e=>setForm(s=>({...s,duration_days:e.target.value}))}/><input className="field" placeholder="search_limit_override" value={form.search_limit_override} onChange={e=>setForm(s=>({...s,search_limit_override:e.target.value}))}/><select className="field" value={form.discount_mode} onChange={e=>setForm(s=>({...s,discount_mode:e.target.value as PromoFormState["discount_mode"]}))}><option value="none">No discount</option><option value="percent">Percent</option><option value="amount">Amount</option></select>{form.discount_mode==="percent"&&<input className="field" placeholder="discount_percent" value={form.discount_percent} onChange={e=>setForm(s=>({...s,discount_percent:e.target.value}))}/>} {form.discount_mode==="amount"&&<input className="field" placeholder="discount_amount" value={form.discount_amount} onChange={e=>setForm(s=>({...s,discount_amount:e.target.value}))}/>}</div>
      <div className="grid gap-3 md:grid-cols-4"><input className="field" placeholder="max_redemptions" value={form.max_redemptions} onChange={e=>setForm(s=>({...s,max_redemptions:e.target.value}))}/><input className="field" placeholder="max_redemptions_per_user" value={form.max_redemptions_per_user} onChange={e=>setForm(s=>({...s,max_redemptions_per_user:e.target.value}))}/><input className="field" type="datetime-local" value={form.starts_at} onChange={e=>setForm(s=>({...s,starts_at:e.target.value}))}/><input className="field" type="datetime-local" value={form.expires_at} onChange={e=>setForm(s=>({...s,expires_at:e.target.value}))}/></div>
      <label className="flex items-center gap-2"><input type="checkbox" checked={form.is_active} onChange={e=>setForm(s=>({...s,is_active:e.target.checked}))}/>Active</label>
      <button onClick={create} className="rounded-2xl bg-gradient-to-r from-rose-700 to-amber-500 px-4 py-3">Create promo code</button>
    </section>
    <section className="rounded-3xl border border-white/10 bg-[#120d0b] p-6"><div className="mb-3 grid gap-2 md:grid-cols-4"><input className="field" placeholder="Search by code/name" value={filters.q} onChange={e=>setFilters(s=>({...s,q:e.target.value}))}/><select className="field" value={filters.audience} onChange={e=>setFilters(s=>({...s,audience:e.target.value}))}><option value="">All audiences</option><option value="users">Users</option><option value="locations">Location owners</option><option value="both">Both</option></select><select className="field" value={filters.promo_type} onChange={e=>setFilters(s=>({...s,promo_type:e.target.value}))}><option value="">All types</option><option value="premium_access">Premium access</option><option value="search_boost">Search boost</option><option value="location_pro_trial">Location pro trial</option><option value="discount">Discount</option></select><select className="field" value={filters.status} onChange={e=>setFilters(s=>({...s,status:e.target.value}))}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="expired">Expired</option><option value="scheduled">Scheduled</option></select></div><button className="rounded-xl border border-white/20 px-3 py-1" onClick={load}>Apply filters</button>
      <div className="mt-4 overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left text-white/70"><th>Code</th><th>Name</th><th>Audience</th><th>Target</th><th>Promo type</th><th>Plan/benefit</th><th>Status</th><th>Redemptions</th><th>Starts</th><th>Expires</th><th>Created</th><th>Actions</th></tr></thead><tbody>{items.map(p=><tr key={p.id} className="border-t border-white/10"><td><button onClick={()=>navigator.clipboard.writeText(p.code)} className="underline">{p.code}</button></td><td>{p.name||"-"}</td><td>{p.audience}</td><td>{p.target_scope}</td><td>{p.promo_type}</td><td>{p.plan_granted||"-"}</td><td>{statusFor(p)}</td><td>{p.redemption_count}{p.max_redemptions!==null?`/${p.max_redemptions}`:""}</td><td>{new Date(p.starts_at).toLocaleDateString()}</td><td>{p.expires_at?new Date(p.expires_at).toLocaleDateString():"-"}</td><td>{new Date(p.created_at).toLocaleDateString()}</td><td><button className="rounded-xl border border-white/20 px-2" onClick={async()=>{await fetch(`/api/admin/promo-codes/${p.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_active:!p.is_active})}); await load();}}>{p.is_active?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table></div>
    </section>
  </div><style jsx>{`.field{min-height:48px;border-radius:1rem;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.03);padding:.6rem .8rem;color:white}`}</style></main>;
}
