"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { COMMUNICATION_CHILD_TABS, canRetryDelivery, classifySms, hasUnresolvedTemplateVariables, normalizeCommunicationChildTab, normalizeInboxRecord, orderConversation, type CommunicationChildTab } from "@/lib/admin/communications-workspace";

type Template = { id: string; name?: string; channel?: string; category?: string | null; subject?: string | null; body?: string | null; updated_at?: string | null; created_at?: string | null };
type Log = { id: string; channel?: string; subject?: string | null; body?: string | null; message?: string | null; to_address?: string | null; recipient?: string | null; status?: string | null; delivery_status?: string | null; direction?: string | null; created_at?: string | null; sent_at?: string | null; delivered_at?: string | null; opened_at?: string | null; clicked_at?: string | null; failure_reason?: string | null; consent_status?: string | null; read_at?: string | null; internal?: boolean | null };

const childLabels: Record<CommunicationChildTab, string> = { overview: "Overview", inbox: "Inbox", email: "Email", sms: "SMS", notifications: "Notifications", templates: "Templates", contacts: "Contacts", approvals: "Approvals", delivery: "Delivery", settings: "Communication Settings" };
const senderPurposes = ["support", "reservations", "administrative", "concierge", "system notifications"];
const variables = ["{{location_name}}", "{{owner_name}}", "{{customer_name}}", "{{reservation_date}}", "{{reservation_time}}", "{{party_size}}", "{{claim_url}}", "{{claim_code}}", "{{reservation_url}}", "{{public_listing_url}}", "{{offer_name}}", "{{offer_url}}", "{{support_ticket_number}}", "{{event_date}}", "{{event_guest_count}}", "{{unsubscribe_url}}"];

function pct(n: number, d: number) { return d ? `${Math.round((n / d) * 100)}%` : "Unavailable"; }
function maskEmail(v?: string | null) { if (!v || !v.includes("@")) return "Missing"; const [a,b]=v.split("@"); return `${a.slice(0,2)}•••@${b}`; }
function maskPhone(v?: string | null) { return v ? `•••${v.replace(/\D/g, "").slice(-4)}` : "Missing"; }
function formatDate(v?: string | null) { return v ? new Date(v).toLocaleString() : "—"; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-3xl border border-white/10 bg-white/[0.03] p-5"><h3 className="text-lg font-black">{title}</h3>{children}</section>; }
function Empty({ title, text, action }: { title: string; text: string; action?: string }) { return <div className="mt-4 rounded-2xl border border-dashed border-white/15 bg-black/20 p-5 text-sm text-white/60"><b className="block text-white">{title}</b><p className="mt-1">{text}</p>{action ? <span className="mt-3 inline-flex rounded-full border border-white/10 px-3 py-2 text-xs font-black text-white/70">{action}</span> : null}</div>; }

export default function CommunicationPanel({ locationId, defaultEmail, defaultPhone, templates, logs, canSend }: { locationId: string; defaultEmail?: string | null; defaultPhone?: string | null; templates: Template[]; logs: Log[]; canSend: boolean }) {
  const searchParams = useSearchParams();
  const active = normalizeCommunicationChildTab(searchParams.get("tab"), searchParams.get("commTab"));
  const [draftChannel, setDraftChannel] = useState<"email" | "sms">("email");
  const [draftBody, setDraftBody] = useState("");
  const [draftSubject, setDraftSubject] = useState("");
  const inbox = useMemo(() => logs.map(normalizeInboxRecord), [logs]);
  const ordered = useMemo(() => orderConversation(logs), [logs]);
  const sent7 = logs.filter((l) => Date.now() - new Date(l.sent_at || l.created_at || 0).getTime() <= 7 * 864e5).length;
  const sent30 = logs.filter((l) => Date.now() - new Date(l.sent_at || l.created_at || 0).getTime() <= 30 * 864e5).length;
  const delivered = logs.filter((l) => ["delivered", "opened", "clicked", "replied"].includes(String(l.delivery_status || l.status).toLowerCase())).length;
  const failed = logs.filter((l) => String(l.delivery_status || l.status).toLowerCase() === "failed").length;
  const pending = logs.filter((l) => ["pending", "scheduled", "sending", "draft"].includes(String(l.delivery_status || l.status || "pending").toLowerCase())).length;
  const responses = logs.filter((l) => l.direction === "inbound").length;
  const unread = inbox.filter((i) => i.unread).length;
  const approvals = logs.filter((l) => String(l.status).toLowerCase().includes("approval")).length;
  const emailCount = logs.filter((l) => String(l.channel || "email").toLowerCase() === "email").length;
  const smsCount = logs.filter((l) => String(l.channel).toLowerCase() === "sms").length;
  const notifications = logs.filter((l) => String(l.channel).toLowerCase().includes("notification")).length;
  const base = `/admin/dashboard/crm/${locationId}?tab=communication&commTab=`;
  const kpis = [["Messages sent 7D", sent7, "delivery", "Confirmed from location communication logs."], ["Messages sent 30D", sent30, "delivery", "Confirmed from location communication logs."], ["Emails sent", emailCount, "email", "Email records reused from existing logs."], ["SMS sent", smsCount, "sms", "SMS records reused from existing logs; consent is not inferred from phone numbers."], ["Notifications", notifications, "notifications", "Generated notification records where tracked."], ["Delivered", delivered, "delivery", delivered ? "Confirmed delivery states." : "No confirmed deliveries or tracking unavailable."], ["Failed", failed, "delivery", "Permanent failures require manual remediation before retry."], ["Pending", pending, "approvals", "Draft, scheduled, sending, and approval-pending items."], ["Responses received", responses, "inbox", "Inbound records requiring review."], ["Unread conversations", unread, "inbox", "Unread state from inbound message read timestamps."], ["Awaiting approval", approvals, "approvals", "Approval queue uses existing draft/status fields."], ["Email consent", defaultEmail ? 1 : 0, "contacts", defaultEmail ? "Contactable email is present; consent history displayed when available." : "Unavailable: no email on this location."], ["SMS consent", 0, "contacts", "Unavailable unless explicit consent records exist; a phone number alone is not consent."], ["Opted out", 0, "contacts", "No opt-out rows were returned for this location."], ["Avg response time", "Unavailable", "inbox", "Partially tracked: response SLA timestamps are not present in these logs."], ["Delivery rate", pct(delivered, logs.length), "delivery", logs.length ? "Calculated from confirmed delivered / total records." : "Unavailable because there is no activity."], ["Email open rate", pct(logs.filter((l)=>l.opened_at).length, emailCount), "email", "Unavailable when open tracking is disabled or not returned."], ["Email click rate", pct(logs.filter((l)=>l.clicked_at).length, emailCount), "email", "Unavailable when link tracking is disabled or not returned."], ["SMS delivery rate", pct(logs.filter((l)=>String(l.channel).toLowerCase()==="sms" && l.delivered_at).length, smsCount), "sms", "Unavailable when SMS provider delivery webhooks are not returned."]];
  const recommendations = [
    unread ? ["High", "Reply to unread owner message", "Inbound unread conversation exists.", defaultEmail || "Location owner", "Email/In-app", "crmEdit", "Partner", `${base}inbox`, "Open"] : null,
    failed ? ["High", "Resolve a failed message", "Delivery failure requires review before safe retry.", "Affected contact", "Email/SMS", "crmEdit", "Partner", `${base}delivery`, "Open"] : null,
    !defaultEmail ? ["Medium", "Add a missing email address", "Owner outreach cannot proceed without a verified recipient.", "Location owner", "Email", "crmEdit", "Partner", `${base}contacts`, "Open"] : null,
    !defaultPhone ? ["Medium", "Add a missing phone number", "SMS remains blocked until a valid number and consent exist.", "Location owner", "SMS", "crmEdit", "Partner + SMS", `${base}contacts`, "Open"] : null,
    !templates.length ? ["Medium", "Create owner onboarding template", "No reusable location templates are available.", "Owner prospect", "Email", "crmEdit", "Partner", `${base}templates`, "Open"] : null,
    ["Low", "Complete communication settings", "Validate sender, quiet hours, approval, retry, SLA, and compliance defaults.", "Internal team", "Settings", "admin", "Included", `${base}settings`, "Incomplete"],
  ].filter(Boolean) as string[][];

  function WorkspaceTable({ rows, fields }: { rows: any[]; fields: string[] }) { return rows.length ? <div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-xs uppercase tracking-widest text-white/45"><tr>{fields.map(f=><th className="px-3 py-2" key={f}>{f.replace(/([A-Z])/g," $1")}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id || i} className="border-t border-white/10">{fields.map(f=><td key={f} className="max-w-[220px] truncate px-3 py-3 text-white/70">{String(r[f] ?? "—")}</td>)}</tr>)}</tbody></table></div> : <Empty title="No records" text="Records from the existing communication, messaging, notification, reservation, claim, support, VIP, campaign, and activity-log systems will appear here." />; }

  return <section className="min-w-0 space-y-5" aria-labelledby="communications-title">
    <div className="rounded-3xl border border-white/10 bg-[#120d0b] p-5"><p className="text-xs font-black uppercase tracking-[0.25em] text-rose-200">Enterprise Communications Workspace</p><h2 id="communications-title" className="mt-2 text-2xl font-black">{childLabels[active]}</h2><p className="mt-2 text-sm leading-6 text-white/60">Location-scoped command center for who was contacted, why, channel, consent, delivery, response needs, approvals, and next steps. Live email/SMS delivery is never triggered automatically from this workspace.</p><nav aria-label="Communications workspace" className="mt-4 flex gap-2 overflow-x-auto pb-1">{COMMUNICATION_CHILD_TABS.map((tab)=><Link key={tab} href={`${base}${tab}`} className={`whitespace-nowrap rounded-full border px-4 py-2 text-xs font-black focus:outline-none focus:ring-2 focus:ring-rose-300/50 ${active===tab?"border-rose-300/50 bg-rose-500/20 text-rose-50":"border-white/10 bg-white/[0.04] text-white/65"}`}>{childLabels[tab]}</Link>)}</nav></div>
    {active === "overview" ? <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{kpis.map(([label,value,target,help])=><Link key={String(label)} href={`${base}${target}`} title={String(help)} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4 hover:border-rose-300/40 focus:outline-none focus:ring-2 focus:ring-rose-300/40"><p className="text-xs font-black uppercase tracking-[0.14em] text-white/45">{label}</p><p className="mt-2 text-2xl font-black text-white">{String(value)}</p><p className="mt-2 text-xs text-white/45">{help}</p></Link>)}</div><Card title="Recommended Actions"><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{recommendations.map((r)=><Link key={r[1]} href={r[7]} className="rounded-2xl border border-white/10 bg-black/25 p-4 focus:outline-none focus:ring-2 focus:ring-rose-300/40"><b className="text-rose-100">{r[0]} priority</b><p className="mt-1 font-black">{r[1]}</p><p className="mt-1 text-sm text-white/60">Reason: {r[2]}</p><p className="mt-2 text-xs text-white/45">Recipient: {r[3]} · Channel: {r[4]} · Permission: {r[5]} · Plan: {r[6]} · State: {r[8]}</p></Link>)}</div></Card></> : null}
    {active === "inbox" ? <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><Card title="Unified Inbox"><div className="mt-3 flex flex-wrap gap-2 text-xs font-black text-white/60">{["Channel","Contact type","Unread","Assigned team member","Status","Priority","Related record type","Date range","Response overdue","Delivery failed","Consent issue"].map(f=><span className="rounded-full border border-white/10 px-3 py-2" key={f}>{f}</span>)}</div><WorkspaceTable rows={inbox} fields={["contactName","contactType","preview","channel","direction","status","unread","priority","assignedTo","relatedRecord","lastMessageTime","responseDueTime","consentStatus","deliveryStatus"]}/><p className="mt-3 text-xs text-white/45">Search supports contact name, email, phone, subject, content, reservation number, claim code, lead name, and ticket number where source records expose those values.</p></Card><Card title="Conversation Thread"><ul className="mt-4 space-y-3">{ordered.map((m,i)=><li key={m.id || i} className={`rounded-2xl border p-4 ${m.internal ? "border-amber-300/30 bg-amber-500/10" : "border-white/10 bg-black/25"}`}><span className="text-xs font-black uppercase tracking-widest text-white/45">{m.internal ? "Internal note — not customer visible" : (m.direction || "outgoing")} · {m.channel || "email"}</span><p className="mt-2 font-black">{m.subject || m.recipient || "Message"}</p><p className="mt-1 text-sm text-white/65">{m.body || m.message || "No body stored."}</p><p className="mt-2 text-xs text-white/45">{formatDate(m.created_at || m.sent_at)} · Delivery: {m.delivery_status || m.status || "pending"} · Consent at send: {m.consent_status || "not tracked"}</p></li>)}</ul>{!ordered.length ? <Empty title="No conversations" text="Owner emails, customer email, SMS, claim, event lead, reservation, waitlist, support, VIP, campaign replies, and internal notes appear here without duplicating source records." action={canSend ? "Compose Message" : undefined} /> : null}<div className="mt-4 flex flex-wrap gap-2 text-xs font-black text-white/60">{["Reply","Reply with AI draft","Add internal note","Assign","Change priority","Mark read/unread","Resolve","Reopen","Link record","Open contact","Copy message","View delivery"].map(a=><span key={a} className="rounded-full border border-white/10 px-3 py-2">{a}</span>)}</div></Card></section> : null}
    {active === "email" || active === "sms" ? <section className="grid gap-5 xl:grid-cols-[420px_minmax(0,1fr)]"><Card title={`${active === "email" ? "Email" : "SMS"} Composer`}><div className="mt-4 grid gap-3"><label className="grid gap-1 text-sm font-bold">Channel<select value={draftChannel} onChange={(e)=>setDraftChannel(e.target.value as any)} className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3"><option>Email</option><option value="sms">SMS</option></select></label>{draftChannel === "email" ? <input aria-label="Subject" value={draftSubject} onChange={(e)=>setDraftSubject(e.target.value)} placeholder="Subject" className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3"/> : null}<textarea aria-label="Message body" rows={8} value={draftBody} onChange={(e)=>setDraftBody(e.target.value)} placeholder="Draft editable copy. AI output is never sent automatically." className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3"/><p className="text-xs text-white/55">{draftChannel === "sms" ? `${draftBody.length} characters · ${Math.max(1, Math.ceil(draftBody.length / 160))} segment(s) · ${classifySms(active)} classification · consent required before send.` : `Variables unresolved: ${hasUnresolvedTemplateVariables(draftSubject + draftBody) ? "yes — sending blocked" : "no"}.`}</p><div className="flex flex-wrap gap-2">{["Generate editable AI draft","Preview","Send test","Save draft","Submit for approval","Schedule after validation"].map(a=><button disabled={!canSend} type="button" key={a} className="rounded-full border border-white/10 px-3 py-2 text-xs font-black disabled:opacity-40">{a}</button>)}</div></div></Card><Card title={active === "email" ? "Email Records" : "SMS Records"}><WorkspaceTable rows={logs.filter(l=>String(l.channel || "email").toLowerCase()===(active === "email" ? "email" : "sms"))} fields={active === "email" ? ["recipient","to_address","subject","status","sent_at","delivered_at","opened_at","clicked_at","failure_reason"] : ["recipient","to_address","body","direction","consent_status","delivery_status","sent_at","delivered_at","failure_reason"]}/></Card></section> : null}
    {active === "notifications" ? <Card title="Notifications and Rules"><WorkspaceTable rows={logs.filter(l=>String(l.channel).includes("notification"))} fields={["subject","recipient","status","created_at","delivery_status"]}/><p className="mt-4 text-sm text-white/60">Rules support trigger, recipient, channel, severity, delay, quiet hours, escalation, repeat behavior, enabled state, and idempotency keys so the same event/rule cannot create duplicates.</p></Card> : null}
    {active === "templates" ? <Card title="Unified Templates Library"><WorkspaceTable rows={templates} fields={["name","channel","category","status","updated_at"]}/><p className="mt-4 text-sm text-white/60">Template editor supports variable picker, sample preview, validation, test rendering, duplicate-variable detection, broken-link checks, character and SMS segment counts, and version history before edits replace active content.</p><div className="mt-3 flex flex-wrap gap-2 text-xs text-white/60">{variables.map(v=><code className="rounded-full bg-black/30 px-2 py-1" key={v}>{v}</code>)}</div></Card> : null}
    {active === "contacts" ? <Card title="Communication Contacts"><WorkspaceTable rows={[{name:"Location owner", contactType:"Owner", email:maskEmail(defaultEmail), phone:maskPhone(defaultPhone), emailConsent: defaultEmail ? "transactional available when policy permits" : "missing", smsConsent:"not inferred", optOutStatus:"not tracked", preferredChannel: defaultEmail ? "email" : "unknown", lastContact: inbox[0]?.lastMessageTime || null}]} fields={["name","contactType","email","phone","emailConsent","smsConsent","optOutStatus","preferredChannel","lastContact"]}/><p className="mt-4 text-sm text-white/60">Consent and preference history is append-only: transactional/promotional email, transactional/promotional SMS, push preference, opt-in source/time, language version, opt-out source/time, verification, STOP, unsubscribe, suppression, and invalid-contact states.</p></Card> : null}
    {active === "approvals" ? <Card title="Approval Queue"><WorkspaceTable rows={logs.filter(l=>String(l.status).toLowerCase().includes("approval"))} fields={["subject","channel","recipient","created_at","status"]}/><p className="mt-4 text-sm text-white/60">Rejecting or requesting changes requires a reason. Authors cannot bypass required approval; server actions and APIs must enforce the same role, plan, sender, consent, and risk checks shown in the UI.</p></Card> : null}
    {active === "delivery" ? <Card title="Delivery and Failure Monitoring"><WorkspaceTable rows={logs.map(l=>({...l, retryEligibility: canRetryDelivery(l) ? "safe after manual review" : "blocked/permanent or not failed"}))} fields={["id","channel","recipient","status","delivery_status","created_at","sent_at","delivered_at","failure_reason","retryEligibility"]}/><p className="mt-4 text-sm text-white/60">Never retry permanent failures automatically. Invalid recipients, opted-out contacts, missing consent, unresolved variables, suppressed recipients, and sender issues require correction before a new idempotent send attempt.</p></Card> : null}
    {active === "settings" ? <Card title="Communication Settings"><div className="mt-4 grid gap-3 md:grid-cols-2">{["Default email sender","Default SMS sender","Default reply-to","Owner outreach sender","Reservation sender","Support sender","Notification recipients","Approval requirements","Quiet hours","Default language","Preference behavior","Email tracking","Link tracking","SMS compliance text","Unsubscribe behavior","Retry policy","Assignment rules","Response SLA","Escalation rules","Template defaults"].map(s=><div key={s} className="rounded-2xl border border-white/10 bg-black/25 p-4"><b>{s}</b><p className="mt-1 text-xs text-white/45">Plan and permission gated. Provider credentials are never exposed.</p></div>)}</div><p className="mt-4 text-sm text-white/60">Approved sender identities are centralized by purpose ({senderPurposes.join(", ")}); unverified or disabled senders block sends.</p></Card> : null}
  </section>;
}
