import { createClient as createSupabaseClient } from "@supabase/supabase-js";
import { ADMIN_PAGE_ACCESS } from "@/lib/admin-permissions";
import { requireAdminRole } from "@/lib/admin-auth";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { requirePublicEnv, requireSupabaseUrl } from "@/lib/env";
import { getSiteUrl } from "@/lib/site-url";
import { logAdminAuditEvent } from "@/lib/admin-audit-log";
import { USER_ROLES, type UserRole } from "@/lib/users/roles";

export const adminUserAccessRoles = ADMIN_PAGE_ACCESS.adminUsers;
export async function requireAdminOrSupport() { return requireAdminRole(adminUserAccessRoles); }
export const PLAN_OPTIONS = ["free", "unlimited", "comped", "admin"] as const;
export const AGE_RANGE_OPTIONS = ["Under 21", "21–24", "25–34", "35–44", "45–54", "55–64", "65+", "Prefer not to say"] as const;
export function like(s?: string | null) { return `%${String(s || "").trim().replace(/[%,]/g, "")}%`; }
async function safe<T>(fn: () => Promise<T>, fallback: T) { try { return await fn(); } catch { return fallback; } }
const emailKey = (email?: string | null) => String(email || "").trim().toLowerCase();
const openStatuses = ["closed", "resolved"];
const uuidRe = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export async function listAdminUsers(filters: { q?: string; role?: string; beta?: string; plan?: string; status?: string; tickets?: string; booked?: string; email?: string; giveaway?: string; page?: number }) {
  await requireAdminOrSupport();
  const page = Math.max(1, Number(filters.page || 1));
  const per = 25;
  const [profiles, appUsers, betaRows, betaApps, launchRows, authUsers] = await Promise.all([
    safe(async () => (await supabaseAdmin.from("user_profiles").select("*").order("created_at", { ascending: false }).limit(1000)).data || [], [] as any[]),
    safe(async () => (await supabaseAdmin.from("users").select("*").order("created_at", { ascending: false }).limit(1000)).data || [], [] as any[]),
    safe(async () => (await supabaseAdmin.from("beta_testers").select("*").order("created_at", { ascending: false }).limit(1000)).data || [], [] as any[]),
    safe(async () => (await supabaseAdmin.from("beta_applications").select("*").order("created_at", { ascending: false }).limit(1000)).data || [], [] as any[]),
    safe(async () => (await supabaseAdmin.from("launch_waitlist_signups").select("*").order("created_at", { ascending: false }).limit(1000)).data || [], [] as any[]),
    safe(async () => (await supabaseAdmin.auth.admin.listUsers({ page: 1, perPage: 1000 })).data.users || [], [] as any[]),
  ]);

  const authById = new Map(authUsers.map((u: any) => [u.id, u]));
  const authByEmail = new Map(authUsers.filter((u: any) => u.email).map((u: any) => [emailKey(u.email), u]));
  const merged = new Map<string, any>();
  const findKey = (id?: string | null, email?: string | null) => {
    if (id && merged.has(`user:${id}`)) return `user:${id}`;
    const e = emailKey(email);
    if (e && merged.has(`email:${e}`)) return `email:${e}`;
    for (const [k, v] of merged) if ((id && (v.id === id || v.user_id === id)) || (e && emailKey(v.email) === e)) return k;
    return id ? `user:${id}` : e ? `email:${e}` : `row:${crypto.randomUUID?.() || Math.random()}`;
  };
  const put = (row: any) => {
    const k = findKey(row.id || row.user_id, row.email);
    const prev = merged.get(k) || {};
    const next = { ...prev, ...row, badges: Array.from(new Set([...(prev.badges || []), ...(row.badges || [])])), id: row.id || row.user_id || prev.id || prev.user_id };
    if (!next.email) next.email = prev.email;
    if (!next.full_name) next.full_name = prev.full_name || prev.name;
    merged.delete(k); merged.set(next.id ? `user:${next.id}` : `email:${emailKey(next.email)}`, next);
  };

  profiles.forEach((p: any) => put({ ...p, hasAccount: true, badges: ["Account User"] }));
  appUsers.forEach((u: any) => put({ ...u, id: u.id || u.user_id, full_name: u.full_name || u.name, hasAccount: true, badges: ["Account User"] }));
  authUsers.forEach((u: any) => put({ id: u.id, email: u.email, full_name: u.user_metadata?.full_name || u.user_metadata?.name, created_at: u.created_at, email_confirmed_at: u.email_confirmed_at, hasAccount: true, badges: ["Account User"] }));
  betaApps.forEach((a: any) => put({ email: a.email, full_name: a.name, phone: a.phone, beta_status: a.status, tester_type: a.tester_type, betaApplicationId: a.id, created_at: a.created_at, badges: ["Beta Applicant"] }));
  launchRows.forEach((l: any) => put({ email: l.email, full_name: l.full_name, phone: l.phone, usually_go_out_area: l.usually_go_out_area, social_handle: l.social_handle, beta_status: l.beta_application_status, giveaway_status: l.giveaway_status, launchSignupId: l.id, created_at: l.created_at, badges: ["Launch List", l.wants_giveaway && l.giveaway_status === "verified" ? "Giveaway Eligible" : l.giveaway_status === "pending_beta_tasks" || l.weekly_task_eligibility_status === "pending_beta_tasks" ? "Pending Weekly Tasks" : l.wants_giveaway ? "Giveaway Pending" : null, !l.email_verified ? "Email Unverified" : null].filter(Boolean) }));
  betaRows.forEach((b: any) => { const auth = (b.user_id && authById.get(b.user_id)) || authByEmail.get(emailKey(b.email)); put({ id: b.user_id || auth?.id || undefined, email: b.email || auth?.email, full_name: b.name, phone: b.phone, beta_status: b.status, betaTesterId: b.id, betaTester: b, isBetaUser: true, hasAccount: Boolean(b.user_id || auth?.id), created_at: b.created_at, badges: ["Beta Tester"] }); });

  const ids = Array.from(new Set(Array.from(merged.values()).map((u: any) => u.id).filter(Boolean)));
  const emails = Array.from(new Set(Array.from(merged.values()).map((u: any) => emailKey(u.email)).filter(Boolean)));
  const [admins, saved, booked, ticketsByUser, ticketsByEmail, subs] = await Promise.all([
    safe(async () => ids.length ? (await supabaseAdmin.from("admin_users").select("user_id,role").in("user_id", ids)).data || [] : [], [] as any[]),
    countBy("saved_plans", ids), countBy("user_outings", ids),
    countBy("support_tickets", ids, "user_id", (q: any) => q.not("status", "in", `(${openStatuses.join(",")})`)), countByEmails(emails),
    safe(async () => ids.length ? (await supabaseAdmin.from("customer_subscriptions").select("user_id,plan_key,status").in("user_id", ids).eq("status", "active")).data || [] : [], [] as any[]),
  ]);
  let users = Array.from(merged.values()).map((u: any) => decorate(u, { admins, saved, booked, ticketsByUser, ticketsByEmail, subs, authById })).filter((u: any) => filterDecorated(u, filters));
  users = users.sort((a: any, b: any) => String(b.created_at || "").localeCompare(String(a.created_at || "")));
  const from = (page - 1) * per; return { users: users.slice(from, from + per), count: users.length, page, per, hasMore: users.length > from + per };
}
function filterDecorated(u: any, f: any) { const q = emailKey(f.q); if (q && ![u.full_name, u.preferred_name, u.email, u.phone, u.mobile_number, u.zip_code, u.social_handle].some((v) => String(v || "").toLowerCase().includes(q))) return false; if (f.beta && f.beta !== "all" && String(u.beta_status || (u.isBetaUser ? "active" : "none")) !== f.beta) return false; if (f.plan && f.plan !== "all" && u.plan !== f.plan) return false; if (f.email && f.email !== "all" && (f.email === "verified") !== Boolean(u.email_confirmed_at || u.email_verified)) return false; if (f.status && f.status !== "all" && !String(u.account_status).toLowerCase().includes(f.status)) return false; if (f.giveaway && f.giveaway !== "all" && u.giveaway_status !== f.giveaway) return false; if (f.tickets === "yes" && u.open_tickets_count < 1) return false; if (f.booked === "yes" && u.booked_outings_count < 1) return false; if (f.role && f.role !== "all" && String(u.role).toLowerCase() !== f.role) return false; return true; }
function decorate(u: any, x: any) { const admin = x.admins.find((a: any) => a.user_id === u.id); const sub = x.subs.find((a: any) => a.user_id === u.id); const auth = u.id ? x.authById.get(u.id) : null; const hasAccount = Boolean(u.hasAccount || u.id); const emailConfirmed = u.email_confirmed_at || auth?.email_confirmed_at; const disabled = u.account_status === "disabled" || u.deleted_at || u.disabled_at || admin?.role === "disabled" || u.role === "disabled"; return { ...u, userId: u.id || null, rowKey: u.id || u.betaTesterId || u.betaApplicationId || u.launchSignupId || u.email, role: admin?.role || u.role || (u.isBetaUser ? "user" : "user"), plan: sub?.plan_key || u.plan || (hasAccount ? "free" : "Pending"), isBetaUser: Boolean(u.isBetaUser || u.betaTesterId), saved_outings_count: u.id ? x.saved[u.id] || 0 : 0, booked_outings_count: u.id ? x.booked[u.id] || 0 : 0, open_tickets_count: (u.id ? x.ticketsByUser[u.id] || 0 : 0) + (x.ticketsByEmail[emailKey(u.email)] || 0), hasAccount, account_status: disabled ? "disabled" : hasAccount ? (emailConfirmed ? "active" : "email_unverified") : "pending_account", detailHref: u.id ? `/admin/dashboard/users/${u.id}` : `/admin/dashboard/users/${u.betaTesterId || u.betaApplicationId || u.launchSignupId}?type=lead` }; }
async function countBy(table: string, ids: string[], col = "user_id", mut?: (q: any) => any) { if (!ids.length) return {}; return safe(async () => { let q = supabaseAdmin.from(table).select(col).in(col, ids); if (mut) q = mut(q); const { data } = await q; return (data || []).reduce((a: any, r: any) => (a[r[col]] = (a[r[col]] || 0) + 1, a), {}); }, {} as Record<string, number>); }
async function countByEmails(emails: string[]) { if (!emails.length) return {}; return safe(async () => { const { data } = await supabaseAdmin.from("support_tickets").select("requester_email,email,status").not("status", "in", `(${openStatuses.join(",")})`); return (data || []).reduce((a: any, r: any) => { const e = emailKey(r.requester_email || r.email); if (emails.includes(e)) a[e] = (a[e] || 0) + 1; return a; }, {}); }, {} as Record<string, number>); }
export async function getAdminUserDetail(userId: string) { await requireAdminOrSupport(); const { data: profile } = await supabaseAdmin.from("user_profiles").select("*").eq("id", userId).maybeSingle(); const auth = uuidRe.test(userId) ? await safe(async () => (await supabaseAdmin.auth.admin.getUserById(userId)).data.user, null as any) : null; let beta = await safe(async () => { const clause = `user_id.eq.${userId}${profile?.email || auth?.email ? `,email.eq.${profile?.email || auth?.email}` : ""}`; const { data } = await supabaseAdmin.from("beta_testers").select("*").or(clause).maybeSingle(); return data; }, null as any); if (!profile && !auth && !beta) beta = await safe(async () => (await supabaseAdmin.from("beta_testers").select("*").eq("id", userId).maybeSingle()).data, null as any); const id = profile?.id || auth?.id || beta?.user_id || null; const email = profile?.email || auth?.email || beta?.email || null; const [admin, saved, booked, res, tickets, usage, sub, assignments, feedback, bugs] = await Promise.all([safe(async () => id ? (await supabaseAdmin.from("admin_users").select("role").eq("user_id", id).maybeSingle()).data : null, null as any), id ? listRows("saved_plans", id) : Promise.resolve([]), id ? listRows("user_outings", id) : Promise.resolve([]), id ? listRows("location_reservations", id) : Promise.resolve([]), listTickets(id || userId, email), id ? listRows("search_usage_events", id, "auth_user_id") : Promise.resolve([]), safe(async () => id ? (await supabaseAdmin.from("customer_subscriptions").select("*").eq("user_id", id).order("created_at", { ascending: false }).limit(1).maybeSingle()).data : null, null as any), beta?.id ? listRows("beta_task_assignments", beta.id, "tester_id") : Promise.resolve([]), beta?.id ? listRows("beta_feedback", beta.id, "tester_id") : Promise.resolve([]), beta?.id ? listRows("beta_bug_reports", beta.id, "tester_id") : Promise.resolve([])]); const hasAccount = Boolean(id); return { profile: { ...(profile || {}), id: id || beta?.id || userId, email, full_name: profile?.full_name || beta?.name || auth?.user_metadata?.full_name, phone: profile?.phone || beta?.phone, role: admin?.role || profile?.role || "user", plan: sub?.plan_key || profile?.plan || (hasAccount ? "free" : "Pending"), email_confirmed_at: auth?.email_confirmed_at, created_at: profile?.created_at || auth?.created_at || beta?.created_at, account_status: profile?.account_status || (profile?.deleted_at || profile?.disabled_at || admin?.role === "disabled" ? "disabled" : hasAccount ? (auth?.email_confirmed_at ? "active" : "email_unverified") : "pending_account"), hasAccount }, beta, saved, booked, reservations: res, tickets, usage, subscription: sub, betaAssignments: assignments, betaFeedback: feedback, betaBugReports: bugs }; }
async function listRows(table: string, userId: string, col = "user_id") { return safe(async () => { const { data } = await supabaseAdmin.from(table).select("*").eq(col, userId).order("created_at", { ascending: false }).limit(50); return data || []; }, [] as any[]); }
export async function listTickets(userId: string, email?: string | null) { return safe(async () => { const { data } = await supabaseAdmin.from("support_tickets").select("*").or(`user_id.eq.${userId}${email ? `,requester_email.eq.${email},email.eq.${email}` : ""}`).order("updated_at", { ascending: false }).limit(50); return data || []; }, [] as any[]); }
export async function updateAdminUserProfile(userId: string, input: any, actor?: any, request?: Request) { const before = (await supabaseAdmin.from("user_profiles").select("*").eq("id", userId).maybeSingle()).data || {}; const row: any = { updated_at: new Date().toISOString() }; for (const k of ["full_name", "preferred_name", "phone", "mobile_number", "zip_code", "sms_opt_in", "birthday_opt_in"]) if (k in input) row[k] = typeof input[k] === "string" ? input[k].trim() || null : input[k]; if ("age_range" in input) { if (input.age_range && !(AGE_RANGE_OPTIONS as readonly string[]).includes(input.age_range)) throw new Error("Invalid age range"); row.age_range = input.age_range || null; } if ("birthday" in input) { const m = String(input.birthday || "").trim().match(/^(\d{1,2})[-/](\d{1,2})$/); if (input.birthday && !m) throw new Error("Birthday must use MM-DD format"); if (m) { const month = Number(m[1]), day = Number(m[2]); const dt = new Date(2024, month - 1, day); if (dt.getMonth() !== month - 1 || dt.getDate() !== day) throw new Error("Invalid birthday"); row.birthday_month = month; row.birthday_day = day; } else { row.birthday_month = null; row.birthday_day = null; } } const { data, error } = await supabaseAdmin.from("user_profiles").upsert({ id: userId, ...row }, { onConflict: "id" }).select("*").single(); if (error) throw error; await logAdminAuditEvent({ actor, targetUserId: userId, targetEmail: data.email || before.email, action: "user_updated", entityType: "user_profile", summary: "User profile updated", beforeData: before, afterData: data, request }); return data; }
export async function updateUserRole(userId: string, role: UserRole, actor: any, request?: Request) { if (!(USER_ROLES as readonly string[]).includes(role)) throw new Error("Invalid role"); const before = (await supabaseAdmin.from("admin_users").select("*").eq("user_id", userId).maybeSingle()).data; if (userId === actor?.user_id && role !== "superadmin") { const { count } = await supabaseAdmin.from("admin_users").select("user_id", { count: "exact", head: true }).eq("role", "superadmin"); if ((count || 0) <= 1) throw new Error("You cannot remove the last superadmin."); } const auth = await safe(async () => (await supabaseAdmin.auth.admin.getUserById(userId)).data.user, null as any); const payload = { user_id: userId, email: auth?.email || before?.email || null, role }; const { data, error } = await supabaseAdmin.from("admin_users").upsert(payload, { onConflict: "user_id" }).select("*").single(); if (error) throw error; await logAdminAuditEvent({ actor, targetUserId: userId, targetEmail: payload.email, action: "user_role_changed", entityType: "admin_user", summary: `Role changed from ${before?.role || "user"} to ${role}`, beforeData: before, afterData: data, request }); return data; }
export async function updateUserPlan(userId: string, plan: string, actor: any, request?: Request) { if (!(PLAN_OPTIONS as readonly string[]).includes(plan)) throw new Error("Invalid plan"); const before = (await supabaseAdmin.from("customer_subscriptions").select("*").eq("user_id", userId).eq("status", "active").order("created_at", { ascending: false }).limit(1).maybeSingle()).data; const payload = { user_id: userId, plan_key: plan, status: "active", provider: "admin", updated_at: new Date().toISOString() }; const { data, error } = before?.id ? await supabaseAdmin.from("customer_subscriptions").update(payload).eq("id", before.id).select("*").single() : await supabaseAdmin.from("customer_subscriptions").insert(payload).select("*").single(); if (error) throw error; await logAdminAuditEvent({ actor, targetUserId: userId, action: "user_plan_changed", entityType: "customer_subscription", entityId: data.id, summary: `Plan changed from ${before?.plan_key || "free"} to ${plan}`, beforeData: before, afterData: data, request }); return data; }
export async function disableAdminUser(userId: string, reason: string, actor: any, request?: Request) { const before = await getAdminUserDetail(userId); const now = new Date().toISOString(); await supabaseAdmin.from("user_profiles").upsert({ id: userId, account_status: "disabled", disabled_at: now, disabled_by: actor.user_id, deleted_at: now, deleted_by: actor.user_id, updated_at: now }, { onConflict: "id" }); await updateUserRole(userId, "disabled", actor, request); await logAdminAuditEvent({ actor, targetUserId: userId, targetEmail: before.profile.email, action: "user_deleted_or_disabled", entityType: "user", summary: `User disabled${reason ? `: ${reason}` : ""}`, beforeData: before.profile, afterData: { account_status: "disabled", reason }, request }); }
export async function sendUserPasswordReset(email: string) { const authClient = createSupabaseClient(requireSupabaseUrl(), requirePublicEnv("NEXT_PUBLIC_SUPABASE_ANON_KEY"), { auth: { persistSession: false, autoRefreshToken: false } }); const redirectTo = `${getSiteUrl().replace(/\/$/, "")}/reset-password`; const { error } = await authClient.auth.resetPasswordForEmail(email, { redirectTo }); if (error) throw error; }
