import { normalizeMarketInput, type MarketKey } from "./location-markets";
export type { MarketKey } from "./location-markets";

export type ParsedPlaceLocation = {
  formattedAddress?: string | null; address?: string | null; city?: string | null; state?: string | null; county?: string | null; borough?: string | null; neighborhood?: string | null; postalCode?: string | null; latitude?: number | null; longitude?: number | null; query?: string | null; requestedArea?: string | null; requestedMarket?: MarketKey | string | null; addressComponents?: GoogleAddressComponent[] | null;
};
export type MarketValidationResult = { ok: boolean; requestedMarket: MarketKey; inferredMarket: MarketKey; correctedMarket?: MarketKey; reason?: string; city?: string | null; state?: string | null; county?: string | null; borough?: string | null; neighborhood?: string | null };
type GoogleAddressComponent = { long_name?: string; short_name?: string; types?: string[] };

const STATE_NAMES: Record<string,string> = { "new york":"NY", ny:"NY", "new jersey":"NJ", nj:"NJ", delaware:"DE", de:"DE", california:"CA", ca:"CA", ohio:"OH", oh:"OH", pennsylvania:"PA", pa:"PA", connecticut:"CT", ct:"CT" };
const LI_COUNTIES = ["Nassau", "Suffolk"];
const LI_CITIES = ["Garden City","Mineola","Westbury","Great Neck","Roslyn","Manhasset","Rockville Centre","Rockville Center","Freeport","Hempstead","Uniondale","Long Beach","Valley Stream","Huntington","Farmingdale","Babylon","Bay Shore","Deer Park","Melville","Commack","Patchogue","Smithtown","Nassau County","Suffolk County"];
const NJ_CITIES = ["Jersey City","Hoboken","Edgewater","Fort Lee","Englewood","Teaneck","Hackensack","Montclair","Newark","Elizabeth","Union","West Orange","Paramus","Clifton"];
const NJ_COUNTIES = ["Hudson","Bergen","Essex","Union","Passaic"];
const WESTCHESTER_CITIES = ["Yonkers","New Rochelle","White Plains","Mount Vernon","Bronxville","Tarrytown"];
const SI_TERMS = ["Staten Island","St. George","Saint George","Stapleton","New Dorp","Tottenville"];
const BRONX_TERMS = ["Bronx","The Bronx","City Island","Fordham","Mott Haven","Riverdale","Pelham Bay","Throgs Neck"];
const NYC_BOROUGHS = ["Manhattan","Brooklyn","Queens"];

function title(value: string) { return value.toLowerCase().split(/\s+/).filter(Boolean).map((p) => p.charAt(0).toUpperCase()+p.slice(1)).join(" "); }
function clean(value: string | null | undefined) { return String(value ?? "").trim().replace(/\s+/g, " ") || null; }
function norm(value: unknown) { return String(value ?? "").toLowerCase().replace(/[’']/g, "").replace(/[^a-z0-9]+/g, " ").trim().replace(/\s+/g, " "); }
function hasAny(input: ParsedPlaceLocation, terms: string[]) { const h = norm([input.query,input.formattedAddress,input.address,input.city,input.county,input.borough,input.neighborhood,input.requestedArea].filter(Boolean).join(" ")); return terms.some((t) => new RegExp(`(^|\\s)${norm(t).replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}(\\s|$)`).test(h)); }
export function normalizeState(value: string | null | undefined): string | null { const v = clean(value); if (!v) return null; return STATE_NAMES[norm(v)] || (v.length === 2 ? v.toUpperCase() : v); }
export function normalizeCity(value: string | null | undefined): string | null { const v = clean(value); if (!v) return null; return norm(v)==="long island city" ? "Long Island City" : title(v); }
export function normalizeCounty(value: string | null | undefined): string | null { const v = clean(value)?.replace(/\s+county$/i, ""); return v ? title(v) : null; }
export function normalizeBorough(value: string | null | undefined): string | null { const v = clean(value); if (!v) return null; const n = norm(v); if (n.includes("queens")) return "Queens"; if (n.includes("brooklyn")) return "Brooklyn"; if (n.includes("manhattan")) return "Manhattan"; if (n.includes("bronx")) return "Bronx"; if (n.includes("staten island")) return "Staten Island"; return title(v); }

export function parseGoogleAddressComponents(addressComponents?: GoogleAddressComponent[] | null): ParsedPlaceLocation { const out: ParsedPlaceLocation = {}; for (const c of addressComponents || []) { const types = c.types || []; if (types.includes("administrative_area_level_1")) out.state = normalizeState(c.short_name || c.long_name); if (types.includes("locality")) out.city = normalizeCity(c.long_name); if (types.includes("administrative_area_level_2")) out.county = normalizeCounty(c.long_name); if (types.includes("sublocality") || types.includes("sublocality_level_1")) out.borough = normalizeBorough(c.long_name); if (types.includes("neighborhood")) out.neighborhood = normalizeCity(c.long_name); if (types.includes("postal_code")) out.postalCode = c.long_name || c.short_name; } return out; }
export function parseFormattedAddress(formattedAddress: string): Partial<ParsedPlaceLocation> { const cleaned = clean(formattedAddress)?.replace(/,\s*(USA|United States)$/i, "") || ""; const parts = cleaned.split(",").map(p=>p.trim()).filter(Boolean); const tail = parts.at(-1) || cleaned; const m = tail.match(/\b([A-Z]{2}|New York|New Jersey|Delaware|California|Ohio|Pennsylvania|Connecticut)\b\s*(\d{5})?\b/i); const cityFromComma = parts.length>=2 ? parts.at(-2) : null; const cityFromSimple = !cityFromComma && m ? cleaned.slice(0, m.index).replace(/[,\s]+$/g, "") : null; return { formattedAddress, address: cleaned, city: normalizeCity(cityFromComma || cityFromSimple), state: normalizeState(m?.[1]), postalCode: m?.[2] || null }; }
function merge(input: ParsedPlaceLocation): ParsedPlaceLocation { return { ...parseFormattedAddress(input.formattedAddress || input.address || ""), ...parseGoogleAddressComponents(input.addressComponents), ...input, state: normalizeState(input.state) ?? parseGoogleAddressComponents(input.addressComponents).state ?? parseFormattedAddress(input.formattedAddress || input.address || "").state ?? null, city: normalizeCity(input.city) ?? parseGoogleAddressComponents(input.addressComponents).city ?? parseFormattedAddress(input.formattedAddress || input.address || "").city ?? null, county: normalizeCounty(input.county) ?? parseGoogleAddressComponents(input.addressComponents).county ?? null, borough: normalizeBorough(input.borough) ?? parseGoogleAddressComponents(input.addressComponents).borough ?? null }; }
export function getExpectedStateForMarket(market: MarketKey): string[] | null { if (market === "NORTHERN_NJ") return ["NJ"]; if (["LONG_ISLAND","WESTCHESTER","STATEN_ISLAND","BRONX_OUTER","NYC_CORE"].includes(market)) return ["NY"]; if (market === "OUTER_NYC") return ["NY","NJ"]; return null; }
export function getApprovedCitiesForMarket(market: MarketKey): string[] { if (market === "LONG_ISLAND") return LI_CITIES; if (market === "NORTHERN_NJ") return NJ_CITIES; if (market === "WESTCHESTER") return WESTCHESTER_CITIES; return []; }
export function getApprovedCountiesForMarket(market: MarketKey): string[] { if (market === "LONG_ISLAND") return LI_COUNTIES; if (market === "NORTHERN_NJ") return NJ_COUNTIES; if (market === "WESTCHESTER") return ["Westchester"]; return []; }
export function isLongIslandCity(input: ParsedPlaceLocation): boolean { return hasAny(input, ["Long Island City", "LIC"]); }
export function inferMarketFromPlace(raw: ParsedPlaceLocation): MarketKey { const input = merge(raw); if (isLongIslandCity(input)) return "NYC_CORE"; const state = normalizeState(input.state); const city = normalizeCity(input.city); const county = normalizeCounty(input.county); const borough = normalizeBorough(input.borough); if (state === "NJ" && (NJ_COUNTIES.includes(county || "") || NJ_CITIES.includes(city || "") || hasAny(input, NJ_CITIES))) return "NORTHERN_NJ"; if (state === "NY" && (LI_COUNTIES.includes(county || "") || LI_CITIES.includes(city || "") || hasAny(input, LI_CITIES))) return "LONG_ISLAND"; if (state === "NY" && (county === "Westchester" || WESTCHESTER_CITIES.includes(city || "") || hasAny(input, WESTCHESTER_CITIES))) return "WESTCHESTER"; if (state === "NY" && (borough === "Staten Island" || hasAny(input, SI_TERMS))) return "STATEN_ISLAND"; if (state === "NY" && (borough === "Bronx" || hasAny(input, BRONX_TERMS))) return "BRONX_OUTER"; if (state === "NY" && (NYC_BOROUGHS.includes(borough || "") || city === "New York")) return "NYC_CORE"; return "UNKNOWN"; }
export function isMarketStateMismatch(input: ParsedPlaceLocation): boolean { const market = (normalizeMarketInput(String(input.requestedMarket || "")) || inferMarketFromPlace(input)) as MarketKey; const expected = getExpectedStateForMarket(market); const state = normalizeState(input.state) ?? merge(input).state; return Boolean(expected?.length && state && !expected.includes(state)); }
export function getMarketMismatchReason(input: ParsedPlaceLocation): string | null { return validatePlaceForMarket(input).reason || null; }
export function validatePlaceForMarket(raw: ParsedPlaceLocation): MarketValidationResult { const input = merge(raw); if (isLongIslandCity(input)) { input.state = "NY"; input.city = "New York"; input.borough = "Queens"; input.neighborhood = "Long Island City"; } const requestedMarket = (normalizeMarketInput(String(raw.requestedMarket || raw.requestedArea || "")) || "UNKNOWN") as MarketKey; const inferredMarket = inferMarketFromPlace(input); const expected = getExpectedStateForMarket(requestedMarket); const state = normalizeState(input.state); const base = { requestedMarket, inferredMarket, correctedMarket: inferredMarket !== "UNKNOWN" ? inferredMarket : undefined, city: input.city, state, county: input.county, borough: input.borough, neighborhood: input.neighborhood };
  if (expected?.length && state && !expected.includes(state)) return { ok: false, ...base, reason: `${requestedMarket} requires state ${expected.join(" or ")}` };
  if (requestedMarket === "UNKNOWN") return { ok: false, ...base, reason: "UNKNOWN market cannot be auto-marked searchable" };
  if (requestedMarket === "LONG_ISLAND" && isLongIslandCity(input)) return { ok: false, ...base, inferredMarket: "NYC_CORE", correctedMarket: "NYC_CORE", reason: "Long Island City is Queens / NYC Core" };
  const cityOk = getApprovedCitiesForMarket(requestedMarket).includes(input.city || "") || getApprovedCountiesForMarket(requestedMarket).includes(input.county || "");
  if (["LONG_ISLAND","NORTHERN_NJ","WESTCHESTER"].includes(requestedMarket) && (input.city || input.county) && !cityOk) return { ok: false, ...base, reason: `Outside approved ${requestedMarket} city/county` };
  if (requestedMarket === "STATEN_ISLAND" && !(input.borough === "Staten Island" || hasAny(input, SI_TERMS))) return { ok: false, ...base, reason: "Outside approved Staten Island area" };
  if (requestedMarket === "BRONX_OUTER" && !(input.borough === "Bronx" || hasAny(input, BRONX_TERMS))) return { ok: false, ...base, reason: "Outside approved Bronx area" };
  if (requestedMarket === "NYC_CORE" && !(NYC_BOROUGHS.includes(input.borough || "") || input.city === "New York" || inferredMarket === "NYC_CORE")) return { ok: false, ...base, reason: "Outside approved NYC Core area" };
  if (inferredMarket !== "UNKNOWN" && inferredMarket !== requestedMarket && requestedMarket !== "OUTER_NYC") return { ok: false, ...base, reason: `Inferred market ${inferredMarket} does not match requested ${requestedMarket}` };
  return { ok: true, ...base };
}
export const MARKET_VALIDATION_REPORT_SQL = `select market, state, count(*) as rows, count(*) filter (where is_searchable = true) as searchable_rows from public.locations where market in ('NORTHERN_NJ', 'LONG_ISLAND', 'WESTCHESTER', 'STATEN_ISLAND', 'BRONX_OUTER', 'NYC_CORE') group by market, state order by market, state;`;
