create extension if not exists pgcrypto;

create table if not exists public.fraud_subjects (
  id uuid primary key default gen_random_uuid(),
  subject_type text not null check (subject_type in ('user','location','claim','organizer','event','experience','reservation','order','payment','payout','review','other')),
  subject_id text not null,
  display_label text,
  risk_score integer not null default 0 check (risk_score between 0 and 100),
  risk_band text not null default 'low' check (risk_band in ('low','guarded','elevated','high','critical')),
  enforcement_state text not null default 'none' check (enforcement_state in ('none','limited','suspended','banned')),
  active_case_id uuid,
  first_seen_at timestamptz not null default now(),
  last_signal_at timestamptz,
  last_reviewed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(subject_type, subject_id)
);

create table if not exists public.fraud_rules (
  id uuid primary key default gen_random_uuid(),
  rule_key text not null unique,
  name text not null,
  subject_type text,
  category text not null,
  description text not null,
  default_score integer not null check (default_score between 0 and 100),
  severity smallint not null check (severity between 1 and 5),
  enabled boolean not null default true,
  auto_case boolean not null default true,
  configuration jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fraud_signals (
  id uuid primary key default gen_random_uuid(),
  subject_type text not null,
  subject_id text not null,
  related_subject_type text,
  related_subject_id text,
  rule_key text references public.fraud_rules(rule_key) on update cascade on delete set null,
  signal_type text not null,
  category text not null,
  source text not null,
  severity smallint not null default 2 check (severity between 1 and 5),
  score_delta integer not null default 10 check (score_delta between -100 and 100),
  confidence numeric(4,3) not null default 1.000 check (confidence between 0 and 1),
  evidence jsonb not null default '{}'::jsonb,
  dedupe_key text,
  observed_at timestamptz not null default now(),
  expires_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index if not exists fraud_signals_dedupe_idx on public.fraud_signals(dedupe_key) where dedupe_key is not null;
create index if not exists fraud_signals_subject_idx on public.fraud_signals(subject_type, subject_id, observed_at desc);
create index if not exists fraud_signals_category_idx on public.fraud_signals(category, observed_at desc);

create table if not exists public.fraud_cases (
  id uuid primary key default gen_random_uuid(),
  case_number bigint generated by default as identity unique,
  primary_subject_type text not null,
  primary_subject_id text not null,
  title text not null,
  summary text,
  status text not null default 'open' check (status in ('open','investigating','awaiting_evidence','actioned','appealed','closed')),
  priority text not null default 'medium' check (priority in ('low','medium','high','urgent')),
  risk_score integer not null default 0 check (risk_score between 0 and 100),
  assigned_to uuid,
  resolution text,
  resolution_notes text,
  opened_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now(),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.fraud_subjects drop constraint if exists fraud_subjects_active_case_id_fkey;
alter table public.fraud_subjects add constraint fraud_subjects_active_case_id_fkey foreign key (active_case_id) references public.fraud_cases(id) on delete set null;
create index if not exists fraud_cases_queue_idx on public.fraud_cases(status, priority, last_activity_at desc);
create index if not exists fraud_cases_subject_idx on public.fraud_cases(primary_subject_type, primary_subject_id);

create table if not exists public.fraud_case_subjects (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.fraud_cases(id) on delete cascade,
  subject_type text not null,
  subject_id text not null,
  relationship text not null default 'related',
  created_at timestamptz not null default now(),
  unique(case_id, subject_type, subject_id)
);

create table if not exists public.fraud_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_user_id uuid,
  reporter_email text,
  reporter_fingerprint text,
  subject_type text not null,
  subject_id text not null,
  reason text not null,
  details text,
  evidence jsonb not null default '{}'::jsonb,
  status text not null default 'new' check (status in ('new','triaged','linked','dismissed','resolved')),
  case_id uuid references public.fraud_cases(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists fraud_reports_queue_idx on public.fraud_reports(status, created_at desc);
create index if not exists fraud_reports_subject_idx on public.fraud_reports(subject_type, subject_id);
create index if not exists fraud_reports_fingerprint_idx on public.fraud_reports(reporter_fingerprint, created_at desc);

create table if not exists public.fraud_actions (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.fraud_cases(id) on delete cascade,
  subject_type text not null,
  subject_id text not null,
  action_type text not null check (action_type in ('monitor','require_verification','hold_publication','remove_content','limit_account','hold_payout','suspend','ban','clear','restore')),
  reason text not null,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  actor_user_id uuid,
  actor_role text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists fraud_actions_case_idx on public.fraud_actions(case_id, created_at desc);
create index if not exists fraud_actions_subject_idx on public.fraud_actions(subject_type, subject_id, created_at desc);

create table if not exists public.fraud_case_notes (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.fraud_cases(id) on delete cascade,
  note text not null,
  visibility text not null default 'internal' check (visibility in ('internal','appeal_visible')),
  actor_user_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.fraud_appeals (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.fraud_cases(id) on delete cascade,
  appellant_user_id uuid,
  subject_type text not null,
  subject_id text not null,
  statement text not null,
  evidence jsonb not null default '{}'::jsonb,
  status text not null default 'submitted' check (status in ('submitted','under_review','granted','denied','withdrawn')),
  reviewed_by uuid,
  reviewed_at timestamptz,
  decision_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists fraud_appeals_status_idx on public.fraud_appeals(status, created_at desc);

create table if not exists public.fraud_identity_links (
  id uuid primary key default gen_random_uuid(),
  identity_type text not null check (identity_type in ('email_hash','phone_hash','device_hash','ip_hash','payment_fingerprint','bank_fingerprint','domain_hash','other')),
  identity_hash text not null,
  subject_type text not null,
  subject_id text not null,
  source text not null,
  confidence numeric(4,3) not null default 1.000 check (confidence between 0 and 1),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique(identity_type, identity_hash, subject_type, subject_id)
);
create index if not exists fraud_identity_lookup_idx on public.fraud_identity_links(identity_type, identity_hash);
create index if not exists fraud_identity_subject_idx on public.fraud_identity_links(subject_type, subject_id);

create table if not exists public.fraud_audit_log (
  id bigint generated by default as identity primary key,
  case_id uuid,
  subject_type text,
  subject_id text,
  event_type text not null,
  actor_user_id uuid,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists fraud_audit_case_idx on public.fraud_audit_log(case_id, created_at desc);
create index if not exists fraud_audit_subject_idx on public.fraud_audit_log(subject_type, subject_id, created_at desc);

create table if not exists public.fraud_detection_runs (
  id uuid primary key default gen_random_uuid(),
  run_type text not null,
  status text not null default 'running' check (status in ('running','succeeded','failed')),
  source text not null default 'edge_function',
  metrics jsonb not null default '{}'::jsonb,
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists fraud_detection_runs_recent_idx on public.fraud_detection_runs(started_at desc);

create or replace function public.fraud_risk_band(score integer)
returns text
language sql
immutable
security invoker
set search_path = public, pg_temp
as $$
  select case
    when score >= 85 then 'critical'
    when score >= 65 then 'high'
    when score >= 40 then 'elevated'
    when score >= 20 then 'guarded'
    else 'low'
  end;
$$;

create or replace function public.fraud_recalculate_subject(p_subject_type text, p_subject_id text)
returns public.fraud_subjects
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_score integer;
  v_subject public.fraud_subjects;
begin
  select greatest(0, least(100, coalesce(round(sum(score_delta * confidence))::integer, 0)))
  into v_score
  from public.fraud_signals
  where subject_type = p_subject_type
    and subject_id = p_subject_id
    and (expires_at is null or expires_at > now());

  insert into public.fraud_subjects(subject_type, subject_id, risk_score, risk_band, last_signal_at)
  values (p_subject_type, p_subject_id, v_score, public.fraud_risk_band(v_score), now())
  on conflict (subject_type, subject_id) do update set
    risk_score = excluded.risk_score,
    risk_band = excluded.risk_band,
    last_signal_at = excluded.last_signal_at,
    updated_at = now()
  returning * into v_subject;
  return v_subject;
end;
$$;

create or replace function public.fraud_ensure_case(p_subject_type text, p_subject_id text, p_reason text default null)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_subject public.fraud_subjects;
  v_case_id uuid;
  v_priority text;
begin
  select * into v_subject from public.fraud_subjects
  where subject_type = p_subject_type and subject_id = p_subject_id;

  if v_subject.id is null then
    v_subject := public.fraud_recalculate_subject(p_subject_type, p_subject_id);
  end if;

  if v_subject.active_case_id is not null then
    update public.fraud_cases
    set risk_score = v_subject.risk_score, last_activity_at = now(), updated_at = now()
    where id = v_subject.active_case_id and status <> 'closed';
    if found then return v_subject.active_case_id; end if;
  end if;

  v_priority := case
    when v_subject.risk_score >= 85 then 'urgent'
    when v_subject.risk_score >= 65 then 'high'
    when v_subject.risk_score >= 40 then 'medium'
    else 'low'
  end;

  insert into public.fraud_cases(primary_subject_type, primary_subject_id, title, summary, priority, risk_score)
  values (
    p_subject_type,
    p_subject_id,
    initcap(p_subject_type) || ' fraud review · ' || p_subject_id,
    coalesce(p_reason, 'Automatically opened from fraud risk signals.'),
    v_priority,
    v_subject.risk_score
  ) returning id into v_case_id;

  insert into public.fraud_case_subjects(case_id, subject_type, subject_id, relationship)
  values (v_case_id, p_subject_type, p_subject_id, 'primary')
  on conflict do nothing;

  update public.fraud_subjects set active_case_id = v_case_id, updated_at = now()
  where subject_type = p_subject_type and subject_id = p_subject_id;

  insert into public.fraud_audit_log(case_id, subject_type, subject_id, event_type, payload)
  values (v_case_id, p_subject_type, p_subject_id, 'case_opened', jsonb_build_object('reason', p_reason, 'risk_score', v_subject.risk_score));
  return v_case_id;
end;
$$;

create or replace function public.fraud_after_signal()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_subject public.fraud_subjects;
  v_auto_case boolean;
begin
  v_subject := public.fraud_recalculate_subject(new.subject_type, new.subject_id);
  select coalesce(auto_case, true) into v_auto_case from public.fraud_rules where rule_key = new.rule_key;
  if v_auto_case is null then v_auto_case := true; end if;

  if v_auto_case and (v_subject.risk_score >= 40 or new.severity >= 4) then
    perform public.fraud_ensure_case(new.subject_type, new.subject_id, 'Opened automatically after ' || new.signal_type || ' signal.');
  end if;

  insert into public.fraud_audit_log(subject_type, subject_id, event_type, payload)
  values (new.subject_type, new.subject_id, 'signal_recorded', jsonb_build_object('signal_id', new.id, 'signal_type', new.signal_type, 'score_delta', new.score_delta));
  return new;
end;
$$;

drop trigger if exists fraud_signal_risk_trigger on public.fraud_signals;
create trigger fraud_signal_risk_trigger
after insert or update of score_delta, confidence, expires_at on public.fraud_signals
for each row execute function public.fraud_after_signal();

create or replace function public.fraud_apply_action_state()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_state text;
begin
  v_state := case
    when new.action_type = 'ban' then 'banned'
    when new.action_type in ('suspend','hold_payout','remove_content') then 'suspended'
    when new.action_type in ('limit_account','hold_publication','require_verification') then 'limited'
    when new.action_type in ('clear','restore') then 'none'
    else null
  end;

  if v_state is not null then
    insert into public.fraud_subjects(subject_type, subject_id, enforcement_state)
    values (new.subject_type, new.subject_id, v_state)
    on conflict(subject_type, subject_id) do update set enforcement_state = excluded.enforcement_state, updated_at = now();
  end if;

  update public.fraud_cases
  set status = case when new.action_type in ('clear','restore') then 'closed' else 'actioned' end,
      last_activity_at = now(), updated_at = now()
  where id = new.case_id;

  insert into public.fraud_audit_log(case_id, subject_type, subject_id, event_type, actor_user_id, payload)
  values (new.case_id, new.subject_type, new.subject_id, 'enforcement_action', new.actor_user_id,
    jsonb_build_object('action_type', new.action_type, 'reason', new.reason, 'ends_at', new.ends_at));
  return new;
end;
$$;

drop trigger if exists fraud_action_state_trigger on public.fraud_actions;
create trigger fraud_action_state_trigger after insert on public.fraud_actions
for each row execute function public.fraud_apply_action_state();

insert into public.fraud_rules(rule_key,name,subject_type,category,description,default_score,severity,auto_case) values
('user_velocity','Abnormal account velocity','user','account_integrity','Rapid signup, login, report, reservation, or transaction behavior inconsistent with normal use.',25,3,true),
('user_identity_reuse','Identity reused across accounts','user','identity','A hashed phone, email, device, IP, or payment identity is linked to multiple accounts.',35,4,true),
('user_chargeback_pattern','Chargeback or payment abuse','user','payments','Repeated chargebacks, disputes, failed payment attempts, or payment method cycling.',55,5,true),
('location_ownership_mismatch','Location ownership mismatch','location','ownership','Claimant identity or evidence conflicts with known location ownership/contact data.',45,4,true),
('location_duplicate','Duplicate or impersonated location','location','content_integrity','Location appears duplicated, fabricated, or designed to impersonate another business.',45,4,true),
('location_contact_anomaly','Suspicious location contact change','location','account_takeover','High-risk changes to phone, email, domain, payout, or ownership details.',35,4,true),
('claim_takeover_attempt','Suspicious claim takeover','claim','ownership','Claim shows takeover indicators, repeated failed verification, or mismatched identity evidence.',60,5,true),
('event_content_deception','Deceptive event listing','event','content_integrity','Event identity, venue, date, ticketing, organizer, or description appears materially deceptive.',40,4,true),
('event_ticketing_abuse','Event ticketing/payment abuse','event','payments','Ticket pricing, payout routing, refunds, disputes, or sales behavior indicates elevated fraud risk.',55,5,true),
('experience_content_deception','Deceptive experience listing','experience','content_integrity','Experience identity, location, capacity, schedule, organizer, or fulfillment appears deceptive.',40,4,true),
('experience_booking_abuse','Experience booking/payment abuse','experience','payments','Booking, payout, refund, or fulfillment behavior indicates elevated fraud risk.',55,5,true),
('report_burst','Coordinated report burst',null,'abuse','A subject received an abnormal volume of independent reports in a short window.',30,3,true),
('linked_bad_actor','Linked to high-risk subject',null,'network','Identity graph links this subject to a suspended, banned, or critical-risk subject.',40,4,true)
on conflict(rule_key) do update set
  name=excluded.name,
  subject_type=excluded.subject_type,
  category=excluded.category,
  description=excluded.description,
  default_score=excluded.default_score,
  severity=excluded.severity,
  auto_case=excluded.auto_case,
  updated_at=now();

alter table public.fraud_subjects enable row level security;
alter table public.fraud_rules enable row level security;
alter table public.fraud_signals enable row level security;
alter table public.fraud_cases enable row level security;
alter table public.fraud_case_subjects enable row level security;
alter table public.fraud_reports enable row level security;
alter table public.fraud_actions enable row level security;
alter table public.fraud_case_notes enable row level security;
alter table public.fraud_appeals enable row level security;
alter table public.fraud_identity_links enable row level security;
alter table public.fraud_audit_log enable row level security;
alter table public.fraud_detection_runs enable row level security;

revoke all on public.fraud_subjects,public.fraud_rules,public.fraud_signals,public.fraud_cases,public.fraud_case_subjects,public.fraud_reports,public.fraud_actions,public.fraud_case_notes,public.fraud_appeals,public.fraud_identity_links,public.fraud_audit_log,public.fraud_detection_runs from anon,authenticated;
revoke execute on function public.fraud_risk_band(integer) from public,anon,authenticated;
revoke execute on function public.fraud_recalculate_subject(text,text) from public,anon,authenticated;
revoke execute on function public.fraud_ensure_case(text,text,text) from public,anon,authenticated;
revoke execute on function public.fraud_after_signal() from public,anon,authenticated;
revoke execute on function public.fraud_apply_action_state() from public,anon,authenticated;
grant execute on function public.fraud_risk_band(integer) to service_role;
grant execute on function public.fraud_recalculate_subject(text,text) to service_role;
grant execute on function public.fraud_ensure_case(text,text,text) to service_role;
