alter table public.locations add column if not exists stripe_customer_id text;
alter table public.locations add column if not exists stripe_subscription_id text;
alter table public.locations add column if not exists stripe_price_id text;
alter table public.locations add column if not exists subscription_plan text default 'free_discovery';
alter table public.locations add column if not exists subscription_status text default 'inactive';
alter table public.locations add column if not exists subscription_interval text;
alter table public.locations add column if not exists subscription_amount_cents integer;
alter table public.locations add column if not exists subscription_currency text default 'usd';
alter table public.locations add column if not exists current_period_start timestamptz;
alter table public.locations add column if not exists current_period_end timestamptz;
alter table public.locations add column if not exists next_billing_date timestamptz;
alter table public.locations add column if not exists trial_ends_at timestamptz;
alter table public.locations add column if not exists cancel_at_period_end boolean default false;
alter table public.locations add column if not exists canceled_at timestamptz;
alter table public.locations add column if not exists billing_grace_ends_at timestamptz;
alter table public.locations add column if not exists last_payment_succeeded_at timestamptz;
alter table public.locations add column if not exists last_payment_failed_at timestamptz;
alter table public.locations add column if not exists past_due_at timestamptz;
alter table public.locations add column if not exists billing_notes text;
create table if not exists public.payment_logs (id uuid primary key default gen_random_uuid(), provider text not null default 'stripe', event_type text not null, stripe_event_id text, stripe_customer_id text, stripe_subscription_id text, stripe_invoice_id text, location_id uuid null, amount_paid_cents integer, amount_due_cents integer, currency text, status text, payload jsonb, processed_at timestamptz, created_at timestamptz default now());
create unique index if not exists payment_logs_stripe_event_id_unique on public.payment_logs(stripe_event_id) where stripe_event_id is not null;
create index if not exists locations_stripe_customer_id_idx on public.locations(stripe_customer_id);
create index if not exists locations_stripe_subscription_id_idx on public.locations(stripe_subscription_id);
create index if not exists locations_subscription_plan_idx on public.locations(subscription_plan);
create index if not exists locations_subscription_status_idx on public.locations(subscription_status);
create index if not exists locations_next_billing_date_idx on public.locations(next_billing_date);
create index if not exists payment_logs_location_id_idx on public.payment_logs(location_id);
create index if not exists payment_logs_event_type_idx on public.payment_logs(event_type);
create index if not exists payment_logs_created_at_idx on public.payment_logs(created_at);
