-- Phase 3: commercial pipelines and forecasting. Additive and rerunnable.
create table if not exists public.crm_pipelines (
 id uuid primary key default gen_random_uuid(), pipeline_key text unique not null, name text not null, description text,
 entity_scope text, currency text not null default 'USD' check(currency ~ '^[A-Z]{3}$'), is_active boolean not null default true,
 display_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.crm_pipeline_stages (
 id uuid primary key default gen_random_uuid(), pipeline_id uuid not null references public.crm_pipelines(id) on delete restrict,
 stage_key text not null, name text not null, description text, display_order integer not null, default_probability integer check(default_probability between 0 and 100),
 stage_category text not null check(stage_category in ('open','won','lost','active','churned')), is_terminal boolean not null default false,
 is_success boolean not null default false, is_loss boolean not null default false, requires_amount boolean not null default false,
 requires_close_date boolean not null default false, requires_loss_reason boolean not null default false, requires_next_step boolean not null default false,
 requires_primary_contact boolean not null default false, requires_location boolean not null default false, max_days_in_stage integer check(max_days_in_stage is null or max_days_in_stage > 0),
 metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(pipeline_id,stage_key)
);
insert into public.crm_pipelines(pipeline_key,name,description,entity_scope,display_order) values
 ('business_claim','Business Claim','Location ownership claim conversion','location',10),('reserve_pro','Reserve Pro','Reserve Pro commercial sales','account_location',20),
 ('promoted_listing','Promoted Listing','Paid listing promotion','location',30),('partnership','Partnership','Strategic commercial partnerships','account',40),
 ('renewal_expansion','Renewal / Expansion','Retention and account growth','account',50)
on conflict(pipeline_key) do update set name=excluded.name,description=excluded.description,entity_scope=excluded.entity_scope,display_order=excluded.display_order;
with stages(pipeline_key,stage_key,name,ord,prob,category,terminal,success,loss,max_days) as (values
 ('business_claim','identified','Identified',10,5,'open',false,false,false,14),('business_claim','outreach_pending','Outreach pending',20,10,'open',false,false,false,7),('business_claim','contacted','Contacted',30,20,'open',false,false,false,14),('business_claim','engaged','Engaged',40,35,'open',false,false,false,14),('business_claim','claim_sent','Claim sent',50,50,'open',false,false,false,10),('business_claim','claim_started','Claim started',60,65,'open',false,false,false,10),('business_claim','claim_review','Claim review',70,85,'open',false,false,false,7),('business_claim','claimed','Claimed',80,100,'won',true,true,false,null),('business_claim','closed_lost','Closed lost',90,0,'lost',true,false,true,null),
 ('reserve_pro','identified','Identified',10,5,'open',false,false,false,14),('reserve_pro','qualified','Qualified',20,20,'open',false,false,false,21),('reserve_pro','demo_scheduled','Demo scheduled',30,35,'open',false,false,false,14),('reserve_pro','demo_completed','Demo completed',40,50,'open',false,false,false,10),('reserve_pro','proposal','Proposal',50,65,'open',false,false,false,14),('reserve_pro','negotiation','Negotiation',60,75,'open',false,false,false,14),('reserve_pro','payment_pending','Payment pending',70,90,'open',false,false,false,7),('reserve_pro','closed_won','Closed won',80,100,'won',true,true,false,null),('reserve_pro','closed_lost','Closed lost',90,0,'lost',true,false,true,null),
 ('promoted_listing','identified','Identified',10,10,'open',false,false,false,14),('promoted_listing','qualified','Qualified',20,30,'open',false,false,false,14),('promoted_listing','proposal','Proposal',30,60,'open',false,false,false,14),('promoted_listing','payment_pending','Payment pending',40,85,'open',false,false,false,7),('promoted_listing','active','Active',50,100,'active',true,true,false,null),('promoted_listing','closed_lost','Closed lost',60,0,'lost',true,false,true,null),
 ('partnership','identified','Identified',10,5,'open',false,false,false,30),('partnership','discovery','Discovery',20,20,'open',false,false,false,21),('partnership','qualified','Qualified',30,35,'open',false,false,false,21),('partnership','proposal','Proposal',40,60,'open',false,false,false,21),('partnership','legal_review','Legal review',50,80,'open',false,false,false,30),('partnership','closed_won','Closed won',60,100,'won',true,true,false,null),('partnership','closed_lost','Closed lost',70,0,'lost',true,false,true,null),
 ('renewal_expansion','upcoming','Upcoming',10,25,'open',false,false,false,30),('renewal_expansion','review','Review',20,40,'open',false,false,false,21),('renewal_expansion','expansion_identified','Expansion identified',30,45,'open',false,false,false,21),('renewal_expansion','proposal','Proposal',40,65,'open',false,false,false,14),('renewal_expansion','negotiation','Negotiation',50,80,'open',false,false,false,14),('renewal_expansion','renewed','Renewed',60,100,'won',true,true,false,null),('renewal_expansion','expanded','Expanded',70,100,'won',true,true,false,null),('renewal_expansion','churned','Churned',80,0,'churned',true,false,true,null)
) insert into public.crm_pipeline_stages(pipeline_id,stage_key,name,display_order,default_probability,stage_category,is_terminal,is_success,is_loss,max_days_in_stage,requires_loss_reason)
select p.id,s.stage_key,s.name,s.ord,s.prob,s.category,s.terminal,s.success,s.loss,s.max_days,s.loss from stages s join public.crm_pipelines p using(pipeline_key)
on conflict(pipeline_id,stage_key) do update set name=excluded.name,display_order=excluded.display_order,default_probability=excluded.default_probability,stage_category=excluded.stage_category,is_terminal=excluded.is_terminal,is_success=excluded.is_success,is_loss=excluded.is_loss,max_days_in_stage=excluded.max_days_in_stage,requires_loss_reason=excluded.requires_loss_reason;

alter table public.crm_opportunities add column if not exists opportunity_number text;
alter table public.crm_opportunities add column if not exists description text;
alter table public.crm_opportunities add column if not exists forecast_category text not null default 'pipeline' check(forecast_category in ('pipeline','best_case','commit','closed','omitted'));
alter table public.crm_opportunities add column if not exists forecast_amount numeric check(forecast_amount is null or forecast_amount >= 0);
alter table public.crm_opportunities add column if not exists weighted_amount numeric generated always as (round(coalesce(amount,0)*coalesce(probability,0)/100,2)) stored;
alter table public.crm_opportunities add column if not exists monthly_recurring_revenue numeric check(monthly_recurring_revenue is null or monthly_recurring_revenue >= 0);
alter table public.crm_opportunities add column if not exists annual_recurring_revenue numeric check(annual_recurring_revenue is null or annual_recurring_revenue >= 0);
alter table public.crm_opportunities add column if not exists one_time_revenue numeric check(one_time_revenue is null or one_time_revenue >= 0);
alter table public.crm_opportunities add column if not exists term_months integer check(term_months is null or term_months > 0);
alter table public.crm_opportunities add column if not exists billing_frequency text check(billing_frequency is null or billing_frequency in ('one_time','monthly','quarterly','annual','custom'));
alter table public.crm_opportunities add column if not exists trial_start_date date;
alter table public.crm_opportunities add column if not exists trial_end_date date;
alter table public.crm_opportunities add column if not exists proposal_url text; alter table public.crm_opportunities add column if not exists proposal_version text; alter table public.crm_opportunities add column if not exists proposal_status text;
alter table public.crm_opportunities add column if not exists contract_status text; alter table public.crm_opportunities add column if not exists contract_url text; alter table public.crm_opportunities add column if not exists contract_effective_date date; alter table public.crm_opportunities add column if not exists contract_expiration_date date;
alter table public.crm_opportunities add column if not exists payment_status text; alter table public.crm_opportunities add column if not exists subscription_id text; alter table public.crm_opportunities add column if not exists invoice_id text; alter table public.crm_opportunities add column if not exists promotion_code text;
alter table public.crm_opportunities add column if not exists discount_amount numeric default 0 check(discount_amount >= 0); alter table public.crm_opportunities add column if not exists discount_percent numeric default 0 check(discount_percent between 0 and 100); alter table public.crm_opportunities add column if not exists discount_expires_at timestamptz;
alter table public.crm_opportunities add column if not exists decision_deadline date; alter table public.crm_opportunities add column if not exists decision_criteria text; alter table public.crm_opportunities add column if not exists decision_process text;
alter table public.crm_opportunities add column if not exists economic_buyer_contact_id uuid references public.crm_contacts(id); alter table public.crm_opportunities add column if not exists champion_contact_id uuid references public.crm_contacts(id); alter table public.crm_opportunities add column if not exists technical_contact_id uuid references public.crm_contacts(id);
alter table public.crm_opportunities add column if not exists competitor_details text; alter table public.crm_opportunities add column if not exists risk_level text check(risk_level is null or risk_level in ('low','medium','high','critical')); alter table public.crm_opportunities add column if not exists risk_summary text; alter table public.crm_opportunities add column if not exists stalled_reason text;
alter table public.crm_opportunities add column if not exists last_stage_changed_at timestamptz not null default now(); alter table public.crm_opportunities add column if not exists forecast_period text;
alter table public.crm_opportunities add column if not exists closed_won_handoff_status text default 'not_started' check(closed_won_handoff_status in ('not_started','pending','in_progress','completed','blocked')); alter table public.crm_opportunities add column if not exists closed_won_handoff_at timestamptz; alter table public.crm_opportunities add column if not exists closed_won_handoff_by uuid references auth.users(id);
alter table public.crm_opportunities add column if not exists assigned_team text; alter table public.crm_opportunities add column if not exists last_activity_at timestamptz; alter table public.crm_opportunities add column if not exists loss_category text; alter table public.crm_opportunities add column if not exists future_follow_up_date date; alter table public.crm_opportunities add column if not exists source_system text; alter table public.crm_opportunities add column if not exists source_record_id text; alter table public.crm_opportunities add column if not exists version integer not null default 1;
create unique index if not exists crm_opportunities_number_uidx on public.crm_opportunities(opportunity_number) where opportunity_number is not null;
create unique index if not exists crm_opportunities_source_uidx on public.crm_opportunities(source_system,source_record_id,pipeline_key) where source_record_id is not null;
create index if not exists crm_opportunities_pipeline_board_idx on public.crm_opportunities(pipeline_key,stage,last_stage_changed_at) where archived_at is null;
create index if not exists crm_opportunities_forecast_idx on public.crm_opportunities(expected_close_date,forecast_category,owner_user_id,assigned_team) where archived_at is null;
create index if not exists crm_opportunities_risk_idx on public.crm_opportunities(risk_level,next_step_at) where archived_at is null and status='open';

create table if not exists public.crm_opportunity_products(id uuid primary key default gen_random_uuid(), opportunity_id uuid not null references public.crm_opportunities(id) on delete cascade, product_key text not null check(product_key in ('reserve_pro_monthly','reserve_pro_annual','promoted_listing','claim_conversion','partnership','multi_location_package','sms_addon','deposit_setup','custom')), product_name text not null, quantity integer not null default 1 check(quantity>0), unit_price numeric not null default 0 check(unit_price>=0), discount_amount numeric not null default 0 check(discount_amount>=0), discount_percent numeric not null default 0 check(discount_percent between 0 and 100), net_amount numeric generated always as (round(greatest(0,quantity*unit_price-discount_amount)*(100-discount_percent)/100,2)) stored, billing_frequency text, term_months integer check(term_months is null or term_months>0), location_id uuid references public.locations(id), metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists crm_opportunity_products_opportunity_idx on public.crm_opportunity_products(opportunity_id,product_key);
create table if not exists public.crm_opportunity_contacts(id uuid primary key default gen_random_uuid(), opportunity_id uuid not null references public.crm_opportunities(id) on delete cascade, contact_id uuid not null references public.crm_contacts(id), role_key text not null check(role_key in ('economic_buyer','decision_maker','champion','influencer','technical','legal','billing','operations','blocker','other')), influence_level text check(influence_level is null or influence_level in ('low','medium','high')), sentiment text check(sentiment is null or sentiment in ('negative','neutral','positive','unknown')), is_primary boolean not null default false, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(opportunity_id,contact_id,role_key));
create unique index if not exists crm_opportunity_contacts_primary_uidx on public.crm_opportunity_contacts(opportunity_id) where is_primary;
create table if not exists public.crm_opportunity_stage_history(id uuid primary key default gen_random_uuid(), opportunity_id uuid not null references public.crm_opportunities(id) on delete restrict, from_stage text, to_stage text not null, from_forecast_category text, to_forecast_category text, actor_user_id uuid references auth.users(id), reason text, entered_at timestamptz not null default now(), exited_at timestamptz, duration_seconds bigint check(duration_seconds is null or duration_seconds>=0), metadata jsonb not null default '{}');
create index if not exists crm_opportunity_stage_history_timeline_idx on public.crm_opportunity_stage_history(opportunity_id,entered_at desc);
create table if not exists public.crm_opportunity_history(id uuid primary key default gen_random_uuid(), opportunity_id uuid not null references public.crm_opportunities(id) on delete restrict, field_name text not null, old_value jsonb, new_value jsonb, actor_user_id uuid references auth.users(id), reason text, changed_at timestamptz not null default now(), metadata jsonb not null default '{}');
create index if not exists crm_opportunity_history_timeline_idx on public.crm_opportunity_history(opportunity_id,changed_at desc);
create table if not exists public.crm_discount_approvals(id uuid primary key default gen_random_uuid(), opportunity_id uuid not null references public.crm_opportunities(id), requested_percent numeric not null check(requested_percent between 0 and 100), required_role text not null check(required_role in ('owner','manager','admin')), status text not null default 'pending' check(status in ('pending','approved','rejected')), requested_by uuid not null references auth.users(id), decided_by uuid references auth.users(id), decision_reason text, created_at timestamptz not null default now(), decided_at timestamptz);
create table if not exists public.crm_forecast_snapshots(id uuid primary key default gen_random_uuid(), snapshot_date date not null, period_key text not null, owner_user_id uuid references auth.users(id), team_key text, pipeline_key text, pipeline_amount numeric not null default 0, weighted_amount numeric not null default 0, best_case_amount numeric not null default 0, commit_amount numeric not null default 0, closed_amount numeric not null default 0, opportunity_count integer not null default 0, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create unique index if not exists crm_forecast_snapshots_identity_uidx on public.crm_forecast_snapshots(snapshot_date,period_key,coalesce(owner_user_id,'00000000-0000-0000-0000-000000000000'::uuid),coalesce(team_key,''),coalesce(pipeline_key,''));
create table if not exists public.crm_revenue_targets(id uuid primary key default gen_random_uuid(), period_key text not null, owner_user_id uuid references auth.users(id), team_key text, pipeline_key text, target_type text not null, target_amount numeric not null check(target_amount>=0), currency text not null default 'USD', created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index if not exists crm_revenue_targets_identity_uidx on public.crm_revenue_targets(period_key,coalesce(owner_user_id,'00000000-0000-0000-0000-000000000000'::uuid),coalesce(team_key,''),coalesce(pipeline_key,''),target_type);

-- Browser access remains deny-by-default except existing fixed-search-path admin predicate.
do $$ declare t text; begin foreach t in array array['crm_pipelines','crm_pipeline_stages','crm_opportunity_products','crm_opportunity_contacts','crm_opportunity_stage_history','crm_opportunity_history','crm_discount_approvals','crm_forecast_snapshots','crm_revenue_targets'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists crm_admin_all on public.%I',t); execute format('create policy crm_admin_all on public.%I for all to authenticated using (public.crm_is_admin()) with check (public.crm_is_admin())',t); end loop; end $$;

create or replace function public.crm_opportunity_history_immutable() returns trigger language plpgsql set search_path=public,pg_temp as $$ begin raise exception 'CRM opportunity history is append-only'; end $$;
do $$ declare t text; begin foreach t in array array['crm_opportunity_stage_history','crm_opportunity_history'] loop execute format('drop trigger if exists %I_immutable on public.%I',t,t); execute format('create trigger %I_immutable before update or delete on public.%I for each row execute function public.crm_opportunity_history_immutable()',t,t); end loop; end $$;

create or replace function public.crm_snapshot_forecast(p_snapshot_date date default current_date, p_period_key text default to_char(current_date,'YYYY-MM')) returns integer language plpgsql security definer set search_path=public,pg_temp as $$
declare affected integer;
begin
 insert into public.crm_forecast_snapshots(snapshot_date,period_key,owner_user_id,team_key,pipeline_key,pipeline_amount,weighted_amount,best_case_amount,commit_amount,closed_amount,opportunity_count)
 select p_snapshot_date,p_period_key,owner_user_id,assigned_team,pipeline_key,
 coalesce(sum(amount) filter(where status='open' and forecast_category<>'omitted'),0),coalesce(sum(weighted_amount) filter(where status='open' and forecast_category<>'omitted'),0),
 coalesce(sum(amount) filter(where forecast_category='best_case'),0),coalesce(sum(amount) filter(where forecast_category='commit'),0),coalesce(sum(amount) filter(where status='won'),0),count(*)
 from public.crm_opportunities where archived_at is null and expected_close_date >= date_trunc('month',p_snapshot_date)::date and expected_close_date < (date_trunc('month',p_snapshot_date)+interval '1 month')::date group by owner_user_id,assigned_team,pipeline_key
 on conflict(snapshot_date,period_key,coalesce(owner_user_id,'00000000-0000-0000-0000-000000000000'::uuid),coalesce(team_key,''),coalesce(pipeline_key,'')) do update set pipeline_amount=excluded.pipeline_amount,weighted_amount=excluded.weighted_amount,best_case_amount=excluded.best_case_amount,commit_amount=excluded.commit_amount,closed_amount=excluded.closed_amount,opportunity_count=excluded.opportunity_count,metadata=jsonb_build_object('refreshed_at',now());
 get diagnostics affected=row_count; return affected;
end $$;
revoke all on function public.crm_snapshot_forecast(date,text) from public,authenticated; grant execute on function public.crm_snapshot_forecast(date,text) to service_role;
comment on function public.crm_snapshot_forecast is 'Idempotent daily forecast snapshot; fixed search_path; service role only.';
