create extension if not exists pgcrypto;
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
do $$ begin
  create type career_job_status as enum ('draft','open','paused','closed','filled','archived'); exception when duplicate_object then null; end $$;

create table if not exists public.career_jobs (
 id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique, department text not null default 'general', subdepartment text, role_track text, location text, workplace_type text default 'remote', employment_type text default 'part_time', compensation_type text, compensation_min numeric, compensation_max numeric, compensation_text text, summary text, overview text, responsibilities text, requirements text, nice_to_have text, benefits text, schedule text, hiring_process text, status text not null default 'draft' check (status in ('draft','open','paused','closed','filled','archived')), visibility text not null default 'public' check (visibility in ('public','private_link','internal_only','hidden')), is_internship boolean default false, internship_type text check (internship_type is null or internship_type in ('paid','unpaid_educational','college_credit','stipend','campus_ambassador','creator_program')), is_paid boolean default true, supports_college_credit boolean default false, requires_school_credit boolean default false, weekly_hours_min integer, weekly_hours_max integer, program_duration_weeks integer, learning_objectives text, compliance_status text default 'not_required', compliance_notes text, hiring_manager_id uuid, created_by uuid, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.career_job_questions (id uuid primary key default gen_random_uuid(), job_id uuid references public.career_jobs(id) on delete cascade, question_label text not null, question_type text default 'textarea', options jsonb default '[]'::jsonb, required boolean default false, sort_order integer default 0, applies_to text default 'all', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.career_applications (id uuid primary key default gen_random_uuid(), job_id uuid references public.career_jobs(id) on delete set null, user_id uuid, first_name text not null, last_name text not null, email text not null, phone text, city text, state text, linkedin_url text, portfolio_url text, website_url text, social_handle text, resume_url text, cover_letter text, status text not null default 'submitted', stage text not null default 'submitted' check (stage in ('submitted','portfolio_review','under_review','shortlisted','interview_requested','interview_scheduled','interview_completed','content_test','offer_pending','offer_sent','hired','not_selected','withdrawn','talent_pool')), score numeric, source text default 'careers_page', assigned_to uuid, last_contacted_at timestamptz, submitted_at timestamptz default now(), created_at timestamptz default now(), updated_at timestamptz default now(), unique(job_id,email));
create table if not exists public.career_application_answers (id uuid primary key default gen_random_uuid(), application_id uuid references public.career_applications(id) on delete cascade, question_id uuid references public.career_job_questions(id) on delete set null, question_label text not null, answer_text text, created_at timestamptz default now());
create table if not exists public.career_application_files (id uuid primary key default gen_random_uuid(), application_id uuid references public.career_applications(id) on delete cascade, file_type text not null, file_url text not null, original_name text, mime_type text, size_bytes bigint, created_at timestamptz default now());
create table if not exists public.career_application_notes (id uuid primary key default gen_random_uuid(), application_id uuid references public.career_applications(id) on delete cascade, admin_id uuid, note text not null, visibility text default 'internal', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.career_application_stage_history (id uuid primary key default gen_random_uuid(), application_id uuid references public.career_applications(id) on delete cascade, from_stage text, to_stage text not null, changed_by uuid, change_reason text, created_at timestamptz default now());
create table if not exists public.career_application_scorecards (id uuid primary key default gen_random_uuid(), application_id uuid references public.career_applications(id) on delete cascade, reviewer_id uuid, communication_score integer, experience_score integer, role_fit_score integer, availability_score integer, professionalism_score integer, market_knowledge_score integer, overall_score integer, recommendation text, notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.career_interviews (id uuid primary key default gen_random_uuid(), application_id uuid references public.career_applications(id) on delete cascade, interviewer_id uuid, scheduled_at timestamptz, duration_minutes integer default 30, meeting_type text default 'video', meeting_url text, location text, status text default 'requested' check (status in ('requested','scheduled','completed','no_show','cancelled','rescheduled')), candidate_notes text, internal_notes text, outcome text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.career_offers (id uuid primary key default gen_random_uuid(), application_id uuid references public.career_applications(id) on delete cascade, job_id uuid references public.career_jobs(id) on delete set null, status text default 'draft' check (status in ('draft','sent','accepted','declined','expired','withdrawn')), employment_type text, pay_type text, compensation_text text, start_date date, expires_at timestamptz, sent_at timestamptz, accepted_at timestamptz, declined_at timestamptz, withdrawn_at timestamptz, created_by uuid, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.career_talent_pool (id uuid primary key default gen_random_uuid(), application_id uuid references public.career_applications(id) on delete cascade, candidate_name text, email text, tags text[] default '{}', owner_id uuid, notes text, status text default 'active', last_contacted_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.career_email_events (id uuid primary key default gen_random_uuid(), application_id uuid references public.career_applications(id) on delete cascade, template_key text, recipient_email text not null, subject text, status text default 'queued', error text, sent_at timestamptz, created_by uuid, created_at timestamptz default now());
create table if not exists public.career_team_conversions (id uuid primary key default gen_random_uuid(), application_id uuid references public.career_applications(id) on delete cascade, user_id uuid, team_role text not null, department text, manager_id uuid, start_date date, permissions jsonb default '{}'::jsonb, assigned_market_id uuid, assigned_locations uuid[] default '{}', converted_by uuid, converted_at timestamptz default now(), created_at timestamptz default now());
create table if not exists public.career_internship_programs (id uuid primary key default gen_random_uuid(), name text not null, department text default 'marketing', track text, paid_status text not null, duration_weeks integer, weekly_hours_min integer, weekly_hours_max integer, learning_objectives text, supervisor_id uuid, status text default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.career_internship_assignments (id uuid primary key default gen_random_uuid(), intern_application_id uuid references public.career_applications(id) on delete cascade, program_id uuid references public.career_internship_programs(id) on delete set null, title text not null, description text, learning_objective text, due_date date, status text default 'assigned', submitted_url text, feedback text, created_by uuid, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.career_internship_checkins (id uuid primary key default gen_random_uuid(), application_id uuid references public.career_applications(id) on delete cascade, supervisor_id uuid, checkin_at timestamptz default now(), notes text, progress_status text, next_steps text, created_at timestamptz default now());
create table if not exists public.career_internship_school_credit (id uuid primary key default gen_random_uuid(), application_id uuid references public.career_applications(id) on delete cascade, school_name text, program_name text, credit_contact_name text, credit_contact_email text, required_hours integer, required_start_date date, required_end_date date, documents_url text, status text default 'pending', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.career_marketing_portfolios (id uuid primary key default gen_random_uuid(), application_id uuid references public.career_applications(id) on delete cascade, platform text, url text, description text, created_at timestamptz default now());
create table if not exists public.career_content_tests (id uuid primary key default gen_random_uuid(), application_id uuid references public.career_applications(id) on delete cascade, prompt text not null, submission_text text, submission_url text, score integer, review_notes text, status text default 'requested', created_at timestamptz default now(), updated_at timestamptz default now());

create index if not exists idx_career_jobs_public on public.career_jobs(status, visibility, department);
create index if not exists idx_career_applications_job_stage on public.career_applications(job_id, stage, submitted_at desc);
create index if not exists idx_career_applications_email on public.career_applications(email);
create index if not exists idx_career_interviews_schedule on public.career_interviews(scheduled_at, status);
create index if not exists idx_career_offers_status on public.career_offers(status, expires_at);

do $$ declare t text; begin foreach t in array array['career_jobs','career_job_questions','career_applications','career_application_notes','career_application_scorecards','career_interviews','career_offers','career_talent_pool','career_internship_programs','career_internship_assignments','career_internship_school_credit','career_content_tests'] loop execute format('drop trigger if exists set_%I_updated_at on public.%I', t, t); execute format('create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()', t, t); end loop; end $$;

do $$ declare t text; begin foreach t in array array['career_jobs','career_job_questions','career_applications','career_application_answers','career_application_files','career_application_notes','career_application_stage_history','career_application_scorecards','career_interviews','career_offers','career_talent_pool','career_email_events','career_team_conversions','career_internship_programs','career_internship_assignments','career_internship_checkins','career_internship_school_credit','career_marketing_portfolios','career_content_tests'] loop execute format('alter table public.%I enable row level security', t); execute format('drop policy if exists "admin service role manages %I" on public.%I', t, t); execute format('create policy "admin service role manages %I" on public.%I for all using (auth.role() = ''service_role'') with check (auth.role() = ''service_role'')', t, t); end loop; end $$;
create policy "public reads open public career jobs" on public.career_jobs for select using (status in ('open','paused') and visibility = 'public');
create policy "users read own career applications" on public.career_applications for select using (user_id = auth.uid() or lower(email) = lower(coalesce(auth.jwt()->>'email','')));
create policy "users update own public career application links" on public.career_applications for update using (user_id = auth.uid() or lower(email)=lower(coalesce(auth.jwt()->>'email',''))) with check (user_id = auth.uid() or lower(email)=lower(coalesce(auth.jwt()->>'email','')));

insert into public.career_jobs (title,slug,department,subdepartment,location,employment_type,compensation_text,summary,status,visibility,is_internship,internship_type,is_paid,supports_college_credit,requires_school_credit,weekly_hours_min,weekly_hours_max,program_duration_weeks,learning_objectives,compliance_status) values
('Paid Social Media Marketing Intern','paid-social-media-marketing-intern','marketing','social_media','Remote / NYC','internship','Paid internship','Create short-form content and help TheOutHaven grow local discovery.', 'open','public',true,'paid',true,true,false,8,15,12,'Learn content planning, social analytics, brand research, and local marketing operations.','reviewed'),
('Social Media Intern — Educational / College Credit','social-media-intern-educational-college-credit','marketing','social_media','Remote / NYC','internship','Educational / College Credit','Educational social media internship for school-credit or structured learning.', 'open','public',true,'college_credit',false,true,true,6,12,12,'Learn marketing, content strategy, social planning, research, and startup operations.','pending_review'),
('Marketing Intern — Paid','marketing-intern-paid','marketing','content','Remote','internship','Paid internship','Support campaigns, research, and community marketing.', 'open','public',true,'paid',true,true,false,8,15,12,'Learn campaign planning, local audience research, and marketing execution.','reviewed'),
('Marketing Intern — Educational / College Credit','marketing-intern-educational-college-credit','marketing','content','Remote','internship','Educational / College Credit','Structured educational marketing internship with school-credit support.', 'open','public',true,'college_credit',false,true,true,6,12,12,'Learn marketing operations, campaign planning, audience research, and reporting.','pending_review'),
('Campus Ambassador','campus-ambassador','campus','ambassador','Campus / Remote','part_time','Paid or campus program track','Represent TheOutHaven on campus and help students discover better outings.', 'open','public',true,'campus_ambassador',true,true,false,5,10,12,'Learn campus outreach, partnerships, and community growth.','reviewed'),
('Influencer Outreach Intern','influencer-outreach-intern','marketing','influencer_outreach','Remote','internship','Paid internship','Research creators and support outreach for local discovery campaigns.', 'open','public',true,'paid',true,true,false,8,12,12,'Learn influencer research, outreach operations, and campaign tracking.','reviewed'),
('Content Creator Intern','content-creator-intern','creator','content','Remote / Local','internship','Paid or creator program track','Create local outing content concepts and social media assets.', 'open','public',true,'creator_program',true,true,false,5,12,12,'Learn creator strategy, local content production, and content testing.','reviewed'),
('Experience Team Associate','experience-team-associate','experience',null,'Remote','part_time','Part-time compensation shared during hiring','Help users and partners have smooth TheOutHaven experiences.', 'draft','public',false,null,true,false,false,null,null,null,null,'not_required'),
('Partner Ambassador','partner-ambassador','partnerships','ambassador','Remote / Local','contract','Commission / contract details shared during hiring','Support partner outreach and onboarding for local businesses.', 'draft','public',false,null,true,false,false,null,null,null,null,'not_required')
on conflict (slug) do nothing;
insert into public.career_job_questions (job_id, question_label, required, sort_order)
select j.id, q.label, q.required, q.ord from public.career_jobs j cross join (values
('Which platforms do you use most?', true, 10),('Do you have experience creating content?', true, 20),('What type of content are you most interested in?', false, 30),('Upload or link examples of content you created.', false, 40),('Are you comfortable being on camera?', false, 50),('Are you comfortable visiting local businesses or events?', false, 60),('What areas can you cover?', false, 70),('Are you applying for paid internship, unpaid educational internship, college credit internship, or not sure?', true, 80),('Is this connected to a school, program, or college credit requirement?', false, 90)) as q(label,required,ord)
where j.department in ('marketing','campus','creator') on conflict do nothing;
