"use client";
import { useState } from "react";

type Action = { label: string; endpoint: string; method?: "GET" | "POST"; body?: Record<string, unknown>; query?: Record<string, string | number | boolean>; tone?: "rose" | "white" | "emerald"; requireInput?: "id" | "q" | "locationId" };
async function readJson(res: Response) { const text = await res.text(); try { return text ? JSON.parse(text) : {}; } catch { return { raw: text }; } }
function urlWithQuery(endpoint: string, query?: Action["query"]) { const url = new URL(endpoint, window.location.origin); Object.entries(query || {}).forEach(([k,v]) => url.searchParams.set(k, String(v))); return url.pathname + url.search; }
export function ActionToolsClient({ actions, inputLabel = "Location ID or search", warning }: { actions: Action[]; inputLabel?: string; warning?: string }) {
  const [busy, setBusy] = useState<string | null>(null); const [result, setResult] = useState<unknown>(null); const [error, setError] = useState<string | null>(null); const [input, setInput] = useState("");
  async function run(action: Action) { setBusy(action.label); setResult(null); setError(null); try { const body = { ...(action.body || {}) }; if (action.requireInput) { if (!input.trim()) throw new Error(`${inputLabel} is required.`); body[action.requireInput] = input.trim(); } const res = await fetch(urlWithQuery(action.endpoint, action.query), { method: action.method || "POST", headers: { "Content-Type": "application/json" }, body: (action.method || "POST") === "GET" ? undefined : JSON.stringify(body) }); const json = await readJson(res); setResult({ status: res.status, ok: res.ok, ...json }); if (!res.ok || json?.success === false) setError(String(json?.error || json?.message || `Request failed (${res.status})`)); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(null); } }
  return <div className="space-y-4">{warning ? <div className="rounded-2xl border border-amber-300/20 bg-amber-500/10 p-4 text-sm font-bold text-amber-100">{warning}</div> : null}<label className="block max-w-xl text-sm font-bold text-white/70">{inputLabel}<input value={input} onChange={(e)=>setInput(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/40 px-4 py-3 text-white outline-none focus:border-rose-300" placeholder="Optional unless noted on button" /></label><div className="flex flex-wrap gap-3">{actions.map((a)=><button key={a.label} disabled={busy!==null} onClick={()=>run(a)} className={`${a.tone === "white" ? "bg-white text-black" : a.tone === "emerald" ? "bg-emerald-500 text-white" : "bg-rose-500 text-white"} rounded-full px-5 py-3 text-sm font-black disabled:opacity-50`}>{busy===a.label ? "Running…" : a.label}</button>)}</div>{error ? <div className="rounded-2xl border border-red-300/30 bg-red-500/15 p-4 text-sm font-bold text-red-100">{error}</div> : null}{result ? <pre className="max-h-[520px] overflow-auto rounded-2xl bg-black/50 p-4 text-xs text-white/70">{JSON.stringify(result,null,2)}</pre> : <div className="rounded-2xl border border-white/10 bg-black/20 p-4 text-sm font-bold text-white/45">Action results appear here.</div>}</div>;
}
