import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase-server";
import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { verifyTurnstileToken, shouldBypassTurnstileForUser } from "@/lib/security/turnstile";
import { sendRawBrandedEmail } from "@/lib/email";
const SAFE="We could not verify that submission. Please refresh and try again.";
function remoteIp(req: NextRequest){return req.headers.get("cf-connecting-ip")||req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||null;}
async function ctx(){const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); let tester:any=null; if(user?.id||user?.email){const or=[`user_id.eq.${user.id}`]; if(user.email)or.push(`email.eq.${user.email}`); const {data}=await supabaseAdmin.from("beta_testers").select("*").or(or.join(",")).maybeSingle(); tester=data;} return {user,tester};}
export async function POST(request:NextRequest){try{const body=await request.json().catch(()=>({})); const title=String(body.title??"").trim(); const description=String(body.description??"").trim(); if(!title||!description)return NextResponse.json({success:false,error:"Title and description are required."},{status:400}); const {user,tester}=await ctx(); const bypass=shouldBypassTurnstileForUser({isAuthenticated:Boolean(user),isBetaTester:Boolean(tester)}); let turnstile:any={success:true,bypassed:true}; if(!bypass){turnstile=await verifyTurnstileToken({token:body.turnstileToken??body["cf-turnstile-response"],remoteIp:remoteIp(request),expectedAction:"beta_bug_report",source:"beta_bug_report",metadata:{severity:body.severity??null}}); if(!turnstile.success)return NextResponse.json({success:false,error:SAFE},{status:400});}
const {data,error}=await supabaseAdmin.from("beta_bug_reports").insert({tester_id:tester?.id??null,user_id:user?.id??null,title,description,steps_to_reproduce:body.steps_to_reproduce||null,expected_result:body.expected_result||null,actual_result:body.actual_result||null,severity:body.severity||"medium",feature_area:body.feature_area||"general",page_url:body.page_url||null,screenshot_url:body.screenshot_url||null,browser:body.browser||null,device:body.device||null,turnstile_verified:!turnstile.bypassed,turnstile_action:turnstile.action??null,turnstile_hostname:turnstile.hostname??null}).select("*").single(); if(error)throw error; if(body.severity==="critical")void sendRawBrandedEmail({to:"admin@theouthaven.com",department:"support",subject:"Critical beta bug reported",heading:"Critical beta bug",body:`${title}\n\n${description}`}); return NextResponse.json({success:true,bug:data});}catch(error){console.error("BETA_BUG_ERROR",error);return NextResponse.json({success:false,error:"Bug report could not be submitted."},{status:500});}}
