export const dynamic = "force-dynamic";

import Link from "next/link";
import { notFound } from "next/navigation";
import { ThumbsDown, ThumbsUp } from "lucide-react";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { KB_SELECT } from "@/lib/knowledge-base/server";
type Props={params:Promise<{slug:string}>};
export default async function HelpArticlePage({params}:Props){ const {slug}=await params; const {data:a}=await supabaseAdmin.from('knowledge_base_articles').select(KB_SELECT).eq('slug',slug).eq('status','published').in('visibility',['public','both']).maybeSingle(); if(!a) notFound(); const {data:related}=await supabaseAdmin.from('knowledge_base_articles').select('id,title,slug,excerpt').eq('status','published').in('visibility',['public','both']).eq('category_id',a.category_id).neq('id',a.id).limit(4); return <main className="min-h-screen bg-[#090706] px-4 py-10 text-white sm:px-6 lg:px-8"><article className="mx-auto max-w-4xl space-y-6"><Link href="/help" className="font-black text-amber-100">← Help Center</Link><section className="rounded-[2rem] border border-white/10 bg-white/[0.04] p-8"><p className="text-sm font-bold uppercase tracking-[0.2em] text-rose-100/50">{a.knowledge_base_categories?.name} · Updated {new Date(a.updated_at).toLocaleDateString()}</p><h1 className="mt-3 text-4xl font-black">{a.title.replace('Public FAQ: ','')}</h1>{a.excerpt&&<p className="mt-4 text-lg text-rose-100/70">{a.excerpt}</p>}</section><section className="rounded-[2rem] border border-white/10 bg-[#120b0a] p-6 leading-8 whitespace-pre-wrap">{a.content}</section><section className="rounded-3xl border border-white/10 bg-white/[0.04] p-5"><b>Was this helpful?</b><div className="mt-3 flex gap-3"><button className="rounded-full border border-white/10 px-4 py-2"><ThumbsUp className="inline h-4 w-4"/> Helpful</button><button className="rounded-full border border-white/10 px-4 py-2"><ThumbsDown className="inline h-4 w-4"/> Not Helpful</button></div></section><section className="grid gap-3 md:grid-cols-2">{(related??[]).map(r=><Link key={r.id} href={`/help/${r.slug}`} className="rounded-3xl border border-white/10 bg-white/[0.04] p-5"><b>{r.title.replace('Public FAQ: ','')}</b><p className="text-sm text-rose-100/60">{r.excerpt}</p></Link>)}</section><section className="rounded-3xl border border-amber-200/20 bg-amber-300/10 p-5"><b>Need more help? Contact support.</b><p className="mt-2 text-rose-100/70">Trying to claim your business? Start a claim from the business owner tools.</p></section></article></main> }
