export type ReviewSignals = Record<string, any>;
export type LocationReviewMlFeatures = Record<string, any>;

const clamp = (n: number, min = 0, max = 100) => Math.max(min, Math.min(max, Number.isFinite(n) ? n : 0));
const words = (v: unknown) => Array.isArray(v) ? v.map(String) : typeof v === "string" ? [v] : [];
const txt = (review: any) => [review.review_text, review.text, review.comment, review.vibe, review.noise_level, review.ai_sentiment, review.service_quality, review.food_quality, review.ambiance_quality, review.price_feeling, review.wait_time, ...words(review.ai_keywords ?? review.keywords), ...words(review.occasion_fit), ...words(review.best_for), ...words(review.avoid_if)].join(" ").toLowerCase();
const has = (text: string, patterns: RegExp[]) => patterns.some((p) => p.test(text));
const ageDays = (d: any) => { const t = new Date(d || 0).getTime(); return Number.isFinite(t) && t > 0 ? (Date.now() - t) / 864e5 : 9999; };
const recentWeight = (d: any) => ageDays(d) <= 30 ? 1.35 : ageDays(d) <= 120 ? 1 : 0.65;
const verifiedWeight = (r: any) => r?.verified_visit || r?.verifiedVisit || r?.verification_source ? 1.6 : 1;
const qualityValue = (v: any) => ({ excellent: 90, good: 75, average: 55, mixed: 48, bad: 20 }[String(v || "").toLowerCase()] ?? 50);

const P = {
  quiet: [/\bquiet\b/,/not (too )?loud/,/conversation/,/\bcozy\b/,/intimate/,/relaxed/,/\bcalm\b/,/low[ -]?key/,/lowkey/,/\bchill\b/],
  loud: [/\bloud\b/,/noisy/,/\bdj\b/,/music blasting/,/\bclub\b/,/dance floor/,/crowded/,/packed/,/party/,/lively/],
  romantic: [/romantic/,/date night/,/intimate/,/cozy/,/anniversary/,/candlelit/,/special occasion/],
  group: [/\bgroup\b/,/girls night/,/friends/,/cocktails/,/fun atmosphere/,/photo worthy/,/\bmusic\b/,/\bvibe\b/],
  family: [/family/,/\bkids\b/,/family friendly/,/stroller/,/casual/,/spacious/],
  photo: [/photo[ -]?worthy/,/instagram/,/pictures/,/decor/,/aesthetic/,/views?/,/skyline/],
  serviceIssue: [/bad service/,/slow service/,/\brude\b/,/ignored/,/poor service/],
  waitIssue: [/long wait/,/waited/,/delayed/,/reservation not ready/],
  valueIssue: [/overpriced/,/expensive for what it is/,/not worth it/],
};

export function extractReviewSignals(review: any): ReviewSignals {
  const text = txt(review); const ai = review || {}; const w = verifiedWeight(review) * recentWeight(review.created_at || review.approved_at);
  const noise = String(ai.noise_level || "").toLowerCase(); const vibe = String(ai.vibe || "").toLowerCase();
  const quiet = has(text, P.quiet) || noise === "quiet";
  const loud = has(text, P.loud) || noise === "loud" || noise === "very loud";
  const romantic = has(text, P.romantic) || ai.date_night || ["romantic","intimate","cozy"].includes(vibe);
  const group = has(text, P.group) || ai.group_friendly;
  const family = has(text, P.family) || ai.family_friendly;
  const photo = has(text, P.photo);
  const serviceIssue = has(text, P.serviceIssue) || ai.service_quality === "bad";
  const waitIssue = has(text, P.waitIssue) || ai.wait_time === "long";
  const valueIssue = has(text, P.valueIssue) || ["overpriced","expensive"].includes(String(ai.price_feeling || "").toLowerCase());
  const sentiment = String(ai.ai_sentiment || ai.sentiment || "neutral").toLowerCase();
  return { weight: w, verified: verifiedWeight(review) > 1, recent: ageDays(review.created_at || review.approved_at) <= 90, rating: Number(ai.rating || 0), aiScoreBoost: Number(ai.ai_score_boost ?? ai.score_boost ?? 0), sentiment, quiet, loud, romantic, group, family, photo, serviceIssue, waitIssue, valueIssue, lively: loud || /lively|energetic|party/.test(text), upscale: /upscale|classy|fine dining|high end/.test(text) || vibe === "upscale" || vibe === "classy", casual: /casual|relaxed|laid back|chill/.test(text) || vibe === "casual", grown: /grown|adult|mature|classy|grown vibe/.test(text), birthday: /birthday|bday/.test(text), girlsNight: /girls night|ladies night|with the girls/.test(text), service: qualityValue(ai.service_quality), food: qualityValue(ai.food_quality), ambiance: qualityValue(ai.ambiance_quality), value: valueIssue ? 25 : /worth it|good value|affordable/.test(text) ? 80 : 55, bestFor: words(ai.best_for), avoidIf: words(ai.avoid_if), keywords: words(ai.ai_keywords ?? ai.keywords) };
}

function score(mentions: number, weight: number, total: number) { if (!total) return 0; return clamp((weight / Math.max(total, 1)) * 55 + Math.min(35, mentions * 8)); }
function termTop(items: string[], limit = 8) { const m = new Map<string, number>(); items.map((s)=>s.toLowerCase().trim()).filter(Boolean).forEach((s)=>m.set(s,(m.get(s)||0)+1)); return [...m.entries()].sort((a,b)=>b[1]-a[1]).map(([k])=>k).slice(0,limit); }

export function calculateReviewConfidence(input: any): number { const approved = Number(input.approved_review_count || 0); const verified = Number(input.verified_review_count || 0); const recent = Number(input.recent_review_count || 0); return clamp(Math.log1p(approved) / Math.log1p(20) * 45 + Math.log1p(verified) / Math.log1p(12) * 40 + Math.min(15, recent * 2)); }
export function calculateReviewQualityScore(input: any): number { const confidence = calculateReviewConfidence(input) / 100; const avg = clamp(Number(input.avg_rating || 0) * 20); const base = avg * .4 + Number(input.service_score || 50) * .15 + Number(input.food_score || 50) * .15 + Number(input.ambiance_score || 50) * .15 + Number(input.value_score || 50) * .1 + clamp((Number(input.avg_ai_score_boost || 0)+10)*5) * .05; const penalties = confidence > .35 ? Number(input.wait_penalty||0)+Number(input.service_penalty||0)+Number(input.overpriced_penalty||0) : 0; return clamp(base - penalties * .25); }

export function aggregateReviewSignals(reviews: any[]): LocationReviewMlFeatures {
  const approved = (reviews || []).filter((r) => String(r.status || "approved") === "approved"); const sigs = approved.map(extractReviewSignals); const total = sigs.length; const sw = sigs.reduce((s,x)=>s+x.weight,0) || 1;
  const c = (k: string) => sigs.filter((s)=>s[k]).length; const w = (k: string) => sigs.reduce((s,x)=>s+(x[k]?x.weight:0),0);
  const avg = (k: string, def=0) => total ? sigs.reduce((s,x)=>s+Number(x[k]||def)*x.weight,0)/sw : 0;
  const row: LocationReviewMlFeatures = { location_id: approved[0]?.location_id, approved_review_count: total, verified_review_count: sigs.filter(s=>s.verified).length, recent_review_count: sigs.filter(s=>s.recent).length, avg_rating: total ? avg("rating") : 0, avg_ai_score_boost: total ? avg("aiScoreBoost") : 0, positive_review_count: sigs.filter(s=>s.sentiment === "positive" || s.rating >= 4).length, neutral_review_count: sigs.filter(s=>s.sentiment === "neutral").length, negative_review_count: sigs.filter(s=>s.sentiment === "negative" || (s.rating && s.rating <= 2)).length };
  Object.assign(row, { quiet_mention_count:c("quiet"), loud_mention_count:c("loud"), romantic_mention_count:c("romantic"), group_mention_count:c("group"), family_mention_count:c("family"), photo_worthy_mention_count:c("photo"), service_issue_count:c("serviceIssue"), wait_issue_count:c("waitIssue"), value_issue_count:c("valueIssue") });
  Object.assign(row, { quiet_score:score(c("quiet"),w("quiet"),total), loud_score:score(c("loud"),w("loud"),total), romantic_score:score(c("romantic"),w("romantic"),total), group_score:score(c("group"),w("group"),total), family_score:score(c("family"),w("family"),total), photo_worthy_score:score(c("photo"),w("photo"),total), lively_score:score(c("lively"),w("lively"),total), upscale_score:score(c("upscale"),w("upscale"),total), casual_score:score(c("casual"),w("casual"),total), relaxed_score:score(c("quiet")+c("casual"),w("quiet")+w("casual"),total), grown_vibe_score:score(c("grown")+c("upscale"),w("grown")+w("upscale"),total), date_night_score:score(c("romantic"),w("romantic"),total), birthday_score:score(c("birthday")+c("group"),w("birthday")+w("group"),total), girls_night_score:score(c("girlsNight")+c("group"),w("girlsNight")+w("group"),total) });
  Object.assign(row, { service_score: avg("service",50), food_score: avg("food",50), ambiance_score: avg("ambiance",50), value_score: avg("value",55), wait_penalty: score(c("waitIssue"),w("waitIssue"),total), overpriced_penalty: score(c("valueIssue"),w("valueIssue"),total), service_penalty: score(c("serviceIssue"),w("serviceIssue"),total), noise_penalty: score(c("loud"),w("loud"),total), crowded_penalty: score(c("loud"),w("loud"),total) });
  row.review_confidence_score = calculateReviewConfidence(row); row.review_freshness_score = clamp(row.recent_review_count / Math.max(total,1) * 100); row.overall_review_quality_score = calculateReviewQualityScore(row); row.top_positive_terms = termTop(sigs.filter(s=>s.sentiment!=="negative").flatMap(s=>s.keywords)); row.top_negative_terms = termTop(sigs.filter(s=>s.sentiment==="negative" || s.serviceIssue || s.waitIssue || s.valueIssue || s.loud).flatMap(s=>[...s.keywords, ...s.avoidIf])); row.best_for_terms = termTop(sigs.flatMap(s=>s.bestFor)); row.avoid_if_terms = termTop(sigs.flatMap(s=>s.avoidIf)); row.last_review_at = approved.map(r=>r.approved_at||r.created_at).sort().pop() || null; row.review_summary = formatReviewIntelligenceSummary(row); return row;
}

function intentText(intent: any) { return [intent?.rawQuery,intent?.normalizedQuery,intent?.primaryIntent,...(intent?.vibes||[]),...(intent?.secondaryIntents||[]),...(intent?.allIntents||[]),...(intent?.normalizedIntent?.vibeTerms||[])].join(" ").toLowerCase().replaceAll("_"," "); }
export function getReviewPenaltyForIntent(intent: any, f: any): number { if (!f) return 0; const q = intentText(intent); const conf=Number(f.review_confidence_score||0); const loudSupport = Number(f.loud_mention_count||0) >= 3 || (Number(f.recent_review_count||0) >= 5 && Number(f.loud_mention_count||0)/Math.max(1,Number(f.recent_review_count||0)) >= .2) || (Number(f.noise_penalty||0) > 55 && conf > 45); if (/quiet|conversation|relaxed|not loud|date/.test(q) && loudSupport) return clamp(Number(f.noise_penalty||0) * conf/100,0,35); const issueSupport = conf > 45; return issueSupport ? clamp((Number(f.wait_penalty||0)+Number(f.service_penalty||0)+Number(f.overpriced_penalty||0))*.12,0,18) : 0; }
export function calculateIntentReviewFit(intent: any, f: any): number { if (!f) return 0; const q = intentText(intent); const conf = clamp(Number(f.review_confidence_score||0))/100; let s=0; if (/quiet|conversation|relaxed|date|romantic/.test(q)) s += Number(f.quiet_score||0)*.18 + Number(f.romantic_score||0)*.22 + Number(f.date_night_score||0)*.18 + Number(f.ambiance_score||0)*.08; if (/girls night|group|friends/.test(q)) s += Number(f.group_score||0)*.22 + Number(f.girls_night_score||0)*.2 + Number(f.lively_score||0)*.12 + Number(f.photo_worthy_score||0)*.12; if (/family|kids|kid friendly/.test(q)) s += Number(f.family_score||0)*.3 + Number(f.service_score||0)*.1 + Number(f.value_score||0)*.08; if (/birthday|celebration|party|nightlife|dj|lively/.test(q)) s += Number(f.birthday_score||0)*.2 + Number(f.group_score||0)*.16 + Number(f.lively_score||0)*.18 + Number(f.photo_worthy_score||0)*.1; if (/grown/.test(q)) s += Number(f.grown_vibe_score||0)*.22 + Number(f.upscale_score||0)*.14 + Number(f.ambiance_score||0)*.1; if (/picture|photo|instagram|aesthetic/.test(q)) s += Number(f.photo_worthy_score||0)*.3 + Number(f.ambiance_score||0)*.1; if (!s) s = Number(f.overall_review_quality_score||0)*.08; return clamp(s*conf - getReviewPenaltyForIntent(intent,f), -35, 45); }
export function calculatePairReviewFit(r: any, a: any, intent: any): number { if (!r && !a) return 0; const rf=calculateIntentReviewFit(intent,r); const af=calculateIntentReviewFit(intent,a); const compat = r && a ? Math.min(Number(r.review_confidence_score||0), Number(a.review_confidence_score||0)) > 35 ? 4 : 0 : 0; return clamp(rf*.55 + af*.45 + compat, -35, 45); }
export function formatReviewIntelligenceSummary(f: any): string { if (!f || !Number(f.approved_review_count||0)) return "No approved review intelligence yet."; const bits:string[]=[]; if (Number(f.review_confidence_score||0)<30) bits.push("Low confidence: not enough reviews yet"); if (Number(f.quiet_score||0)>50 && Number(f.romantic_score||0)>40) bits.push("Strong quiet/date-night fit"); if (Number(f.group_score||0)>50 || Number(f.girls_night_score||0)>50) bits.push("Strong group outing fit"); if (Number(f.family_score||0)>50) bits.push("Family-friendly fit"); if (Number(f.wait_issue_count||0)>=3) bits.push("Repeated wait concerns"); if (Number(f.loud_mention_count||0)===1) bits.push("One-off noise issue only: not affecting ranking yet"); return bits.length ? bits.join(" · ") : "Approved reviews are contributing quality and intent-fit signals."; }
