export type WeightedComponent = { name: string; score: number | null | undefined; weight: number; confidence?: number | null; reason?: string };
export function clampScore(value: number | null | undefined, min = 0, max = 100) { const n = Number(value ?? 0); return Number(Math.min(max, Math.max(min, Number.isFinite(n) ? n : 0)).toFixed(2)); }
export function safeDivide(numerator: number | null | undefined, denominator: number | null | undefined, fallback = 0) { const n = Number(numerator ?? 0), d = Number(denominator ?? 0); return Number.isFinite(n) && Number.isFinite(d) && d !== 0 ? n / d : fallback; }
export function normalizeCount(count: number | null | undefined, saturation = 25) { return clampScore(Math.log1p(Math.max(0, Number(count ?? 0))) / Math.log1p(saturation) * 100); }
export function confidenceWeight(count: number | null | undefined, fullConfidenceAt = 30) { return clampScore(safeDivide(count, fullConfidenceAt), 0, 1); }
export function freshnessWeight(date: string | Date | null | undefined, halfLifeDays = 45) { if (!date) return 0; const age = Math.max(0, Date.now() - new Date(date).getTime()) / 864e5; return clampScore(Math.pow(0.5, age / halfLifeDays), 0, 1); }
export function hasSupportThreshold(count: number | null | undefined, threshold = 3) { return Number(count ?? 0) >= threshold; }
export function patternStrength(count: number | null | undefined, verifiedCount = count) { const c = Math.max(0, Number(count ?? 0)); const v = Math.max(0, Number(verifiedCount ?? c)); if (c <= 0) return 0; if (c === 1) return 0.12; if (c === 2) return 0.25; if (c >= 5 && v >= 3) return 1; if (c >= 3 && v >= 2) return 0.65; return 0.35; }
export function combineWeightedComponents(components: WeightedComponent[]) { let total = 0, weight = 0; const explanations: string[] = []; for (const c of components) { const w = Math.max(0, Number(c.weight || 0)) * clampScore(c.confidence ?? 1, 0, 1); if (!w) continue; total += clampScore(c.score) * w; weight += w; if (c.reason) explanations.push(c.reason); } return { score: weight ? clampScore(total / weight) : 0, explanations }; }
export function scoreExplainer(label: string, score: number | null | undefined, confidence?: number | null) { const s = clampScore(score); const c = confidence == null ? null : clampScore(confidence, 0, 1); return `${label}: ${s.toFixed(0)}${c == null ? "" : ` (${Math.round(c * 100)}% confidence)`}`; }
