"use client";
import { useState, type ReactNode } from "react";
import { PRICE_RANGE_OPTIONS, normalizeTagList } from "@/lib/location-profile-fields";
import { formatOperatingHoursForEditor, parseWeeklyHoursFromEditor } from "@/lib/weekly-hours";

type Props = { table?: string; id: string; record: Record<string, any>; canEdit: boolean; canViewAdvancedSystemData: boolean; saveMode?: "admin" | "owner"; type?: string; aiHelperEnabled?: boolean; aiHelperAccessLabel?: string };
const input="w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-white outline-none disabled:opacity-60";
const label="space-y-2 text-sm font-bold text-white/65";
function arr(v:any){return Array.isArray(v)?v.join(", "):String(v??"");}
function mergeTags(a:any,b:any){return Array.from(new Set([...normalizeTagList(a),...normalizeTagList(b)].map(t=>t.toLowerCase().trim()).filter(Boolean))).join(", ");}
function Field({label: l,helper,children}:{label:string;helper?:string;children:ReactNode}){return <label className={label}><span>{l}</span>{children}{helper?<p className="text-xs font-medium leading-5 text-white/45">{helper}</p>:null}</label>}
function ReadOnly({label:l,helper,value}:{label:string;helper?:string;value:any}){return <Field label={l} helper={helper}><textarea readOnly rows={4} value={Array.isArray(value)?value.join(", "):(value&&typeof value==='object'?JSON.stringify(value,null,2):String(value??""))} className={`${input} font-mono text-xs`} /></Field>}
export default function LocationProfileEditor({table="locations",id,record,canEdit,canViewAdvancedSystemData,saveMode="admin",type,aiHelperEnabled=false,aiHelperAccessLabel}:Props){
 const [v,setV]=useState({description:String(record.description??""),primary_tag:String(record.primary_tag??""),cuisine:String(record.cuisine??""),price_range:String(record.price_range??""),semantic_tags:arr(record.semantic_tags)||arr([record.tags,record.search_keywords,record.intent_tags,record.vibe_tags,record.date_style_tags,record.special_features].flat()),best_for_tags:arr(record.best_for_tags)||arr(record.best_for),weekly_hours:formatOperatingHoursForEditor(record.operating_hours,record.google_opening_hours??record.google_regular_opening_hours??record.google_hours??record.regularOpeningHours??record.weekday_text)});
 const [status,setStatus]=useState(""); const [aiStatus,setAiStatus]=useState(""); const [ai,setAi]=useState<any>(null); const set=(k:string,val:any)=>setV(c=>({...c,[k]:val}));
 async function save(){setStatus("Saving…"); let operating_hours:any; try{operating_hours=parseWeeklyHoursFromEditor(v.weekly_hours)}catch(e:any){setStatus(e.message||"Weekly Hours could not be parsed.");return;} const updates:any={description:v.description,primary_tag:v.primary_tag,cuisine:v.cuisine,price_range:v.price_range,semantic_tags:normalizeTagList(v.semantic_tags),best_for_tags:normalizeTagList(v.best_for_tags),best_for:normalizeTagList(v.best_for_tags),operating_hours}; const res=await fetch(saveMode==="owner"?"/api/locations/edit-context":"/api/admin/crm/location-enhancement",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(saveMode==="owner"?{type,id,payload:updates}:{table,id,updates})}); const data=await res.json().catch(()=>({})); setStatus(res.ok?"Saved profile fields.":(data.error||"Could not save profile fields."));}
 async function generate(){setAiStatus("Generating suggestions...");setAi(null);const res=await fetch('/api/locations/optimize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,table,type,name:record.name??record.restaurant_name??record.activity_name,description:v.description,primary_tag:v.primary_tag,cuisine:v.cuisine,semantic_tags:v.semantic_tags,best_for_tags:v.best_for_tags,best_for:record.best_for,category:record.category,primary_category:record.primary_category,price_range:v.price_range,city:record.city,neighborhood:record.neighborhood,location_type:record.location_type})});const data=await res.json().catch(()=>({}));if(!res.ok){setAiStatus(data.error||'AI suggestions failed.');return;}setAi(data.suggestions);setAiStatus('');}
 function apply(field:string,value:any){if(value===undefined||value===null||value==='')return;setV(current=>({...current,[field]:field==='semantic_tags'||field==='best_for_tags'?mergeTags(current[field],value):String(value)}));setAiStatus(`${field.replaceAll('_',' ')} applied. Click Save to keep it.`);}
 function applyAll(){if(!ai)return;setV(current=>({...current,description:ai.description?String(ai.description):current.description,primary_tag:ai.primary_tag?String(ai.primary_tag):current.primary_tag,cuisine:ai.cuisine?String(ai.cuisine):current.cuisine,price_range:ai.price_range?String(ai.price_range):current.price_range,semantic_tags:mergeTags(current.semantic_tags,ai.semantic_tags),best_for_tags:mergeTags(current.best_for_tags,ai.best_for_tags)}));setAiStatus('All AI suggestions applied. Click Save to keep them.');}
 const sugg=(title:string,field:string,value:any)=><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-3"><p className="text-xs font-black uppercase tracking-[0.18em] text-white/45">{title}</p><p className="mt-1 whitespace-pre-wrap text-sm text-white">{Array.isArray(value)?value.join(', '):value||'—'}</p><button type="button" onClick={()=>apply(field,value)} disabled={!value} className="mt-2 rounded-full border border-white/10 px-3 py-1 text-xs font-black text-white disabled:cursor-not-allowed disabled:opacity-40">Apply</button></div>;
 return <section className="rounded-3xl border border-white/10 bg-white/[0.03] p-5"><div className="flex justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.25em] text-rose-200">Profile Editor</p><h2 className="mt-2 text-2xl font-black">Location Profile</h2></div><button type="button" onClick={save} disabled={!canEdit} className="h-fit rounded-full bg-rose-600 px-5 py-2.5 text-sm font-black text-white disabled:opacity-50">Save</button></div>{aiHelperEnabled?<div className="mt-4 rounded-2xl border border-rose-300/20 bg-rose-950/20 p-4"><button type="button" onClick={generate} disabled={!canEdit} className="rounded-full bg-rose-600 px-4 py-2 text-sm font-black text-white disabled:opacity-50">Generate with AI</button><p className="mt-2 text-xs text-white/50">Suggest Description, Primary Tag, Cuisine, Price Range, Search Boost Tags, and Best For Tags from this profile. {aiHelperAccessLabel??''}</p>{aiStatus?<p className="mt-2 text-sm font-bold text-white/70">{aiStatus}</p>:null}{ai?<div className="mt-4 grid gap-3"><div><h4 className="text-lg font-black">AI Suggestions</h4><p className="text-sm text-white/55">Review these suggestions before applying. They will not save until you click Save.</p></div><div className="grid gap-3 md:grid-cols-2">{sugg('Description','description',ai.description)}{sugg('Primary Tag','primary_tag',ai.primary_tag)}{sugg('Cuisine','cuisine',ai.cuisine)}{sugg('Price Range','price_range',ai.price_range)}{sugg('Search Boost Tags','semantic_tags',ai.semantic_tags)}{sugg('Best For Tags','best_for_tags',ai.best_for_tags)}</div><div className="flex gap-2"><button type="button" onClick={applyAll} className="rounded-full bg-white px-4 py-2 text-xs font-black text-black">Apply All Suggestions</button><button type="button" onClick={()=>setAi(null)} className="rounded-full border border-white/10 px-4 py-2 text-xs font-black text-white">Dismiss</button></div></div>:null}</div>:null}{status?<p className="mt-4 text-sm font-bold text-white/70">{status}</p>:null}<div className="mt-5 grid gap-4">
 <article className="rounded-2xl border border-white/10 bg-black/20 p-4"><h3 className="text-lg font-black">Profile Basics</h3><p className="text-sm text-white/55">Main details customers see and search uses.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><Field label="Description"><textarea value={v.description} onChange={e=>set('description',e.target.value)} rows={4} className={input}/></Field><Field label="Primary Tag" helper="Main category/search identity for the location."><input value={v.primary_tag} onChange={e=>set('primary_tag',e.target.value)} placeholder="Mediterranean restaurant, rooftop bar, hookah lounge, bowling alley" className={input}/></Field><Field label="Cuisine" helper="Food type or cuisine style."><input value={v.cuisine} onChange={e=>set('cuisine',e.target.value)} placeholder="Mediterranean, Italian, Seafood" className={input}/></Field><Field label="Price Range" helper="Choose the approved price range for this location."><select value={v.price_range} onChange={e=>set('price_range',e.target.value)} className={input}><option value="">Select price range</option>{PRICE_RANGE_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></Field></div></article>
 <article className="rounded-2xl border border-white/10 bg-black/20 p-4"><h3 className="text-lg font-black">Search & Matching</h3><p className="text-sm text-white/55">Help TheOutHaven match this place to the right searches.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><Field label="Search Boost Tags" helper="Words or phrases that help this place show up in the right searches."><textarea value={v.semantic_tags} onChange={e=>set('semantic_tags',e.target.value)} placeholder="romantic, live music, girls night" className={input}/></Field><Field label="Best For Tags" helper="Occasions, groups, or use cases this place is best for."><textarea value={v.best_for_tags} onChange={e=>set('best_for_tags',e.target.value)} placeholder="date night, brunch, family outing" className={input}/></Field></div></article>
 <article className="rounded-2xl border border-white/10 bg-black/20 p-4"><h3 className="text-lg font-black">Weekly Hours</h3><Field label="Weekly Hours" helper="Use AM/PM. Use one day per line. Use Closed for closed days. For split hours, separate ranges with a comma."><textarea value={v.weekly_hours} onChange={e=>set('weekly_hours',e.target.value)} rows={8} placeholder={"Monday - 8:30 AM - 10:30 PM\nTuesday - 8:30 AM - 10:30 PM\nSaturday - 10:00 AM - 2:00 AM\nSunday - Closed"} className={input}/></Field></article>
 {canViewAdvancedSystemData?<details className="rounded-2xl border border-white/10 bg-black/20 p-4"><summary className="cursor-pointer"><span className="text-lg font-black">Advanced / System Data</span><p className="text-sm text-white/55">Internal fields used by imports, reviews, and search.</p></summary><div className="mt-4 grid gap-3 md:grid-cols-2"><ReadOnly label="Review Keywords" helper="Auto-generated from reviews. Private/internal search data." value={record.review_keywords}/><ReadOnly label="Search Document" helper="Auto-generated combined search text. Used by search for faster matching." value={record.search_document}/><ReadOnly label="Semantic Search Text" helper="Generated natural-language search summary." value={record.semantic_search_text}/><ReadOnly label="Operating Hours JSON" value={record.operating_hours}/><ReadOnly label="Special Hours JSON" value={record.special_hours}/></div></details>:null}
 </div></section>}
