"use client";
import { useState, type ReactNode } from "react";
import { PRICE_RANGE_OPTIONS, normalizeTagList } from "@/lib/location-profile-fields";

type Props = { table?: string; id: string; record: Record<string, any>; canEdit: boolean; canViewAdvancedSystemData: boolean; saveMode?: "admin" | "owner"; type?: string };
const input="w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-white outline-none disabled:opacity-60";
const label="space-y-2 text-sm font-bold text-white/65";
function arr(v:any){return Array.isArray(v)?v.join(", "):String(v??"");}
function Field({label: l,helper,children}:{label:string;helper?:string;children:ReactNode}){return <label className={label}><span>{l}</span>{children}{helper?<p className="text-xs font-medium leading-5 text-white/45">{helper}</p>:null}</label>}
function ReadOnly({label:l,helper,value}:{label:string;helper?:string;value:any}){return <Field label={l} helper={helper}><textarea readOnly rows={4} value={Array.isArray(value)?value.join(", "):(value&&typeof value==='object'?JSON.stringify(value,null,2):String(value??""))} className={`${input} font-mono text-xs`} /></Field>}
export default function LocationProfileEditor({table="locations",id,record,canEdit,canViewAdvancedSystemData,saveMode="admin",type}:Props){
 const [v,setV]=useState({description:String(record.description??""),primary_tag:String(record.primary_tag??""),cuisine:String(record.cuisine??""),price_range:String(record.price_range??""),semantic_tags:arr(record.semantic_tags)||arr([record.tags,record.search_keywords,record.intent_tags,record.vibe_tags,record.date_style_tags,record.special_features].flat()),best_for_tags:arr(record.best_for_tags)||arr(record.best_for),operating_hours:record.operating_hours??null});
 const [status,setStatus]=useState(""); const set=(k:string,val:any)=>setV(c=>({...c,[k]:val}));
 async function save(){setStatus("Saving…"); const updates:any={description:v.description,primary_tag:v.primary_tag,cuisine:v.cuisine,price_range:v.price_range,semantic_tags:normalizeTagList(v.semantic_tags),best_for_tags:normalizeTagList(v.best_for_tags),best_for:normalizeTagList(v.best_for_tags),operating_hours:v.operating_hours};
 const res=await fetch(saveMode==="owner"?"/api/locations/edit-context":"/api/admin/crm/location-enhancement",{method:saveMode==="owner"?"PATCH":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(saveMode==="owner"?{type,id,payload:updates}:{table,id,updates})}); const data=await res.json().catch(()=>({})); setStatus(res.ok?("Saved profile fields."):(data.error||"Could not save profile fields."));}
 return <section className="rounded-3xl border border-white/10 bg-white/[0.03] p-5"><div className="flex justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.25em] text-rose-200">Profile Editor</p><h2 className="mt-2 text-2xl font-black">Location Profile</h2></div><button type="button" onClick={save} disabled={!canEdit} className="h-fit rounded-full bg-rose-600 px-5 py-2.5 text-sm font-black text-white disabled:opacity-50">Save</button></div>{status?<p className="mt-4 text-sm font-bold text-white/70">{status}</p>:null}<div className="mt-5 grid gap-4">
  <article className="rounded-2xl border border-white/10 bg-black/20 p-4"><h3 className="text-lg font-black">Profile Basics</h3><p className="text-sm text-white/55">Main details customers see and search uses.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><Field label="Description"><textarea value={v.description} onChange={e=>set('description',e.target.value)} rows={4} className={input}/></Field><Field label="Primary Tag" helper="Main category/search identity for the location."><input value={v.primary_tag} onChange={e=>set('primary_tag',e.target.value)} placeholder="Mediterranean restaurant, rooftop bar, hookah lounge, bowling alley" className={input}/></Field><Field label="Cuisine" helper="Food type or cuisine style. Use this for restaurants, cafes, lounges with food, brunch spots, dessert spots, and other food-related locations."><input value={v.cuisine} onChange={e=>set('cuisine',e.target.value)} placeholder="Mediterranean, Italian, Seafood, Caribbean, Soul food, Vegan" className={input}/></Field><Field label="Price Range" helper="Choose the approved price range for this location."><select value={v.price_range} onChange={e=>set('price_range',e.target.value)} className={input}><option value="">Select price range</option>{PRICE_RANGE_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></Field></div></article>
  <article className="rounded-2xl border border-white/10 bg-black/20 p-4"><h3 className="text-lg font-black">Search & Matching</h3><p className="text-sm text-white/55">Help TheOutHaven match this place to the right searches.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><Field label="Search Boost Tags" helper="Words or phrases that help this place show up in the right searches."><textarea value={v.semantic_tags} onChange={e=>set('semantic_tags',e.target.value)} placeholder="romantic, live music, girls night, birthday dinner, cozy, outdoor seating" className={input}/></Field><Field label="Best For Tags" helper="Occasions, groups, or use cases this place is best for."><textarea value={v.best_for_tags} onChange={e=>set('best_for_tags',e.target.value)} placeholder="date night, brunch, family outing, friends night, anniversary, group dinner" className={input}/></Field></div></article>
  <article className="rounded-2xl border border-white/10 bg-black/20 p-4"><h3 className="text-lg font-black">Weekly Hours</h3><p className="text-sm text-white/55">Use one day per line. Use AM/PM. Use Closed for closed days.</p><p className="mt-2 whitespace-pre-line text-xs text-white/45">Monday - 8:30 AM - 10:30 PM{"\n"}Tuesday - 8:30 AM - 10:30 PM{"\n"}Wednesday - 8:30 AM - 10:30 PM{"\n"}Thursday - 8:30 AM - 10:30 PM{"\n"}Friday - 8:30 AM - 11:30 PM{"\n"}Saturday - 10:00 AM - 11:30 PM{"\n"}Sunday - 10:00 AM - 9:00 PM</p></article>
  {canViewAdvancedSystemData?<details className="rounded-2xl border border-white/10 bg-black/20 p-4"><summary className="cursor-pointer"><span className="text-lg font-black">Advanced / System Data</span><p className="text-sm text-white/55">Internal fields used by imports, reviews, and search.</p></summary><div className="mt-4 grid gap-3 md:grid-cols-2"><ReadOnly label="Review Keywords" helper="Auto-generated from reviews. Private/internal search data." value={record.review_keywords}/><ReadOnly label="Search Document" helper="Auto-generated combined search text. Used by search for faster matching." value={record.search_document}/><ReadOnly label="Semantic Search Text" helper="Generated natural-language search summary." value={record.semantic_search_text}/><ReadOnly label="Operating Hours JSON" value={record.operating_hours}/><ReadOnly label="Special Hours JSON" value={record.special_hours}/></div></details>:null}
 </div></section>}
