"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type Props = { initialData: any; locationId: string; mode?: "business" | "admin"; contextKey?: "locationId" | "adminLocationId" | "demoLocationId"; returnHref?: string; canEdit?: boolean; embedded?: boolean; contextPayload?: Record<string, any> };
const input = "w-full rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-sm font-bold text-white outline-none focus:border-rose-300/50";

export default function MenuEditorClient({ initialData, locationId, mode = "business", contextKey = "locationId", returnHref, canEdit, embedded = false, contextPayload = {} }: Props) {
  const [data, setData] = useState(initialData?.data || initialData);
  const effectiveCanEdit = canEdit ?? data?.permissions?.canEdit !== false;
  const [busy, setBusy] = useState(false);
  const page = data?.page || {};
  const sections = data?.sections || [];
  const items = data?.items || [];
  const [settings, setSettings] = useState({ title: page.title || "Menu", description: page.description || "", external_url: page.external_url || "", pdf_url: page.pdf_url || "", status: page.status || (page.is_active ? "published" : "draft") });
  const [sectionTitle, setSectionTitle] = useState("");
  const [item, setItem] = useState({ section_id: "", name: "", description: "", price_cents: "", price_label: "", image_url: "", tags: "", is_available: true, is_featured: false });
  const grouped = useMemo(() => Object.groupBy ? Object.groupBy(items, (x: any) => x.section_id || "") : items.reduce((a:any,x:any)=>((a[x.section_id||""] ||= []).push(x),a),{}), [items]);
  const stats = { sections: sections.length, items: items.length, unavailable: items.filter((x:any)=>x.is_available === false).length };
  async function call(method: string, body: any) { setBusy(true); const res = await fetch("/api/business/menu", { method, headers: { "content-type": "application/json" }, body: JSON.stringify({ ...contextPayload, ...body, [contextKey]: locationId, locationId }) }); const json = await res.json(); setBusy(false); if (!res.ok) return alert(json.message || "Menu could not be saved"); setData(json.data); return json; }
  return <main className={embedded ? "text-white" : "min-h-screen bg-[#07090d] p-4 text-white sm:p-6 lg:p-8"}>
    <div className={embedded ? "space-y-5" : "mx-auto max-w-7xl space-y-5"}>
      <section className="rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_top_left,rgba(225,6,42,.25),transparent_35%),linear-gradient(135deg,#14090d,#0a0b10)] p-5 shadow-2xl shadow-black/40">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.28em] text-rose-200">TheOutHaven Commerce</p><h1 className="mt-2 text-4xl font-black">Menu Manager</h1><p className="mt-2 text-white/60">Create, edit, preview, and publish your menu.</p><p className="mt-2 text-sm font-bold text-white/45">{data?.location?.name || data?.location?.location_name || "Selected location"}</p></div><div className="flex flex-wrap gap-2"><Status status={settings.status}/><Link href={data?.previewUrl || "#"} className="rounded-full border border-white/15 px-4 py-2 text-sm font-black">Preview public menu</Link>{returnHref ? <Link href={returnHref} className="rounded-full border border-white/15 px-4 py-2 text-sm font-black">Back</Link> : null}<button disabled={!effectiveCanEdit || busy} onClick={() => call("PATCH", { action: settings.status === "published" ? "unpublish_page" : "publish_page", ...settings })} className="rounded-full bg-rose-600 px-5 py-2 text-sm font-black disabled:opacity-50">{settings.status === "published" ? "Unpublish" : "Publish"}</button></div></div>
      </section>
      <div className="grid gap-5 xl:grid-cols-[1fr_320px]"><div className="space-y-5">
        <Card title="Menu page settings"><div className="grid gap-3 md:grid-cols-2"><label>Title<input className={input} value={settings.title} onChange={e=>setSettings({...settings,title:e.target.value})}/></label><label>Status<select className={input} value={settings.status} onChange={e=>setSettings({...settings,status:e.target.value})}><option>draft</option><option>published</option><option>hidden</option></select></label><label className="md:col-span-2">Description<textarea className={input} rows={3} value={settings.description} onChange={e=>setSettings({...settings,description:e.target.value})}/></label><label>External menu URL<input className={input} value={settings.external_url} onChange={e=>setSettings({...settings,external_url:e.target.value})}/></label><label>PDF menu URL<input className={input} value={settings.pdf_url} onChange={e=>setSettings({...settings,pdf_url:e.target.value})}/></label></div><button disabled={!effectiveCanEdit||busy} onClick={()=>call("PATCH",{action:"update_page",...settings})} className="mt-4 rounded-full bg-white px-5 py-2 text-sm font-black text-black disabled:opacity-50">Save settings</button></Card>
        <Card title="Sections & items" action={<div className="flex gap-2"><input value={sectionTitle} onChange={e=>setSectionTitle(e.target.value)} placeholder="New section" className={input}/><button disabled={!effectiveCanEdit||busy} onClick={async()=>{await call("POST",{action:"create_section",title:sectionTitle});setSectionTitle("")}} className="rounded-2xl bg-rose-600 px-4 text-sm font-black disabled:opacity-50">Add section</button></div>}>{!sections.length ? <div className="rounded-3xl border border-dashed border-white/15 bg-black/25 p-8 text-center"><h3 className="text-2xl font-black">No menu yet</h3><p className="mt-2 text-white/55">Add your first section to start building your public menu.</p></div> : <div className="space-y-4">{sections.map((s:any,si:number)=><details key={s.id} open className="rounded-3xl border border-white/10 bg-black/25 p-4"><summary className="cursor-pointer text-xl font-black">{s.title || s.name}<span className="ml-3 text-xs text-white/35">#{si+1}</span></summary><div className="mt-3 grid gap-3">{(grouped[s.id]||[]).map((it:any)=><div key={it.id} className="rounded-2xl border border-white/10 bg-white/[.04] p-3"><div className="flex justify-between gap-3"><div><p className="font-black">{it.name} {it.is_featured ? <span className="text-rose-200">Featured</span>:null}</p><p className="text-sm text-white/50">{it.description}</p><p className="text-sm font-bold">{it.price_label || it.price || (it.price_cents != null ? `$${(it.price_cents/100).toFixed(2)}` : "")}</p></div><div className="flex gap-2"><button onClick={()=>call("PATCH",{action:"update_item", item_id:it.id, ...it, is_available:!it.is_available})} className="text-xs font-black text-white/60">{it.is_available?"Mark unavailable":"Mark available"}</button><button onClick={()=>call("DELETE",{action:"delete_item",item_id:it.id})} className="text-xs font-black text-rose-200">Delete</button></div></div></div>)}<button onClick={()=>setItem({...item,section_id:s.id})} className="rounded-2xl border border-white/10 px-4 py-2 text-sm font-black text-white/70">Add item here</button></div></details>)}</div>}</Card>
        {item.section_id ? <Card title="Item editor"><div className="grid gap-3 md:grid-cols-2"><input className={input} placeholder="Item name" value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/><input className={input} placeholder="Price cents (1299)" value={item.price_cents} onChange={e=>setItem({...item,price_cents:e.target.value})}/><input className={input} placeholder="Price label" value={item.price_label} onChange={e=>setItem({...item,price_label:e.target.value})}/><input className={input} placeholder="Image URL" value={item.image_url} onChange={e=>setItem({...item,image_url:e.target.value})}/><input className={input} placeholder="Tags comma-separated" value={item.tags} onChange={e=>setItem({...item,tags:e.target.value})}/><textarea className={input} placeholder="Description" value={item.description} onChange={e=>setItem({...item,description:e.target.value})}/></div><div className="mt-3 flex flex-wrap gap-3"><label><input type="checkbox" checked={item.is_available} onChange={e=>setItem({...item,is_available:e.target.checked})}/> Available</label><label><input type="checkbox" checked={item.is_featured} onChange={e=>setItem({...item,is_featured:e.target.checked})}/> Featured</label><button onClick={async()=>{await call("POST",{action:"create_item",...item,price_cents:item.price_cents?Number(item.price_cents):null,tags:item.tags.split(',').map(t=>t.trim()).filter(Boolean)});setItem({...item,name:"",description:"",price_cents:"",price_label:"",image_url:"",tags:""})}} className="rounded-full bg-rose-600 px-5 py-2 text-sm font-black">Save item</button><button onClick={()=>setItem({...item,section_id:""})} className="rounded-full border border-white/10 px-5 py-2 text-sm font-black">Cancel</button></div></Card> : null}
      </div><aside className="space-y-4"><Card title="Summary"><p>{stats.sections} sections</p><p>{stats.items} items</p><p>{stats.unavailable} unavailable</p><p className="mt-3 text-sm text-white/45">Last updated: {page.updated_at ? new Date(page.updated_at).toLocaleString() : "Not saved"}</p></Card><Card title="Quick actions"><div className="grid gap-2"><button onClick={()=>setSectionTitle(sectionTitle||"New Section")} className="rounded-2xl border border-white/10 px-4 py-3 text-left font-black">Add section</button><button onClick={()=>setItem({...item,section_id:sections[0]?.id||""})} className="rounded-2xl border border-white/10 px-4 py-3 text-left font-black">Add item</button><Link href={data?.previewUrl || "#"} className="rounded-2xl border border-white/10 px-4 py-3 font-black">Preview public menu</Link></div></Card></aside></div>
    </div>
  </main>;
}
function Card({title,action,children}:any){return <section className="rounded-[1.6rem] border border-white/10 bg-[#10131a] p-5 shadow-xl shadow-black/20"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-xl font-black">{title}</h2>{action}</div>{children}</section>}
function Status({status}:any){return <span className="rounded-full border border-rose-300/20 bg-rose-500/10 px-3 py-2 text-xs font-black uppercase tracking-widest text-rose-100">{status || "draft"}</span>}
