import { getEmailSignature, type EmailDepartment } from "../emailDepartments";

type BaseEmailLayoutProps = { previewText?: string; heading: string; bodyHtml: string; ctaLabel?: string; ctaUrl?: string; department?: EmailDepartment | string; signature?: string; footerNote?: string };
const escapeHtml = (v: string) => String(v).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const signatureToHtml = (s: string) => escapeHtml(s).replace(/\n/g, "<br />");

export function baseEmailLayout({ previewText, heading, bodyHtml, ctaLabel, ctaUrl, department, signature, footerNote }: BaseEmailLayoutProps) {
  const finalSignature = signature || getEmailSignature(department);
  const buttonHtml = ctaLabel && ctaUrl ? `<tr><td style="padding: 28px 0 8px 0;"><a href="${escapeHtml(ctaUrl)}" style="display:inline-block;background:#ffffff;color:#111111;text-decoration:none;font-weight:700;font-size:15px;line-height:20px;padding:14px 22px;border-radius:999px;">${escapeHtml(ctaLabel)}</a></td></tr><tr><td style="padding: 10px 0 0 0;color:#a7a7a7;font-size:13px;line-height:20px;">If the button does not work, copy and paste this link into your browser:<br /><a href="${escapeHtml(ctaUrl)}" style="color:#ffffff;text-decoration:underline;word-break:break-all;">${escapeHtml(ctaUrl)}</a></td></tr>` : "";
  return `<!doctype html><html><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width,initial-scale=1" /><title>${escapeHtml(heading)}</title></head><body style="margin:0;padding:0;background:#0b0b0c;color:#f5f5f5;font-family:Arial,Helvetica,sans-serif;">${previewText ? `<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">${escapeHtml(previewText)}</div>` : ""}<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#0b0b0c;margin:0;padding:32px 16px;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#141416;border:1px solid #2a2a2d;border-radius:24px;overflow:hidden;"><tr><td style="padding:28px 28px 10px 28px;"><div style="font-size:13px;letter-spacing:.16em;text-transform:uppercase;color:#b9b9bd;font-weight:700;">TheOutHaven.com</div><h1 style="margin:18px 0 0 0;color:#ffffff;font-size:30px;line-height:38px;font-weight:800;">${escapeHtml(heading)}</h1></td></tr><tr><td style="padding:8px 28px 28px 28px;color:#dedee3;font-size:16px;line-height:25px;">${bodyHtml}<table role="presentation" cellspacing="0" cellpadding="0">${buttonHtml}</table><div style="margin-top:30px;color:#dedee3;font-size:15px;line-height:24px;">${signatureToHtml(finalSignature)}</div>${footerNote ? `<div style="margin-top:18px;color:#9b9ba1;font-size:13px;line-height:20px;">${footerNote}</div>` : ""}</td></tr></table><div style="max-width:640px;margin:18px auto 0 auto;color:#8c8c92;font-size:12px;line-height:18px;text-align:center;">You are receiving this email from TheOutHaven.com.</div></td></tr></table></body></html>`;
}
