import Link from "next/link";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { getPublicLocationHref } from "@/lib/locations/public-location-url";
export const dynamic = "force-dynamic";
function price(it:any){return it.price_label || it.price || (it.price_cents != null ? `$${(it.price_cents/100).toFixed(2)}` : "");}
function tags(v:any){return Array.isArray(v) ? v : typeof v === "string" ? (()=>{try{return JSON.parse(v)}catch{return v.split(',')}})() : []}
function typePlural(t:string){return t === "activities" || t === "activity" ? "activities" : "restaurants"}
async function resolveLocation(locationId:string){
  const { data } = await supabaseAdmin.from("locations").select("*").or(`id.eq.${locationId},source_id.eq.${locationId},source_location_id.eq.${locationId}`).maybeSingle();
  return data;
}
export default async function Page({ params, searchParams }: { params: Promise<{ type: string; locationId: string }>; searchParams?: Promise<Record<string,string|string[]|undefined>> }) {
  const { type, locationId } = await params; const sp = (await searchParams) || {};
  const preview = sp.demo === "1" || sp.fromDemoCenter === "1" || sp.adminLocationMode === "1" || Boolean(sp.adminLocationId);
  const requestedId = String(sp.adminLocationId || sp.locationId || locationId);
  const location = await resolveLocation(requestedId) || await resolveLocation(locationId);
  const canonicalId = String(location?.id || requestedId);
  let pageQuery = supabaseAdmin.from("location_commerce_pages").select("*").eq("location_id", canonicalId).eq("page_type", "menu").order("sort_order").limit(1);
  if (!preview) pageQuery = pageQuery.eq("status", "published").eq("is_active", true);
  const { data: page } = await pageQuery.maybeSingle();
  const [sectionsRes, itemsRes] = page ? await Promise.all([supabaseAdmin.from("location_commerce_sections").select("*").eq("location_id", canonicalId).eq("commerce_page_id", page.id).eq("is_active", true).order("sort_order"), supabaseAdmin.from("location_commerce_items").select("*").eq("location_id", canonicalId).eq("commerce_page_id", page.id).order("is_available", { ascending: false }).order("sort_order")]) : [{data:[]},{data:[]}];
  const sections = sectionsRes.data || [], items = itemsRes.data || [];
  const grouped = items.reduce((a:any,x:any)=>((a[x.section_id||""] ||= []).push(x),a),{});
  const back = getPublicLocationHref(location || { id: locationId, type });
  const editorParams = new URLSearchParams(); for (const [k,v] of Object.entries(sp)) if (typeof v === 'string') editorParams.set(k,v); if (preview) { editorParams.set('adminLocationId', canonicalId); editorParams.set('locationId', canonicalId); editorParams.set('type', typePlural(type)==='activities'?'activity':'restaurant'); }
  const editorBack = `/locations/${typePlural(type)}/${encodeURIComponent(locationId)}/edit${editorParams.toString()?`?${editorParams}`:''}#menu`;
  return <main className="min-h-screen bg-[#07090d] text-white"><section className="border-b border-white/10 bg-[radial-gradient(circle_at_top,rgba(225,6,42,.25),transparent_35%),#0b0d12] px-4 py-12"><div className="mx-auto max-w-5xl"><Link href={back} className="text-sm font-black text-rose-200">← Back to location</Link>{preview && page && page.status !== 'published' ? <span className="ml-3 rounded-full bg-amber-400/15 px-3 py-1 text-xs font-black uppercase text-amber-100">Draft preview</span> : null}<h1 className="mt-4 text-5xl font-black">{page?.title || "Menu"}</h1><p className="mt-3 text-xl text-white/70">{location?.name || location?.location_name || "TheOutHaven location"}</p><p className="mt-2 text-white/45">{[location?.address, location?.city, location?.state].filter(Boolean).join(", ")}</p>{page?.description ? <p className="mt-5 max-w-3xl text-white/65">{page.description}</p> : null}</div></section><div className="mx-auto max-w-5xl space-y-8 px-4 py-8">{!page ? <div className="rounded-3xl border border-white/10 bg-white/[.04] p-8 text-center"><h2 className="text-3xl font-black">{preview ? "No menu has been created yet." : "Menu is not available yet."}</h2><p className="mt-2 text-white/55">{preview ? "Go back to Menu Editor to add sections and items." : "Please check back soon."}</p><Link href={preview ? editorBack : back} className="mt-5 inline-flex rounded-full bg-rose-600 px-5 py-3 font-black">{preview ? "Back to Menu Editor" : "Back to profile"}</Link></div> : sections.map((s:any)=><section key={s.id} className="rounded-[1.7rem] border border-white/10 bg-[#10131a] p-5"><h2 className="text-3xl font-black">{s.title || s.name}</h2>{s.description ? <p className="mt-2 text-white/55">{s.description}</p> : null}<div className="mt-5 grid gap-4 md:grid-cols-2">{(grouped[s.id]||[]).map((it:any)=><article key={it.id} className={`overflow-hidden rounded-3xl border border-white/10 bg-black/25 ${it.is_available === false ? "opacity-55" : ""}`}>{it.image_url ? <img src={it.image_url} alt="" className="h-44 w-full object-cover"/> : null}<div className="p-4"><div className="flex justify-between gap-3"><h3 className="text-xl font-black">{it.name}</h3><p className="font-black text-rose-100">{price(it)}</p></div><p className="mt-2 text-sm text-white/55">{it.description}</p><div className="mt-3 flex flex-wrap gap-2">{it.is_featured ? <span className="rounded-full bg-rose-500/15 px-2 py-1 text-xs font-black text-rose-100">Featured</span> : null}{it.is_available === false ? <span className="rounded-full bg-white/10 px-2 py-1 text-xs font-black">Unavailable</span> : null}{tags(it.tags).map((t:string)=><span key={t} className="rounded-full border border-white/10 px-2 py-1 text-xs font-bold text-white/60">{t}</span>)}</div></div></article>)}</div></section>)}</div></main>;
}
