"use client";
import Link from "next/link";
import { formatReservationTime } from "@/lib/reservations/ui";
import { dedupeFloorResources, getFloorSnapshotState, resourceCapacity, resourceId, resourceName } from "@/lib/reservations/floorSnapshot";

export default function ReserveFloorSnapshot({resources,reservations,onReservationSelect,onResourceSelect,assigningReservation,assigningResourceId,settingsHref="/reserve/dashboard?tab=settings&section=layout"}:{resources:any[];reservations:any[];onReservationSelect?:(reservation:any)=>void;onResourceSelect?:(resource:any)=>void;assigningReservation?:any;assigningResourceId?:string;settingsHref?:string}){
  const floorResources=dedupeFloorResources(resources);
  return <section className="reserve-card rounded-[2rem] p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase reserve-muted">Floor snapshot</p><h2 className="text-xl font-black">Tables & spaces</h2>{assigningReservation&&<p className="mt-1 text-xs font-bold text-red-500">Choose a table for {assigningReservation.customer_name||'this guest'}.</p>}</div><Link href={settingsHref} className="whitespace-nowrap text-xs font-black text-red-500">Set up layout</Link></div>{floorResources.length? <div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-2 2xl:grid-cols-3">{floorResources.map((resource)=>{const id=resourceId(resource);const state=getFloorSnapshotState(resource,reservations);const inAssignMode=Boolean(assigningReservation);const disabled=inAssignMode&&!state.available;const assigning=assigningResourceId===id;const statusClass=state.status==='Open'?'bg-emerald-500/15 text-emerald-600':state.status==='Seated'?'bg-red-500/15 text-red-600':state.status==='Arrived'?'bg-amber-500/15 text-amber-600':'bg-black/10';return <button type="button" key={id||`${resourceName(resource)}-${resourceCapacity(resource)}`} disabled={disabled||assigning} onClick={()=>{if(inAssignMode){if(state.available)onResourceSelect?.(resource);return;} if(state.reservation)onReservationSelect?.(state.reservation);}} className={`reserve-soft min-h-[92px] rounded-2xl p-3 text-left transition disabled:cursor-not-allowed disabled:opacity-55 ${inAssignMode&&state.available?'cursor-pointer ring-2 ring-emerald-500/60 hover:scale-[1.01]':'hover:scale-[1.002]'}`}><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate text-sm font-black">{resourceName(resource)}</p><p className="text-[11px] reserve-muted">Cap {resourceCapacity(resource)||'—'}</p></div><span className={`inline-flex max-w-max shrink-0 whitespace-nowrap rounded-full px-2 py-0.5 text-[11px] font-black leading-5 ${statusClass}`}>{state.status}{state.available?' · Available':' · Unavailable'}</span></div>{state.reservation?<div className="mt-2 rounded-xl bg-black/10 px-2 py-1.5"><p className="truncate text-xs font-black">{state.reservation.customer_name||'Guest'}</p><p className="text-[11px] reserve-muted">Party {state.reservation.party_size||'—'} · {formatReservationTime(state.reservation.reservation_time)}</p></div>:<p className="mt-2 text-xs font-bold reserve-muted">{assigning?'Assigning table…':inAssignMode&&state.available?'Click to assign':state.available?'Open':'Unavailable'}</p>}</button>})}</div>:<div className="reserve-soft mt-4 rounded-2xl p-5"><p className="font-black">No tables or bookable spaces are set up yet.</p><p className="mt-1 text-sm reserve-muted">Set up a layout to assign reservations to real floor resources.</p><Link className="mt-3 inline-block reserve-primary rounded-full px-4 py-2 text-sm font-black" href={settingsHref}>Set up layout</Link></div>}</section>
}
