"use client";
import { formatReservationTime, getReservationPrimaryNextAction, getReservationStatusLabel } from '@/lib/reservations/ui';
import ReserveQuickActionButton from './ReserveQuickActionButton';
import ReserveStatusBadge from './ReserveStatusBadge';

function assigned(reservation:any){return reservation.assigned_resource_label||reservation.reservable_item_name||reservation.resource_label||'Unassigned'}

export default function ReserveTimeline({reservations,selectedId,onSelect,onStatus,onAssign,updatingId}:{reservations:any[];selectedId?:string;onSelect:(r:any)=>void;onStatus:(r:any,s:string)=>void;onAssign?:(r:any)=>void;updatingId?:string}){
  return <div className="space-y-1.5">{reservations.map((reservation)=>{const action=getReservationPrimaryNextAction(reservation.status);return <button type="button" key={reservation.id} onClick={()=>onSelect(reservation)} className={`reserve-soft w-full rounded-xl px-2.5 py-2 text-left transition hover:scale-[1.002] ${selectedId===reservation.id?'ring-2 ring-red-600 bg-red-500/10':''}`}><div className="grid gap-1.5 sm:grid-cols-[64px_minmax(0,1fr)_auto] sm:items-center"><p className="whitespace-nowrap text-xs font-black">{formatReservationTime(reservation.reservation_time)}</p><div className="min-w-0"><div className="flex min-w-0 flex-wrap items-center gap-1.5"><h3 className="min-w-0 truncate text-sm font-black">{reservation.customer_name||'Guest'}</h3><ReserveStatusBadge status={reservation.status} label={getReservationStatusLabel(reservation.status)}/></div><p className="mt-0.5 truncate text-[11px] leading-4 reserve-muted">Party {reservation.party_size||'—'} · {assigned(reservation)}</p></div><div className="flex flex-wrap gap-1 sm:flex-nowrap sm:justify-end" onClick={(event)=>event.stopPropagation()}><ReserveQuickActionButton disabled={updatingId===reservation.id || !!action.disabledReason || !action.targetStatus} title={action.disabledReason} onClick={()=>action.targetStatus&&onStatus(reservation,action.targetStatus)}>{updatingId===reservation.id?'Updating…':action.label}</ReserveQuickActionButton>{onAssign&&<ReserveQuickActionButton onClick={()=>onAssign(reservation)}>Assign</ReserveQuickActionButton>}</div></div></button>})}</div>
}
