import { NextRequest, NextResponse } from "next/server";
import { requireAdminApiRole } from "@/lib/admin-api-auth";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { normalizeAnchorText } from "@/lib/search/anchors/normalize";
const roles = ["superadmin", "admin", "manager"] as const;
const writable = new Set(["canonical_name","aliases","anchor_type","source_type","city","state","borough","neighborhood","county","market","latitude","longitude","default_radius_miles","max_radius_miles","radius_strategy","google_place_id","external_id","linked_location_id","priority","confidence","is_active","is_searchable","review_status","metadata"]);
export async function GET(_: NextRequest, ctx: { params: Promise<{ id: string }> }) { const auth = await requireAdminApiRole(roles); if (auth.error) return auth.error; const { id } = await ctx.params; const { data, error } = await supabaseAdmin.from("search_anchors").select("*").eq("id", id).single(); return error ? NextResponse.json({ success:false,error:error.message},{status:404}) : NextResponse.json({ success:true, anchor:data }); }
export async function PATCH(req: NextRequest, ctx: { params: Promise<{ id: string }> }) { const auth = await requireAdminApiRole(roles); if (auth.error) return auth.error; const { id } = await ctx.params; const input = await req.json().catch(()=>({})); const payload:any={}; for (const [k,v] of Object.entries(input)) if (writable.has(k)) payload[k]=v; if (payload.canonical_name) payload.normalized_name=normalizeAnchorText(payload.canonical_name); const { data,error } = await supabaseAdmin.from("search_anchors").update(payload).eq("id",id).select("*").single(); return error ? NextResponse.json({success:false,error:error.message},{status:400}) : NextResponse.json({success:true,anchor:data}); }
export async function DELETE(_: NextRequest, ctx: { params: Promise<{ id: string }> }) { const auth = await requireAdminApiRole(roles); if (auth.error) return auth.error; const { id } = await ctx.params; const { data: anchor } = await supabaseAdmin.from("search_anchors").select("usage_count,successful_search_count,no_result_count").eq("id", id).single(); if (Number(anchor?.usage_count ?? 0) > 0) { const { error } = await supabaseAdmin.from("search_anchors").update({ is_active:false,is_searchable:false,review_status:"disabled" }).eq("id",id); return NextResponse.json({success:!error, soft_deleted:true, error:error?.message}); } const { error } = await supabaseAdmin.from("search_anchors").delete().eq("id", id); return NextResponse.json({ success: !error, error: error?.message }); }
