"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clipboard, ExternalLink, RefreshCw, Rocket, ShieldAlert } from "lucide-react";
import { areas, roles, statusLabels, STATUS_OPTIONS } from "@/lib/production-finish-line/seeds";

type Row = Record<string, any>;
type Data = { items: Row[]; access: Row[]; qr: Row[]; commands: Row[]; prompts: Row[] };
const empty: Data = { items: [], access: [], qr: [], commands: [], prompts: [] };
const cls: Record<string,string> = { passed:"border-emerald-400/30 bg-emerald-500/15 text-emerald-100", blocked:"border-red-400/30 bg-red-500/15 text-red-100", in_progress:"border-sky-400/30 bg-sky-500/15 text-sky-100", testing:"border-blue-400/30 bg-blue-500/15 text-blue-100", pr_open:"border-purple-400/30 bg-purple-500/15 text-purple-100", needs_codex:"border-amber-400/30 bg-amber-500/15 text-amber-100", skipped:"border-white/15 bg-white/10 text-white/60", not_started:"border-white/15 bg-white/[0.04] text-white/55", not_run:"border-white/15 bg-white/[0.04] text-white/55", failed:"border-red-400/30 bg-red-500/15 text-red-100" };
function Pill({ value }: { value:string }) { return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[11px] font-black uppercase ${cls[value] || cls.not_started}`}>{statusLabels[value] || value}</span>; }
function Card({ children, className="" }: { children:React.ReactNode; className?:string }) { return <section className={`rounded-3xl border border-white/10 bg-[#0b1020]/82 p-4 shadow-2xl shadow-black/20 ${className}`}>{children}</section>; }
function Field({ row, collection, name, value, onSave, type="text" }: any) { const [v,setV]=useState(value ?? ""); useEffect(()=>setV(value ?? ""),[value]); const save=()=>String(v)!==String(value??"")&&onSave(collection,row.id,{[name]:v}); return <input type={type} value={v} onChange={e=>setV(e.target.value)} onBlur={save} className="w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-xs text-white outline-none focus:border-purple-400/60" />; }
function Notes(p:any){return <textarea value={p.value??""} onChange={e=>p.onSave(p.collection,p.row.id,{[p.name||"notes"]:e.target.value})} rows={2} className="w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-xs text-white outline-none focus:border-purple-400/60"/>}
function StatusSelect({row,collection,onSave,field="status", options=STATUS_OPTIONS}: any){return <select value={row[field]||"not_started"} onChange={e=>onSave(collection,row.id,{[field]:e.target.value,last_checked:new Date().toISOString()})} className="rounded-xl border border-white/10 bg-[#111827] px-2 py-2 text-xs font-bold text-white"><option value="not_run">Not run</option>{options.map((s:string)=><option key={s} value={s}>{statusLabels[s]||s}</option>)}<option value="failed">Failed</option></select>}
async function copy(t:string){ await navigator.clipboard?.writeText(t); }

export default function ProductionCommandCenterClient({ adminName, adminRole }: { adminName:string; adminRole:string }) {
 const [data,setData]=useState<Data>(empty); const [loading,setLoading]=useState(true); const [tab,setTab]=useState("Week 1");
 const load=async()=>{setLoading(true); const r=await fetch('/api/admin/production-finish-line',{cache:'no-store'}); const j=await r.json(); if(j.success) setData(j.data); setLoading(false)}; useEffect(()=>{load()},[]);
 const save=async(collection:string,id:string,updates:Row)=>{setData(d=>({...d,[collection]:d[collection as keyof Data].map((r:Row)=>r.id===id?{...r,...updates}:r)})); await fetch('/api/admin/production-finish-line',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({collection,id,updates})});};
 const gates=data.items.filter(i=>i.item_type==='gate'), tasks=data.items.filter(i=>i.item_type==='daily_task'), decision=data.items.find(i=>i.item_type==='decision'), check=(t:string)=>data.items.filter(i=>i.item_type===t);
 const kpi=useMemo(()=>{const scored=[...gates,...data.commands.map(c=>({...c,status:c.result==='passed'?'passed':c.result==='failed'?'blocked':c.result}))]; const passed=scored.filter(i=>i.status==='passed').length; const score=scored.length?Math.round(passed/scored.length*100):0; const p0Blocked=gates.filter(g=>g.priority==='P0'&&g.status==='blocked').length; const p1=gates.filter(g=>g.priority==='P1'&&g.status!=='passed'&&g.status!=='skipped').length; const prod=gates.find(g=>g.title==='Production Checks')?.status; const overall=p0Blocked?'Not Ready':(gates.filter(g=>g.priority==='P0').every(g=>g.status==='passed')?(prod==='passed'?'Ready for Production':'Ready for Pilot'):'Not Ready'); return {score,p0Blocked,p1,prod,overall};},[gates,data.commands]);
 const promptPassed=data.prompts.filter(p=>p.status==='passed').length, blockers=data.prompts.filter(p=>p.status==='blocked'||p.status==='needs_codex').slice(0,3);
 return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,rgba(124,58,237,.25),transparent_35%),linear-gradient(135deg,#020617,#050816_55%,#08040f)] px-4 pb-14 pt-6 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-[1600px] space-y-5">
  <header className="rounded-[2rem] border border-white/10 bg-black/30 p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.32em] text-purple-200">Admin / Launch Ops</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">Production Finish Line Command Center</h1><p className="mt-2 text-sm text-white/65">Track every step to production. Fix issues. Ship with confidence.</p></div><div className="flex flex-wrap gap-2"><button onClick={load} className="rounded-full border border-white/10 bg-white/10 px-4 py-2 text-sm font-black"><RefreshCw className="mr-2 inline h-4 w-4"/>Refresh</button><span className="rounded-full border border-purple-300/30 bg-purple-500/15 px-4 py-2 text-sm font-black">{adminName} · {adminRole}</span></div></div></header>
  <div className="grid gap-3 md:grid-cols-5">{[["Readiness Score",`${kpi.score}%`],["Overall Status",kpi.overall],["P0 Blockers",kpi.p0Blocked],["P1 Items",kpi.p1],["Production Checks",statusLabels[kpi.prod||'not_started']]].map(([l,v])=><Card key={l}><p className="text-xs font-black uppercase text-white/45">{l}</p><p className="mt-2 text-2xl font-black">{v}</p></Card>)}</div>
  <Card><div className="mb-3 flex items-center gap-2"><Rocket className="text-purple-300"/><h2 className="text-xl font-black">Launch Gates</h2></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{gates.map(g=><div key={g.id} className="rounded-2xl border border-white/10 bg-white/[0.035] p-3"><div className="flex items-start justify-between gap-2"><div><p className="font-black">{g.title}</p><p className="text-xs text-white/45">{g.priority} · {g.owner||'Unassigned'}</p></div><Pill value={g.status}/></div><div className="mt-3 grid grid-cols-2 gap-2"><StatusSelect row={g} collection="items" onSave={save}/><Field row={g} collection="items" name="owner" value={g.owner} onSave={save}/><Field row={g} collection="items" name="test_url" value={g.test_url} onSave={save}/><Field row={g} collection="items" name="github_pr_url" value={g.github_pr_url} onSave={save}/></div><div className="mt-2"><Notes row={g} collection="items" value={g.notes} onSave={save}/></div></div>)}</div></Card>
  <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card><h2 className="text-xl font-black">Daily Task Board</h2><div className="my-3 flex gap-2 overflow-x-auto">{["Week 1","Week 2","Week 3","Week 4","Final 2 Days"].map(w=><button key={w} onClick={()=>setTab(w)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-black ${tab===w?'bg-purple-600':'bg-white/10'}`}>{w}</button>)}</div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="text-left text-xs uppercase text-white/45"><tr><th>Day</th><th>Task</th><th>Gate</th><th>Status</th><th>PR / Codex</th></tr></thead><tbody>{tasks.filter(t=>t.week===tab).map(t=><tr key={t.id} className="border-t border-white/10"><td className="py-2">{t.day}</td><td className="font-bold">{t.title}</td><td>{t.gate}</td><td><StatusSelect row={t} collection="items" onSave={save}/></td><td className="grid min-w-64 gap-1 py-1"><Field row={t} collection="items" name="github_pr_url" value={t.github_pr_url} onSave={save}/><Field row={t} collection="items" name="codex_task_url" value={t.codex_task_url} onSave={save}/></td></tr>)}</tbody></table></div></Card>
  <Card><h2 className="text-xl font-black">Search Reliability Summary</h2><p className="mt-1 text-sm text-white/55">Manual prompt tracking only. The existing Search Health system remains the source of truth.</p><div className="my-3 flex flex-wrap gap-2"><Link className="rounded-full bg-purple-600 px-4 py-2 text-xs font-black" href="/admin/dashboard/search-health">Open Search Health <ExternalLink className="inline h-3 w-3"/></Link><Link className="rounded-full bg-white/10 px-4 py-2 text-xs font-black" href="/create">Open /create</Link><span className="rounded-full bg-emerald-500/15 px-4 py-2 text-xs font-black">{data.prompts.length?Math.round(promptPassed/data.prompts.length*100):0}% · {promptPassed}/{data.prompts.length} passed</span></div><div className="space-y-2">{blockers.map(b=><p key={b.id} className="rounded-xl bg-red-500/10 p-2 text-xs">{b.prompt} — {b.issue_type||'Blocker'}</p>)}</div><div className="mt-3 max-h-96 overflow-auto">{data.prompts.map(p=><div key={p.id} className="mb-2 rounded-2xl border border-white/10 p-3"><button onClick={()=>copy(p.prompt)} className="float-right text-white/50"><Clipboard className="h-4 w-4"/></button><p className="pr-8 text-sm font-black">{p.prompt}</p><div className="mt-2 grid gap-2 sm:grid-cols-2"><StatusSelect row={p} collection="prompts" onSave={save}/><Field row={p} collection="prompts" name="issue_type" value={p.issue_type} onSave={save}/><Field row={p} collection="prompts" name="actual_result" value={p.actual_result} onSave={save}/><Field row={p} collection="prompts" name="github_pr_url" value={p.github_pr_url} onSave={save}/></div></div>)}</div></Card></div>
  <div className="grid gap-5 xl:grid-cols-2"><Matrix data={data.access} save={save}/><Checklist title="Reserve Checklist" rows={check('reserve')} save={save}/><Checklist title="Beta Readiness" rows={check('beta')} save={save}/><Checklist title="Security Checklist" rows={check('security')} save={save}/></div>
  <Card><div className="flex items-center gap-2"><ShieldAlert className="text-amber-200"/><h2 className="text-xl font-black">QR Claim Pilot</h2></div><p className="mt-1 rounded-2xl border border-amber-300/20 bg-amber-500/10 p-3 text-sm font-bold text-amber-100">Do not send more than 25 postcards until all P0 gates pass.</p><div className="mt-3 overflow-x-auto"><table className="min-w-[1200px] text-xs"><thead className="text-left uppercase text-white/45"><tr>{['#','Location','Claim URL','QR','Printed','Mailed','Scanned','Submitted','Approved','Dashboard','Status','Notes'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{data.qr.map(q=><tr key={q.id} className="border-t border-white/10"><td>{q.pilot_number}</td><td className="min-w-52"><Field row={q} collection="qr" name="location_name" value={q.location_name} onSave={save}/></td><td>{q.claim_url}</td>{['qr_verified','postcard_printed','mailed','scanned','claim_submitted','claim_approved','owner_dashboard_works'].map(f=><td key={f}><input type="checkbox" checked={!!q[f]} onChange={e=>save('qr',q.id,{[f]:e.target.checked})}/></td>)}<td><StatusSelect row={q} collection="qr" onSave={save}/></td><td className="min-w-52"><Notes row={q} collection="qr" value={q.notes} onSave={save}/></td></tr>)}</tbody></table></div></Card>
  <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card><h2 className="text-xl font-black">Production Command Results</h2><p className="text-sm text-white/55">Commands are copyable only. They are never executed from the browser.</p>{data.commands.map(c=><div key={c.id} className="mt-2 grid gap-2 rounded-2xl border border-white/10 p-3 md:grid-cols-[1fr_auto_auto]"><code className="text-xs text-purple-100">{c.command}</code><button onClick={()=>copy(c.command)} className="rounded-full bg-purple-600 px-3 py-1 text-xs font-black">Copy</button><StatusSelect row={c} collection="commands" field="result" options={[]} onSave={save}/><Notes row={c} collection="commands" value={c.notes} onSave={save}/></div>)}</Card><Card><CheckCircle2 className="h-8 w-8 text-emerald-300"/><h2 className="mt-2 text-xl font-black">Go / No-Go</h2><p className="mt-2 text-3xl font-black">{kpi.overall}</p><p className="mt-2 text-sm text-white/55">Rules: any P0 blocked means Not Ready; all P0 passed with P1 remaining means Ready for Pilot; all P0 passed and Production Checks passed means Ready for Production.</p>{decision&&<div className="mt-3 space-y-2"><Field row={decision} collection="items" name="owner" value={decision.owner} onSave={save}/><Notes row={decision} collection="items" value={decision.notes} onSave={save}/></div>}</Card></div>
  {loading&&<p className="text-center text-white/50">Loading latest stored data…</p>}
 </div></main>
}
function Matrix({data,save}:any){return <Card><h2 className="text-xl font-black">Access Matrix</h2><div className="mt-3 overflow-x-auto"><table className="min-w-[900px] text-xs"><thead><tr><th className="p-2 text-left">Role</th>{areas.map(a=><th key={a} className="p-2 text-left">{a}</th>)}</tr></thead><tbody>{roles.map(r=><tr key={r} className="border-t border-white/10"><td className="font-black">{r}</td>{areas.map(a=>{const row=data.find((x:Row)=>x.role_name===r&&x.area_name===a); return <td key={a} className="p-1 align-top">{row&&<><StatusSelect row={row} collection="access" onSave={save}/><Notes row={row} collection="access" value={row.notes} onSave={save}/></>}</td>})}</tr>)}</tbody></table></div></Card>}
function Checklist({title,rows,save}:any){return <Card><h2 className="text-xl font-black">{title}</h2><div className="mt-3 space-y-2">{rows.map((r:Row)=><div key={r.id} className="grid gap-2 rounded-2xl border border-white/10 p-3 sm:grid-cols-[1fr_auto]"><p className="font-bold">{r.title}</p><StatusSelect row={r} collection="items" onSave={save}/><div className="sm:col-span-2"><Notes row={r} collection="items" value={r.notes} onSave={save}/></div></div>)}</div></Card>}
