export const STATUS_OPTIONS = ["not_started","in_progress","blocked","needs_codex","pr_open","testing","passed","skipped"] as const;
export type ProductionStatus = (typeof STATUS_OPTIONS)[number];
export const statusLabels: Record<string,string> = { not_started:"Not started", in_progress:"In progress", blocked:"Blocked", needs_codex:"Needs Codex", pr_open:"PR open", testing:"Testing", passed:"Passed", skipped:"Skipped" };
export const gateSeeds = [
  ["Search Reliability","P0"],["Location Access","P0"],["Owner Dashboard","P0"],["Reserve","P0"],["QR Claim Flow","P0"],["Beta Program","P1"],["Security","P0"],["Production Checks","P0"],["25-Card Pilot","P1"],
].map(([title,priority],i)=>({item_type:"gate",sort_order:i+1,title,priority,status:"not_started",owner:"Ops",notes:"",test_url:"",codex_task_url:"",github_pr_url:""}));
const taskWeeks = {
 "Week 1":["Build Production Command Center","Load top search prompts","Run top 10 search prompts","Fix Search: No Results Issues","Re-test Search Prompts"],
 "Week 2":["Build access matrix","Test superadmin access","Test demo access","Test owner dashboard access","Fix false no-access errors"],
 "Week 3":["Test Reserve reservations","Test waitlist","Test walk-ins","Test QR claim code","Test owner claim approval","Test beta signup","Test beta weekly completion"],
 "Week 4":["Security checklist review","Harden debug/admin/cron routes","Service-role guard review","Production command results","Full web smoke test","25-card pilot setup"],
 "Final 2 Days":["Go/No-Go review","Launch small pilot monitoring"],
} as const;
export const dailyTaskSeeds = Object.entries(taskWeeks).flatMap(([week,tasks])=>tasks.map((task,i)=>({item_type:"daily_task",week,day:`Day ${i+1}`,title:task,gate: task.includes("Search")||task.includes("prompts")?"Search Reliability":task.includes("access")||task.includes("owner")?"Location Access":task.includes("Reserve")||task.includes("waitlist")||task.includes("walk-in")?"Reserve":task.includes("QR")||task.includes("claim")?"QR Claim Flow":task.includes("beta")?"Beta Program":task.includes("Security")||task.includes("Service")||task.includes("debug")?"Security":task.includes("Production")||task.includes("smoke")?"Production Checks":"25-Card Pilot",status:"not_started",sort_order:0,notes:"",codex_task_url:"",github_pr_url:""})));
export const checklistSeeds = (type:string, items:string[]) => items.map((title,i)=>({item_type:type,title,status:"not_started",sort_order:i+1,priority:type==="security"?"P0":"P1",owner:"Ops",notes:"",codex_task_url:"",github_pr_url:""}));
export const reserveSeeds = checklistSeeds("reserve", ["Create reservation","Refresh and confirm reservation remains","Check in reservation","Assign table/resource","Confirm status becomes seated","Complete visit","Create waitlist entry","Refresh and confirm waitlist remains","Convert waitlist to reservation if supported","Create walk-in","Refresh and confirm walk-in remains","Assign walk-in to table/resource"]);
export const betaSeeds = checklistSeeds("beta", ["Beta signup submitted","Turnstile passed","Beta application created","Beta tester row created","Auth user linked","Password setup email sent","User lands on /user/dashboard/beta","Weekly task assigned","Weekly task completed","Success message appears under submit button","Journey Map shows 5/5","Completion email sends once","Reload does not duplicate email"]);
export const securitySeeds = checklistSeeds("security", ["Admin debug routes gated","/api/debug disabled or admin-gated","Cron routes fail closed","No query-string secrets in production cron","Service-role routes have auth checks","Public endpoints have safe payloads","Manual admin triggers require admin","Secrets not exposed in UI/logs","npm audit high-risk review completed","Sensitive admin pages require admin auth"]);
export const searchPromptSeeds = ["steak dinner and rooftop drinks 30 minute walk apart","girls night dinner with cocktails","seafood dinner with theatre after","rooftop dinner in Queens","seafood rooftop restaurant","chicken lunch in Astoria","bar with wings nyc","best bar to watch the Knicks game in Harlem","steak dinner and hookah lounge after","restaurant with activity walking distance"].map((prompt,i)=>({prompt,expected_result:"Relevant restaurants and/or outing pairs for the prompt",actual_result:"",status:"not_started",issue_type:"",notes:"",sort_order:i+1,codex_task_url:"",github_pr_url:""}));
export const roles = ["Superadmin","Admin","Demo Admin","Owner","Location Admin","View Only","Logged Out"];
export const areas = ["Location Dashboard","Location Editor","Menu Editor","Photo Upload","Recommended Details","Marketing Center","Reserve Dashboard","Public Profile"];
export const accessSeeds = roles.flatMap((role,ri)=>areas.map((area,ai)=>({role_name:role,area_name:area,expected_behavior: role==="Logged Out"?"Redirect to login or public-safe view":"Access according to role permissions",actual_behavior:"",status:"not_started",notes:"",sort_order:ri*areas.length+ai+1,codex_task_url:"",github_pr_url:""})));
export const qrSeeds = Array.from({length:25},(_,i)=>({pilot_number:i+1,location_id:"",location_name:`Pilot location ${i+1}`,address:"",claim_code:`PILOT-${String(i+1).padStart(2,"0")}`,claim_url:`/business/claim?code=PILOT-${String(i+1).padStart(2,"0")}`,qr_verified:false,postcard_printed:false,mailed:false,scanned:false,claim_started:false,claim_submitted:false,claim_approved:false,owner_dashboard_works:false,status:"not_started",notes:"",codex_task_url:"",github_pr_url:""}));
export const commandSeeds = ["npm run production-check:strict","npm run production-check:live","npm run test:search-production","npm run test:search-quality","npm run test:search-route-regression","npm run test:enterprise-search","npm run test:reserve","npm run test:location-editor","npm run test:beta-production-readiness","npm run test:beta-guided-route","npm run build"].map((command,i)=>({command,last_run_date:null,result:"not_run",runner:"",notes:"",sort_order:i+1,codex_task_url:"",github_pr_url:""}));
export const decisionSeed = { item_type:"decision",title:"Go / No-Go Decision",status:"blocked",notes:"",owner:"",codex_task_url:"",github_pr_url:"" };
