import { haversineMiles } from "../../enterprise/distance";
import { geoTierRank, pairGeoTier } from "../geo/geoPolicy";
import type { PairingDebugTrace, PairingRejectionReason, SearchTrace } from "../observability/searchTrace";
import type { SearchPlan } from "../planner/searchPlanTypes";
import type { ScoredCandidate } from "../scoring/scoringTypes";
import type { SearchPair } from "./pairingTypes";
import { validatePairDistance } from "./validatePairDistance";

const MAX_REJECTED_PAIR_SAMPLES=200; const TARGET_PAIR_COUNT=20; const MIN_VALID_FRONTIER=48;
function locationOf(c:ScoredCandidate){return c.candidate.candidate.location as any} function retrievedOf(c:ScoredCandidate){return c.candidate.candidate}
function diversifyPairs(pairs:SearchPair[],limit=20,maxPerRestaurant=2,maxPerActivity=2){const ru=new Map<string,number>(),au=new Map<string,number>(),out:SearchPair[]=[];for(const p of pairs){const r=String(p.restaurant.candidate.candidate.location.id),a=String(p.activity.candidate.candidate.location.id);if((ru.get(r)??0)>=maxPerRestaurant||(au.get(a)??0)>=maxPerActivity)continue;out.push(p);ru.set(r,(ru.get(r)??0)+1);au.set(a,(au.get(a)??0)+1);if(out.length>=limit)break}return out}
function emptyRejectionCounts():PairingDebugTrace["rejectionCounts"]{return{distance_exceeded:0,missing_coordinates:0,market_mismatch:0,walkability_constraint:0,schedule_open_hours_conflict:0,same_venue_constraint:0,insufficient_domain_candidates:0,other:0}}
function tierReason(t:SearchPair["geoTier"]){return t==="exact_locality"?"both venues match the requested locality":t==="nearby_radius"?"nearby options outside the exact locality":"broader geographic fallback options"}
function pairTrace(p:SearchPair):PairingDebugTrace["finalEligiblePairs"][number]{return{restaurantId:String(p.restaurant.candidate.candidate.location.id),activityId:String(p.activity.candidate.candidate.location.id),distanceMiles:p.distanceMiles,walkingMinutes:p.walkingMinutes,geoTier:p.geoTier??"exact_locality"}}
export function explicitDistanceRequested(plan:SearchPlan){if(plan.pairing.requireWalkable||plan.pairing.maxWalkingMinutes!=null||plan.pairing.maxDrivingMinutes!=null)return true;return /\b(?:within|under|less than|no more than|max(?:imum)?|up to)\s+\d+(?:\.\d+)?(?:\s*[-–—]\s*|\s+)(?:mile|miles|mi|minute|minutes|min)\b|\b\d+(?:\.\d+)?(?:\s*[-–—]\s*|\s+)(?:mile|miles|mi|minute|minutes|min)(?:\s*[-–—]\s*|\s+)(?:away|apart|walk|walking|drive|driving)\b|\bwalking distance\b/i.test(plan.rawQuery)}

export async function buildPairs({plan,restaurants,activities,trace}:{plan:SearchPlan;restaurants:ScoredCandidate[];activities:ScoredCandidate[];trace?:SearchTrace}):Promise<SearchPair[]>{
 const rs=restaurants.slice(0,20),as=activities.slice(0,20),hardDistance=explicitDistanceRequested(plan),pairs:SearchPair[]=[];
 const theoretical=rs.length*as.length;
 const debug:PairingDebugTrace={restaurantCandidates:restaurants.length,activityCandidates:activities.length,theoreticalPairCandidates:theoretical,pairCandidatesEvaluated:0,pairCandidatesSkipped:0,shortCircuitApplied:false,shortCircuitReason:null,targetPairCount:TARGET_PAIR_COUNT,frontierPairCount:0,validPairCountBeforeRender:0,validPairCountAfterConstraints:0,validPairCountAfterDiversification:0,renderEligiblePairCount:0,finalEligiblePairs:[],eligibilityContractValid:true,eligibilityContractViolation:null,rejectionCounts:emptyRejectionCounts(),rejectedPairs:[],nearestRejectedPair:null,allCandidatePairsExceededTravelLimit:false,primaryFailure:null};
 const meta=new Map<ScoredCandidate,{id:string|null;coords:{lat:number;lng:number}|null;unavailable:boolean;tier:any;ml:number}>();
 const get=(c:ScoredCandidate)=>{let m=meta.get(c);if(m)return m;const l=locationOf(c),lat=Number(l.latitude),lng=Number(l.longitude);m={id:l?.id==null?null:String(l.id),coords:Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null,unavailable:l?.is_open===false||l?.open_now===false||l?.schedule_match===false||l?.availability_status==="closed"||l?.availability_status==="unavailable",tier:retrievedOf(c).geoMatch?.tier??"outside_scope",ml:Math.min(5,Number(l.ml_pair_score??0))};meta.set(c,m);return m};
 const reject=(reason:PairingRejectionReason,r:ScoredCandidate|null,a:ScoredCandidate|null,detail:string,d:number|null=null,w:number|null=null)=>{debug.rejectionCounts[reason]+=1;const row={restaurantId:r?get(r).id:null,activityId:a?get(a).id:null,reason,detail,distanceMiles:d,walkingMinutes:w};if(d!=null&&(!debug.nearestRejectedPair||debug.nearestRejectedPair.distanceMiles==null||d<debug.nearestRejectedPair.distanceMiles))debug.nearestRejectedPair=row;if(debug.rejectedPairs.length<MAX_REJECTED_PAIR_SAMPLES)debug.rejectedPairs.push(row)};
 if(!rs.length||!as.length)reject("insufficient_domain_candidates",null,null,!rs.length&&!as.length?"restaurant_and_activity_candidates_empty":!rs.length?"restaurant_candidates_empty":"activity_candidates_empty");
 const frontier:{r:ScoredCandidate;a:ScoredCandidate;upper:number}[]=[];
 for(const r of rs)for(const a of as)frontier.push({r,a,upper:(r.scores.total+a.scores.total)*.4+25});
 frontier.sort((x,y)=>y.upper-x.upper); debug.frontierPairCount=frontier.length;
 let bestTierRank=Number.POSITIVE_INFINITY;
 for(let i=0;i<frontier.length;i++){
  const {r,a}=frontier[i],rm=get(r),am=get(a); debug.pairCandidatesEvaluated++;
  const geoTier=pairGeoTier(rm.tier,am.tier); if(!geoTier){reject("market_mismatch",r,a,`restaurant=${rm.tier};activity=${am.tier}`);continue}
  const tierRank=geoTierRank(geoTier); if(bestTierRank<Number.POSITIVE_INFINITY&&tierRank>bestTierRank&&diversifyPairs(pairs.filter(p=>geoTierRank(p.geoTier)===bestTierRank)).length>=TARGET_PAIR_COUNT){debug.shortCircuitApplied=true;debug.shortCircuitReason="higher_geo_tier_fully_satisfied";break}
  if(rm.unavailable||am.unavailable){reject("schedule_open_hours_conflict",r,a,`restaurantUnavailable=${rm.unavailable};activityUnavailable=${am.unavailable}`);continue}
  const sameVenue=rm.id===am.id;if(plan.pairing.sameVenueRequired&&!sameVenue){reject("same_venue_constraint",r,a,"same_venue_required");continue}
  const distance=sameVenue?0:rm.coords&&am.coords?haversineMiles(rm.coords.lat,rm.coords.lng,am.coords.lat,am.coords.lng):null,walking=distance==null?null:Math.ceil(distance*20);
  if(!sameVenue&&distance==null&&hardDistance){reject("missing_coordinates",r,a,"hard_distance_requires_coordinates");continue}
  if(hardDistance&&!validatePairDistance(plan,distance,walking)){const wc=plan.pairing.requireWalkable||plan.pairing.maxWalkingMinutes!=null;reject(wc?"walkability_constraint":"distance_exceeded",r,a,wc?"requested_walking_limit_exceeded":"requested_distance_limit_exceeded",distance,walking);continue}
  const ds=distance==null?40:Math.max(0,100-distance*12),ml=Math.max(rm.ml,am.ml),total=(r.scores.total+a.scores.total)*.4+ds*.2+ml-tierRank*12;
  pairs.push({restaurant:r,activity:a,distanceMiles:distance,walkingMinutes:walking,walkingMinutesSource:walking==null?"unavailable":"estimated",geoTier,isFallbackPair:geoTier!=="exact_locality",scores:{restaurant:r.scores.total,activity:a.scores.total,distance:ds,combinedQuality:(r.scores.quality+a.scores.quality)/2,sequence:100,mlPairBoost:ml,total},reasons:[sameVenue?"both roles at one venue":tierReason(geoTier),walking==null?"walking time unavailable":`about ${walking} minutes walking`]});
  bestTierRank=Math.min(bestTierRank,tierRank);
  if(pairs.length>=MIN_VALID_FRONTIER){const chosen=pairs.filter(p=>geoTierRank(p.geoTier)===bestTierRank).sort((x,y)=>y.scores.total-x.scores.total);const diversified=diversifyPairs(chosen);const next=frontier[i+1];const floor=diversified.length>=TARGET_PAIR_COUNT?diversified[diversified.length-1].scores.total:Number.NEGATIVE_INFINITY;if(diversified.length>=TARGET_PAIR_COUNT&&(!next||next.upper<=floor)){debug.shortCircuitApplied=true;debug.shortCircuitReason="quality_frontier_satisfied";break}}
 }
 debug.pairCandidatesSkipped=Math.max(0,theoretical-debug.pairCandidatesEvaluated);debug.validPairCountBeforeRender=pairs.length;debug.validPairCountAfterConstraints=pairs.length;
 pairs.sort((x,y)=>geoTierRank(x.geoTier)-geoTierRank(y.geoTier)||y.scores.total-x.scores.total);const exact=pairs.filter(p=>p.geoTier==="exact_locality"),near=pairs.filter(p=>p.geoTier==="nearby_radius"),broad=pairs.filter(p=>p.geoTier==="broader_fallback"),selected=exact.length?exact:near.length?near:broad,diversified=diversifyPairs(selected);
 debug.validPairCountAfterDiversification=diversified.length;debug.renderEligiblePairCount=diversified.length;debug.finalEligiblePairs=diversified.map(pairTrace);debug.eligibilityContractValid=debug.renderEligiblePairCount===debug.finalEligiblePairs.length;debug.eligibilityContractViolation=debug.eligibilityContractValid?null:`renderEligiblePairCount=${debug.renderEligiblePairCount};finalEligiblePairs=${debug.finalEligiblePairs.length}`;
 const travel=debug.rejectionCounts.walkability_constraint+debug.rejectionCounts.distance_exceeded;debug.allCandidatePairsExceededTravelLimit=hardDistance&&debug.pairCandidatesEvaluated>0&&diversified.length===0&&travel===debug.pairCandidatesEvaluated;
 debug.primaryFailure=restaurants.length===0||activities.length===0?"insufficient_domain_candidates":debug.pairCandidatesEvaluated===0?"no_pair_candidates":debug.allCandidatePairsExceededTravelLimit?"travel_constraint_exceeded":debug.rejectionCounts.market_mismatch>=debug.pairCandidatesEvaluated?"market_mismatch":debug.rejectionCounts.walkability_constraint>=debug.pairCandidatesEvaluated?"walkability_constraint":debug.rejectionCounts.distance_exceeded>=debug.pairCandidatesEvaluated?"distance_exceeded":debug.rejectionCounts.missing_coordinates>=debug.pairCandidatesEvaluated?"missing_coordinates":debug.rejectionCounts.schedule_open_hours_conflict>=debug.pairCandidatesEvaluated?"schedule_open_hours_conflict":diversified.length===0?"no_valid_pairs":null;
 if(trace){trace.pairingDebug=debug;trace.counts.pairsBuilt=pairs.length;trace.counts.pairsValid=diversified.length;trace.decisions.push({stage:"pairing_performance",decision:debug.shortCircuitApplied?"short_circuit_applied":"full_frontier_required",reason:JSON.stringify({theoreticalPairCandidates:theoretical,pairCandidatesEvaluated:debug.pairCandidatesEvaluated,pairCandidatesSkipped:debug.pairCandidatesSkipped,shortCircuitReason:debug.shortCircuitReason})});trace.decisions.push({stage:"pairing_eligibility",decision:debug.eligibilityContractValid?(diversified.length?"pairs_available":"pairs_unavailable"):"pairing_contract_violation",reason:JSON.stringify({...debug,servedGeoTier:diversified[0]?.geoTier??null})})}
 return diversified;
}
