-- Fix admin CRM filtered tabs by ensuring the CRM view exposes the fields used by the app.
-- This migration is additive on locations and rebuilds only the admin CRM view, not public search views.

alter table if exists public.locations
  add column if not exists crm_status text,
  add column if not exists outreach_status text default 'none',
  add column if not exists crm_priority text default 'normal',
  add column if not exists follow_up_date date,
  add column if not exists active boolean default true,
  add column if not exists is_searchable boolean default true,
  add column if not exists plan text default 'free_discovery',
  add column if not exists plan_status text default 'inactive',
  add column if not exists upgrade_score integer default 0,
  add column if not exists churn_risk integer default 0;

alter table if exists public.locations
  add column if not exists name text,
  add column if not exists status text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now(),
  add column if not exists restaurant_name text,
  add column if not exists activity_name text,
  add column if not exists location_type text,
  add column if not exists address text,
  add column if not exists city text,
  add column if not exists borough text,
  add column if not exists neighborhood text,
  add column if not exists state text,
  add column if not exists zip_code text,
  add column if not exists phone text,
  add column if not exists website text,
  add column if not exists reservation_url text,
  add column if not exists reservation_link text,
  add column if not exists booking_url text,
  add column if not exists external_reservation_url text,
  add column if not exists image_url text,
  add column if not exists main_image text,
  add column if not exists images text[],
  add column if not exists subscription_plan text,
  add column if not exists subscription_status text,
  add column if not exists opportunity_score numeric default 0,
  add column if not exists churn_risk_score numeric default 0,
  add column if not exists upgrade_probability numeric default 0,
  add column if not exists engagement_score numeric default 0,
  add column if not exists traffic_score numeric default 0,
  add column if not exists conversion_score numeric default 0,
  add column if not exists retention_score numeric default 0,
  add column if not exists trend_score numeric default 0,
  add column if not exists owner_email text,
  add column if not exists owner_user_id uuid,
  add column if not exists is_claimed boolean default false,
  add column if not exists claim_status text,
  add column if not exists owner_name text,
  add column if not exists owner_phone text,
  add column if not exists claim_code text,
  add column if not exists claim_url text,
  add column if not exists claim_qr_url text,
  add column if not exists qr_link text,
  add column if not exists qr_code_data_url text,
  add column if not exists primary_category text,
  add column if not exists cuisine text,
  add column if not exists cuisine_type text,
  add column if not exists description text,
  add column if not exists last_contacted_at timestamptz,
  add column if not exists priority_level text,
  add column if not exists internal_notes text;


do $$
begin
  if to_regclass('public.locations') is not null then
    execute $view$
      create or replace view public.admin_crm_locations_view as
      select
        l.id,
        l.id as location_id,
        coalesce(l.name, l.restaurant_name, l.activity_name, 'Untitled Location') as name,
        coalesce(l.name, l.restaurant_name, l.activity_name, 'Untitled Location') as location_name,
        l.restaurant_name,
        l.activity_name,
        l.location_type,
        l.address,
        l.city,
        coalesce(l.borough, l.neighborhood, l.city) as borough,
        l.state,
        l.zip_code,
        l.phone,
        l.website,
        l.reservation_url,
        l.reservation_link,
        l.booking_url,
        l.external_reservation_url,
        coalesce(l.reservation_url, l.reservation_link, l.booking_url, l.external_reservation_url) as best_reservation_url,
        l.image_url,
        l.main_image,
        l.images,
        l.is_searchable,
        l.active,
        l.status,
        l.crm_status,
        l.outreach_status,
        l.crm_priority,
        l.follow_up_date,
        l.plan,
        l.plan_status,
        l.subscription_plan,
        l.subscription_status,
        l.upgrade_score,
        l.churn_risk,
        coalesce(l.opportunity_score, l.upgrade_score, 0) as opportunity_score,
        coalesce(l.churn_risk_score, l.churn_risk, 0) as churn_risk_score,
        coalesce(l.upgrade_probability, 0) as upgrade_probability,
        coalesce(l.engagement_score, 0) as engagement_score,
        coalesce(l.traffic_score, 0) as traffic_score,
        coalesce(l.conversion_score, 0) as conversion_score,
        coalesce(l.retention_score, 0) as retention_score,
        coalesce(l.trend_score, 0) as trending_score,
        coalesce(analytics.profile_views_30d, 0) as profile_views_30d,
        coalesce(analytics.search_appearances_30d, 0) as search_appearances_30d,
        coalesce(analytics.reservation_completions_30d, 0) as reservation_completions_30d,
        coalesce(analytics.saves_30d, 0) as saves_30d,
        coalesce(analytics.conversion_rate_30d, 0) as conversion_rate_30d,
        l.owner_email,
        l.owner_user_id,
        l.is_claimed,
        l.claim_status,
        l.owner_name,
        l.owner_phone,
        l.claim_code,
        l.claim_url,
        l.claim_qr_url,
        l.qr_link,
        l.qr_code_data_url,
        l.primary_category as category,
        l.primary_category,
        l.cuisine,
        l.cuisine_type,
        l.description,
        l.last_contacted_at,
        l.priority_level,
        l.internal_notes,
        l.created_at,
        l.updated_at
      from public.locations l
      left join (
        select
          lda.location_id,
          sum(lda.profile_views) as profile_views_30d,
          sum(lda.search_appearances) as search_appearances_30d,
          sum(lda.share_clicks) as saves_30d,
          sum(lda.reservation_completions) as reservation_completions_30d,
          case when sum(lda.profile_views) > 0
            then sum(lda.reservation_completions)::numeric / sum(lda.profile_views)::numeric
            else 0 end as conversion_rate_30d
        from public.location_daily_analytics lda
        where lda.analytics_date >= (current_date - interval '30 days')
        group by lda.location_id
      ) analytics on analytics.location_id = l.id;
    $view$;
  end if;
end $$;
