-- Search Foundation V3: additive profile storage. Public search remains on V2 until rollout is enabled.
create table public.location_search_profiles (
 location_id uuid primary key references public.locations(id) on delete cascade, primary_domain text not null check(primary_domain in ('restaurant','activity','nightlife','hybrid')), supported_domains text[] not null default '{}', restaurant_categories text[] not null default '{}', cuisines text[] not null default '{}', foods text[] not null default '{}', activity_categories text[] not null default '{}', nightlife_categories text[] not null default '{}', meal_periods text[] not null default '{}', features text[] not null default '{}', audiences text[] not null default '{}', occasions text[] not null default '{}', vibes text[] not null default '{}', canonical_terms text[] not null default '{}', exclusions text[] not null default '{}', search_text text not null default '', search_tsv tsvector generated always as (to_tsvector('simple',search_text)) stored, latitude double precision, longitude double precision, market text, city text, neighborhood text, borough text, county text, state text, classification_sources jsonb not null default '{}', evidence jsonb not null default '[]', manual_overrides jsonb not null default '{}', confidence numeric not null default 0 check(confidence between 0 and 1), needs_review boolean not null default false, review_reasons text[] not null default '{}', reviewed_at timestamptz, reviewed_by uuid, profile_version integer not null check(profile_version>0), profile_hash text not null, generated_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index location_search_profiles_search_idx on public.location_search_profiles using gin(search_tsv);
do $$ declare c text; begin foreach c in array array['supported_domains','restaurant_categories','cuisines','foods','activity_categories','nightlife_categories','meal_periods','features','audiences','occasions','vibes','canonical_terms','exclusions'] loop execute format('create index location_search_profiles_%I_gin on public.location_search_profiles using gin(%I)',c,c); end loop; end $$;
create index location_search_profiles_geo_idx on public.location_search_profiles(market,state,county,borough,city,neighborhood); create index location_search_profiles_status_idx on public.location_search_profiles(needs_review,confidence,profile_version,updated_at);
alter table public.location_search_profiles enable row level security;
create policy "admin profiles inspect" on public.location_search_profiles for select to authenticated using (exists(select 1 from public.admin_users au where au.user_id=auth.uid() and au.role in ('superadmin','admin','editor','reviewer','viewer')));

create table public.location_search_profile_refresh_queue (id uuid primary key default gen_random_uuid(),location_id uuid not null references public.locations(id) on delete cascade,reason text not null,status text not null default 'pending' check(status in ('pending','processing','completed','failed','cancelled')),requested_by uuid,requested_at timestamptz not null default now(),available_at timestamptz not null default now(),attempts integer not null default 0,max_attempts integer not null default 5,locked_at timestamptz,locked_by text,lease_expires_at timestamptz,completed_at timestamptz,last_error text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index location_search_profile_queue_active on public.location_search_profile_refresh_queue(location_id) where status in ('pending','processing'); create index location_search_profile_queue_claim on public.location_search_profile_refresh_queue(status,available_at,lease_expires_at);
create table public.location_search_profile_runs (id uuid primary key default gen_random_uuid(),run_type text not null check(run_type in ('full_backfill','filtered_backfill','missing_only','stale_only','selected_locations','validation','single_location')),status text not null default 'queued' check(status in ('queued','running','completed','completed_with_errors','failed','cancelling','cancelled')),filters jsonb not null default '{}',requested_by uuid,requested_at timestamptz not null default now(),started_at timestamptz,completed_at timestamptz,cancelled_at timestamptz,total_targeted integer not null default 0,total_processed integer not null default 0,total_succeeded integer not null default 0,total_failed integer not null default 0,total_skipped integer not null default 0,total_needs_review integer not null default 0,cursor_value text,batch_size integer not null check(batch_size in (25,50,100,250)),current_batch integer not null default 0,error_summary jsonb not null default '{}',metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.location_search_profile_run_items (id uuid primary key default gen_random_uuid(),run_id uuid not null references public.location_search_profile_runs(id) on delete cascade,location_id uuid not null references public.locations(id) on delete cascade,status text not null default 'pending' check(status in ('pending','processing','completed','failed','skipped','cancelled')),attempt_count integer not null default 0,error text,review_reasons text[] not null default '{}',profile_version integer,profile_hash text,started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(run_id,location_id)); create index location_search_run_items_claim on public.location_search_profile_run_items(run_id,status,created_at);
alter table public.location_search_profile_refresh_queue enable row level security; alter table public.location_search_profile_runs enable row level security; alter table public.location_search_profile_run_items enable row level security;
create policy "admin queue inspect" on public.location_search_profile_refresh_queue for select to authenticated using (exists(select 1 from public.admin_users au where au.user_id=auth.uid() and au.role in ('superadmin','admin','editor','reviewer','viewer'))); create policy "admin runs inspect" on public.location_search_profile_runs for select to authenticated using (exists(select 1 from public.admin_users au where au.user_id=auth.uid() and au.role in ('superadmin','admin','editor','reviewer','viewer'))); create policy "admin run items inspect" on public.location_search_profile_run_items for select to authenticated using (exists(select 1 from public.admin_users au where au.user_id=auth.uid() and au.role in ('superadmin','admin','editor','reviewer','viewer')));
create or replace function public.enqueue_location_search_profile_refresh() returns trigger language plpgsql security invoker set search_path='' as $$ begin insert into public.location_search_profile_refresh_queue(location_id,reason) values(new.id,'location_classification_changed') on conflict(location_id) where status in ('pending','processing') do update set updated_at=now(),reason=excluded.reason; return new; end $$;
create trigger locations_enqueue_search_profile after insert or update of location_type,restaurant_name,activity_name,primary_category,activity_type,cuisine,cuisine_type,tags,vibe_tags,best_for_tags,date_style_tags,search_keywords,google_types,semantic_tags,intent_tags,description,public_visibility_tier,curation_tier,source_quality_status,quality_status,data_status,status,is_searchable,is_hidden,is_low_level,active,deleted_at,market,city,neighborhood,borough,county,state,latitude,longitude on public.locations for each row execute function public.enqueue_location_search_profile_refresh();

create table public.search_profile_shadow_comparisons(id uuid primary key default gen_random_uuid(),request_id text not null,created_at timestamptz not null default now(),query_hash text not null,normalized_search_type text,primary_domain text,current_candidate_ids uuid[] not null default '{}',profile_candidate_ids uuid[] not null default '{}',current_qualified_lane_ids jsonb not null default '{}',profile_qualified_lane_ids jsonb not null default '{}',pair_keys text[] not null default '{}',fulfillment jsonb not null default '{}',result_counts jsonb not null default '{}',recall_metrics jsonb not null default '{}',precision_metrics jsonb not null default '{}',divergence_reasons text[] not null default '{}',timings jsonb not null default '{}',errors jsonb not null default '{}'); alter table public.search_profile_shadow_comparisons enable row level security;
