-- Multi-market coordinate-first local area geography.
-- NYC keeps its finer DCP NTA polygons; NY/NJ/CT expansion markets use authoritative
-- Census TIGERweb place/CDP/county-subdivision polygons loaded administratively.

create table if not exists public.local_area_boundaries (
  id bigint generated by default as identity primary key,
  state text not null,
  geo_id text not null,
  name text not null,
  area_type text not null check (area_type in ('incorporated_place','census_designated_place','county_subdivision')),
  priority smallint not null,
  source_name text not null default 'US Census Bureau TIGERweb',
  source_vintage text not null default '2025-01-01',
  geom extensions.geometry(MultiPolygon,4326) not null,
  centroid extensions.geometry(Point,4326) generated always as (extensions.st_pointonsurface(geom)) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(state, area_type, geo_id)
);

create index if not exists local_area_boundaries_geom_gix
  on public.local_area_boundaries using gist (geom);
create index if not exists local_area_boundaries_state_priority_idx
  on public.local_area_boundaries(state, priority, name);

alter table public.local_area_boundaries enable row level security;
revoke all on table public.local_area_boundaries from anon, authenticated;

alter table public.locations add column if not exists local_area_code text;
alter table public.locations add column if not exists local_area_type text;
create index if not exists locations_local_area_code_idx
  on public.locations(local_area_code) where local_area_code is not null;
create index if not exists locations_neighborhood_lower_idx
  on public.locations(lower(neighborhood)) where neighborhood is not null;

create or replace function public.lookup_local_area(
  p_latitude double precision,
  p_longitude double precision,
  p_state text default null
)
returns table(
  area_code text,
  area_name text,
  area_type text,
  area_source text,
  borough text
)
language plpgsql
stable
set search_path = public, extensions
as $$
declare
  v_nyc record;
begin
  if p_latitude is null or p_longitude is null then
    return;
  end if;

  -- Preserve NYC's finer-grained DCP NTA model.
  if upper(coalesce(p_state,'NY')) = 'NY'
     and p_latitude between 40.45 and 40.95
     and p_longitude between -74.30 and -73.65 then
    select * into v_nyc
    from public.lookup_nyc_neighborhood(p_latitude, p_longitude)
    limit 1;

    if found then
      area_code := v_nyc.nta_code;
      area_name := v_nyc.neighborhood;
      area_type := 'nyc_nta';
      area_source := 'nyc_dcp_2020_nta_coordinates';
      borough := v_nyc.borough;
      return next;
      return;
    end if;
  end if;

  return query
  select
    b.geo_id,
    b.name,
    b.area_type,
    'census_tigerweb_2025_coordinates'::text,
    null::text
  from public.local_area_boundaries b
  where (p_state is null or b.state = upper(p_state))
    and extensions.st_covers(
      b.geom,
      extensions.st_setsrid(extensions.st_makepoint(p_longitude, p_latitude),4326)
    )
  order by b.priority asc,
           extensions.st_area(b.geom::extensions.geography) asc,
           b.geo_id
  limit 1;
end;
$$;

create or replace function public.sync_location_neighborhood_from_coordinates()
returns trigger
language plpgsql
set search_path = public, extensions
as $$
declare
  v record;
begin
  if new.latitude is null or new.longitude is null then
    return new;
  end if;

  if tg_op = 'INSERT'
     or new.latitude is distinct from old.latitude
     or new.longitude is distinct from old.longitude
     or new.state is distinct from old.state
     or new.neighborhood is null
     or new.local_area_code is null then
    select * into v
    from public.lookup_local_area(
      new.latitude::double precision,
      new.longitude::double precision,
      new.state
    )
    limit 1;

    if found then
      new.neighborhood := v.area_name;
      new.local_area_code := v.area_code;
      new.local_area_type := v.area_type;
      new.neighborhood_source := v.area_source;
      new.neighborhood_resolved_at := now();

      if v.area_type = 'nyc_nta' then
        new.neighborhood_nta_code := v.area_code;
        new.borough := v.borough;
      else
        new.neighborhood_nta_code := null;
      end if;
    end if;
  end if;

  return new;
end;
$$;

-- Administrative import helper. Feed a TIGERweb GeoJSON FeatureCollection with
-- STATE, GEOID, BASENAME/NAME properties. Geometry is repaired and polygon-only
-- components are retained so malformed source rings cannot weaken the schema.
create or replace function public.ingest_local_area_geojson(
  p_geojson jsonb,
  p_area_type text,
  p_priority smallint,
  p_source_vintage text default '2025-01-01'
)
returns integer
language plpgsql
security invoker
set search_path = public, extensions
as $$
declare
  v_count integer;
begin
  if p_area_type not in ('incorporated_place','census_designated_place','county_subdivision') then
    raise exception 'Unsupported local area type: %', p_area_type;
  end if;

  with features as (
    select f
    from jsonb_array_elements(coalesce(p_geojson->'features','[]'::jsonb)) f
  ), parsed as (
    select
      case f->'properties'->>'STATE'
        when '36' then 'NY'
        when '34' then 'NJ'
        when '09' then 'CT'
        else upper(f->'properties'->>'STATE')
      end as state,
      f->'properties'->>'GEOID' as geo_id,
      coalesce(nullif(f->'properties'->>'BASENAME',''), f->'properties'->>'NAME') as name,
      extensions.st_multi(
        extensions.st_collectionextract(
          extensions.st_makevalid(
            extensions.st_setsrid(
              extensions.st_geomfromgeojson((f->'geometry')::text),4326
            )
          ),3
        )
      )::extensions.geometry(MultiPolygon,4326) as geom
    from features
    where f->'geometry' is not null
  ), upserted as (
    insert into public.local_area_boundaries(
      state,geo_id,name,area_type,priority,source_vintage,geom
    )
    select state,geo_id,name,p_area_type,p_priority,p_source_vintage,geom
    from parsed
    where state in ('NY','NJ','CT')
      and geo_id is not null
      and name is not null
      and not extensions.st_isempty(geom)
    on conflict(state,area_type,geo_id) do update
      set name=excluded.name,
          priority=excluded.priority,
          source_vintage=excluded.source_vintage,
          geom=excluded.geom,
          updated_at=now()
    returning 1
  )
  select count(*) into v_count from upserted;

  return v_count;
end;
$$;

revoke all on function public.lookup_local_area(double precision,double precision,text)
  from public, anon, authenticated;
revoke all on function public.ingest_local_area_geojson(jsonb,text,smallint,text)
  from public, anon, authenticated;
grant execute on function public.lookup_local_area(double precision,double precision,text)
  to service_role;
grant execute on function public.ingest_local_area_geojson(jsonb,text,smallint,text)
  to service_role;
