begin;

create table if not exists public.knowledge_entities (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null,
  canonical_key text not null,
  canonical_name text not null,
  location_id uuid null references public.locations(id) on delete cascade,
  attributes jsonb not null default '{}'::jsonb,
  confidence numeric(5,4) not null default 1.0 check (confidence >= 0 and confidence <= 1),
  source text not null default 'derived',
  source_updated_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (entity_type, canonical_key)
);

create unique index if not exists knowledge_entities_location_uidx
  on public.knowledge_entities(location_id)
  where location_id is not null;

create index if not exists knowledge_entities_type_name_idx
  on public.knowledge_entities(entity_type, canonical_name);

create table if not exists public.knowledge_entity_aliases (
  id bigint generated by default as identity primary key,
  entity_id uuid not null references public.knowledge_entities(id) on delete cascade,
  alias text not null,
  normalized_alias text not null,
  source text not null default 'derived',
  confidence numeric(5,4) not null default 1.0 check (confidence >= 0 and confidence <= 1),
  created_at timestamptz not null default now(),
  unique (entity_id, normalized_alias)
);

create index if not exists knowledge_entity_aliases_lookup_idx
  on public.knowledge_entity_aliases(normalized_alias);

create table if not exists public.knowledge_edges (
  id uuid primary key default gen_random_uuid(),
  subject_entity_id uuid not null references public.knowledge_entities(id) on delete cascade,
  predicate text not null,
  object_entity_id uuid not null references public.knowledge_entities(id) on delete cascade,
  confidence numeric(5,4) not null default 1.0 check (confidence >= 0 and confidence <= 1),
  source text not null default 'derived',
  valid_from timestamptz null,
  valid_to timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (subject_entity_id, predicate, object_entity_id)
);

create index if not exists knowledge_edges_subject_idx
  on public.knowledge_edges(subject_entity_id, predicate);

create index if not exists knowledge_edges_object_idx
  on public.knowledge_edges(object_entity_id, predicate);

create table if not exists public.knowledge_entity_features (
  id bigint generated by default as identity primary key,
  entity_id uuid not null references public.knowledge_entities(id) on delete cascade,
  feature_key text not null,
  feature_value jsonb not null,
  source text not null default 'derived',
  confidence numeric(5,4) not null default 1.0 check (confidence >= 0 and confidence <= 1),
  freshness timestamptz null,
  verified_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (entity_id, feature_key, source)
);

create index if not exists knowledge_entity_features_entity_idx
  on public.knowledge_entity_features(entity_id, feature_key);

create table if not exists public.knowledge_edge_evidence (
  id bigint generated by default as identity primary key,
  edge_id uuid not null references public.knowledge_edges(id) on delete cascade,
  evidence_type text not null,
  evidence_ref text null,
  payload jsonb not null default '{}'::jsonb,
  confidence numeric(5,4) not null default 1.0 check (confidence >= 0 and confidence <= 1),
  created_at timestamptz not null default now()
);

create index if not exists knowledge_edge_evidence_edge_idx
  on public.knowledge_edge_evidence(edge_id);

create table if not exists public.knowledge_graph_versions (
  id bigint generated by default as identity primary key,
  version text not null unique,
  status text not null default 'building',
  source_snapshot jsonb not null default '{}'::jsonb,
  entity_count bigint not null default 0,
  edge_count bigint not null default 0,
  started_at timestamptz not null default now(),
  completed_at timestamptz null,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.knowledge_entities enable row level security;
alter table public.knowledge_entity_aliases enable row level security;
alter table public.knowledge_edges enable row level security;
alter table public.knowledge_entity_features enable row level security;
alter table public.knowledge_edge_evidence enable row level security;
alter table public.knowledge_graph_versions enable row level security;

revoke all on table public.knowledge_entities from anon, authenticated;
revoke all on table public.knowledge_entity_aliases from anon, authenticated;
revoke all on table public.knowledge_edges from anon, authenticated;
revoke all on table public.knowledge_entity_features from anon, authenticated;
revoke all on table public.knowledge_edge_evidence from anon, authenticated;
revoke all on table public.knowledge_graph_versions from anon, authenticated;

grant select, insert, update, delete on table public.knowledge_entities to service_role;
grant select, insert, update, delete on table public.knowledge_entity_aliases to service_role;
grant select, insert, update, delete on table public.knowledge_edges to service_role;
grant select, insert, update, delete on table public.knowledge_entity_features to service_role;
grant select, insert, update, delete on table public.knowledge_edge_evidence to service_role;
grant select, insert, update, delete on table public.knowledge_graph_versions to service_role;

grant usage, select on all sequences in schema public to service_role;


commit;
