import type { EnterpriseLocation, EnterprisePair, SearchIntent } from "./types";
import { getRecordDistanceMiles } from "./distance";
import { scoreGeoMatch } from "./geo-taxonomy";
const titleCase=(s:string)=>s.split(/\s+/).filter(Boolean).map(w=>w[0]?.toUpperCase()+w.slice(1)).join(" ");
export function getPairDistanceMiles(restaurant: EnterpriseLocation, activity: EnterpriseLocation) { const d=getRecordDistanceMiles(restaurant,activity); return d==null?null:Number(d.toFixed(2)); }
export function scorePair(pair: Pick<EnterprisePair,"restaurant"|"activity"|"distance_miles">, intent: SearchIntent) { let score=Number(pair.restaurant.match_score??0)+Number(pair.activity.match_score??0)+scoreGeoMatch(pair.restaurant,intent.geo)+scoreGeoMatch(pair.activity,intent.geo); if (pair.restaurant.neighborhood&&pair.activity.neighborhood&&String(pair.restaurant.neighborhood).toLowerCase()===String(pair.activity.neighborhood).toLowerCase()) score+=120; else if (pair.restaurant.borough&&pair.activity.borough&&String(pair.restaurant.borough).toLowerCase()===String(pair.activity.borough).toLowerCase()) score+=80; else if (pair.restaurant.city&&pair.activity.city&&String(pair.restaurant.city).toLowerCase()===String(pair.activity.city).toLowerCase()) score+=50; const d=pair.distance_miles; if (d!=null) score+=d<=1.5?100:d<=3?75:d<=8?10:-100; return score; }
export function buildPairTitle(_pair: Pick<EnterprisePair,"restaurant"|"activity">, intent: SearchIntent) { const food=intent.restaurantIntent.foodTerms.find(t=>!["restaurant","dining"].includes(t)) ?? intent.restaurantIntent.cuisineTerms[0] ?? intent.restaurantIntent.mealTerms[0] ?? "Dinner"; const act=intent.activityIntent.activityTerms.find(t=>!["activity","things to do"].includes(t)) ?? "Activity"; return `${titleCase(food)} + ${titleCase(act)} Night`; }
export function buildPairExplanation(pair: Pick<EnterprisePair,"restaurant"|"activity"|"distance_miles">, intent: SearchIntent) { const geo=intent.geo.neighborhood??intent.geo.borough??intent.geo.city??intent.geo.county??"your area"; const distance=pair.distance_miles!=null?`, about ${pair.distance_miles} miles apart`:""; return `This works because both options fit ${geo}${distance}, and match your restaurant + activity request.`; }
export function createSearchPairs(restaurants: EnterpriseLocation[], activities: EnterpriseLocation[], intent: SearchIntent) { const pairs: EnterprisePair[]=[]; for (const restaurant of restaurants.slice(0,12)) for (const activity of activities.slice(0,12)) { const distance_miles=getPairDistanceMiles(restaurant,activity); const pair={ restaurant, activity, distance_miles, title:"", explanation:"", score:0 }; pair.title=buildPairTitle(pair,intent); pair.explanation=buildPairExplanation(pair,intent); pair.score=scorePair(pair,intent); pairs.push(pair); } return pairs.sort((a,b)=>b.score-a.score).slice(0,8); }
