const SEARCH_RECOVERY_REGRESSION_PROMPTS = [
  "date night in Queens tonight at 8pm with dinner and something fun after",
  "seafood rooftop restaurant in Manhattan this Friday at 7:30pm",
  "girls night in Brooklyn with drinks and a lounge after",
  "steakhouse and hookah in Queens Saturday night",
  "romantic dinner and jazz activity near Harlem tomorrow at 6pm",
  "brunch and museum date in Manhattan Sunday afternoon",
  "casual lunch and bowling near Astoria today at 2pm",
  "birthday dinner with activity after in Long Island City at 9pm",
  "Italian restaurant and comedy show in NYC this weekend",
  "seafood dinner near me with something fun after",
  "cheap date night in Brooklyn under 100 dollars",
  "upscale anniversary dinner in Manhattan with rooftop drinks after",
  "fun things to do in Long Island tonight",
  "dinner and arcade near Times Square",
  "Afrobeats lounge and dinner in Queens",
  "family friendly restaurant and activity in Brooklyn Sunday afternoon",
  "late night food and pool hall near me",
  "sushi and karaoke in Manhattan Friday night",
  "romantic activity first then dinner in Williamsburg",
  "outdoor activity and brunch in Queens this weekend",
] as const;

export const DEFAULT_SEARCH_QA_PROMPTS = [
  ...SEARCH_RECOVERY_REGRESSION_PROMPTS,
  "Best bar to watch the Knicks game in Harlem",
  "casual dinner relaxed activity no club",
  "girls night dinner and drinks",
  "steak dinner and rooftop drinks after",
  "restaurant with activity walking distance",
  "seafood dinner with theatre after",
  "dinner and hookah lounge after",
  "rooftop drinks in Harlem",
  "romantic date night in Brooklyn",
  "something fun after dinner",
  "bar with TVs for NBA game",
  "dinner and lounge but not a club",
  "sports bar to watch the game near me",
  "where can I watch the Giants game in Queens",
  "bar showing the Mets game in Brooklyn",
  "sports lounge for UFC fight night",
  "pub to watch football in Manhattan",
  "bar with big screens in Harlem",
  "casual bar to watch basketball",
  "Italian dinner and comedy show after",
  "sushi dinner and karaoke after",
  "Mexican dinner and bowling nearby",
  "dinner and arcade games",
  "romantic dinner and jazz lounge",
  "brunch and museum after",
  "restaurant and activity walking distance",
  "dinner and drinks walking distance",
  "steak dinner and rooftop drinks 30 minute walk apart",
  "restaurant with activity close by",
  "dinner and something fun nearby",
  "date night within walking distance",
  "food and activity close together",
  "restaurant and lounge near each other",
  "brunch and activity nearby",
  "date night in Queens",
  "romantic dinner near me tonight",
  "birthday dinner with activity after",
  "girls night drinks and lounge in Brooklyn",
  "brunch and museum date",
  "seafood restaurant in Queens",
  "steakhouse near me",
  "bowling near me tonight",
  "Black-owned romantic restaurant",
  "wheelchair accessible brunch spot",
  "date night in Long Island",
  "dinner then drinks less than 20 minutes away",
  "seafood and comedy show walking distance",
  "cute date idea in Queens",
  "upscale date night in Manhattan",
  "lowkey date night in Harlem",
  "fun first date idea",
  "anniversary dinner and activity",
  "birthday date night",
  "romantic dinner with live music",
  "date night with cocktails after",
  "surprise me with a date idea",
  "ladies night with cocktails",
  "fun girls night in Brooklyn",
  "birthday dinner and lounge after",
  "group dinner and activity",
  "girls night rooftop drinks",
  "brunch for girls day",
  "dinner and dancing after",
  "cocktail lounge for a group",
  "fun group activity after dinner",
  "casual dinner and relaxed activity",
  "lowkey dinner and drinks",
  "chill lounge after dinner",
  "quiet date night",
  "relaxed activity after brunch",
  "casual dinner with something fun after",
  "not too loud drinks spot",
  "laid back bar in Queens",
  "easy first date idea",
  "cozy restaurant and activity",
  "best rooftop lounge in Brooklyn",
  "cocktail bar in Queens",
  "lounge with good music",
  "upscale lounge near me",
  "rooftop bar with city views",
  "drinks after dinner",
  "speakeasy in Manhattan",
  "cocktails and small bites",
  "romantic rooftop drinks",
  "hookah lounge after dinner",
  "dinner and hookah nearby",
  "best hookah lounge in Queens",
  "hookah and food in Brooklyn",
  "late night hookah lounge",
  "date night with hookah",
  "chill hookah spot",
  "hookah lounge with music",
  "upscale hookah lounge",
  "birthday hookah lounge",
  "best steakhouse in Manhattan",
  "seafood restaurant in Harlem",
  "romantic Italian restaurant",
  "brunch spot in Brooklyn",
  "sushi near me",
  "Mexican food in Queens",
  "Black-owned restaurant in NYC",
  "rooftop restaurant in Manhattan",
  "casual dinner in the Bronx",
  "birthday dinner restaurant",
  "fun activity in Brooklyn",
  "things to do in Queens tonight",
  "comedy show in Manhattan",
  "karaoke in Harlem",
  "bowling near me",
  "arcade games in NYC",
  "museum date idea",
  "jazz lounge in Brooklyn",
  "paint and sip near me",
  "live music in Harlem",
  "where should we go tonight",
  "plan a cute night out",
  "I want food and vibes",
  "somewhere grown and sexy",
  "not a club but still fun",
  "dinner then somewhere chill",
  "something romantic but not boring",
  "good vibes and good food",
  "take me somewhere different",
  "bar to watch the game",
  "watch Knicks in Harlem",
  "best game day bar",
  "sports lounge near Harlem",
  "drinks after dinner not rooftop",
  "restaurant with activity close by but no long walk",
  "seafood dinner with show after",
  "girls night dinner drinks no theater",
] as const;

export const SEARCH_QA_PROMPT_GROUPS = {
  searchRecoveryRegressionPack: [...SEARCH_RECOVERY_REGRESSION_PROMPTS],
  core: [
    "Best bar to watch the Knicks game in Harlem",
    "casual dinner relaxed activity no club",
    "girls night dinner and drinks",
    "restaurant with activity walking distance",
    "something fun after dinner",
  ],
  sportsWatch: [
    "Best bar to watch the Knicks game in Harlem",
    "bar with TVs for NBA game",
    "sports bar to watch the game near me",
    "where can I watch the Giants game in Queens",
    "bar showing the Mets game in Brooklyn",
    "sports lounge for UFC fight night",
    "pub to watch football in Manhattan",
    "bar with big screens in Harlem",
    "casual bar to watch basketball",
    "bar to watch the game",
    "watch Knicks in Harlem",
    "best game day bar",
    "sports lounge near Harlem",
  ],
  relaxedNoClub: [
    "casual dinner relaxed activity no club",
    "dinner and lounge but not a club",
    "casual dinner and relaxed activity",
    "lowkey dinner and drinks",
    "chill lounge after dinner",
    "quiet date night",
    "relaxed activity after brunch",
    "not too loud drinks spot",
    "laid back bar in Queens",
    "not a club but still fun",
    "dinner then somewhere chill",
  ],
  walkingDistance: [
    "restaurant with activity walking distance",
    "restaurant and activity walking distance",
    "dinner and drinks walking distance",
    "steak dinner and rooftop drinks 30 minute walk apart",
    "restaurant with activity close by",
    "date night within walking distance",
    "food and activity close together",
    "dinner then drinks less than 20 minutes away",
    "seafood and comedy show walking distance",
    "restaurant with activity close by but no long walk",
  ],
  mixedOuting: [
    "girls night dinner and drinks",
    "steak dinner and rooftop drinks after",
    "seafood dinner with theatre after",
    "Italian dinner and comedy show after",
    "sushi dinner and karaoke after",
    "Mexican dinner and bowling nearby",
    "dinner and arcade games",
    "brunch and museum after",
    "birthday dinner and lounge after",
    "group dinner and activity",
  ],
  nightlife: [
    "rooftop drinks in Harlem",
    "best rooftop lounge in Brooklyn",
    "cocktail bar in Queens",
    "lounge with good music",
    "upscale lounge near me",
    "rooftop bar with city views",
    "drinks after dinner",
    "speakeasy in Manhattan",
    "cocktails and small bites",
    "romantic rooftop drinks",
  ],
  hookah: [
    "dinner and hookah lounge after",
    "hookah lounge after dinner",
    "dinner and hookah nearby",
    "best hookah lounge in Queens",
    "hookah and food in Brooklyn",
    "late night hookah lounge",
    "date night with hookah",
    "chill hookah spot",
    "hookah lounge with music",
    "upscale hookah lounge",
    "birthday hookah lounge",
  ],
  dateNight: [
    "romantic date night in Brooklyn",
    "cute date idea in Queens",
    "upscale date night in Manhattan",
    "lowkey date night in Harlem",
    "fun first date idea",
    "anniversary dinner and activity",
    "birthday date night",
    "romantic dinner with live music",
    "date night with cocktails after",
    "surprise me with a date idea",
  ],
  activityOnly: [
    "fun activity in Brooklyn",
    "things to do in Queens tonight",
    "comedy show in Manhattan",
    "karaoke in Harlem",
    "bowling near me",
    "arcade games in NYC",
    "museum date idea",
    "jazz lounge in Brooklyn",
    "paint and sip near me",
    "live music in Harlem",
  ],
  restaurantOnly: [
    "best steakhouse in Manhattan",
    "seafood restaurant in Harlem",
    "romantic Italian restaurant",
    "brunch spot in Brooklyn",
    "sushi near me",
    "Mexican food in Queens",
    "Black-owned restaurant in NYC",
    "rooftop restaurant in Manhattan",
    "casual dinner in the Bronx",
    "birthday dinner restaurant",
  ],
} as const;
