"use client";
import { useState } from "react";
import TurnstileWidget from "@/components/security/TurnstileWidget";
export default function BetaFeedbackForm({ assignmentId, defaultPrompt, requireTurnstile = true }: { assignmentId?: string; defaultPrompt?: string; requireTurnstile?: boolean }) {
  const [token,setToken]=useState(""); const [status,setStatus]=useState<string|null>(null); const [loading,setLoading]=useState(false);
  async function submit(formData:FormData){setLoading(true);setStatus(null);const payload=Object.fromEntries(formData.entries()) as any; payload.turnstileToken=token; payload.assignmentId=assignmentId; try{const res=await fetch("/api/beta/feedback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await res.json(); if(!res.ok)throw new Error(data.error||"Feedback failed"); setStatus("Thank you — your feedback was submitted.");}catch(e){setStatus(e instanceof Error?e.message:"Feedback failed");}finally{setLoading(false);}}
  const input="rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-white outline-none placeholder:text-white/35";
  return <form action={submit} className="grid gap-4 rounded-3xl border border-white/10 bg-white/[.04] p-6"><div className="grid gap-4 md:grid-cols-2"><select name="feedback_type" className={input}><option value="general">General</option><option value="bad_search_results">Bad search results</option><option value="search_was_slow">Search was slow</option><option value="confusing">Confusing</option><option value="feature_request">Feature request</option><option value="bug">Bug</option></select><select name="feature_area" className={input}><option value="general">General</option><option value="search_quality">Search quality</option><option value="search_speed">Search speed</option><option value="natural_search">Natural search</option><option value="location_page">Location page</option><option value="reservations">Reservations</option></select><input name="page_url" placeholder="Page URL" className={input}/><input name="search_query" defaultValue={defaultPrompt??""} placeholder="What did you search?" className={input}/><input name="submitted_prompt" defaultValue={defaultPrompt??""} placeholder="Submitted prompt" className={input}/><select name="speed_rating" className={input}><option value="">Speed rating</option><option value="fast">Fast</option><option value="okay">Okay</option><option value="slow">Slow</option><option value="very_slow">Very slow</option><option value="failed">Failed</option></select><select name="result_accuracy_rating" className={input}><option value="">Accuracy rating</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select><select name="rating" className={input}><option value="">Overall rating</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></div><textarea name="expected_result" placeholder="What did you expect to see?" className={`${input} min-h-24`}/><textarea name="actual_result" placeholder="What actually happened?" className={`${input} min-h-24`}/><textarea name="message" required placeholder="Tell us what felt slow, confusing, inaccurate, or broken." className={`${input} min-h-32`}/><input name="screenshot_url" placeholder="Screenshot URL (optional)" className={input}/>{requireTurnstile&&<><p className="text-sm text-white/55">Verification helps protect TheOutHaven from spam.</p><TurnstileWidget action="beta_feedback" onToken={setToken}/></>}{status&&<p className="text-sm font-bold text-rose-100">{status}</p>}<button disabled={loading} className="rounded-full bg-rose-600 px-6 py-3 text-sm font-black text-white disabled:opacity-60">Submit feedback</button></form>
}
