"use client";
import { useMemo, useState } from "react";
import { formatOperatingHoursForEditor, parseWeeklyHoursFromEditor } from "@/lib/weekly-hours";
const DAYS=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"] as const;
type Range={open:string;close:string}; type DayState={closed:boolean;ranges:Range[]};
function emptyWeek():Record<string,DayState>{return Object.fromEntries(DAYS.map(d=>[d.toLowerCase(),{closed:true,ranges:[{open:"09:00",close:"17:00"}]}]));}
function fromOperatingHours(value:any){const week=emptyWeek();try{const text=formatOperatingHoursForEditor(value);const parsed=parseWeeklyHoursFromEditor(text);if(parsed) for(const day of Object.keys(week)){const v=(parsed as any)[day]; if(v){week[day]={closed:Boolean(v.closed),ranges:(v.ranges?.length?v.ranges:[{open:"09:00",close:"17:00"}]).map((r:any)=>({open:r.open||"09:00",close:r.close||"17:00"}))}}}}catch{}return week;}
function validTime(t:string){return /^([01]\d|2[0-3]):[0-5]\d$/.test(t)}
export default function LocationEditorHoursPanel({ value, importedHours, isAdmin, onChange }:{value:any; importedHours?:any; isAdmin?:boolean; onChange:(hours:any, summary:string)=>void}){const initial=useMemo(()=>fromOperatingHours(value),[]);const [week,setWeek]=useState(initial);const [error,setError]=useState("");function emit(next=week){for(const label of DAYS){const day=label.toLowerCase(), row=next[day]; if(!row.closed){for(const r of row.ranges){if(!r.open||!r.close){setError(`${label} needs both an open and close time.`);return} if(!validTime(r.open)||!validTime(r.close)){setError(`Please use a valid time like 9:00 AM.`);return}}}}setError("");const out:any={};for(const label of DAYS){const day=label.toLowerCase(), row=next[day];out[day]=row.closed?{closed:true,ranges:[]}: {closed:false,ranges:row.ranges};}onChange(out,formatOperatingHoursForEditor(out));}
function update(day:string, patch:Partial<DayState>){const next={...week,[day]:{...week[day],...patch}};setWeek(next);emit(next)}
return <div className="grid gap-4"><p className="text-sm font-semibold text-white/60">Use this to show guests when this location is open.</p>{importedHours?<div className="rounded-3xl border border-amber-300/25 bg-amber-400/10 p-4"><h3 className="font-black text-amber-100">Imported hours found</h3><p className="mt-1 text-sm text-white/60">Review before saving.</p><button type="button" onClick={()=>{const next=fromOperatingHours(importedHours);setWeek(next);emit(next)}} className="mt-3 rounded-full border border-amber-200/30 px-4 py-2 text-xs font-black">Use imported hours</button></div>:null}{error?<div className="rounded-2xl border border-red-400/30 bg-red-500/10 p-3 text-sm font-bold text-red-100">{error}</div>:null}<div className="grid gap-3">{DAYS.map(label=>{const day=label.toLowerCase(), row=week[day];return <div key={day} className="rounded-3xl border border-white/10 bg-black/25 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h3 className="text-lg font-black">{label}</h3><label className="text-sm font-bold text-white/70"><input type="checkbox" checked={!row.closed} onChange={e=>update(day,{closed:!e.target.checked})} /> Open</label></div>{!row.closed?<div className="mt-3 grid gap-2">{row.ranges.map((r,i)=><div key={i} className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input type="time" value={r.open} onChange={e=>{const ranges=[...row.ranges];ranges[i]={...ranges[i],open:e.target.value};update(day,{ranges})}} className="rounded-2xl border border-white/10 bg-black/35 px-3 py-2 font-bold text-white"/><input type="time" value={r.close} onChange={e=>{const ranges=[...row.ranges];ranges[i]={...ranges[i],close:e.target.value};update(day,{ranges})}} className="rounded-2xl border border-white/10 bg-black/35 px-3 py-2 font-bold text-white"/><button type="button" onClick={()=>update(day,{ranges:row.ranges.filter((_,idx)=>idx!==i)})} className="rounded-2xl border border-white/10 px-3 py-2 text-xs font-black">Remove</button></div>)}<button type="button" onClick={()=>update(day,{ranges:[...row.ranges,{open:"17:00",close:"22:00"}]})} className="rounded-2xl border border-white/10 px-3 py-2 text-sm font-black text-left">Add another time range</button></div>:<p className="mt-2 text-sm text-white/45">Closed all day</p>}</div>})}</div>{isAdmin?<details className="rounded-2xl border border-white/10 bg-black/25 p-4"><summary className="cursor-pointer font-black">Advanced hours data</summary><pre className="mt-3 overflow-auto text-xs text-white/50">{JSON.stringify(value,null,2)}</pre></details>:null}</div>}
