"use client";
import { useEffect, useState } from "react";
import type { LocationEditorContext } from "./location-editor-context";
function copy(text:string){navigator.clipboard?.writeText(text).catch(()=>{});} function download(data:string,name:string){const a=document.createElement('a');a.href=data;a.download=name;a.click();}
export default function LocationEditorQrPanel({ context, links }: { context: LocationEditorContext; links: { publicPage: string; menuViewer: string; reserveDashboard: string } }) {
  const [row,setRow]=useState<any>(null); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState("");
  async function load(){const res=await fetch(`/api/locations/edit-context?type=${context.type}&id=${encodeURIComponent(context.effectiveLocationId)}`,{cache:"no-store"}); const json=await res.json(); setRow(json.location||null)}
  useEffect(()=>{load().catch(()=>setMsg("QR details could not be loaded."));},[context.effectiveLocationId,context.type]);
  async function generate(){setBusy(true);setMsg(""); const res=await fetch('/api/business/qr-codes/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({locationId:context.effectiveLocationId,adminLocationId:context.adminLocationId,demo:context.isDemoMode})}); const json=await res.json().catch(()=>({})); setBusy(false); setMsg(res.ok?"QR codes are ready for this location.":json.error||json.message||"QR generation failed."); await load().catch(()=>{});}
  const qrs=[{name:"Public profile QR",url:row?.public_location_url||links.publicPage,img:row?.qr_code_data_url||row?.qr_code_url},{name:"Claim QR",url:row?.claim_url||row?.qr_link,img:row?.claim_qr_url||row?.claim_qr_code_url},{name:"Menu QR",url:links.menuViewer,img:null},{name:"Reservation QR",url:links.reserveDashboard,img:null}];
  return <div className="space-y-4"><div className="flex flex-wrap gap-2"><button onClick={generate} disabled={busy} className="rounded-full bg-rose-600 px-5 py-2 text-sm font-black disabled:opacity-50">{busy?'Generating…':'Generate / repair QR codes for this location'}</button>{msg?<span className="rounded-full border border-white/10 px-4 py-2 text-sm font-bold text-white/70">{msg}</span>:null}</div><div className="grid gap-4 md:grid-cols-2">{qrs.map(q=><div key={q.name} className="rounded-3xl border border-white/10 bg-black/25 p-4"><h3 className="font-black">{q.name}</h3><p className="mt-2 break-all text-xs text-white/45">{q.url||'Generate QR codes to create this destination.'}</p>{q.img?<img src={q.img} alt={q.name} className="mt-4 h-44 w-44 rounded-2xl bg-white p-2"/>:<div className="mt-4 grid h-44 w-44 place-items-center rounded-2xl border border-dashed border-white/15 text-center text-xs text-white/35">QR image appears after generation when supported</div>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>q.url&&copy(q.url)} className="rounded-full border border-white/10 px-3 py-2 text-xs font-black">Copy link</button>{q.url?<a href={q.url} target="_blank" className="rounded-full border border-white/10 px-3 py-2 text-xs font-black">Open destination</a>:null}{q.img?<button onClick={()=>download(q.img,`${q.name}.png`)} className="rounded-full border border-white/10 px-3 py-2 text-xs font-black">Download QR</button>:null}<button onClick={()=>window.print()} className="rounded-full border border-white/10 px-3 py-2 text-xs font-black">Print QR</button></div></div>)}</div></div>;
}
