import Link from "next/link";
import CrmWorkspaceShell from "@/components/admin/crm/CrmWorkspaceShell";
import { requireAdminRole } from "@/lib/admin-auth";
import { ADMIN_PAGE_ACCESS } from "@/lib/admin-permissions";
import { SUPPORT_PRIORITIES, SUPPORT_STATUSES } from "@/lib/support/canonical";
import { getSupportOperationsSettings } from "@/lib/support/operations";
import { supportSettingsAction } from "./actions";

export const dynamic = "force-dynamic";
const days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const input = "rounded-xl border border-white/10 bg-black/30 p-2 text-sm";

export default async function Page() {
  await requireAdminRole(ADMIN_PAGE_ACCESS.crm);
  const s = await getSupportOperationsSettings();
  return <CrmWorkspaceShell><main className="space-y-6 text-white">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.25em] text-rose-300">Support operations</p><h1 className="text-3xl font-black">Support Settings</h1><p className="text-white/60">Configure routing, service levels, reusable replies, and time-based automation.</p></div><Link href="/admin/dashboard/crm/support" className="rounded-xl bg-white/10 px-4 py-2 font-bold">Back to queues</Link></header>

    <Section title="Groups" description="Operational ownership for support queues.">{s.groups.map((g:any)=><form action={supportSettingsAction} key={g.id} className="grid gap-2 rounded-xl bg-black/20 p-3 md:grid-cols-6"><Hidden entity="group" id={g.id}/><input name="key" defaultValue={g.key} className={input}/><input name="name" defaultValue={g.name} className={input}/><input name="description" defaultValue={g.description||""} className={`${input} md:col-span-2`}/><input name="sort_order" type="number" defaultValue={g.sort_order} className={input}/><Toggle name="active" checked={g.active}/><button className="rounded-xl bg-white/10 px-3 py-2 font-bold">Save</button></form>)}</Section>

    <Section title="SLA policies" description="Targets are counted only during active business hours.">{s.slas.map((x:any)=><form action={supportSettingsAction} key={x.id} className="grid gap-2 rounded-xl bg-black/20 p-3 md:grid-cols-5"><Hidden entity="sla" id={x.id}/><select name="priority" defaultValue={x.priority} className={input}>{SUPPORT_PRIORITIES.map(p=><option key={p}>{p}</option>)}</select><input name="first_response_minutes" type="number" defaultValue={x.first_response_minutes} className={input}/><input name="resolution_minutes" type="number" defaultValue={x.resolution_minutes} className={input}/><Toggle name="active" checked={x.active}/><button className="rounded-xl bg-white/10 px-3 py-2 font-bold">Save</button></form>)}</Section>

    <Section title="Business hours" description="Timezone-aware weekly support schedule.">{s.businessHours.map((x:any)=><form action={supportSettingsAction} key={x.id} className="grid gap-2 rounded-xl bg-black/20 p-3 md:grid-cols-6"><Hidden entity="business_hours" id={x.id}/><input type="hidden" name="day_of_week" value={x.day_of_week}/><div className="p-2 font-bold">{days[x.day_of_week]}</div><input name="start_time" type="time" defaultValue={String(x.start_time).slice(0,5)} className={input}/><input name="end_time" type="time" defaultValue={String(x.end_time).slice(0,5)} className={input}/><input name="timezone" defaultValue={x.timezone} className={input}/><Toggle name="active" checked={x.active}/><button className="rounded-xl bg-white/10 px-3 py-2 font-bold">Save</button></form>)}</Section>

    <Section title="Macros" description="One-click replies and ticket changes.">{s.macros.map((m:any)=><form action={supportSettingsAction} key={m.id} className="grid gap-2 rounded-xl bg-black/20 p-3 md:grid-cols-4"><Hidden entity="macro" id={m.id}/><input name="key" defaultValue={m.key} className={input}/><input name="name" defaultValue={m.name} className={input}/><select name="set_status" defaultValue={m.set_status||""} className={input}><option value="">No status change</option>{SUPPORT_STATUSES.map(v=><option key={v}>{v}</option>)}</select><select name="set_priority" defaultValue={m.set_priority||""} className={input}><option value="">No priority change</option>{SUPPORT_PRIORITIES.map(v=><option key={v}>{v}</option>)}</select><textarea name="body" defaultValue={m.body||""} rows={3} className={`${input} md:col-span-2`}/><select name="assigned_group" defaultValue={m.assigned_group||""} className={input}><option value="">Keep group</option>{s.groups.map((g:any)=><option key={g.key} value={g.key}>{g.name}</option>)}</select><input name="tags" defaultValue={(m.tags||[]).join(", ")} placeholder="tags" className={input}/><Toggle name="active" checked={m.active}/><button className="rounded-xl bg-white/10 px-3 py-2 font-bold">Save</button></form>)}</Section>

    <Section title="Triggers" description="First matching active rule routes new and reopened tickets.">{s.triggers.map((t:any)=><form action={supportSettingsAction} key={t.id} className="grid gap-2 rounded-xl bg-black/20 p-3 md:grid-cols-4"><Hidden entity="trigger" id={t.id}/><input name="key" defaultValue={t.key} className={input}/><input name="name" defaultValue={t.name} className={input}/><input name="category_contains" defaultValue={t.category_contains||""} placeholder="category contains" className={input}/><input name="source_contains" defaultValue={t.source_contains||""} placeholder="source contains" className={input}/><input name="requester_type" defaultValue={t.requester_type||""} placeholder="requester type (optional)" className={input}/><select name="require_location" defaultValue={t.require_location===true?"true":t.require_location===false?"false":"any"} className={input}><option value="any">Any location state</option><option value="true">Location required</option><option value="false">No location</option></select><select name="target_group" defaultValue={t.target_group||""} className={input}><option value="">No group</option>{s.groups.map((g:any)=><option key={g.key} value={g.key}>{g.name}</option>)}</select><select name="set_priority" defaultValue={t.set_priority||""} className={input}><option value="">Keep priority</option>{SUPPORT_PRIORITIES.map(v=><option key={v}>{v}</option>)}</select><input name="add_tags" defaultValue={(t.add_tags||[]).join(", ")} placeholder="tags to add" className={input}/><input name="sort_order" type="number" defaultValue={t.sort_order} className={input}/><Toggle name="active" checked={t.active}/><button className="rounded-xl bg-white/10 px-3 py-2 font-bold">Save</button></form>)}</Section>

    <Section title="Time automations" description="Rules executed by the support automation worker.">{s.automations.map((a:any)=><form action={supportSettingsAction} key={a.id} className="grid gap-2 rounded-xl bg-black/20 p-3 md:grid-cols-5"><Hidden entity="automation" id={a.id}/><input name="key" defaultValue={a.key} className={input}/><input name="name" defaultValue={a.name} className={input}/><select name="rule_type" defaultValue={a.rule_type} className={input}><option value="auto_close_resolved">Auto-close resolved</option><option value="waiting_reminder">Waiting reminder</option></select><input name="minutes_after" type="number" defaultValue={a.minutes_after} className={input}/>{a.rule_type==="waiting_reminder"?<select name="status" defaultValue={a.config?.status||"waiting_on_customer"} className={input}><option value="waiting_on_customer">Waiting on customer</option><option value="waiting_on_internal">Waiting internal</option></select>:null}<Toggle name="enabled" checked={a.enabled}/><button className="rounded-xl bg-white/10 px-3 py-2 font-bold">Save</button></form>)}</Section>
  </main></CrmWorkspaceShell>;
}
function Hidden({entity,id}:{entity:string,id:string}) { return <><input type="hidden" name="entity" value={entity}/><input type="hidden" name="id" value={id}/></>; }
function Toggle({name,checked}:{name:string,checked:boolean}) { return <label className="flex items-center gap-2 rounded-xl bg-white/5 p-2 text-sm"><input type="checkbox" name={name} defaultChecked={checked}/> Active</label>; }
function Section({title,description,children}:{title:string;description:string;children:React.ReactNode}) { return <section className="space-y-3 rounded-2xl border border-white/10 bg-white/[.03] p-4"><div><h2 className="text-xl font-black">{title}</h2><p className="text-sm text-white/55">{description}</p></div>{children}</section>; }
