"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

type Assignment = { id: string; status?: string | null; assigned_prompt?: string | null; beta_tasks?: any };
type ResultItem = { id?: string; name?: string | null; restaurant_name?: string | null; activity_name?: string | null; business_name?: string | null; city?: string | null; borough?: string | null; neighborhood?: string | null; address?: string | null; primary_category?: string | null; cuisine?: string | null; activity_type?: string | null; description?: string | null; review_snippet?: string | null; main_image?: string | null; image_url?: string | null; images?: string[] | null; type?: string | null; location_type?: string | null; source_table?: string | null };

const card = "rounded-[1.75rem] border border-white/10 bg-white/[0.045] p-5 shadow-2xl shadow-black/20";
const input = "rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none placeholder:text-white/35 focus:border-rose-200/50";
const primary = "rounded-full bg-gradient-to-r from-rose-500 to-rose-700 px-5 py-3 text-sm font-black text-white shadow-lg shadow-rose-950/30 disabled:cursor-not-allowed disabled:opacity-50";
const secondary = "rounded-full border border-white/10 bg-black/30 px-4 py-2 text-xs font-black text-white hover:border-rose-200/40";

function taskTitle(a: Assignment) { return a.beta_tasks?.title || "Beta task"; }
function isSearchTask(a: Assignment) { const t = `${taskTitle(a)} ${a.beta_tasks?.feature_area || ""}`.toLowerCase(); return t.includes("search") || t.includes("prompt") || t.includes("plan flow"); }
function isFeedbackTask(a: Assignment) { const t = `${taskTitle(a)} ${a.beta_tasks?.feature_area || ""}`.toLowerCase(); return t.includes("feedback"); }
function isProfileTask(a: Assignment) { const t = `${taskTitle(a)} ${a.beta_tasks?.feature_area || ""}`.toLowerCase(); return t.includes("profile") || t.includes("preferences"); }
function isChooseTask(a: Assignment) { const t = `${taskTitle(a)} ${a.beta_tasks?.feature_area || ""}`.toLowerCase(); return t.includes("location") || t.includes("photo") || t.includes("spot") || t.includes("choose"); }
function friendlyStatus(status?: string | null, needsFeedback = false) { if (status === "completed") return "Completed"; if (needsFeedback) return "Needs Feedback"; if (status === "in_progress") return "In Progress"; if (status === "review_pending") return "Admin Review Pending"; return "Not Started"; }
function resultName(r: ResultItem) { return r.name || r.restaurant_name || r.activity_name || r.business_name || "TheOutHaven spot"; }
function imageFor(r: ResultItem) { return r.main_image || r.image_url || (Array.isArray(r.images) ? r.images[0] : null); }
function areaFor(r: ResultItem) { return [r.neighborhood || r.borough, r.city].filter(Boolean).join(", ") || r.address || "Area available in details"; }
function categoryFor(r: ResultItem) { return r.primary_category || r.cuisine || r.activity_type || r.type || r.location_type || "Recommended spot"; }

export default function BetaCommandCenter({ assignments, weekStart, giveawayStatus, feedbackCount, profileComplete }: { assignments: Assignment[]; weekStart: string; giveawayStatus?: string | null; feedbackCount: number; profileComplete: boolean }) {
  const [items, setItems] = useState<ResultItem[]>([]);
  const [query, setQuery] = useState("birthday dinner in Queens");
  const [busy, setBusy] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [local, setLocal] = useState<Record<string, string>>({});
  const [feedback, setFeedback] = useState({ feature_area: "Search results", feel: "Easy", message: "", improve: "" });
  const completed = assignments.filter((a) => (local[a.id] || a.status) === "completed").length;
  const total = Math.max(assignments.length, 5);
  const searchTask = assignments.find(isSearchTask);
  const chooseTask = assignments.find((a) => isChooseTask(a) && !isSearchTask(a));
  const feedbackTask = assignments.find(isFeedbackTask);
  const percent = Math.round((completed / total) * 100);
  const giveawayLabel = completed >= total ? "Qualified for review" : completed > 0 ? "In progress" : "Needs tasks";

  async function patch(id: string, action: "start" | "complete", body: any = {}) {
    const res = await fetch(`/api/beta/tasks/${id}/${action}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    if (!res.ok) throw new Error("task");
    setLocal((s) => ({ ...s, [id]: action === "complete" ? "completed" : s[id] || "in_progress" }));
  }
  async function runSearch(e: React.FormEvent) {
    e.preventDefault(); if (!query.trim() || !searchTask) return; setBusy("search"); setNotice(null); setError(null);
    try { await patch(searchTask.id, "start", { submitted_prompt: query, used_custom_prompt: true }); const res = await fetch(`/api/explore/search?q=${encodeURIComponent(query)}&kind=all&limit=6&betaAssignmentId=${encodeURIComponent(searchTask.id)}&usedCustomPrompt=true`); const data = await res.json(); if (!res.ok || data.success === false) throw new Error("search"); setItems((data.items || data.restaurants || data.activities || []).slice(0, 6)); await patch(searchTask.id, "complete"); setNotice("Search recorded for your beta task."); }
    catch { setError("We could not run that search. Please try again."); }
    finally { setBusy(null); }
  }
  async function chooseSpot(r: ResultItem) { const id = chooseTask?.id || searchTask?.id; if (!id) return; setBusy(`choose-${r.id}`); setError(null); setNotice(null); try { await patch(id, "complete"); setNotice("Spot selected. Thanks for testing this recommendation."); } catch { setError("We could not save that spot yet. Please try again."); } finally { setBusy(null); } }
  async function submitFeedback(e: React.FormEvent) { e.preventDefault(); if (!feedback.message.trim()) return; setBusy("feedback"); setError(null); setNotice(null); try { const res = await fetch("/api/beta/feedback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ feedback_type: "weekly_beta", feature_area: feedback.feature_area, message: `${feedback.feel}: ${feedback.message}${feedback.improve ? `\n\nImprove: ${feedback.improve}` : ""}`, assignmentId: feedbackTask?.id, page_url: location.href, search_query: query }) }); if (!res.ok) throw new Error("feedback"); if (feedbackTask) await patch(feedbackTask.id, "complete"); setFeedback((f) => ({ ...f, message: "", improve: "" })); setNotice("Feedback submitted. Thank you for helping improve TheOutHaven."); } catch { setError("We could not submit your feedback. Please try again."); } finally { setBusy(null); } }

  const checklist = [
    ["Joined beta program", true], ["Verified account", true], ["Ran required searches", Boolean(searchTask && (local[searchTask.id] || searchTask.status) === "completed")], ["Chose or saved a spot", Boolean((chooseTask && (local[chooseTask.id] || chooseTask.status) === "completed") || items.length > 0)], ["Submitted feedback", Boolean(feedbackCount > 0 || (feedbackTask && (local[feedbackTask.id] || feedbackTask.status) === "completed"))], ["Final review", completed >= total || giveawayStatus === "verified"],
  ];

  return <div className="grid gap-6">
    <section className="rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_top_left,rgba(225,29,72,.2),transparent_32%),linear-gradient(135deg,#160d0c,#080407)] p-6 md:p-8"><p className="text-xs font-black uppercase tracking-[.32em] text-rose-200">TheOutHaven Beta</p><h1 className="mt-3 text-4xl font-black md:text-5xl">Beta Program</h1><p className="mt-3 max-w-3xl text-white/70">Complete your weekly beta tasks, test TheOutHaven like a real user, and submit feedback to stay eligible for the giveaway.</p><div className="mt-6 grid gap-3 md:grid-cols-3"><Pill label="Current week" value={weekStart}/><Pill label="Giveaway" value={giveawayLabel}/><Pill label="Weekly progress" value={`${completed} of ${total} completed`}/></div></section>
    <div className="grid gap-4 lg:grid-cols-3"><Overview title="Weekly Progress" value={`${completed} of ${total} completed`} percent={percent}/><Overview title="Giveaway Progress" value={giveawayLabel}/><Overview title="Feedback Submitted" value={`${feedbackCount} this week`}/></div>
    {(notice || error) && <p className={`rounded-2xl border p-4 text-sm font-bold ${error ? "border-red-300/20 bg-red-500/10 text-red-100" : "border-emerald-300/20 bg-emerald-500/10 text-emerald-100"}`}>{error || notice}</p>}
    <section className="grid gap-4"><div><h2 className="text-3xl font-black">This Week’s Beta Tasks</h2><p className="mt-2 text-sm text-white/60">Finish the tasks below by the end of the week. Your progress helps us improve TheOutHaven before launch.</p></div>{assignments.map((a) => <article key={a.id} className={card}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="text-xl font-black">{isSearchTask(a) ? "Search for outing ideas" : isFeedbackTask(a) ? "Submit beta feedback" : isChooseTask(a) ? "Choose a spot you would try" : taskTitle(a)}</h3><p className="mt-2 text-sm leading-6 text-white/62">{isSearchTask(a) ? "Try real searches you would use for dates, birthdays, brunch, friends, family outings, or celebrations." : isFeedbackTask(a) ? "Tell us what worked, what was confusing, and what needs improvement." : isChooseTask(a) ? "Pick one restaurant, activity, or TheOutHaven recommended outing you would actually consider." : a.beta_tasks?.instructions || a.beta_tasks?.description || "Complete this weekly beta task and share what you noticed."}</p></div><span className="w-fit rounded-full border border-white/10 bg-black/30 px-3 py-1 text-xs font-black text-white/75">{friendlyStatus(local[a.id] || a.status, isFeedbackTask(a) && feedbackCount === 0)}</span></div>{isSearchTask(a) && a.id === searchTask?.id ? <form onSubmit={runSearch} className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><input className={input} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="birthday dinner in Queens"/><button disabled={busy === "search"} className={primary}>{busy === "search" ? "Searching…" : "Run Search"}</button></form> : null}{isFeedbackTask(a) ? <FeedbackForm feedback={feedback} setFeedback={setFeedback} submitFeedback={submitFeedback} busy={busy === "feedback"}/> : null}{isProfileTask(a) ? <Link href="/user/dashboard/preferences" className={`mt-5 inline-flex ${primary}`}>{profileComplete ? "Review Profile" : "Complete Profile"}</Link> : null}</article>)}</section>
    {items.length ? <section className={card}><h2 className="text-2xl font-black">Choose a spot you would try</h2><p className="mt-2 text-sm text-white/60">Pick one restaurant, activity, or TheOutHaven recommended outing you would actually consider.</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((r, i) => <div key={`${r.id}-${i}`} className="overflow-hidden rounded-3xl border border-white/10 bg-black/25"><div className="relative h-36 bg-white/5">{imageFor(r) ? <Image src={imageFor(r)!} alt="" fill className="object-cover"/> : null}</div><div className="p-4"><h3 className="font-black">{resultName(r)}</h3><p className="mt-1 text-xs font-bold text-rose-100">{areaFor(r)} · {categoryFor(r)}</p><p className="mt-2 line-clamp-3 text-sm text-white/58">{r.review_snippet || r.description || "A TheOutHaven recommendation from your beta search."}</p><button onClick={() => chooseSpot(r)} disabled={busy === `choose-${r.id}`} className={`mt-4 ${secondary}`}>{busy === `choose-${r.id}` ? "Saving…" : "Choose This Spot"}</button></div></div>)}</div></section> : null}
    <div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><section className={card}><h2 className="text-2xl font-black">Giveaway Progress</h2><p className="mt-2 text-sm text-white/60">Complete your required beta tasks and submit feedback to qualify for the weekly gift card giveaway.</p><div className="mt-5 grid gap-3">{checklist.map(([label, done]) => <div key={String(label)} className="flex items-center gap-3 rounded-2xl bg-black/25 p-3"><span className={`grid h-7 w-7 place-items-center rounded-full ${done ? "bg-emerald-500 text-black" : "bg-white/10 text-white/45"}`}>{done ? "✓" : ""}</span><span className="text-sm font-bold text-white/75">{label}</span></div>)}</div></section><section className={card}><h2 className="text-2xl font-black">Beta Help / Tips</h2><p className="mt-3 text-sm leading-6 text-white/65">Use real searches you would actually use for dates, birthdays, brunch, family outings, friend outings, or celebrations. Your feedback helps improve TheOutHaven before launch.</p></section></div>
  </div>;
}
function Pill({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-black/30 p-4"><p className="text-[11px] font-black uppercase tracking-[.2em] text-rose-100">{label}</p><p className="mt-1 font-black text-white">{value}</p></div>; }
function Overview({ title, value, percent }: { title: string; value: string; percent?: number }) { return <section className={card}><p className="text-xs font-black uppercase tracking-[.24em] text-rose-200">{title}</p><h2 className="mt-2 text-2xl font-black">{value}</h2>{typeof percent === "number" ? <div className="mt-4 h-3 rounded-full bg-white/10"><div className="h-3 rounded-full bg-gradient-to-r from-rose-500 to-amber-300" style={{ width: `${Math.min(100, percent)}%` }}/></div> : <p className="mt-3 text-sm text-white/55">Keep completing weekly tasks and feedback.</p>}</section>; }
function FeedbackForm({ feedback, setFeedback, submitFeedback, busy }: any) { return <form onSubmit={submitFeedback} className="mt-5 grid gap-3"><select className={input} value={feedback.feature_area} onChange={(e) => setFeedback((f: any) => ({ ...f, feature_area: e.target.value }))}>{["Search results", "Recommendations", "Profile", "Booking / reservation", "Mobile experience", "Other"].map((x) => <option key={x}>{x}</option>)}</select><textarea required className={input} value={feedback.message} onChange={(e) => setFeedback((f: any) => ({ ...f, message: e.target.value }))} placeholder="What happened?"/><div className="flex flex-wrap gap-2">{["Easy", "Confusing", "Broken", "Missing info"].map((x) => <button type="button" key={x} onClick={() => setFeedback((f: any) => ({ ...f, feel: x }))} className={`rounded-full border px-4 py-2 text-xs font-black ${feedback.feel === x ? "border-rose-200 bg-rose-500/25" : "border-white/10 bg-black/25"}`}>{x}</button>)}</div><textarea className={input} value={feedback.improve} onChange={(e) => setFeedback((f: any) => ({ ...f, improve: e.target.value }))} placeholder="Optional: What should we improve?"/><button disabled={busy} className={primary}>{busy ? "Submitting…" : "Submit Feedback"}</button></form>; }
