"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useRef, useState } from "react";

type Assignment = { id: string; status?: string | null; assigned_prompt?: string | null; beta_tasks?: any };
type GroupType = "profile" | "search" | "choose_spot" | "feedback" | "other";
type ResultItem = { id?: string; source_id?: string; location_id?: string; name?: string | null; restaurant_name?: string | null; activity_name?: string | null; business_name?: string | null; title?: string | null; city?: string | null; borough?: string | null; neighborhood?: string | null; area?: string | null; address?: string | null; primary_category?: string | null; category?: string | null; cuisine?: string | null; activity_type?: string | null; description?: string | null; reason?: string | null; review_snippet?: string | null; main_image?: string | null; image_url?: string | null; image?: string | null; images?: string[] | null; type?: string | null; location_type?: string | null; source_table?: string | null; detail_location_type?: string | null };
type TaskGroup = { type: GroupType; title: string; description: string; assignments: Assignment[]; completed: boolean; inProgress: boolean; completedCount: number; total: number };

const card = "rounded-[1.75rem] border border-white/10 bg-white/[0.045] p-5 shadow-2xl shadow-black/20";
const input = "rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none placeholder:text-white/35 focus:border-rose-200/50";
const primary = "rounded-full bg-gradient-to-r from-rose-500 to-rose-700 px-5 py-3 text-sm font-black text-white shadow-lg shadow-rose-950/30 disabled:cursor-not-allowed disabled:opacity-50";
const secondary = "rounded-full border border-white/10 bg-black/30 px-4 py-2 text-xs font-black text-white hover:border-rose-200/40 disabled:cursor-not-allowed disabled:opacity-50";

const GROUP_COPY: Record<GroupType, { title: string; description: string }> = {
  profile: { title: "Finish your profile", description: "Complete the basics that help TheOutHaven personalize your beta experience." },
  search: { title: "Search for outing ideas", description: "Try real searches you would use for dates, birthdays, brunch, friends, family outings, or celebrations." },
  choose_spot: { title: "Choose a spot you would try", description: "Pick one restaurant, activity, or TheOutHaven recommended outing you would actually consider." },
  feedback: { title: "Submit beta feedback", description: "Tell us what worked, what was confusing, and what needs improvement." },
  other: { title: "Additional beta task", description: "Complete this weekly beta task and share what you noticed." },
};
const FLOW: GroupType[] = ["profile", "search", "choose_spot", "feedback", "other"];

function taskTitle(a: Assignment) { return a.beta_tasks?.title || "Beta task"; }
function haystack(a: Assignment) { return `${taskTitle(a)} ${a.beta_tasks?.slug || ""} ${a.beta_tasks?.task_key || ""} ${a.beta_tasks?.key || ""} ${a.beta_tasks?.feature_area || ""} ${a.beta_tasks?.test_url || ""}`.toLowerCase(); }
function groupType(a: Assignment): GroupType { const t = haystack(a); if (t.includes("profile") || t.includes("account") || t.includes("password") || t.includes("email") || t.includes("preferences")) return "profile"; if (t.includes("search") || t.includes("prompt") || t.includes("plan flow")) return "search"; if (t.includes("choose") || t.includes("save") || t.includes("spot") || t.includes("recommendation") || t.includes("try") || t.includes("location")) return "choose_spot"; if (t.includes("feedback") || t.includes("bug") || t.includes("report")) return "feedback"; return "other"; }
function statusOf(a: Assignment, local: Record<string, string>) { return local[a.id] || a.status || "not_started"; }
function resultName(r: ResultItem) { return r.name || r.restaurant_name || r.activity_name || r.business_name || r.title || "TheOutHaven spot"; }
function imageFor(r: ResultItem) { return r.main_image || r.image_url || r.image || (Array.isArray(r.images) ? r.images[0] : null); }
function areaFor(r: ResultItem) { return [r.neighborhood || r.borough || r.area, r.city].filter(Boolean).join(", ") || r.address || "Area available in details"; }
function categoryFor(r: ResultItem) { return r.primary_category || r.category || r.cuisine || r.activity_type || r.type || r.location_type || "Recommended spot"; }
function itemType(r: ResultItem) { const raw = `${r.location_type || r.type || r.source_table || r.detail_location_type || ""}`.toLowerCase(); return raw.includes("activity") ? "activity" : "restaurant"; }
function itemKey(r: ResultItem, i: number) { return String(r.id || r.source_id || r.location_id || `${itemType(r)}-${resultName(r)}-${areaFor(r)}-${i}`); }
function normalizeGenerateResults(data: any): ResultItem[] { const restaurants = Array.isArray(data?.restaurants) ? data.restaurants : []; const activities = Array.isArray(data?.activities) ? data.activities : []; const cards = Array.isArray(data?.cards) ? data.cards : []; const matched = Array.isArray(data?.matched_locations) ? data.matched_locations : []; const pairs = Array.isArray(data?.pairs) ? data.pairs.flatMap((p: any) => [p?.restaurant, p?.activity, p?.location, p?.primary, p?.secondary].filter(Boolean)) : []; const raw = [...restaurants, ...activities, ...(cards.length ? cards : matched), ...pairs]; const seen = new Set<string>(); return raw.filter((item: ResultItem, index: number) => { const key = itemKey(item, index).toLowerCase(); if (seen.has(key)) return false; seen.add(key); return true; }).slice(0, 6); }

export default function BetaCommandCenter({ assignments, weekStart, giveawayStatus, feedbackCount, profileComplete }: { assignments: Assignment[]; weekStart: string; giveawayStatus?: string | null; feedbackCount: number; profileComplete: boolean }) {
  const searchRef = useRef<HTMLElement | null>(null);
  const [items, setItems] = useState<ResultItem[]>([]);
  const [latestQuery, setLatestQuery] = useState<string | null>(null);
  const [selectedSpot, setSelectedSpot] = useState<ResultItem | null>(null);
  const [query, setQuery] = useState("birthday dinner in Queens");
  const [busy, setBusy] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [local, setLocal] = useState<Record<string, string>>({});
  const [feedbackSubmitted, setFeedbackSubmitted] = useState(feedbackCount > 0);
  const [feedback, setFeedback] = useState({ feature_area: "Search results", feel: "Easy", message: "", improve: "" });

  const groups = useMemo(() => buildGroups(assignments, local, profileComplete, feedbackSubmitted), [assignments, local, profileComplete, feedbackSubmitted]);
  const active = groups.find((g) => !g.completed);
  const completed = groups.reduce((sum, g) => sum + g.completedCount, 0);
  const total = Math.max(groups.reduce((sum, g) => sum + g.total, 0), 5);
  const percent = Math.round((completed / total) * 100);
  const giveawayLabel = completed >= total || giveawayStatus === "verified" ? "Qualified for review" : completed > 0 ? "In progress" : "Needs tasks";

  async function patchMany(group: TaskGroup, action: "start" | "complete", body: any = {}) {
    await Promise.all(group.assignments.map(async (a) => { const res = await fetch(`/api/beta/tasks/${a.id}/${action}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!res.ok) throw new Error("task"); }));
    setLocal((s) => Object.fromEntries([...Object.entries(s), ...group.assignments.map((a) => [a.id, action === "complete" ? "completed" : s[a.id] || "in_progress"])]));
  }
  async function runSearch(e?: React.FormEvent) { e?.preventDefault(); const search = groups.find((g) => g.type === "search"); if (!query.trim() || !search) return; setBusy("search"); setNotice(null); setError(null); setSelectedSpot(null); try { await patchMany(search, "start", { submitted_prompt: query, used_custom_prompt: true }); const res = await fetch("/api/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ input: query, query, message: query, prompt: query, betaAssignmentId: search.assignments[0]?.id, usedCustomPrompt: true }) }); const raw = await res.text(); const data = raw ? JSON.parse(raw) : {}; if (!res.ok || data.error) throw new Error(data.user_message || data.reply || "search"); setItems(normalizeGenerateResults(data)); setLatestQuery(query); await patchMany(search, "complete", { submitted_prompt: query, used_custom_prompt: true }); setNotice("Search recorded for your beta task."); } catch { setError("We could not run that search. Please try again."); } finally { setBusy(null); } }
  async function chooseSpot(group: TaskGroup, r: ResultItem) { setBusy(`choose-${itemKey(r, 0)}`); setError(null); setNotice(null); try { await patchMany(group, "complete", { selected_spot: { id: r.id || r.source_id || r.location_id || null, name: resultName(r), type: itemType(r) } }); setSelectedSpot(r); setNotice("Spot selected. Thanks for testing this recommendation."); } catch { setError("We could not save that spot yet. Please try again."); } finally { setBusy(null); } }
  async function submitFeedback(group: TaskGroup, e: React.FormEvent) { e.preventDefault(); if (!feedback.message.trim()) return; setBusy("feedback"); setError(null); setNotice(null); try { const res = await fetch("/api/beta/feedback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ feedback_type: "weekly_beta", feature_area: feedback.feature_area, message: `${feedback.feel}: ${feedback.message}${feedback.improve ? `\n\nImprove: ${feedback.improve}` : ""}`, assignmentId: group.assignments[0]?.id, page_url: location.href, search_query: latestQuery || query }) }); if (!res.ok) throw new Error("feedback"); await patchMany(group, "complete"); setFeedbackSubmitted(true); setFeedback((f) => ({ ...f, message: "", improve: "" })); setNotice("Feedback submitted. Thank you for helping improve TheOutHaven."); } catch { setError("We could not submit your feedback. Please try again."); } finally { setBusy(null); } }

  const checklist = [["Joined beta program", true], ["Verified account", true], ["Ran required searches", groups.find((g) => g.type === "search")?.completed ?? false], ["Chose or saved a spot", groups.find((g) => g.type === "choose_spot")?.completed ?? false], ["Submitted feedback", groups.find((g) => g.type === "feedback")?.completed ?? feedbackSubmitted], ["Final review", completed >= total || giveawayStatus === "verified"]] as const;

  return <div className="grid gap-6">
    <section className="rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_top_left,rgba(225,29,72,.2),transparent_32%),linear-gradient(135deg,#160d0c,#080407)] p-6 md:p-8"><p className="text-xs font-black uppercase tracking-[.32em] text-rose-200">TheOutHaven Beta</p><h1 className="mt-3 text-4xl font-black md:text-5xl">Beta Program</h1><p className="mt-3 max-w-3xl text-white/70">Complete your weekly beta tasks, test TheOutHaven like a real user, and submit feedback to stay eligible for the giveaway.</p><div className="mt-6 grid gap-3 md:grid-cols-3"><Pill label="Current week" value={weekStart}/><Pill label="Giveaway" value={giveawayLabel}/><Pill label="Weekly progress" value={`${completed} of ${total} completed`}/></div></section>
    <div className="grid gap-4 lg:grid-cols-3"><Overview title="Weekly Progress" value={`${completed} of ${total} completed`} percent={percent}/><Overview title="Giveaway Progress" value={giveawayLabel}/><Overview title="Feedback Submitted" value={`${feedbackSubmitted ? Math.max(1, feedbackCount) : feedbackCount} this week`}/></div>
    {(notice || error) && <p className={`rounded-2xl border p-4 text-sm font-bold ${error ? "border-red-300/20 bg-red-500/10 text-red-100" : "border-emerald-300/20 bg-emerald-500/10 text-emerald-100"}`}>{error || notice}</p>}
    <section className="grid gap-4"><div><p className="text-xs font-black uppercase tracking-[.28em] text-rose-200">Your Next Step</p><h2 className="mt-2 text-3xl font-black">This Week’s Beta Tasks</h2><p className="mt-2 text-sm text-white/60">Finish the guided flow below by the end of the week. Duplicate weekly task rows are grouped here without changing your saved beta records.</p></div>{groups.map((g) => { const state = g.completed ? "completed" : active?.type === g.type ? "active" : "locked"; return <article key={g.type} ref={g.type === "search" ? searchRef : undefined} className={`${card} ${state === "active" ? "border-rose-200/45 bg-rose-500/[0.08]" : state === "completed" ? "border-emerald-200/25 bg-emerald-500/[0.06]" : "opacity-75"}`}><TaskHeader group={g} state={state}/><TaskBody group={g} state={state} query={query} setQuery={setQuery} runSearch={runSearch} busy={busy} latestQuery={latestQuery} items={items} selectedSpot={selectedSpot} chooseSpot={chooseSpot} feedback={feedback} setFeedback={setFeedback} submitFeedback={submitFeedback} goSearch={() => searchRef.current?.scrollIntoView({ behavior: "smooth", block: "center" })}/></article>; })}</section>
    <div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><section className={card}><h2 className="text-2xl font-black">Giveaway Progress</h2><p className="mt-2 text-sm text-white/60">Complete your required beta tasks and submit feedback to qualify for review.</p><div className="mt-5 grid gap-3">{checklist.map(([label, done]) => <div key={String(label)} className="flex items-center gap-3 rounded-2xl bg-black/25 p-3"><span className={`grid h-7 w-7 place-items-center rounded-full ${done ? "bg-emerald-500 text-black" : "bg-white/10 text-white/45"}`}>{done ? "✓" : ""}</span><span className="text-sm font-bold text-white/75">{label}</span></div>)}</div></section><section className={card}><h2 className="text-2xl font-black">Beta Help / Tips</h2><p className="mt-3 text-sm leading-6 text-white/65">Use real searches you would actually use for dates, birthdays, brunch, family outings, friend outings, or celebrations. Your feedback helps improve TheOutHaven before launch.</p></section></div>
  </div>;
}
function buildGroups(assignments: Assignment[], local: Record<string, string>, profileComplete: boolean, feedbackSubmitted: boolean): TaskGroup[] { const map = new Map<GroupType, Assignment[]>(); assignments.forEach((a) => { const type = groupType(a); map.set(type, [...(map.get(type) || []), a]); }); return FLOW.filter((type) => map.has(type)).map((type) => { const list = map.get(type)!; const completedCount = list.filter((a) => statusOf(a, local) === "completed").length; const inProgress = list.some((a) => statusOf(a, local) === "in_progress"); const forcedComplete = (type === "profile" && profileComplete) || (type === "feedback" && feedbackSubmitted); const completed = forcedComplete || completedCount === list.length; return { type, title: GROUP_COPY[type].title, description: list.length === 1 ? list[0].beta_tasks?.description || GROUP_COPY[type].description : GROUP_COPY[type].description, assignments: list, completed, inProgress, completedCount: completed ? list.length : completedCount, total: list.length }; }); }
function TaskHeader({ group, state }: { group: TaskGroup; state: "completed" | "active" | "locked" }) { return <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="text-xl font-black">{group.title}</h3><p className="mt-2 text-sm leading-6 text-white/62">{group.description}</p>{group.total > 1 && <p className="mt-2 text-xs font-bold text-rose-100">{group.completedCount} of {group.total} {group.type === "search" ? "searches" : "tasks"} completed</p>}</div><span className={`w-fit rounded-full border px-3 py-1 text-xs font-black ${state === "completed" ? "border-emerald-200/25 bg-emerald-500/10 text-emerald-100" : state === "active" ? "border-rose-200/35 bg-rose-500/15 text-rose-50" : "border-white/10 bg-black/30 text-white/60"}`}>{state === "completed" ? "Completed" : group.inProgress ? "In Progress" : state === "active" ? "Not Started" : "Locked"}</span></div>; }
function TaskBody(props: any) { const { group, state } = props; if (state === "completed") return <CompletedBody {...props}/>; if (state === "locked") return <LockedBody group={group} goSearch={props.goSearch}/>; if (group.type === "search") return <form onSubmit={props.runSearch} className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><input className={input} value={props.query} onChange={(e) => props.setQuery(e.target.value)} placeholder="birthday dinner in Queens"/><button disabled={props.busy === "search"} className={primary}>{props.busy === "search" ? "Searching…" : "Run Search"}</button></form>; if (group.type === "choose_spot") return <ChooseBody {...props}/>; if (group.type === "feedback") return <FeedbackForm {...props}/>; if (group.type === "profile") return <Link href="/user/dashboard/preferences" className={`mt-5 inline-flex ${primary}`}>Finish Profile</Link>; return <p className="mt-5 rounded-2xl border border-white/10 bg-black/25 p-4 text-sm text-white/65">This step is reviewed by TheOutHaven team after you complete your required beta tasks.</p>; }
function CompletedBody({ group, latestQuery, selectedSpot, runSearch, busy }: any) { const text = group.type === "search" ? "Search recorded for your beta task." : group.type === "choose_spot" ? "Spot selected. Thanks for testing this recommendation." : group.type === "feedback" ? "Feedback submitted. Thank you for helping improve TheOutHaven." : group.type === "profile" ? "Profile setup is complete." : "This task is complete."; return <div className="mt-5 rounded-2xl border border-emerald-200/15 bg-emerald-500/10 p-4"><p className="text-sm font-bold text-emerald-50">{text}</p>{group.type === "search" && latestQuery && <p className="mt-1 text-xs text-white/60">Latest search: “{latestQuery}”</p>}{group.type === "choose_spot" && selectedSpot && <p className="mt-1 text-xs text-white/60">Selected: {resultName(selectedSpot)}</p>}{group.type === "search" && <button onClick={() => runSearch()} disabled={busy === "search"} className={`mt-3 ${secondary}`}>Run another search</button>}</div>; }
function LockedBody({ group, goSearch }: { group: TaskGroup; goSearch: () => void }) { const message = group.type === "search" ? "Finish your profile first. Then you’ll be able to run your beta search task." : group.type === "choose_spot" ? "Run a search first, then your results will appear here so you can choose a spot." : group.type === "feedback" ? "Choose a spot first. Then you’ll be able to submit feedback about your test." : "Complete the current beta step first, then this task will unlock."; return <div className="mt-5 rounded-2xl border border-white/10 bg-black/25 p-4"><p className="text-sm text-white/65">{message}</p>{group.type === "choose_spot" && <button onClick={goSearch} className={`mt-3 ${secondary}`}>Go to Search Task</button>}</div>; }
function ChooseBody({ group, items, selectedSpot, chooseSpot, busy, goSearch }: any) { if (selectedSpot) return <CompletedBody group={group} selectedSpot={selectedSpot}/>; if (!items.length) return <LockedBody group={group} goSearch={goSearch}/>; return <div className="mt-5"><p className="text-sm font-bold text-white/75">Choose one result from your latest search.</p><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((r: ResultItem, i: number) => <div key={itemKey(r, i)} className="overflow-hidden rounded-3xl border border-white/10 bg-black/25"><div className="relative h-36 bg-white/5">{imageFor(r) ? <Image src={imageFor(r)!} alt="" fill className="object-cover"/> : null}</div><div className="p-4"><h3 className="font-black">{resultName(r)}</h3><p className="mt-1 text-xs font-bold text-rose-100">{areaFor(r)} · {categoryFor(r)}</p><p className="mt-2 line-clamp-3 text-sm text-white/58">{r.reason || r.review_snippet || r.description || "A TheOutHaven recommendation from your beta search."}</p><button onClick={() => chooseSpot(group, r)} disabled={busy === `choose-${itemKey(r, 0)}`} className={`mt-4 ${secondary}`}>{busy === `choose-${itemKey(r, 0)}` ? "Saving…" : "Choose This Spot"}</button></div></div>)}</div></div>; }
function FeedbackForm({ group, feedback, setFeedback, submitFeedback, busy }: any) { return <form onSubmit={(e) => submitFeedback(group, e)} className="mt-5 grid gap-3"><label className="text-xs font-black uppercase tracking-[.2em] text-white/45">What were you testing?</label><select className={input} value={feedback.feature_area} onChange={(e) => setFeedback((f: any) => ({ ...f, feature_area: e.target.value }))}>{["Search results", "Recommendations", "Profile", "Booking / reservation", "Mobile experience", "Other"].map((x) => <option key={x}>{x}</option>)}</select><textarea required className={input} value={feedback.message} onChange={(e) => setFeedback((f: any) => ({ ...f, message: e.target.value }))} placeholder="What happened?"/><label className="text-xs font-black uppercase tracking-[.2em] text-white/45">How did it feel?</label><div className="flex flex-wrap gap-2">{["Easy", "Confusing", "Broken", "Missing info"].map((x) => <button type="button" key={x} onClick={() => setFeedback((f: any) => ({ ...f, feel: x }))} className={`rounded-full border px-4 py-2 text-xs font-black ${feedback.feel === x ? "border-rose-200 bg-rose-500/25" : "border-white/10 bg-black/25"}`}>{x}</button>)}</div><textarea className={input} value={feedback.improve} onChange={(e) => setFeedback((f: any) => ({ ...f, improve: e.target.value }))} placeholder="What should we improve?"/><button disabled={busy} className={primary}>{busy ? "Submitting…" : "Submit Feedback"}</button></form>; }
function Pill({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-black/30 p-4"><p className="text-[11px] font-black uppercase tracking-[.2em] text-rose-100">{label}</p><p className="mt-1 font-black text-white">{value}</p></div>; }
function Overview({ title, value, percent }: { title: string; value: string; percent?: number }) { return <section className={card}><p className="text-xs font-black uppercase tracking-[.24em] text-rose-200">{title}</p><h2 className="mt-2 text-2xl font-black">{value}</h2>{typeof percent === "number" ? <div className="mt-4 h-3 rounded-full bg-white/10"><div className="h-3 rounded-full bg-gradient-to-r from-rose-500 to-amber-300" style={{ width: `${Math.min(100, percent)}%` }}/></div> : <p className="mt-3 text-sm text-white/55">Keep completing weekly tasks and feedback.</p>}</section>; }
